### ISSUE TITLE
Error calling /info with Sping Boot 2.5.4

### ISSUE THREAD

**Issue by 7--** [spring-projects/spring-framework#27507] opened 2021-10-01 14:45 UTC
When calling /info you have this error:
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class java.time.Instant]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.Collections$UnmodifiableMap["build"]->java.util.LinkedHashMap["time"]) at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:460) at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104) at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:183) at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) at

**Comment by bclozel** [comment] 2021-10-01 15:58
This is the Spring Framework issue tracker, please use the Spring Boot issue tracker in the future for Spring Boot-related bugs.

In this case, this is a duplicate of spring-projects/spring-boot#26859 - please look at the comments there. Your application might be defining its own `ObjectMapper` bean incorrectly, or you might be missing the required dependency. There's no need to create a new issue or add a new comment there, since all related problems are pretty well covered already.

**Closed by bclozel** 2021-10-01 15:58 UTC
Labels: status: waiting-for-triage
