### ISSUE TITLE
Support Kotlin parameter default values in HTTP handler methods

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21139] opened 2018-03-15 15:21 UTC
**[Take Weiland](https://jira.spring.io/secure/ViewProfile.jspa?name=diesieben07)** opened **[SPR-16598](https://jira.spring.io/browse/SPR-16598?redirect=false)** and commented

Support specifying defaults for e.g. `@RequestMapping` via Kotlin parameter default values like so:

```
@GetMapping
fun get(@RequestParam limit: Int = 20)
```

Such a method should behave equivalent to `@RequestMapping` with `defaultValue`, except that the value does not need to be processed by converters, etc.

This can be implemented in `org.springframework.web.method.support.InvocableHandlerMethod` using Kotlin Reflection (`KCallable#callBy`), which allows omitting parameters with default values.

---

**Affects:** 5.0.4

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1741

2 votes, 5 watchers

**Comment by AlexTrotsenko** [comment] 2020-05-25 19:18
Is there any updates on this issue?

**Comment by codeMoney095** [comment] 2021-01-24 16:56
I'm also interested in this feature.

**Comment by jlous** [comment] 2021-02-05 14:30
The pull-request was closed in August 2020.

**Comment by jlous** [comment] 2021-02-05 14:46
Treating it like a Spring defaultValue is not feasible, because Kotlin's "default value" is a piece of essentially arbitrary object-internal kotlin code, which Spring has no access to.

An alternative approach would be to use @JvmOverloads to have kotlin generate explicit permutations of the method signature. Spring would need to select the right one depending on which params are present, in stead of rejecting them all as ambiguous endpoint mappings like it does now.

In any case: the situation today is that such an endpoint will compile and run without incident, right up until a request hits it without specifying the parameter in question, in which case it will throw an NPE from way inside Spring's parameter mapping. That has got to be the wrong approach whichever way you look at it.

**Comment by igorwojda** [comment] 2023-02-22 13:32
@jlous I would like to understand this issue a bit more. What exactly is required on the Kotlin side to make this work as expected with Spring (no duplicated default values)? Perhaps the ability to access default value via reflection?

**Comment by igorwojda** [comment] 2023-02-23 08:03
I have opened issue in Kotlin issue tracker: https://youtrack.jetbrains.com/issue/KT-56893/Provide-a-way-to-read-default-argument-values

**Comment by sdeleuze** [comment] 2023-02-23 09:05
Let's try to see if we can support that in 6.1 (no promise but I will try).

**Comment by sdeleuze** [comment] 2023-02-23 13:53
As discussed in the Kotlin issue, we are probably going to handle this with a refined variant of the [original PR](https://github.com/spring-projects/spring-framework/pull/1741).

**Closed** 2023-06-22 14:09 UTC
Labels: in: web, type: enhancement, theme: kotlin

**Comment by sdeleuze** [comment] 2023-06-22 14:14
I have pushed support for Kotlin parameter default values in handler methods. It allows to write:
`@RequestParam value: String = "default"`
as an alternative to:
`@RequestParam(defaultValue = "default") value: String`

Both Spring MVC and WebFlux are supported, including on suspending functions.

The changes are quite involved, so I would appreciate feedback based on Spring Framework `6.1.0-SNAPSHOT`.

**Comment by sdeleuze** [comment] 2023-11-28 21:47
@Quantum64 Please create a dedictaed issue with a reproducer.

**Comment by efemoney** [comment] 2023-11-29 11:09
This change caused another regression using extension receivers. Not necessarily a regression even, more a bug as the change just **completely ignores** Kind.EXTENSION_RECEIVER.

I personally blame java here because of the lack of exhaustive checks for non-expression `switch` statements.

**Comment by sdeleuze** [comment] 2023-12-08 08:03
@efemoney Could you please create a new issue with a reproducer please (attached archive or link to a repository)?

**Comment by efemoney** [comment] 2023-12-08 10:16
Sure, let me do that.

**Comment by efemoney** [comment] 2023-12-22 01:29
@sdeleuze I see you just fixed this yesterday. Looking forwrd to the release. Sorry I didnt get to creating an issue.
