### ISSUE TITLE
Spring 5 - JDBC gets column names from other schema in MySQL

### ISSUE THREAD

**Issue by csaba97** [spring-projects/spring-framework#23483] opened 2019-08-18 18:32 UTC
When using Spring MVC 5.1.8.RELEASE along with JdbcTemplate, JDBC and MySQL Workbench, the query which is automatically created does not look for tables only in the current schema defined in the JDBC URL, but it also looks for tables in other schemas. So, if I have 2 schemas: _app1_ and _app2_ and each one has a table named "table" then the field names are returned from app2, even if app1 appears in the JDBC URL. 

I tried debugging the application and found out that the issue comes from the class **GenericTableMetaDataProvider** from the package **org.springframework.jdbc.core.metadata** and the method is **locateTableAndProcessMetaData()**...The thing is that this method parses the whole database and uses a HashMap to store the table where the key is just a part of the jdbc URL(not the whole one). So, in the first iteration, the correct table is stored there but after that, the table is overriden by the table in the other schema.

The MySQL - JDBC URL used was: **jdbc:mysql://localhost:3306/app1**
The same thing can be observed when using H2 database, but usually that is used only with integration tests and only one schema is used....

I attached 2 screenshots, one with the value of the key in the HashMap when using H2 database and one with MySQL. Also, I observed that this only happens when inserting data, not retrieving. The JdbcTemplade code that reproduced this is quite simple:
```java
SimpleJdbcInsert insert = new SimpleJdbcInsert(jdbcTemplate);
insert.setTableName("table");
insert.usingGeneratedKeyColumns("id");
Map<String, Object> map = new HashMap<>();

//...populate map

//insert new object, the query created will contain incorrect field names
int id = insert.executeAndReturnKey(map).intValue();
```

**H2:**  
![h2](https://user-images.githubusercontent.com/37183688/63228608-2057f500-c1fe-11e9-87a2-46998d38245b.png)

**MySQL:**  
![mysql](https://user-images.githubusercontent.com/37183688/63228607-1f26c800-c1fe-11e9-9565-c2b312ef7186.png)

**Comment by snicoll** [comment] 2019-08-19 05:23
Thanks for the report and the analysis. This is a duplicate of #22015

**Closed by snicoll** 2019-08-19 05:23 UTC
Labels: status: waiting-for-triage
