### ISSUE TITLE
WebClient.ResponseSpec.onStatus, Unexpected behavior when response body empty

### ISSUE THREAD

**Issue by danielra** [spring-projects/spring-framework#4735] opened 2019-01-10 21:49 UTC
When I use the WebClient.ResponseSpec.onStatus method and try to create an exception that requires the response body content but the response body is empty, the Flux returned by a subsequent bodyToFlux call actually receives an onComplete instead of the expected onError.

To illustrate the behavior, I've created a sample project which reproduces the unexpected behavior in a test case here: https://github.com/danielra/webclient_response_spec_onstatus_empty_response_body_issue_repro
The project uses spring boot version `2.1.1.RELEASE` as seen [here](https://github.com/danielra/webclient_response_spec_onstatus_empty_response_body_issue_repro/blob/master/build.gradle#L3).

When run via `./gradlew test --debug` the test case ([here](https://github.com/danielra/webclient_response_spec_onstatus_empty_response_body_issue_repro/blob/master/src/test/java/com/example/demo/DemoApplicationTests.java#L52)) which has at least one character of response body content passes as expected - but the test case which has an empty response body ([here](https://github.com/danielra/webclient_response_spec_onstatus_empty_response_body_issue_repro/blob/master/src/test/java/com/example/demo/DemoApplicationTests.java#L38)) unexpectedly fails.

Please let me know if any further information would be useful.

**Comment by poutsma** [comment] 2019-11-14 15:37
With the introduction of `ClientResponse::createException` in 5.2, it is no longer necessary to consume the body bytes themselves. Using that method, I was not able to reproduce this issue.

Closing this issue for now, but let us know if there is something to look at.

**Closed by poutsma** 2019-11-14 15:37 UTC
Labels: status: waiting-for-triage

**Comment by rstoyanchev** [comment] 2019-11-15 09:21
Most likely superseded by #22825.
