### ISSUE TITLE
Why is there no index directory on the left? The operation now is very inconvenient!

### ISSUE THREAD

**Issue by starSmallDream** [spring-projects/spring-framework#27228] opened 2021-07-30 05:13 UTC
Why is there no index directory on the left? The operation now is very inconvenient!

link: https://docs.spring.io/spring-framework/docs/current/reference/html/core.html

**Comment by bclozel** [comment] 2021-07-30 06:50
Closing as another duplicate of #27177

**Closed by bclozel** 2021-07-30 06:50 UTC
Labels: status: waiting-for-triage
