### ISSUE TITLE
Webflux http.server.requests 200 Metrics not Recorded

### ISSUE THREAD

**Issue by HarryEMartland** [spring-projects/spring-framework#23243] opened 2019-07-05 15:39 UTC
**Affects:** webflux 2.1.5.RELEASE & 2.1.6.RELEASE
---
The default metrics for rest controllers (http.server.requests) is not reporting 200 responses however it does record if an error is thrown. The error looks to have been introduced in 2.1.4.RELEASE.

See https://github.com/HarryEMartland/webflux-metrics-issue for an example application

|Spring Boot Version | Server  | Controller Response | Metrics Reported |
|--------------------|---------|---------------------|------------------|
|2.1.6.RELEASE       | webflux | Mono                | no               | 
|2.1.6.RELEASE       | webflux | String              | no               | 
|2.1.6.RELEASE       | webflux | Exception           | yes              | 
|2.1.6.RELEASE       | web     | String              | yes              | 
|2.1.5.RELEASE       | webflux | String              | no               | 
|2.1.5.RELEASE       | webflux | Mono                | no               | 
|2.1.5.RELEASE       | webflux | Exception           | yes              | 
|2.1.5.RELEASE       | web     | String              | yes              | 
|2.1.4.RELEASE       | webflux | String              | yes              | 
|2.1.4.RELEASE       | webflux | Mono                | yes              | 
|2.1.4.RELEASE       | webflux | Exception           | yes              | 
|2.1.4.RELEASE       | web     | String              | yes              |

**Comment by sbrannen** [comment] 2019-07-06 12:19
This sounds like an issue in Spring Boot.

@philwebb, @wilkinsona, @snicoll Can one of you take a look at this?

**Comment by wilkinsona** [comment] 2019-07-06 17:42
Looks a lot like the problem reported in https://github.com/spring-projects/spring-boot/issues/17103. @bclozel investigated that one and identified that it was a combination of a Framework issue and a Reactor Netty issue.

**Comment by bclozel** [comment] 2019-07-06 19:49
Closing as a duplicate of #22952

**Closed by bclozel** 2019-07-06 19:49 UTC
Labels: status: waiting-for-triage

**Comment by HarryEMartland** [comment] 2019-08-17 09:46
This looks to be fixed in 2.1.8.BUILD-SNAPSHOT
