### ISSUE TITLE
AbstractPlatformTransactionManager "this.logger" is null

### ISSUE THREAD

**Issue by guy1699** [spring-projects/spring-framework#29592] opened 2022-11-28 07:04 UTC
**Affects:** \5.3.13

I'm extending `JpaTransactionManager` (which extends `AbstractPlatformTransactionManager`)
Creating a `@Bean` of my class.

Then I get to this situation you see in the image which not suppose to be possible since the `logger` is being initiated already.
`protected transient Log logger = LogFactory.getLog(getClass());`

![Screen Shot 2022-11-28 at 09 03 26](https://user-images.githubusercontent.com/15769295/204214648-145354ed-e1f7-43dc-8c67-0bdf75fc4765.png)

It happens when I have an `Aspect` for every method
```
@Pointcut("within(com.mydomain..*)")
  public void everyMethodExecution() {
  }

  @Around("everyMethodExecution()")
  public Object logAroundMethod(ProceedingJoinPoint joinPoint) throws Throwable {
    Object o = joinPoint.proceed();
    return o;
  }
```

**Comment by mdeinum** [comment] 2022-11-28 09:18
This is due to the aspects. The aspects result in a proxy being generated. As the method is `final` that cannot be proxied. What now happens is that the method is invoked on the proxy instead of passing through the proxy and eventually invoking the actual method. The proxy, due to its nature, doesn't have any of the fields initialized (or injected). 


You might want to refine your pointcut expression to exclude this specific subclass of the `JpaTransactionManager`, that way it won't be proxied and it will work as it should.

**Comment by sbrannen** [comment] 2022-11-28 16:18
> You might want to refine your pointcut expression to exclude this specific subclass of the `JpaTransactionManager`, that way it won't be proxied and it will work as it should.

Indeed.

Before @mdeinum posted his comment, I was going to point out that your pointcut is too broad: it's rarely a good idea to have an aspect applied to every single bean in your project. Rather, you should apply aspects based on certain packages/types or based on the presence of specific annotations.

In light of the above, I am closing this issue as "works as designed".

**Closed by sbrannen** 2022-11-28 16:18 UTC
Labels: status: waiting-for-triage

**Comment by guy1699** [comment] 2022-11-29 06:23
Thanks for the explanation @mdeinum
