### ISSUE TITLE
webflux cpu useage is slow grow

### ISSUE THREAD

**Issue by cjdxhjj** [spring-projects/spring-framework#26801] opened 2021-04-14 08:05 UTC
**Affects:** \<Spring Framework version>
2.3.4
---

link to https://github.com/spring-projects/spring-framework/issues/26741

my app sometimes very slow, even though there is almost very few request, so i watch my app use jprofile, after a long time monitor， i have found the cpu usage is very strange， it alway grow when it reach the 100% usage, and down to 0 again and again.

![image](https://user-images.githubusercontent.com/5616997/114674881-42d74400-9d3a-11eb-9048-c08acb725571.png)

![image](https://user-images.githubusercontent.com/5616997/114675010-60a4a900-9d3a-11eb-882a-de24c6bd8c60.png)

![image](https://user-images.githubusercontent.com/5616997/114675115-7c0fb400-9d3a-11eb-865e-46fc6b70122f.png)

![image](https://user-images.githubusercontent.com/5616997/114675170-87fb7600-9d3a-11eb-992f-3cf1d9020fc3.png)

mem usage
![image](https://user-images.githubusercontent.com/5616997/114675451-d27cf280-9d3a-11eb-8303-c072b6453905.png)

![image](https://user-images.githubusercontent.com/5616997/114675537-ede7fd80-9d3a-11eb-858d-5db7857877e0.png)

it report that the cpu usage from 0 to 100 is more often after time elapse。

is there any suggest for me?

**Comment by cjdxhjj** [comment] 2021-04-14 09:20
the jps is here
[m.zip](https://github.com/spring-projects/spring-framework/files/6309796/m.zip)

**Comment by bclozel** [comment] 2021-04-14 10:23
I don't see any `org.springframework.*` class in those stack traces. Maybe [this section of the Lettuce documentation is relevant](https://lettuce.io/core/release/reference/index.html#faq.reactive-single-connection)?

I'm closing this issue as nothing here shows that Spring Framework is involved. Maybe asking a question on StackOverflow will help you narrow down the cause of this issue.

**Closed by bclozel** 2021-04-14 10:23 UTC
Labels: status: waiting-for-triage
