### ISSUE TITLE
JmsTemplate with TransactionSession does not call rollback, while sending message error.  [SPR-16850]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21390] opened 2018-05-21 12:57 UTC
**[hezhou](https://jira.spring.io/secure/ViewProfile.jspa?name=hezhou66)** opened **[SPR-16850](https://jira.spring.io/browse/SPR-16850?redirect=false)** and commented

JmsTemplate with sessionTransacted does not call rollback method when sending message error,maybe jms provider has received this message but network time out. But then users will use this session's producer to send a new message, and commit it, which will commit all the two message.   In this situation, users will be very confused about the first error message.

why JmsTemplate does cant call rollback when error , but auto call commit method when sending success.

---

**Affects:** 4.3.17

**Comment by snicoll** [comment] 2023-09-19 14:05
Duplicate of #21305

**Closed by snicoll** 2023-09-19 14:05 UTC
Labels: status: waiting-for-triage, in: messaging
