### ISSUE TITLE
Received the integer type of LinkedHashMap from the long type of HashMap ?

### ISSUE THREAD

**Issue by wangnanyang** [spring-projects/spring-framework#22498] opened 2019-03-01 15:38 UTC
I use 4.53.22.RELEASE  version of spring framework, and the service provider interacts with consumers using the List < Map < String, Object > return value result set. The problem is that the long in map < String, Object > is converted to integer, that is, result. get (0). get ("count"). getClass () is the integer type from the long at the service provider to the service consumer. How can I solve this problem? Thank you!

@GetMapping("/report/common/data/search")
public List<Map<String, Object>> searchSaleReport(@RequestParam("param") String param) {
return saleReportService.searchSaleReport(param);
}

@FeignClient("${sale.feign.name}")
public interface SaleReportService {
@GetMapping("/report/common/data/search")
List<Map<String, Object>> searchSaleReport(@RequestParam("param") String param);
}

**Comment by snicoll** [comment] 2019-03-01 17:04
Please do not open duplicated issues.

Duplicate of #22495

**Closed by snicoll** 2019-03-01 17:04 UTC
Labels: status: waiting-for-triage
