### ISSUE TITLE
ServletWebRequest.getHeaderValues throwing NPE when header information is not available

### ISSUE THREAD

**Issue by ketsorbit** [spring-projects/spring-framework#22547] opened 2019-02-27 05:03 UTC
in ServletWebRequest class -> getHeaderValues() method:

getRequest().getHeaders(headerName) may return null .. and so, StringUtils.tostringArray() throws Null Pointer Exception.

**Comment by philwebb** [comment] 2019-03-08 17:41
This looks like a framework bug so I've transferred the issue.

**Comment by jhoeller** [comment] 2019-03-08 21:00
A `null` return value is defined to only happen if "the container does not allow access to header information" according to the `HttpServletRequest` javadoc... In any case, we should handle this defensively.

**Comment by jhoeller** [comment] 2019-03-08 21:30
This turns out to be a regression from 4.3.x, introduced during our 5.0 nullability revision of `StringUtils`.

**Closed** 2019-03-08 22:10 UTC
Labels: in: web, status: backported, type: regression
