### ISSUE TITLE
PostProcessorRegistrationDelegate.sortPostProcessors optimization.

### ISSUE THREAD

**Issue by cherishsince** [spring-projects/spring-framework#24885] opened 2020-04-09 06:16 UTC
version: 5.2.4

```java
private static void sortPostProcessors(List<?> postProcessors, ConfigurableListableBeanFactory beanFactory) {
		Comparator<Object> comparatorToUse = null;
		if (beanFactory instanceof DefaultListableBeanFactory) {
			comparatorToUse = ((DefaultListableBeanFactory) beanFactory).getDependencyComparator();
		}
		if (comparatorToUse == null) {
			comparatorToUse = OrderComparator.INSTANCE;
		}
		postProcessors.sort(comparatorToUse);
	}
```

`postProcessors` size < 1, Can return directly.

**Comment by sbrannen** [comment] 2020-04-09 10:24
This is a duplicate of #24776.

@cherishsince, please be careful not to create the same issue twice.

**Closed by sbrannen** 2020-04-09 10:24 UTC
Labels: in: core, status: duplicate
