### ISSUE TITLE
@NotNull annotation is not enforced for @RequestParam when parameter is passed as an empty value

### ISSUE THREAD

**Issue by selalerercapitolis** [spring-projects/spring-framework#26841] opened 2021-04-21 14:34 UTC
**Affects:** \Spring Boot v2.3.9.RELEASE, Spring v5.2.13.RELEASE
---

When annotating a parameter of type Long of a controller with @NotNull for a @Get method and passing the parameter as empty value, the parameter is received as null.

```
@RestController
@RequestMapping("testController1")
public class TestController {

    @GetMapping("testMethod1")
    public Long testMethod(@RequestParam @NotNull Long param1) {
        assertNotNull(param1);
        return param1;
    }

}
```

Getting 400 when requesting http://localhost:8082/testController1/testMethod1
Getting 200 when requesting http://localhost:8082/testController1/testMethod1?param1=555
Getting 500 when requesting http://localhost:8082/testController1/testMethod1?param1=&param2=bla

Expecting to 400 for the last case too.

**Comment by selalerercapitolis** [comment] 2021-04-21 15:49
Those two seem related:
https://github.com/spring-projects/spring-framework/issues/15035
https://github.com/spring-projects/spring-framework/issues/15207

**Comment by bclozel** [comment] 2022-06-22 08:56
Closing as a duplicate of #16519 and #11041

**Closed by bclozel** 2022-06-22 08:56 UTC
Labels: status: waiting-for-triage, in: web
