### ISSUE TITLE
MethodParameter.isOptional() fails with ArrayIndexOutOfBoundsException [SPR-17629]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22160] opened 2018-12-28 13:36 UTC
**[shollander](https://jira.spring.io/secure/ViewProfile.jspa?name=shollander)** opened **[SPR-17629](https://jira.spring.io/browse/SPR-17629?redirect=false)** and commented

Calling `org.springframework.core.MethodParameter.isOptional()` can fail with an `ArrayIndexOutOfBoundsException`.  I have a custom `ResponseBodyAdvice` class that calls this method in `supports()`. It fails when it hits `org.springframework.boot.actuate.endpoint.web.servelt.WebMvcEndpointHandlerMappings$WebMvcLinksHandler.links` with the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: -1
    at org.springframework.web.method.HandlerMethod$HandlerMethodParamater.getParameterAnnotations(HandlerMethod.java:484) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
    at org.springframework.core.MethodParameter.hasNullableAnnotation(MethodParameter.java:357) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
    at org.springframework.core.MethodParameter.isOptional(MethodParameter.java:345) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
    at com.example.advice.OptionalResponseBodyAdvice.supports(OptionalResponseBodyAdvice.java:18) ~[main/:na]
    at org.springframework.web.servlet.mvc.method.annotation.RequestBodyAdviceChain.processBody(RequestBodyAdviceChain.java:140) ~[spring-webmvc-5.1.3.RELEASE.jar:5.1.3.RELEASE]
```

---

**Affects:** 5.1.3

**Issue Links:**
- #15682 Enable REST controller method parameter annotations on an interface

**Referenced from:** commits https://github.com/spring-projects/spring-framework/commit/1faeeaea14f8961a49d280da528fa4623fe7cfee

**Comment by shollander** [comment] 2019-01-16 16:56
@jhoeller This issue has not been fixed in 5.1.4. I still get the same `ArrayIndexOutOfBoundsException`, this time at line 486:

> java.lang.ArrayIndexOutOfBoundsException: -1
    at org.springframework.web.method.HandlerMethod$HandlerMethodParamater.getParameterAnnotations(HandlerMethod.java:486) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
    at org.springframework.core.MethodParameter.hasNullableAnnotation(MethodParameter.java:357) ~[spring-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
    at org.springframework.core.MethodParameter.isOptional(MethodParameter.java:345) ~[spring-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
    at com.example.advice.OptionalResponseBodyAdvice.supports(OptionalResponseBodyAdvice.java:19) ~[main/:na]
    at org.springframework.web.servlet.mvc.method.annotation.RequestBodyAdviceChain.processBody(RequestBodyAdviceChain.java:140) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]

The problem is that the `getParameterIndex()` method called at [HandlerMethod.java:484](https://github.com/spring-projects/spring-framework/blob/1faeeaea14f8961a49d280da528fa4623fe7cfee/spring-web/src/main/java/org/springframework/web/method/HandlerMethod.java#L484) will return `-1` (as documented in its JavaDoc) in the case of a return type. The change in 1faeeae only addresses checking the upper bounds of `index` but not the lower bounds.

**Comment by rstoyanchev** [comment] 2019-01-17 20:25
I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by shollander** [comment] 2019-01-18 03:43
@rstoyanchev Thank you.

**Comment by jhoeller** [comment] 2019-01-24 10:33
I've created #22303 as a follow-up for 5.1.5, leaving this one as the ticket for the 5.1.4 release.

**Closed by jhoeller** 2019-01-24 10:33 UTC
Labels: for: team-attention, in: web, type: bug

**Comment by Moonergfp** [comment] 2023-06-28 10:28
The 5.1.5 release notes don't contain the update, do they? i don't find it out.
https://github.com/spring-projects/spring-framework/releases?page=9

**Comment by bclozel** [comment] 2023-06-28 11:33
@Moonergfp I'm seeing it listed under the bugs section on the release page: https://github.com/spring-projects/spring-framework/releases/tag/v5.1.5.RELEASE

**Comment by Moonergfp** [comment] 2023-06-28 15:20
I see, but what is the difference between these two release notes? And why does the description in https://github.com/spring-projects/spring-framework/releases?page=9 have fewer details than https://github.com/spring-projects/spring-framework/releases/tag/v5.1.5.RELEASE?
@bclozel

**Comment by bclozel** [comment] 2023-06-28 15:24
@Moonergfp The first link is a link to a page, a collection of releases. The second link is a link to a single release.

**Comment by bclozel** [comment] 2023-06-28 15:37
I don't see a `v5.1.5.RELEASE` release on that page.

**Comment by Moonergfp** [comment] 2023-06-29 06:04
I misspoke, it should be v5.1.15.RELEASE.
