### ISSUE TITLE
Partially correct pointcut example.

### ISSUE THREAD

**Issue by kumaraman528** [spring-projects/spring-framework#34142] opened 2024-12-23 17:48 UTC
Page: 333 (334)

"Any join point (method execution only in Spring AOP) which takes a single parameter, and
where the runtime type of the argument passed has the @Classified annotation:"

The solution in the documentation is:

@args(com.xyz.security.Classified)

However, the actual solution should be:

@execution(* *(..)) && args(arg) && @args(com.xyz.security.Classified).

The example in the documentation does not account for the requirement of a single parameter.

fix- [pr](https://github.com/spring-projects/spring-framework/pull/34143)

**Comment by snicoll** [comment] 2024-12-24 09:46
Closing as duplicate of #34143 

@kumaraman528 going forward, please do not open an issue if you intend to send a PR.

**Closed by snicoll** 2024-12-24 09:46 UTC
Labels: status: waiting-for-triage
