### ISSUE TITLE
WebTestClient cannot block when receive infinity stream of SSE

### ISSUE THREAD

**Issue by Slava96** [spring-projects/spring-framework#24131] opened 2019-12-04 13:50 UTC
**Affects:** 5.1.5.RELEASE

---
I try to receive infinity Flux of server sent events represented by strings.

On my test - WebTestClient always throw IllegalStateException, because on the 'exchange' method it uses block with timeout.

**Controller code:**

```java
private final DirectProcessor<Signal> sseProcessor;

@GetMapping(value = "/signals", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
public Flux<String> sendSignals() {
    return sseProcessor.publishOn(Schedulers.parallel())
            .doOnNext(signal -> signal.setSent(ZonedDateTime.now()))
            .map(writeSignalAsString())
            .filter(Objects::nonNull);
}
```

**Model:**

```java
@Data
@NoArgsConstructor
public class Signal {
    private String id;
    private Type type;
    private ZonedDateTime initiated;
    private ZonedDateTime sent;
    private ZonedDateTime effective;
    private String clue;
    private Map<String, Object> data = new HashMap<>();

    public enum Type {
        TECH_DEDUPLICATION
    }
}
```

Test code:
```java
        FluxExchangeResult<String> sseFlux = client.get()
                .uri("/v1/signals")
                .exchange()
                .expectStatus().isOk()
                .expectHeader().contentTypeCompatibleWith(TEXT_EVENT_STREAM)
                .returnResult(String.class);

        StepVerifier.create(sseFlux.getResponseBody())
                .assertNext(json -> {
                    String signalInstanceId = JsonPath.parse(json).read("$.data.data.instanceId");
                    assertThat(signalInstanceId, is(duplicateInstanceId));
                })
                .thenCancel().verify();
```

**Comment by rstoyanchev** [comment] 2019-12-04 16:37
There was a related recent change #23936 but with or without it I can't reproduce it. Can you try with the latest 5.1.12 (and also 5.2.2) just to be sure? If you still see the problem, please provide a sample.

**Comment by spring-issuemaster** [comment] 2019-12-11 16:38
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-12-18 16:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-12-18 16:40 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
