### ISSUE TITLE
Improve documentation on support for a language-only Locale requested via "Accept-Language"

### ISSUE THREAD

**Issue by chulbert** [spring-projects/spring-framework#28673] opened 2022-06-21 17:52 UTC
```
@Test
public void resolvePreferredAgainstLanguageOnly() {
    this.resolver.setSupportedLocales(Arrays.asList(GERMANY, US));
    assertThat(this.resolver.resolveLocaleContext(exchange(UK, ENGLISH)).getLocale()).isEqualTo(US);
}

```

This test should _pass_.  If a client requests `en-GB, en` and the supported locales are `de-DE, en-US` then this should resolve to US because `en` (English of any kind) matches `en-US` (US English).  Instead it incorrectly resolves to `en-GB`.

Note: There is an existing test with the same name that I believe has this wrong:

```
@Test
public void resolvePreferredAgainstLanguageOnly() {
    this.resolver.setSupportedLocales(Collections.singletonList(ENGLISH));
    assertThat(this.resolver.resolveLocaleContext(exchange(GERMANY, US, UK)).getLocale()).isEqualTo(ENGLISH);
}
```

This test _should_ also pass but not because it "matches" -- it should resolve to ENGLISH because that's the only supported locale.

This affects all versions.

**Comment by rstoyanchev** [comment] 2023-01-27 15:54
I think this makes sense. Currently, we do a special match for a "supported" `Locale` that is language-only, but we don't do the same for a "request" `Locale` that is language-only. In the latter case we could actually use the supported `Locale` as is, i.e. with the country.

> This test should also pass but not because it "matches" -- it should resolve to ENGLISH because that's the only supported locale.

We do fall back on a default `Locale` if configured, or otherwise on the first supported `Locale`. In this case, we just happen to match even earlier on the language. I don't see anything wrong there.

**Comment by rstoyanchev** [comment] 2023-02-07 17:41
**Team Decision:** following an extensive team discussion, first I'll say the current behavior is intentional. 

The idea is that a server is in control of what should happen, and can for example be configured to also support `en` in addition to `en-US` and `en-GB` it wants to support requests for a language-only locale such as `en`, but if it's not added then it means we don't match on such request, and fall back on the default `Locale`. This is also how `java.util.ResourceBundle` behaves.

For now I am going to turn this into a documentation issues in order to make it more clear that this is by design.

We can also consider a future enhancement where we take further action if we fall back on the default locale, and there are 1 or more requested locales, and the default locale doesn't match the language of any of them. However, that would be a behavior change and we could only introduce in 6.1 at the earliest.

**Comment by Cadarin212** [comment] 2023-02-07 20:35
<img width="830" alt="merged_entitlements" src="https://user-images.githubusercontent.com/122121545/217359102-5ac16c19-896d-4062-9cad-21904fb763b4.png">

> `35.146.99.71`

**Comment by Cadarin212** [comment] 2023-02-07 20:36
https://developer.android.com/jetpack/compose/tooling/studio?authuser=2#preview-features
Duplicate of #

**Closed** 2023-02-13 18:40 UTC
Labels: type: documentation, in: web
