### ISSUE TITLE
Memory leak with CglibAopProxy$ProxyCallbackFilter

### ISSUE THREAD

**Issue by Pancor** [spring-projects/spring-framework#26266] opened 2020-12-14 11:40 UTC
It seems that there is a memory leak with Spring Boot 2.4.1 on my Debian 10.5 with Java 11.0.1 when using `@PreAuthorize("hasRole('ROLE')")` annotation on controller's endpoint. As you can see in the first image, there is constant grow in old generation memory of G1 garbage collector when running tests. The grow stops at max heap size which is 512 MB. I prepared a [sample project](https://github.com/Pancor/leak) where you can reproduce the problem. 

<details>
  <summary>Memory usage 1</summary>
  
![image](https://user-images.githubusercontent.com/24636767/102074708-75f9dd00-3e05-11eb-97ec-927ef3d27a80.png)
  
</details>
<details>
  <summary>Memory usage 2</summary>
  
![image](https://user-images.githubusercontent.com/24636767/102074755-88741680-3e05-11eb-81e6-8d0620f987d1.png)
  
</details>

After importing the project just run this command:

`./gradlew clean test`

Tests will fail because they assume that HTTP response will be 200, but it is 401, but it shouldn't matter.
If you remove `@PreAuthorize` from [DummyController](https://github.com/Pancor/leak/blob/master/src/main/java/pl/pancordev/leak/controllers/DummyController.java) or `prePostEnabled = true` from [SecurityConfig](https://github.com/Pancor/leak/blob/master/src/main/java/pl/pancordev/leak/SecurityConfig.java) then memory usage seems to be ok.
<details>
  <summary>Memory usage 3</summary>
  
![image](https://user-images.githubusercontent.com/24636767/102076516-18b35b00-3e08-11eb-9d64-c4717c6737b0.png)
  
</details>
<details>
  <summary>Memory usage 4</summary>
  
![image](https://user-images.githubusercontent.com/24636767/102076541-236df000-3e08-11eb-98ab-ce1bb912493e.png)
  
</details>

The project uses dummy controller with one endpoint which has `@PreAuthorize("hasRole('ROLE')")` annotation. It has also basic `SecurityConfig` to enable `@PreAuthorize` annotation. Controller uses some dummy services to make sure that for each test Spring will recreate the context. I also set `spring.test.context.cache.maxSize=1` in [build.gradle](https://github.com/Pancor/leak/blob/master/build.gradle) to make sure that the grow of memory does not come from cache.

If you have any more questions about my configuration or anything else, let me know.

**Comment by mdeinum** [comment] 2020-12-14 14:05
This sounds a bit like #14113 which was, once upon a time, solved (accidentally) with #21674.

**Comment by Nazukin-Dmitry** [comment] 2021-04-24 13:05
Any updates here? Some cglib generated proxy classes keep reference to BeanFactory, so BeanFactory can't be garbage collected, and memory footprint grows and grows. It is the most sensitive in SpringBootTests, where a lot of contexts could be created.
For example, spring security proxies keep reference to BeanFactory in MethodSecurityMetadataSourceAdvisor.

**Comment by sbrannen** [comment] 2021-04-27 15:13
If the cause of the problem is due to the fact that Spring Security's `MethodSecurityMetadataSourceAdvisor` is retaining a reference to the `BeanFactory` (which seems plausible based on the current [source code](https://github.com/spring-projects/spring-security/blob/e2993d93e109c1a3c9020b7ea9efb6e556751ed4/core/src/main/java/org/springframework/security/access/intercept/aopalliance/MethodSecurityMetadataSourceAdvisor.java)), then the solution might be to refactor `MethodSecurityMetadataSourceAdvisor` so that it releases that reference when the enclosing `ApplicationContext` is closed.

@rwinch & @jhoeller, thoughts?

**Comment by rwinch** [comment] 2021-04-28 03:41
Thanks for bringing this to my attention @sbrannen.

It does appear that the class generated by CGLIB is (indirectly) holding a reference to `MethodSecurityMetadataSourceAdvisor` which in turn holds a reference to the `BeanFactory`.

For reference here is a list of objects retained by `ProxyCallbackFilter`

![image](https://user-images.githubusercontent.com/362503/116342117-b1d78280-a7a7-11eb-9c60-34549bdbf6bd.png)

Here is the shortest GC Root of `ProxyCalbackFilter`

![image](https://user-images.githubusercontent.com/362503/116342226-e0edf400-a7a7-11eb-8b05-d9f26f8329e6.png)

I don't think Spring Security is the correct place to solve this. Any cleanup that the `Advisor`s perform would just be masking the actual leak which is in Spring Framework + CGLIB. Even if the `Advisor` cleans up all of its resources, the `Advisor` itself is leaked and so are lower level objects (i.e. [`AdvisedSupport`](https://github.com/spring-projects/spring-framework/blob/e4a5d2aaa59266b294e155c4fd80b9ef3e852330/spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java#L61)).

I think it would be ideal if Spring Framework could remove the reference to the `ProxyCallbackFilter` on [`CALLBACK_FILTER` ](https://github.com/spring-projects/spring-framework/blob/e4a5d2aaa59266b294e155c4fd80b9ef3e852330/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L201) of the generated class once we know that the `CALLBACK_FILTER` is no longer needed. It might also mark the generated class as `closed` so that if it is used again it reports an error.

Removing the refererence to `ProxyCallbackFilter` would ensure that references to `AdvisedSupport` are cleaned up along with its [`methodCache`](https://github.com/spring-projects/spring-framework/blob/e4a5d2aaa59266b294e155c4fd80b9ef3e852330/spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java#L84), all references to its [`advisors`](https://github.com/spring-projects/spring-framework/blob/e4a5d2aaa59266b294e155c4fd80b9ef3e852330/spring-aop/src/main/java/org/springframework/aop/framework/AdvisedSupport.java#L96), and its remaining members. It's important to note that cleaning up references to `advisors` will clean up the reference to `MethodSecurityMetadataSourceAdvisor` and thus the `BeanFactory` it refers to. It will also cleanup references to other `Advisor`s and any large objects they might refer to. For example, `AbstractBeanFactoryPointcutAdvisor` has it's own [`BeanFactory` reference](https://github.com/spring-projects/spring-framework/blob/e4a5d2aaa59266b294e155c4fd80b9ef3e852330/spring-aop/src/main/java/org/springframework/aop/support/AbstractBeanFactoryPointcutAdvisor.java#L50).

**Comment by Nazukin-Dmitry** [comment] 2021-04-28 08:15
I wouldn't say that problem only in `MethodSecurityMetadataSourceAdvisor`. 

In our application I also see reference from `RetryConfiguration`:

![image](https://user-images.githubusercontent.com/15947012/116367792-5db4b880-a810-11eb-8fb6-7435cd663a8f.png)


And such chain(related to `RefreshScope`) keeps reference to `GenericWebApplicationContext` .

![image](https://user-images.githubusercontent.com/15947012/116369373-fac42100-a811-11eb-8a2c-fa23e6302532.png)

**Comment by grubeninspekteur** [comment] 2021-08-05 10:42
> Obviously this still means the generated classes are still unnecessarily around, but I'm not sure we can drop the references to those given they are held by the jdk.

Would it be possible to generate cglib classes using a classloader that is tied to the ApplicationContext? So when the context gets dropped, the loader is no longer referenced from the GC root and the classes are unloaded.

**Comment by rwinch** [comment] 2021-08-19 18:07
@grubeninspekteur Switching the `ClassLoader` used to create the cglib classes will cause ``ClassCastException``s to be thrown unless the entire application uses the new `ClassLoader` which will likely lead to other problems.

**Comment by sbrannen** [comment] 2021-09-09 11:54
Related issues:

-  #27375

**Comment by jhoeller** [comment] 2021-09-14 12:14
Closing this one based on the assumption that #27375 covers all occurrences of this leak (as a regression in the 5.3.x line). Please give the 5.3.10 release a try, it's available in snapshots already and will be officially released tomorrow!

**Comment by rwinch** [comment] 2021-09-15 21:59
@jhoeller Unfortunately, it does not appear to have fixed this specific issue. Updating the [original sample](https://github.com/spring-projects/spring-framework/issues/26266#issue-766468495) to use Spring 5.3.10 does not resolve the issue. I've put together a [branch named spring-5.3.10](https://github.com/rwinch/leak/tree/spring-5.3.10) that demonstrates it is not fixed. If you run `./gradlew check` you will see lots of failed tests (expected) and then eventually you will start getting out of memory errors. I haven't  looked into if anything has changed from the previous assessment, but the take away at this point is the tests still produce out of memory errors.

Can we please reopen the issue?

**Comment by sbrannen** [comment] 2021-09-16 12:22
Thanks for trying out the sample against 5.3.10 and providing that branch.

We'll look into it.

**Comment by nkonev** [comment] 2021-10-06 23:48
For the interest - I can't reproduce it on my Mac with `./gradlew check`
<img width="1792" alt="Снимок экрана 2021-10-07 в 02 46 46" src="https://user-images.githubusercontent.com/3160384/136298724-ddbe8a22-cdf8-44a3-b7af-03472d3c819b.png">

**Comment by nkonev** [comment] 2021-10-11 17:31
I don't have neither GRADLE_OPTS, not gradle.properties
```
MacBook-Pro-Nikita:spring-framework-gh-26266 nkonev$ ls -lah ~/.gradle/
total 0
drwxr-xr-x  11 nkonev  staff   352B  8 сен 01:35 .
drwxr-xr-x+ 78 nkonev  staff   2,4K  9 окт 05:34 ..
drwxr-xr-x   7 nkonev  staff   224B  7 окт 02:45 .tmp
drwxr-xr-x  18 nkonev  staff   576B  6 окт 12:41 caches
drwxr-xr-x  16 nkonev  staff   512B  6 окт 12:41 daemon
drwxr-xr-x   2 nkonev  staff    64B  4 мар  2021 jdks
drwxr-xr-x   2 nkonev  staff    64B  9 окт 05:08 kotlin-profile
drwxr-xr-x  13 nkonev  staff   416B  6 окт 12:32 native
drwxr-xr-x   9 nkonev  staff   288B  8 сен 01:36 notifications
drwxr-xr-x   3 nkonev  staff    96B 11 авг 13:29 workers
drwxr-xr-x   3 nkonev  staff    96B 18 фев  2021 wrapper
MacBook-Pro-Nikita:spring-framework-gh-26266 nkonev$ echo $GRADLE_OPTS

MacBook-Pro-Nikita:spring-framework-gh-26266 nkonev$

MacBook-Pro-Nikita:spring-framework-gh-26266 nkonev$ echo $JAVA_HOME

MacBook-Pro-Nikita:spring-framework-gh-26266 nkonev$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

MacBook-Pro-Nikita:spring-framework-gh-26266 nkonev$ ./gradlew --version

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.8 (AdoptOpenJDK 11.0.8+10)
OS:           Mac OS X 10.16 x86_64
```

Yes, I reproduced leak in the [original](https://github.com/Pancor/leak) example.

<img width="1267" alt="Снимок экрана 2021-10-11 в 20 25 39" src="https://user-images.githubusercontent.com/3160384/136831279-175ea531-f59c-444a-b052-d22ec8a72006.png">


Consider to force-kill gradle daemons, I did it before the test, something like
```bash
jps | grep -i gradle | awk '{print $1}' | xargs kill -9
```

**Comment by rwinch** [comment] 2021-10-11 19:54
@nkonev  Hmm..Not sure why you are getting a difference in behavior but good to know. Thanks!

**Comment by nkonev** [comment] 2021-12-10 07:50
May be related with https://github.com/mockito/mockito/issues/2503

**Comment by redhead** [comment] 2022-06-02 22:11
We are having the same issue. We start and close some contexts during the lifetime of our app. If that happens a lot, after a while we get OOM.

After manually nulling all CALLBACK_FILTER references in all proxy classes, the bean factory is finally garbage collected.

> I think it would be ideal if Spring Framework could remove the reference to the ProxyCallbackFilter on [CALLBACK_FILTER](https://github.com/spring-projects/spring-framework/blob/e4a5d2aaa59266b294e155c4fd80b9ef3e852330/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L201)of the generated class once we know that the CALLBACK_FILTER is no longer needed. It might also mark the generated class as closed so that if it is used again it reports an error.

This would be great. I tried to find a way to do it myself, but didn't find any hook that would allow me that. One dirty way was listing all classes from ClassLoader, filtering those containing `BySpring`, making the field accessible and setting it to null by reflection.

This however won't work if there is more than one context and I don't know which proxy classes belong to context that I'm closing.

I also tried to collect proxy classes in a custom class loader which I set before the context startup but that didn't really work either. The classes were coming from different class loaders in the hierarchy (some are loaded from parent, cglib proxy classes are magically set to the child loader by reflection.. then they don't match or are not assignable from one to another, and he'll is lose, so this is not a way to go I guess).

**Comment by redhead** [comment] 2022-06-07 10:29
I tried to write a class loader to collect created proxy classes and clean the static field after the context is closed. However, our setup of contexts is not trivial and I was running into many class-to-class problems (classes not assignable to each other, etc.).

So I went for the BeanPostProcessor instead, which might not work at all times maybe, but works for us so far.


```
public class MemoryLeakFixBeanFactoryPostProcessor implements BeanPostProcessor, DisposableBean {

    /**
     * See {@link org.springframework.cglib.proxy.Enhancer}
     */
    private static final String CGLIB_PROXY_STATIC_FIELD_WITH_MEMORY_LEAK = "CGLIB$CALLBACK_FILTER";

    /**
     * See {@link org.springframework.cglib.core.SpringNamingPolicy}
     */
    private static final String SPRING_CGLIB_PROXY_CLASS_NAME_TAG = "BySpringCGLIB";

    private final Set<Class<?>> classesToCleanUp = new HashSet<>();

    @Override
    public Object postProcessAfterInitialization(Object bean, @Nonnull String beanName) throws BeansException {
        if (bean.getClass().getName().contains(SPRING_CGLIB_PROXY_CLASS_NAME_TAG)) {
            classesToCleanUp.add(cls);
        }
        return bean;
    }

    @Override
    public void destroy() throws Exception {
        classesToCleanUp.forEach(cls -> {
            try {
                var field = cls.getDeclaredField(CGLIB_PROXY_STATIC_FIELD_WITH_MEMORY_LEAK);
                field.setAccessible(true);
                field.set(null, null);
            } catch (Exception e) {
                // we can't do anything..
            }
        });
        classesToCleanUp.clear();
    }
}
```

It collects the bean classes if they are Spring proxy classes and clears the static field when the bean post processor is disposed (context is closed).

**Comment by rwinch** [comment] 2022-06-07 18:37
Thanks for sharing the workaround @redhead!

**Comment by vikeychen** [comment] 2022-07-30 07:19
I have made a pull request for this.

**Comment by Evenprime** [comment] 2022-11-21 07:35
Will this issue also affect the new Spring Releases, e.g. Spring Boot 3.0.x and the then used Spring Framework 6.0.x ?

**Comment by kicktipp** [comment] 2023-03-28 08:44
Same here. with spring-boot 3.0.4 and spring-framework 6.0.6 

Running a few integration test with @DirtiesContext and then I get an OOM after a few tests.  

In my case it seems to be the @Validated annotation 
```

@Controller
@Validated
@RequiredArgsConstructor
public class WettquoteLigamappingAnlegenServiceGQL {
     // ... injected services fields ...
    @Transactional
    @MutationMapping
    public @NotNull WettquoteLigamappingDTO wettquoteLigamappingAnlegen(
             @Argument @NotNull @Valid WettquoteLigamappingForm wettquoteLigamappingForm) {
            // ....
    }
}

```

After running three simple tests with @DirtiesContext I have3 applicationContexts on the heap.
Setting a breakpoint in one test, doing  forced GC and getting a heap with YourKit Profiler looks like this:

![Bildschirmfoto vom 2023-03-28 10-41-34](https://user-images.githubusercontent.com/2265253/228180061-379789e8-a315-496d-98b6-4831138b8ce6.png)

After adding this workaround to my test context, everything works again: ((thanks to @redhead, code slightly modified)

```
package de.kicktipp.testutils;

import lombok.extern.slf4j.Slf4j;
import org.jetbrains.annotations.NotNull;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.DisposableBean;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.stereotype.Component;
import java.util.HashSet;
import java.util.Set;

//https://github.com/spring-projects/spring-framework/issues/26266
@Component
@Slf4j
public class MemoryLeakFix implements BeanPostProcessor, DisposableBean {

    private static final String CGLIB_PROXY_STATIC_FIELD_WITH_MEMORY_LEAK = "CGLIB$CALLBACK_FILTER";
    private static final String SPRING_CGLIB_PROXY_CLASS_NAME_TAG = "SpringCGLIB";

    private final Set<Class<?>> classesToCleanUp = new HashSet<>();

    @Override
    public Object postProcessAfterInitialization(Object bean, @NotNull String beanName) throws BeansException {
        if (bean.getClass().getName().contains(SPRING_CGLIB_PROXY_CLASS_NAME_TAG)) {
            classesToCleanUp.add(bean.getClass());
        }
        return bean;
    }

    @Override
    public void destroy() {
        classesToCleanUp.forEach(cls -> {
            try {
                var field = cls.getDeclaredField(CGLIB_PROXY_STATIC_FIELD_WITH_MEMORY_LEAK);
                field.setAccessible(true);
                field.set(null, null);
            } catch (NoSuchFieldException e) {
                log.info("No Field", e);
            } catch (IllegalAccessException e) {
                log.error(e.getMessage(), e);
            }
        });
        classesToCleanUp.clear();
    }
}
```

**Comment by jhoeller** [comment] 2023-06-07 23:31
I've got a promising solution in the works where we reduce the `ProxyCallbackFilter` instance to a plain key role, stubbing out the Advisors with key stubs once the class has been generated. While the `CGLIB$CALLBACK_FILTER` while remain non-null, its content will not retain any leaky references anymore, independent from the concrete `Advisor` implementations in use there.

**Closed** 2023-06-08 16:11 UTC
Labels: in: test, type: bug, in: core

**Comment by debraj-manna** [comment] 2024-03-05 16:24
Can someone please let me know if the issue that is being discussed here is similar to the one I am observing [here](https://stackoverflow.com/q/78105872/785523)?
