### ISSUE TITLE
Cannot bind for the generic collection property extended from super class

### ISSUE THREAD

**Issue by ScOrPiOzzy** [spring-projects/spring-framework#23937] opened 2019-11-05 13:55 UTC
Hello everyone!!
Here is code:
### Form.java (super class)
```java
public class Form<T>{
    private String code;
    private Integer uid;
    private List<T> items;
// getter... 
// setter...
}
```
### XyzForm.java
```java
public class XyzForm extends Form<XyzFormItem>{
// ...
}
```
### XyzFormItem.java
```java
public class XyzFormItem{
private String name;
private float price;
// getter ...
// setter ...
}
```
=================

### Ajax post data:
```json
{
  "code":"",
  "uid": "",
  "items[0].name":"apple",
  "items[0].price": 3.5,
  "items[1].name":"pear",
  "items[1].price": 2.0
}
``` 
### IndexController.java
```java
@PostMapping("/save")
public Object save(XyzForm entity){
// TODO save
    return 1;
}
```
Then I got:
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_211]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_211]
        at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:638) ~[classes/:5.0.6.RELEASE]
```
eh....
After perusing the source code, I made a little change to method:`AbstractNestablePropertyAccessor.growCollectionIfNecessary`, 
```java
private void growCollectionIfNecessary(Collection<Object> collection, int index, String name, PropertyHandler ph, int nestingLevel) {
		if (!isAutoGrowNestedPaths()) {
			return;
		}
		int size = collection.size();
		if (index >= size && index < this.autoGrowCollectionLimit) {
			// Class<?> elementType = ph.getResolvableType().getNested(nestingLevel).asCollection().resolveGeneric();
                            Class<?> elementType = ph.toTypeDescriptor().getResolvableType().getNested(nestingLevel).asCollection().resolveGeneric();
			if (elementType != null) {
				for (int i = collection.size(); i < index + 1; i++) {
					collection.add(newValue(elementType, null, name));
				}
			}
		}
	}
```

It's seems good to me. But is there any danger or side effects to the framework?? Or it's just a bug...

**Comment by rstoyanchev** [comment] 2019-11-13 10:41
I can't reproduce the issue and you seem to be mixing JSON and form data. 

In the controller signature, an Object without any annotations is considered a command object (as if annotated with `@ModelAttribute`) and data binding is applied via request parameters parsed by the Servlet container from the body of an "application/x-www-form-urlencoded" request.

The Ajax post data (assuming that's the data on the wire) looks like JSON syntax though, but within that the `items[0].name` key is Java bean notation as expected for form data. It is not JSON array syntax.

**Comment by rstoyanchev** [comment] 2019-11-13 10:43
I'm closing because there doesn't seem to be enough reason to suspect a framework issue. Feel free to leave further comments but this sure looks more suited for StackOverflow.

**Closed by rstoyanchev** 2019-11-13 10:43 UTC
Labels: status: waiting-for-triage
