### ISSUE TITLE
org.springframework.aop.framework.DefaultAopProxyFactory Serializable without Serialization UID

### ISSUE THREAD

**Issue by mattwmj** [spring-projects/spring-framework#23044] opened 2019-05-28 06:57 UTC
I am using SkyWalking javaagent to enhance DefaultAopProxyFactory which changes the class structures.

Since DefaultAopProxyFactory  has no static serialization uid specified, the change of class structure changes the calculated Serialization UID.

When serialize/deserialize the enhanced DefaultAopProxyFactory instance, because of the Serialization UID inconsistence, java.io.InvalidClassException happens.

I believe that DefaultAopProxyFactory  with static serialization UID could avoid similar problems.

FYI

https://github.com/apache/skywalking/issues/2768

https://github.com/spring-projects/spring-security-oauth/issues/1684

**Comment by snicoll** [comment] 2023-11-12 09:47
Sorry this got overlooked, and this has been implemented in the meantime.

Duplicate of #27784

**Closed by snicoll** 2023-11-12 09:47 UTC
Labels: status: waiting-for-triage, in: core
