### ISSUE TITLE
Having two bean factory methods with different return type results in NoSuchBeanDefinitionException [SPR-17437]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21970] opened 2018-10-26 12:39 UTC
**[Matúš Sekáč](https://jira.spring.io/secure/ViewProfile.jspa?name=msekac)** opened **[SPR-17437](https://jira.spring.io/browse/SPR-17437?redirect=false)** and commented

When I create two bean factory methods with the same name and different return type (and with qualifiers of course), the Application Context fails to start and the error message suggests that there is no bean of either type defined. This is misleading error message. It should either work (all information to distinguish beans is there), or fail with proper error message (Eg. ambiguous factory method definition).

See attached example project.

---

**Affects:** 5.0.10

**Attachments:**
- [spring-example.zip](https://jira.spring.io/secure/attachment/26077/spring-example.zip) (_73.62 kB_)

**Comment by snicoll** [comment] 2023-09-18 10:21
Unfortunately, this does not create two beans but the context chooses the factory method that matches the state of the application context, in a similar fashion that the most suitable constructor is chosen if a target bean defines more than one. 

This is confusing indeed and such arrangement is going to be deprecated.

Duplicate of #31073

**Closed by snicoll** 2023-09-18 10:21 UTC
Labels: status: waiting-for-triage, in: core
