### ISSUE TITLE
IncompatibleClassChangeError on Jetty WebSocket ExtensionFactory

### ISSUE THREAD

**Issue by zhouxiaohai** [spring-projects/spring-framework#23500] opened 2019-08-22 06:05 UTC
![image](https://user-images.githubusercontent.com/17846308/63427719-64d6d100-c448-11e9-84df-b119494b318b.png)

error log:
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.socket.server.HandshakeFailureException: Uncaught failure for request http://192.168.76.142:9095/login?pushToken=eyJhbGciOiJIUzI1NiJ9.eyJwdXNoX2RldmljZUlkIjoiNjY2ODc5MzExNTc2ODEzNTY4IiwiYWxpYXMiOiJ1NDAxMDkiLCJjcmVhdGlvbl9kYXRlIjoxNTY2NDUyOTA2Nzg3LCJjbGllbnRfdHlwZSI6InVzZXIiLCJkZWFkbGluZSI6MTU5Nzk4ODkwNjc5MSwiZXhwIjoxNTk3OTg4OTA2LCJub25jZSI6IkdBYjhVb1BXMTJZQTY2Njg3OTMxMTU5Nzc4NTA4OCIsImRldmljZUlkIjoiZmZmZmZmZmYtYzk1Yi1iYzJkLTAwMDAtMDAwMDVhMmZiMjJjLWNvbV9qaWFtaV9nemIifQ.w_vbUFvxbIUzhgTaVXV8L1ICsoLyBc0-yDbY2Txqqgw&deviceToken=97aec1bf-4f1c-4834-afd4-a2b79d7eb50d; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:243)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.web.socket.server.HandshakeFailureException: Uncaught failure for request http://192.168.76.142:9095/login?pushToken=eyJhbGciOiJIUzI1NiJ9.eyJwdXNoX2RldmljZUlkIjoiNjY2ODc5MzExNTc2ODEzNTY4IiwiYWxpYXMiOiJ1NDAxMDkiLCJjcmVhdGlvbl9kYXRlIjoxNTY2NDUyOTA2Nzg3LCJjbGllbnRfdHlwZSI6InVzZXIiLCJkZWFkbGluZSI6MTU5Nzk4ODkwNjc5MSwiZXhwIjoxNTk3OTg4OTA2LCJub25jZSI6IkdBYjhVb1BXMTJZQTY2Njg3OTMxMTU5Nzc4NTA4OCIsImRldmljZUlkIjoiZmZmZmZmZmYtYzk1Yi1iYzJkLTAwMDAtMDAwMDVhMmZiMjJjLWNvbV9qaWFtaV9nemIifQ.w_vbUFvxbIUzhgTaVXV8L1ICsoLyBc0-yDbY2Txqqgw&deviceToken=97aec1bf-4f1c-4834-afd4-a2b79d7eb50d; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.server.support.WebSocketHttpRequestHandler.handleRequest(WebSocketHttpRequestHandler.java:174)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:53)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	... 49 common frames omitted
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.buildWebSocketExtensions(JettyRequestUpgradeStrategy.java:170)
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.getSupportedExtensions(JettyRequestUpgradeStrategy.java:164)
	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.doHandshake(AbstractHandshakeHandler.java:283)
	at org.springframework.web.socket.server.support.WebSocketHttpRequestHandler.handleRequest(WebSocketHttpRequestHandler.java:167)
	... 53 common frames omitted
```

**Comment by rstoyanchev** [comment] 2019-08-22 06:36
When creating an issue, please include a description of the problem instead of just pasting a stacktrace. From the root cause exception, I would guess some kind of dependency version mismatch, so please take a closer look at the dependency tree for your application and make sure you're using Jetty 9.4+ and that all Jetty artifacts are of the same version.

I am closing this but if you believe there is an issue, please provide a better description, and include the dependency tree.

**Comment by goekay** [comment] 2019-08-23 13:12
we are experiencing the same issue with the same stacktrace [in our project](https://github.com/RWTH-i5-IDSG/steve/pull/167), and i kindly suggest reopening this issue to investigate it. the same version is used for all jetty artifacts and the only change in our project is the linked version bump. we are using spring version 5.1.6.RELEASE, updating to the latest 5.1.9.RELEASE did not fix it.

after looking at the aforementioned class `ExtensionFactory`, i saw that it was an abstract class before but was changed to an interface in the new version. maybe this was a breaking change due to some internal reflection usage in spring websocket?

**Comment by rstoyanchev** [comment] 2019-08-23 13:43
Yes this seems to be a case of a binary incompatible change in Jetty between 9.4.19.v20190610 and 9.4.20.v20190813. In `JettyRequestUpgradeStrategy` we are checking for the presence of extensions.  

In the very least we'll upgrade to 9.4.20 in order to provide a version compiled against that. We could also catch the error and log a warning instead of failing. The connection might still work even without the negotiated extension.

**Closed** 2019-08-29 12:14 UTC
Labels: in: web, type: enhancement

**Comment by rstoyanchev** [comment] 2019-08-29 12:21
I've upgraded our build to Jetty 9.4.20.v20190813. Upgrading an application to Spring Framework 5.1.10 will solve the problem. I've also added a fallback to access the extension names via reflection which keeps 5.1.10 compatible also with Jetty versions below 9.4.20.v20190813.

**Comment by andrei-ivanov** [comment] 2019-08-29 12:56
Btw, the incompatible change seems to have been reverted for 9.4.21: 
eclipse/jetty.project#4020

**Comment by goekay** [comment] 2019-08-29 13:27
oh man it is ugly indeed.

not only that, the class/interface in question `ExtensionFactory` is marked as deprecated and is removed in jetty 10.0 (https://github.com/eclipse/jetty.project/pull/4026 and https://github.com/eclipse/jetty.project/pull/4026/commits/6bcfa2dc6ef409ce0ef55b81d7765f63e4cd5b86). they added a new method `WebSocketServerFactory.getAvailableExtensionNames()` to access the extensions without the detour over `ExtensionFactory`.

this change should be kept in mind for future compatibility.

**Comment by andrei-ivanov** [comment] 2019-08-29 13:41
You could add some suggestions there, maybe things can still be improved

**Comment by rstoyanchev** [comment] 2019-09-02 14:44
Thanks for the pointers @goekay and @andrei-ivanov. The change here should keep the Spring Framework 5.1.10+ compatible with all 9.4.x versions. Meanwhile I've also created #23565 to switch to the new `getAvailableExtensionNames`.
