### ISSUE TITLE
@Conditional bean called multiple times 

### ISSUE THREAD

**Issue by JerryJavaCoding** [spring-projects/spring-framework#24759] opened 2020-03-22 14:22 UTC
Whats happening is that my project which implements the Condition interface is getting instantiated multiple times and its match method also gets called 3 times.if any logic in matches method will to be called 3 times,is necessary?

**Comment by snicoll** [comment] 2020-03-22 18:56
@JerryJavaCoding it is impossible to know with the level of details that you've shared. Please provide a small sample (github repo or zip) that we can run to reproduce the issue you've described.

**Comment by spring-issuemaster** [comment] 2020-03-29 19:01
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-05 19:00
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-05 19:01 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by AmanMulani** [comment] 2023-06-27 13:25
> Whats happening is that my project which implements the Condition interface is getting instantiated multiple times and its match method also gets called 3 times.if any logic in matches method will to be called 3 times,is necessary?

Any updates on what had happened? I am seeing the same issue now

**Comment by bclozel** [comment] 2023-06-27 13:33
@AmanMulani if you're seeing the same issue, please share a minimal sample application that reproduces the problem and we'll have a look.
