### ISSUE TITLE
websocket.js:6 WebSocket connection to 'ws://localhost:8080/test-info/442/nlflwasu/websocket' failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by ghj1040110333** [spring-projects/spring-framework#27235] opened 2021-08-01 23:26 UTC
**Affects:** \<Spring Framework version>

---

**Comment by ghj1040110333** [comment] 2021-08-01 23:27
how to resolve it ,help me!

**Comment by snicoll** [comment] 2021-08-02 06:13
Duplicate of https://github.com/spring-projects/spring-boot/issues/27540

**Closed by snicoll** 2021-08-02 06:13 UTC
Labels: status: waiting-for-triage
