### ISSUE TITLE
Rollback transactions in case if Exception was thrown

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-framework#23789] opened 2019-10-13 10:06 UTC
At the moment a transaction is rollback only if it was thrown a `RuntimeException`.

In Kotlin there is no checked exceptions, so compiler to do not force to check when is was thrown an `Exception`.
When some library from Java throw an `Exception`, in Kotlin methods with `@Transactional` annotation do not rollback.

**Comment by raderio** [comment] 2019-10-13 10:38
The quick-fix is to use `@Transactional(rollbackFor = [Exception::class])` instead of `@Transactional`.
But it will be better to handle this by default in Spring.

**Comment by snicoll** [comment] 2019-10-13 11:27
Duplicate of #23473

**Closed by snicoll** 2019-10-13 11:27 UTC
Labels: status: waiting-for-triage
