### ISSUE TITLE
Failure in native image with multiple data sources when one is selected via `@Qualifier`

### ISSUE THREAD

**Issue by 358071956** [spring-projects/spring-framework#29805] opened 2023-01-12 03:56 UTC
code like this

```java
@Component
public class ImpalaConnection {
    @Autowired
    @Qualifier("ImpalaDS")
    private DataSource impala;
}
```

confusing that build success but running fail

```
[           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'impalaConnection': Unsatisfied dependency expressed through field 'impala': Error creating bean with name 'ImpalaDS': Instantiation of supplied bean failed
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:195) ~[na:na]
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveAndSet(AutowiredFieldValueResolver.java:167) ~[na:na]
        at com.backendapi.common.db.ImpalaConnection__Autowiring.apply(ImpalaConnection__Autowiring.java:14) ~[na:na]
        at org.springframework.beans.factory.support.InstanceSupplier$1.get(InstanceSupplier.java:82) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[backend-api:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[backend-api:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[backend-api:6.0.3]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[backend-api:3.0.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[backend-api:3.0.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[backend-api:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[backend-api:3.0.1]
        at com.backendapi.BackendApiApplication.main(BackendApiApplication.java:34) ~[backend-api:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ImpalaDS': Instantiation of supplied bean failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:189) ~[na:na]
        ... 20 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
        at org.apache.commons.dbcp2.BasicDataSource.<clinit>(BasicDataSource.java:87) ~[backend-api:2.7.0]
        at com.backendapi.config.ImpalaDataSourceConfig.impalaDataSource(ImpalaDataSourceConfig.java:78) ~[backend-api:na]
        at com.backendapi.config.ImpalaDataSourceConfig__BeanDefinitions.lambda$getImpalaDSInstanceSupplier$0(ImpalaDataSourceConfig__BeanDefinitions.java:31) ~[na:na]
        at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63) ~[backend-api:6.0.3]
        at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$withGenerator$0(BeanInstanceSupplier.java:173) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[backend-api:6.0.3]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[backend-api:6.0.3]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[backend-api:6.0.3]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:220) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[backend-api:6.0.3]
        ... 32 common frames omitted
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.apache.commons.dbcp2.LocalStrings, locale zh_CN_#Hans
        at java.base@17.0.5/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045) ~[backend-api:na]
        at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683) ~[backend-api:na]
        at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586) ~[backend-api:na]
        at java.base@17.0.5/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549) ~[backend-api:na]
        at java.base@17.0.5/java.util.ResourceBundle.getBundle(ResourceBundle.java:858) ~[backend-api:na]
        at org.apache.commons.dbcp2.Utils.<clinit>(Utils.java:37) ~[na:na]
```

**Comment by sbrannen** [comment] 2023-01-13 16:46
The cause of the error in the stack trace you provided is the following.

> Caused by: java.util.MissingResourceException: Can't find bundle for base name org.apache.commons.dbcp2.LocalStrings, locale zh_CN_#Hans

Have you registered the `org.apache.commons.dbcp2.LocalStrings` resource bundle _manually_ via the appropriate GraalVM native image configuration file or _programmatically_ via `org.springframework.aot.hint.ResourceHints.registerResourceBundle(String)`?

**Comment by spring-projects-issues** [comment] 2023-01-20 16:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-01-27 16:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-01-27 16:47 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder, theme: aot
