### ISSUE TITLE
Add `@Profile` support for tests

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-framework#33489] opened 2024-09-05 02:40 UTC
I'd like some tests enabled only for specified profiles, for example:

```java
@SpringJUnitConfig
abstract class TestBase {

	@Profile("foo")
	@Test
	void test_only_run_with_profile_foo() {

	}

	@Profile("bar")
	@Test
	void test_only_run_with_profile_bar() {

	}
}

@ActiveProfiles("foo")
class FooTests extends TestBase {

}

@ActiveProfiles("bar")
class BarTests extends TestBase {

}

```

There is a workaround but not elegant: `@EnabledIf(value = "#{environment.matchesProfiles('foo')}", loadContext = true)`

**Comment by sbrannen** [comment] 2024-09-05 09:51
Closing as a:

- duplicate of #20849

**Closed by sbrannen** 2024-09-05 09:51 UTC
Labels: status: waiting-for-triage, in: test
