### ISSUE TITLE
StreamingResponseBody endpoint returns an invalid object in case of 500 error code.

### ISSUE THREAD

**Issue by feco16** [spring-projects/spring-framework#27053] opened 2021-06-11 14:32 UTC
**Affects:** 5.3.8

---

When a `StreamingResponseBody` endpoint throws an exception, and it's handled by the `RestControllerAdvice` which handles as a 500 error, something strange happens. The endpoint returns the custom object and the default Spring WhiteLabel Error object together, resulting in an invalid JSON object.

I think that the problem is caused by this line https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/StreamingResponseBodyReturnValueHandler.java#L111

**Steps to reproduce:**
1. MyRestController class
```Java
@RestController
public class MyRestController {
    @GetMapping("/whiteLabelError")
    public StreamingResponseBody whiteLabelError() {
        return out -> {
            throw new RuntimeException();
        };
    }
```
2. RestControllerAdvice class
```java
import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;

@RestControllerAdvice
public class MyRestControllerAdvice extends ResponseEntityExceptionHandler {

    @ExceptionHandler(value = {RuntimeException.class})
    private ResponseEntity<Object> handleRestRuntimeException(final RuntimeException ex, final WebRequest request) {
        return handleExceptionInternal(ex, INTERNAL_SERVER_ERROR, new HttpHeaders(), INTERNAL_SERVER_ERROR, request);
    }
}
```

**The endpoint's response:**

```json
"INTERNAL_SERVER_ERROR"{
    "timestamp": 1623421573315,
    "status": 500,
    "error": "Internal Server Error",
    "path": "/exceptions/whiteLabelError"
}
```

**Comment by rstoyanchev** [comment] 2021-06-11 16:36
As [indicated](https://github.com/spring-projects/spring-framework/blob/main/CONTRIBUTING.md#create-an-issue) in our guidelines, issue descriptions should be complete, and self-sufficient. Please, edit the description to provide all details relevant details independent of SO.

**Comment by feco16** [comment] 2021-06-17 11:27
I've updated the description

**Comment by snicoll** [comment] 2023-09-25 08:55
@feco16 please move that code in text into an actual sample that we can run ourselves. In order to reproduce, we'd have to do that anyway and we might be missing a detail in doing so. Thanks!

**Comment by rstoyanchev** [comment] 2023-10-02 09:58
This is a duplicate of #30702, subsequently superseded by PR #31104, and further refined in #31154.

**Closed by rstoyanchev** 2023-10-02 09:58 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, in: web, status: feedback-reminder
