### ISSUE TITLE
`<constructor-arg>` has no effect when app is compiled/run as an AOT native image

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-framework#29087] opened 2022-09-06 09:53 UTC
I'm using the latest snapshots of boot 3 and i'm seeing that a bean with two constructors, that we've specifed using XML and the `<constructor-arg>` element, doesn't get invoked. the default-no arg constructor does. 

if i run the same code again on the JRE (ignoring AOT), then it works as expected, invoking the constructor that takes a `String`

I put together a [reproducer here](https://github.com/joshlong/spring-aot-tests-xml-constructor-args)

**Comment by snicoll** [comment] 2022-09-06 12:43
Thanks for the sample. The problem is that `<constructor-arg>` is registering a "generic" argument value, rather than an indexed argument value. AOT only supports the latter. To support the former, we'd have to massage the constructor to identify a matching argument.

**Comment by snicoll** [comment] 2022-09-09 14:16
So this turned out to be a duplicate of #27920. The example was useful as it gave us additional ideas, namely pre-converting generic types.

**Closed by snicoll** 2022-09-09 14:16 UTC
Labels: in: core, type: enhancement, theme: aot
