### ISSUE TITLE
@PreDestroy methods: messages logged with logback are lost

### ISSUE THREAD

**Issue by Katharsas** [spring-projects/spring-framework#24431] opened 2020-01-26 22:59 UTC
Affected:
Spring MVC: 5.2.2 (and older most likely)
Logback Version: 1.2.3

When using SLF4J with logback to log in a `@PreDestroy` method of a `@Service` class, the messages are lost because apparently logback shuts itself down before the user's `@PreDestroy` methods complete. Its easy to not notice the missing logs for a while.

The current workaround is to disable the servlet lifecycle feature of logback. Ideally either Spring or Logback would figure out when to shut Logback down without users having to workaround this (btw, i don't know if the current workaround has any negative effects like preventing proper Logback shutdown).

This is basically the same issue as:
https://stackoverflow.com/questions/47184045/spring-predestroy-no-logging-because-logback-stops-too-soon
and similar to (but for Spring instead of Spring Boot and logback instead of Log4j2):
https://github.com/spring-projects/spring-boot/issues/11360

**Comment by rstoyanchev** [comment] 2020-01-27 17:21
You could try a web-fragment to your WAR mode that fixes the order of spring_web relative to other fragments with a declaration like this:

```xml
<absolute-ordering>
    <others/>
    <name>spring_web</name>
    <name>ch.qos.logback.classic.servlet.LogbackServletContainerInitializer</name
</absolute-ordering>
```

If this can be confirmed to work, I can add something to our docs, but I don't think we are in a position to control the order of `ServletContainerInializer`s are invoked.

This reminds me also of a [recent change](https://bz.apache.org/bugzilla/show_bug.cgi?id=64021) in Tomcat related to the order of SCI initialization. If you're using Tomcat it's worth trying one of the fixed versions to see if it makes a difference.

**Comment by spring-issuemaster** [comment] 2020-02-03 17:22
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-02-10 17:26
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-02-10 17:26 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
