### ISSUE TITLE
Support SpEL expressions in @Qualifier

### ISSUE THREAD

**Issue by mwisnicki** [spring-projects/spring-framework#28981] opened 2022-08-19 22:12 UTC
If `@Qualifier` supported SpEL it would make configuration driven selection of beans much easier.

```java

interface Provider {}

@Component @Qualifier("file") class FileProvider implements Provider {}
@Component @Qualifier("db") class DbProvider implements Provider {}

class Service {
  @Autowired @Qualifier("${app.provider}") Provider;
}
```

Saves me from creating config class with multiple `@ConditionalOnProprety` beans.

**Comment by mwisnicki** [comment] 2022-08-19 22:16
Forgot to mention this is for the case where one need both instances to exist in the app.
Otherwise you can put `@Conditional` on implementation classes.

**Comment by snicoll** [comment] 2022-08-22 03:34
Thanks for the suggestion. This is a duplicate of https://github.com/spring-projects/spring-framework/issues/27283

**Closed by snicoll** 2022-08-22 03:34 UTC
Labels: status: waiting-for-triage
