### ISSUE TITLE
Possible connection leak in combination of webflux with spring-data-redis-reactive

### ISSUE THREAD

**Issue by vadger** [spring-projects/spring-framework#24083] opened 2019-11-26 11:20 UTC
Hello,

we're using redis pub-sub via spring-data-redis-reactive to stream events to client (webapp and mobile) using SSE (server sent events). In short each customer has own channel where events are streamed. Client opens a connection and listens for incoming events. Periodically connection is terminated by proxy and client reopens it. Typically there very few events are sent. With such behaviour we discovered that redis connections opened by client when events stream is created are not closed when event stream is cancelled (connection termination either by a client or proxy). We started getting very weird NPE-s caused by exceeding direct memory buffer limit (lettuce is using by default direct memory). After experimenting we came to conclusion that redis connections are not closed. Actually they are closed when after cancelling stream an event in sent to the channel (or two events if channel has received at least one event while being active).

We have prepared a simple project where this issue can be reproduced (see README for steps to reproduce): [https://gitlab.com/vadim-gerassimov/lettuce-sse](https://gitlab.com/vadim-gerassimov/lettuce-sse)

Current work around is periodically sending ping events to the active redis channels. 

Regards,
Vadim

**Comment by rstoyanchev** [comment] 2019-11-27 11:35
I've tried the sample and I am not able to reproduce the problem.


* "/redis-connections" --> "[1]"
* "/events"
* "/redis-connections" --> "[2]"
* "/send-message"
* "/redis-connections" --> "[2]"
* close events tab
* "/redis-connections" --> "[1]"

I also inserted a log() operator:
```java
    return redisTemplate
        .listenToChannel("some:channel:123")
        .doOnError(t -> logger.error("Error when parsing entry", t))
        .log()
        .map(ReactiveSubscription.Message::getMessage);
```

After closing the tab, I see immediately:
```
2019-11-27 11:17:05.304  INFO 2638 --- [or-http-epoll-2] reactor.Flux.Peek.1                      : cancel()
```

I am running on Linux with epoll and Chromium browser. On startup I see:

```
2019-11-27 11:16:07.173  INFO 2638 --- [or-http-epoll-2] io.lettuce.core.EpollProvider            : Starting with epoll library
2019-11-27 11:16:07.193  INFO 2638 --- [or-http-epoll-2] io.lettuce.core.KqueueProvider           : Starting without optional kqueue library
```

If you're running on something else, that could be a reason for the difference, or it might be that . Generally this is one of the weaknesses of SSE where without some sort of heartbeat mechanism, the server may not detect the client has gone away until the next attempt to write. We do have this [also mentioned](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-streaming) in the docs. 

For example you could merge with another Flux that issues an empty String periodically which the client would have to filter out:

```java
return redisTemplate
    .listenToChannel("some:channel:123")
    .doOnError(t -> logger.error("Error when parsing entry", t))
    .map(ReactiveSubscription.Message::getMessage)
    .mergeWith(Flux.interval(Duration.ofSeconds(10)).map(aLong -> ""));
```

Or a comment only event:

```java
@GetMapping(path = "/events", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
public Flux<ServerSentEvent<String>> events() {
  
  Flux<ServerSentEvent<String>> heartbeats = Flux.interval(Duration.ofSeconds(10)).map(aLong ->
          ServerSentEvent.<String>builder().comment("Heartbeat").build());
  
  return redisTemplate
  .listenToChannel("some:channel:123")
  .doOnError(t -> logger.error("Error when parsing entry", t))
  .map(message -> ServerSentEvent.builder(message.getMessage()).build())
  .mergeWith(heartbeats);
}
```

**Comment by vadger** [comment] 2019-11-27 13:00
@rstoyanchev hmm, I have a mac pro with jdk 11

The difference in startup log is that on my mac it starts without epoll

```
2019-11-27 14:49:11.372  INFO 57062 --- [           main] c.e.lettucesse.LettuceSseApplication     : Started LettuceSseApplication in 1.8 seconds (JVM running for 2.176)
2019-11-27 14:49:25.098  INFO 57062 --- [ctor-http-nio-2] io.lettuce.core.EpollProvider            : Starting without optional epoll library
2019-11-27 14:49:25.099  INFO 57062 --- [ctor-http-nio-2] io.lettuce.core.KqueueProvider           : Starting without optional kqueue library
```

But in production environment it starts with epoll and the issue exists. Let me try to deploy the sample app to some VM to see how it behaves there and if the issue can be reproduced I'll drop the link.

**Comment by rstoyanchev** [comment] 2019-11-27 13:15
@vadger, sure but just keep the general point in mind. As mentioned in the docs, disconnects are not always detected reliably, so you'll need some form of heartbeat since SSE doesn't have one built-in.

**Comment by vadger** [comment] 2019-11-27 14:49
@rstoyanchev yeah I see the docs. In this case let's close an issue if it's known that without heartbeat it might not know that connections has been already closed. Thanks for explanation.

**Comment by rstoyanchev** [comment] 2019-11-27 15:01
Okay, by the way I just recalled this issue here that is relevant https://github.com/reactor/reactor-netty/issues/283.

**Closed by rstoyanchev** 2019-11-27 15:01 UTC
Labels: status: feedback-provided, status: waiting-for-triage
