### ISSUE TITLE
parameterized tests based on spring profiles

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-framework#23680] opened 2019-09-23 17:49 UTC
I'm testing various FHIR endpoint functionality, these tests are functionally identical except an `@ActiveProfiles` I'd like to apply. Here's what I imagine writing, basically all tests in the test would be run for each parameterized profile, e.g. foo and bar, regular active profiles e.g. baz, would still be always applied.

```
@ParameterizedTestActiveProfiles("foo", "bar")
@ActiveProfiles("baz")
```

**Comment by sbrannen** [comment] 2019-09-24 10:56
Duplicate of #13977 and #20849

See also: https://github.com/junit-team/junit5/issues/878

**Closed by sbrannen** 2019-09-24 10:56 UTC
Labels: in: test, status: waiting-for-triage
