### ISSUE TITLE
Support `@ControllerAdvice` on `@Bean` factory method

### ISSUE THREAD

**Issue by piotrpolak** [spring-projects/spring-framework#25346] opened 2020-06-30 17:04 UTC
I am developing a shared component where all the configuration classes are registered using `spring.factories`.

The library provides some generic error handler implemented as a `@ControllerAdvice`.

The current implementation of `@ControllerAdvice` forces me to place the annotation on the class (see below) which makes it error prone. If the user of my component decides to use overly broad classpath scan (hypothetical situation and a bad practice) it will result in the `GlobalExceptionHandler` being registered multiple times.

```java
@Configuration
public class SharedErrorHandlerConfiguration {

    @Bean
    SharedExceptionHandler sharedExceptionHandler() {
        return new SharedExceptionHandler();
    }
}
// ...

@ControllerAdvice
public class SharedExceptionHandler {
    // ...
}
```

I would like to register the controller advice using factory method -- for example:

```java
@Configuration
public class SharedErrorHandlerConfiguration {

    @Bean
    @ControllerAdvice
    SharedExceptionHandler sharedExceptionHandler() {
        return new SharedExceptionHandler();
    }
}
// ...
// No annotation here
public class SharedExceptionHandler {
    // ...
}
```

Could you please change the target of the `@ControllerAdvice` annotation from `@Target(ElementType.TYPE)` to `@Target({ElementType.TYPE, ElementType.METHOD})` to support controller advice defined using factory method?

**Comment by sbrannen** [comment] 2023-09-28 12:50
> Could you please change the target of the `@ControllerAdvice` annotation from `@Target(ElementType.TYPE)` to `@Target({ElementType.TYPE, ElementType.METHOD})` to support controller advice defined using factory method?

Although `@ControllerAdvice` may not be declared on a method (by design), there's nothing stopping you from creating your own custom annotation like the following.

```java
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@ControllerAdvice
public @interface MyControllerAdvice {
}
```

If you use that in your example, it works as you would expect.

```java
@Configuration
public class SharedErrorHandlerConfiguration {

    @Bean
    @MyControllerAdvice
    SharedExceptionHandler sharedExceptionHandler() {
        return new SharedExceptionHandler();
    }
}
// ...
// No annotation here
public class SharedExceptionHandler {
    // ...
}
```

**Comment by bclozel** [comment] 2023-09-28 18:33
I fail to understand how enabling this would prevent mistakes when developers configure classpath scanning in your library package. With this, your `@Configuration` class would be scanned and parsed anyway.

Sorry it took us so long to get to your issue; if you're still struggling with such issues, maybe giving a better picture of your library and its configuration setup would help us think about other solutions.

In the meantime, I'll close this issue as we are declining the proposed solution.

**Closed by bclozel** 2023-09-28 18:33 UTC
Labels: status: waiting-for-triage, in: web
