### ISSUE TITLE
Circular bean reference error in Spring Boot v2.6.0 and above

### ISSUE THREAD

**Issue by fteran** [spring-projects/spring-framework#28463] opened 2022-05-15 12:44 UTC
The same project running in Spring Boot v2.5.13 runs without any errors, but when upgrading to Spring Boot v2.6.0 or above it fails with error message:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:
```

How to reproduce:
Check working code from https://github.com/fteran/spring-security-oauth-demo.git
Update pom.xml line 8 to `<version>2.6.0</version>`
Run project by executing command: .\mvnw spring-boot:run

**Comment by sbrannen** [comment] 2022-05-15 13:00
Closing as a duplicate of https://github.com/spring-projects/spring-boot/issues/30854 in the Spring Boot issue tracker.

**Closed by sbrannen** 2022-05-15 13:00 UTC
Labels: status: waiting-for-triage
