### ISSUE TITLE
Blocking call according to BlockHound in spring-tx

### ISSUE THREAD

**Issue by kurt-jadson** [spring-projects/spring-framework#27040] opened 2021-06-08 18:01 UTC
**Summary**: When making some transactional insert/update/delete to database I get a blocking call issue (Tracked by Block Hound)
This is related with UUID class because SecureRandom uses /dev/random which has block behaviour.

**Alternative:** Replace SecureRandom by /dev/urandom is not an alternative in my case, can you provide a fix for non blocking thread in this case?

** Source of the problem**: [this line](https://github.com/spring-projects/spring-framework/blob/000b6a7e9500b81986b21c42b72198aff89fe9ae/spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionContext.java#L43)

**Stack trace**:
````
		at java.io.FileInputStream.readBytes(FileInputStream.java) ~[?:?]
		at java.io.FileInputStream.read(FileInputStream.java:279) ~[?:?]
		at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:?]
		at sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424) ~[?:?]
		at sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:526) ~[?:?]
		at sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:545) ~[?:?]
		at sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220) ~[?:?]
		at java.security.SecureRandom.nextBytes(SecureRandom.java:751) ~[?:?]
		at java.util.UUID.randomUUID(UUID.java:150) ~[?:?]
		at org.springframework.transaction.reactive.TransactionContext.<init>(TransactionContext.java:43) ~[spring-tx-5.3.7.jar:5.3.7]
		at org.springframework.transaction.reactive.TransactionContext.<init>(TransactionContext.java:60) ~[spring-tx-5.3.7.jar:5.3.7]
		at org.springframework.transaction.reactive.TransactionContextHolder.createContext(TransactionContextHolder.java:63) ~[spring-tx-5.3.7.jar:5.3.7]
		at org.springframework.transaction.reactive.TransactionContextManager.lambda$getOrCreateContext$2(TransactionContextManager.java:91) ~[spring-tx-5.3.7.jar:5.3.7]
````

**Version:** org.springframework:spring-tx:5.3.7

**Comment by jhoeller** [comment] 2021-06-08 21:20
This is a duplicate of #26955 - we're revisiting that UUID generation call for 5.3.9, probably switching to a simpler id generation strategy (since the id is mostly just used for logging anyway).

**Closed by jhoeller** 2021-06-08 21:20 UTC
Labels: status: duplicate
