### ISSUE TITLE
HibernateJpaDialect: Default to MySQL55Dialect based on InnoDB [SPR-16468]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21013] opened 2018-02-05 16:12 UTC
**[Mike Eltsufin](https://jira.spring.io/secure/ViewProfile.jspa?name=meltsufin)** opened **[SPR-16468](https://jira.spring.io/browse/SPR-16468?redirect=false)** and commented

`MySQL5Dialect` set currently as default is based on the MyISAM storage engine, which is not recommended.
MySQL 5.5 has been out since 2010. So, it's pretty safe to go with it as the default dialect.

Related to: https://github.com/spring-cloud/spring-cloud-gcp/issues/392.

See PR: https://github.com/spring-projects/spring-framework/pull/1660

---

**Affects:** 5.0.3

**Reference URL:** https://stackoverflow.com/questions/1459265/hibernate-create-mysql-innodb-tables-instead-of-myisam

**Issue Links:**
- #21005 Add SAP HANA to common JPA database platforms

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1660

1 votes, 4 watchers

**Comment by snicoll** [comment] 2019-03-08 15:12
Duplicate of #22326

**Closed by snicoll** 2019-03-08 15:12 UTC
Labels: in: data, type: enhancement
