### ISSUE TITLE
`NestedRuntimeException` cannot be logged to JSON

### ISSUE THREAD

**Issue by adamzr** [spring-projects/spring-framework#27167] opened 2021-07-14 01:25 UTC
**Affects:** all
---
Spring has an exception called `NestedRuntimeException`. We use log4j2 with a JSON logger. That exception (and its many children) cannot be logged, they blow up the logger because `getMostSpecificCause` returns a self-reference if there is no cause on the exception.

I guess this falls somewhere between a bug report and a feature request. I think that many people use JSON logging and log exceptions, therefore it would be nice if all exceptions could be serialized safely with Jackson.

I just need an annotation on that method to tell Jackson to ignore it.

Thanks!

**Comment by sdeleuze** [comment] 2023-10-24 09:14
Hi, and sorry for the delay. Could you please provide a reproducer (as an archive or a Git repository) to allow us to see the behavior you are describing?

**Comment by adamzr** [comment] 2023-10-24 17:57
@sdeleuze To reproduce make an exception that extends NestedRuntimeException (or use one of the many existing ones). Throw that exception and log it out.

Use log4j2 by adding:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
``` to your `pom.xml` file (if you use Maven).

Put a file in src/main/resources called `log4j2.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <CustomLevels>
        
        <CustomLevel name="CLIENT_DATA" intLevel="550"/>
    </CustomLevels>
    <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
            <JsonLayout eventEol="true" compact="true"
                properties="true" includeTimeMillis="true"
                objectMessageAsJsonObject="true">
                <KeyValuePair key="java-version"
                    value="${java:version}" />
                <KeyValuePair key="java-runtime"
                    value="${java:runtime}" />
                <KeyValuePair key="java-vm"
                    value="${java:vm}" />
                <KeyValuePair key="java-os"
                    value="${java:os}" />
                <KeyValuePair key="java-locale"
                    value="${java:locale}" />
                <KeyValuePair key="java-hw"
                    value="${java:hw}" />
            </JsonLayout>
        </Console>
    </Appenders>
    <Loggers>
        <asyncLogger
            name="org.springframework"
            level="debug" />
        <asyncRoot level="debug">
            <AppenderRef ref="STDOUT" />
        </asyncRoot>
    </Loggers>
</Configuration>
```
(or something similar).

I do not believe that this is unique to Log4j2.
I think you need to:

1. Throw an exception that extends NestedRuntimeException
2. Log it out
3. Configure your logger to log only JSON

NestedRuntimeException has a circular reference. It cannot easily be converted to JSON and it therefore crashes the logger.

**Comment by sbrannen** [comment] 2023-10-25 08:43
@adamzr, thanks for providing the additional information.

Please note that `NestedRuntimeException` is not designed for recursive introspection of its getter methods. In addition, `getMostSpecificCause()` is documented to return a reference to the "present exception if there is no root cause".

Thus, `NestedRuntimeException` works as designed.

> I just need an annotation on that method to tell Jackson to ignore it.

We unfortunately cannot add a Jackson-specific annotation to `NestedRuntimeException`.

To address the recursion you are encountering, you will either need to ask the maintainers of `JsonLayout` to introduce support for excluding specific properties or implement your own extension of `JsonLayout` that allows you to do that.

Examples of the latter can be found on the Internet -- for example, [How to customize or remove default attributes in Log4j2 - JSON Layout](https://stackoverflow.com/questions/61620495/how-to-customize-or-remove-default-attributes-in-log4j2-json-layout).

In light of that, I am closing this issue.

**Closed by sbrannen** 2023-10-25 08:43 UTC
Labels: status: declined, in: core

**Comment by adamzr** [comment] 2023-10-25 17:52
@sbrannen I think you should keep this ticket open as a feature request rather than as a bug.

As you noted NestedRuntimeException is not designed for recursive introspection of its getter methods. I am asking to change that design.

Logging exceptions is one of the most common kind of objects to log.

Outputting logs in JSON is [a best practice](https://paul.querna.org/articles/2011/12/26/log-for-machines-in-json/) and one of the most common ways of emitting structured log messages. It is recommended by [Loggly](https://www.loggly.com/use-cases/what-is-structured-logging-and-how-to-use-it/), [Elastic](https://www.elastic.co/blog/structured-logging-filebeat), [Loki](https://grafana.com/blog/2022/05/16/all-things-logs-best-practices-for-logging-and-grafana-loki/#:~:text=it%E2%80%99s%20fine%20to%20log%20json%2C%20it%E2%80%99s%20ubiquitous%2C%20and%20all%20of%20the%20logging%20tools%20work%20with%20it%20well.), [Splunk](https://dev.splunk.com/enterprise/docs/developapps/addsupport/logging/loggingbestpractices/#Use-developer-friendly-formats), and pretty much every other logging system.

So, while I agree that this issue can be worked around, I think it is a common issue that Spring should help people avoid.
