### ISSUE TITLE
Custom annotations not working in upgrading from 2.0.8 to spring 2.3.4

### ISSUE THREAD

**Issue by nandwaniS** [spring-projects/spring-framework#26717] opened 2021-03-23 18:08 UTC
Issue is similar to https://stackoverflow.com/questions/60184960/componentscan-does-not-find-own-custom-annotations-after-update-from-spring-boot where the custom annotation is not being read by MetadataReaderFactory in class reader. For previous versions, the annotation was being read by the class reader.

**Affects** : spring-framework 5.2.9, 
Is it a known issue or the later versions of spring have fixed it? I tried using 5.3.3 spring framework but the class reader doesnt read the annotation still. Please note that we do not have any Retention policy specified earlier, do we need to add retention policy as runtime to our annotation to make it work? Issue doesnt occur in 5.0.12

---

**Comment by snicoll** [comment] 2021-03-24 08:43
> Do we need to add retention policy as runtime to our annotation to make it work

Yes. Arguably, an annotation without retention worked so far by accident. It really should have one to begin with.

Duplicate of #21502

**Closed by snicoll** 2021-03-24 08:43 UTC
Labels: status: waiting-for-triage
