### ISSUE TITLE
DispatcherServlet did not process request in Spring 3.0.3 version.

### ISSUE THREAD

**Issue by caltinsoy** [spring-projects/spring-framework#30038] opened 2023-02-26 19:03 UTC
**Affects:** \<**3.0.3**>

---

I tried send basic get requests with **Spring 3.0.3** version and probably DispatcherServlet can not process request. But I saw a couple of  log ,like  :

INFO 21148 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
INFO 21148 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
INFO 21148 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms

I also created another demo project to process basic Get request  and there was no problem. I used Spring  **2.7.9.** . I used Java 17 in both of them.

Same controller class ,
First project's (**demo**)  pom's parent like :  (3.0.3)

```
  <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.3</version>
        <relativePath/> 
    </parent>
```

Second project's (**demo1**) pom's parent like : (2.7.9)

```
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.9</version>
        <relativePath/> 
    </parent>
```

```
@RestController
public class PaymentController {
    @GetMapping("/hello")
    public void test()  {
        System.out.println("Hello World!");
    }
}
```

I also added projects .
[demo.zip](https://github.com/spring-projects/spring-framework/files/10834478/demo.zip)
[demo1.zip](https://github.com/spring-projects/spring-framework/files/10834480/demo1.zip)

**Comment by bclozel** [comment] 2023-02-27 05:28
I think this is a duplicate of #30031. If there is no space character in your application path we can reopen this issue.

**Closed** 2023-02-27 05:28 UTC
Labels: status: duplicate, in: core
