### ISSUE TITLE
No primary or single unique constructor found for interface org.springframework.http.codec.multipart.FilePart

### ISSUE THREAD

**Issue by huberchrigu** [spring-projects/spring-framework#31790] opened 2023-12-08 11:44 UTC
I have a `@RestController` with the method 
```kotlin
@PostMapping 
fun uploadDocument(@Valid data: UploadData, exchange: ServerWebExchange)
```
where `UploadData` contains a field
```kotlin
@field:NotNull(message = "file must not be null") private val file: FilePart?
```
Before the upgrade to Spring Boot 3.2.0, the Bean Validation worked as expected if "file" was missing in the request body. Since the Spring upgrade, I get the exception "No primary or single unique constructor found for interface org.springframework.http.codec.multipart.FilePart" instead.

**Comment by snicoll** [comment] 2023-12-08 13:08
Thanks for the report, this is a duplicate of #31669.

**Closed by snicoll** 2023-12-08 13:08 UTC
Labels: status: waiting-for-triage

**Comment by sbrannen** [comment] 2023-12-08 13:12
And potentially a duplicate of #31778, if the affected code is using WebFlux instead of MVC.
