### ISSUE TITLE
SEVERE [https-jsse-nio-8443-Acceptor] org.apache.tomcat.util.net.Acceptor.run Socket accept failed

### ISSUE THREAD

**Issue by Parashuraam** [spring-projects/spring-framework#29073] opened 2022-09-05 08:55 UTC
Hi Team,

      can someone help me with the below issue?

     OS Name:  Red Hat Enterprise Linux Server
     OS Version: 7.9 (Maipo)
     OS Kernel :  3.10.0-1160.76.1.el7.x86_64
     Tomcat Server version: Apache Tomcat/9.0.58
     Server version: Apache Tomcat/9.0.58
     Architecture:   amd64
     JVM Version:    1.8.0_221-b32
     JVM Vendor:     Oracle Corporation
     :: Spring Boot ::        (v2.1.2.RELEASE)

      **ERROR :**

      04-Sep-2022 13:05:47.165 SEVERE [https-jsse-nio-8443-Acceptor] org.apache.tomcat.util.net.Acceptor.run Socket accept failed
        java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
                at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:548)
                at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78)
                at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
                at java.lang.Thread.run(Thread.java:748)

**Comment by bclozel** [comment] 2022-09-05 09:32
This is a duplicate of #26434, but related to Spring Framework. See [Mark's comment for proper resolution](https://github.com/spring-projects/spring-framework/issues/26434#issuecomment-1003713436).

**Closed by bclozel** 2022-09-05 09:32 UTC
Labels: status: waiting-for-triage

**Comment by Parashuraam** [comment] 2022-09-05 09:37
please can you tell me solution steps for it.

**Comment by bclozel** [comment] 2022-09-05 09:56
Please read the comment I've pointed to. This is related to an OS bug. Follow Mark's advice for resolution.

**Comment by btpnlsl** [comment] 2022-09-06 03:21
@bclozel The OS bug in the Linux TCP/IP stack was fixed in version 5.10-rc6 of the Linux kernel and was backported to LTS versions of the kernel as well.  I don't think it is helpful to continue to report this to Ubuntu as requested by Mark as they have already incorporated this bugfix into their LTS versions. The best solution now is to look for an OS version which incorporates the fix.

@Parashuraam You would need to update your OS (RedHat) and investigate to determine which versions of RedHat have incorporated the bugfix.    

The bugfix you are looking for is this one: [https://github.com/torvalds/linux/commit/01770a166165738a6e05c3d911fb4609cc4eb416](https://github.com/torvalds/linux/commit/01770a166165738a6e05c3d911fb4609cc4eb416)

**Comment by y0zg** [comment] 2022-09-21 08:22
Does anyone know how to fix this on AWS EKS? 
I see the latest kernel version in AMIs - 5.4 https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md
