### ISSUE TITLE
Server request URL with spring-webflux 6.0.5 is in resolved IP6 format

### ISSUE THREAD

**Issue by intosoft** [spring-projects/spring-framework#30033] opened 2023-02-25 11:36 UTC
After upgrade to spring boot 3.0.3, **Swagger authorization** stopped working on `http://localhost:8080`.

![image](https://user-images.githubusercontent.com/5756904/221354661-2474985f-fec3-46b6-9c49-5941e4acaf0f.png)

The issue is caused by changed method:

```java
private static URI resolveBaseUrl(HttpServerRequest request) throws URISyntaxException {
		String scheme = getScheme(request);

		InetSocketAddress hostAddress = request.hostAddress();
		...
}
```

From:

```java
private static URI resolveBaseUrl(HttpServerRequest request) throws URISyntaxException {
		String scheme = getScheme(request);
		String header = request.requestHeaders().get(HttpHeaderNames.HOST);
		...
}
```

The root cause of issue is that instead of resolving host to `http://localhost`, it resolves `http://[0:0:0:0:0:0:0:1]`.

The main functionality of swagger works with this IP address, but **authorization fails** because it redirects to:

![image](https://user-images.githubusercontent.com/5756904/221354738-6f282ff7-180f-4cfa-bf95-fc18c0f7a3dc.png)

To fix that issue I can set `server.address`, but then it breaks accessing swagger by external IP.

I found the issue after checking swagger, but rest of application works fine. Should openapi be fixed or `resolveBaseUrl` method?

Even enforcing IP4 by `-Djava.net.preferIPv4Stack=true` does not solve issue.

Downgrading to spring-web 6.0.4 solves the issue. Also using IP instead of DSN does not generate such issues.

**Comment by intosoft** [comment] 2023-02-27 14:35
@bclozel - thanks for handling this.

**Comment by wilkinsona** [comment] 2023-02-27 17:26
We suspect that https://github.com/spring-projects/spring-boot/issues/34395 is another symptom of the same underlying problem.

**Comment by rstoyanchev** [comment] 2023-02-27 18:40
Indeed, both this issue and https://github.com/spring-projects/spring-boot/issues/34395 are linked to the change in #28601. 

I tried the sample from https://github.com/spring-projects/spring-boot/issues/34395, and the case there is an "X-Forwarded-Host" that contains both host and port (e.g. "localhost:3000"). When we parse the "Host" header ourselves, we handle this case. However, when relying on Reactor's `request.hostAddress()`, the `hostString` in it has the port and so the `java.net.URI` constructor fails with such a host. @violetagg, is there another Reactor request method we should use that takes care of this, or should we always parse the `hostString` we get from `requst.hostAddress()` just like we [parse the "Host" header](https://github.com/spring-projects/spring-framework/blob/c859211f7a312e625a408a8d03fad8e17667d719/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpRequest.java#L88-L109)? 

The case reported here is a little different. It looks like `request.hostAddress()` has a `hostString` that differs from what's in the "Host" header. I'm not clear on how we would decide when to use one or the other. @violetagg any insight fro your side would be appreciated.

**Comment by bclozel** [comment] 2023-02-28 07:02
See #30047 for a possible fix involving Netty's ˋNetUtil`.

**Comment by rstoyanchev** [comment] 2023-02-28 08:00
#30047 looks more of an optimization that avoids an extra URI creation. I'm not sure it solves the issues here, but worth to consider at the same time.

**Comment by rstoyanchev** [comment] 2023-02-28 12:26
As expected, Netty's `NetUtil` doesn't do anything for a `hostString` that has a port, so #30047 doesn't help for https://github.com/spring-projects/spring-boot/issues/34395, and I suspect it doesn't help for this issue either, but I have no way to confirm that. 

@intosoft  if you can provide an isolated sample to debug or verify changes with, that would be very helpful

**Comment by msosa** [comment] 2023-02-28 13:37
But <host> according to them may _optionally_ include a port

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

> The Host request header specifies the host and port number of the server to which the request is being sent.

I would think that `X-Forwarded-Host` would be closely related to just the `Host` header

**Comment by violetagg** [comment] 2023-02-28 13:42
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host
@msosa 

[Syntax]
Host: <host>:<port>

[Directives]
<host>
the domain name of the server (for virtual hosting).

<port> Optional
TCP port number on which the server is listening.

[Examples]
Host: developer.mozilla.org

**Comment by rstoyanchev** [comment] 2023-02-28 14:13
Also the port is present in both `"X-Forwarded-Port: 3000"` and `"X-Forwarded-Host: localhost:3000"`, and it's not clear why does it have to be in "X-Forwarded-Host", but also creates ambiguity. They are the same in this case, but generally when both are present one would have to be preferred over the other. This is why it makes sense that "X-Forwarded-Host" is for the host (only) while the port is specified via "X-Forwarded-Port".

**Comment by msosa** [comment] 2023-02-28 14:29
I definitely agree that it is odd to have the port in the `X-Forwarded-Host`, not sure why my frontend proxy sends the header in that way.

I did think that `Host` could include port and `X-Forwarded-Host` is just a forwarded header of that. But if that's not the case I'll try and find another proxy that sends the header correctly, or just stick with `framework` strategy until it changes similarly

**Comment by abelsromero** [comment] 2023-02-28 15:02
We found a related issue when running spring-cloud-gateway with oauth spring-security integration. The redirect_uris sent to the auth server now contain the port (even when using 80) and when running with `localhost` they are sent as `127.0.0.1`. That means the admin needs to change the auth server configuration.
I narrowed it down to the actual commit related to https://github.com/spring-projects/spring-framework/issues/28601 issue. A custom build of 6.0.5 without that commit works fine.

**Comment by violetagg** [comment] 2023-02-28 15:06
> We found a related issue when running spring-cloud-gateway with oauth spring-security integration. The redirect_uris sent to the auth server now contain the port (even when using 80) and when running with `localhost` they are sent as `127.0.0.1`. That means the admin needs to change the auth server configuration.
> I narrowed it down to the actual commit related to #28601 issue. A custom build of 6.0.5 without that commit works fine.

This is related to the first issue isn't it? Not the one with `X-Forwarded-For`?

**Comment by msosa** [comment] 2023-03-01 09:00
Here is an [example](https://github.com/msosa/swagger-webflux) that reproduces the problem for the first issue(the non `X-Forwarded-For` issue). The `Servers` dropdown represents the url as
```
http://[0:0:0:0:0:0:0:1]:8080 - Generated server url
```
instead of 
```
http://localhost:8080 - Generated server url
```

**Comment by aperusset** [comment] 2023-03-01 09:14
Hello everyone ! FYI, to "quick fix" this issue, I found two "temporaray" solutions (of which I am not aware of the side effects).

1. Add these properties to `application.yml` file :

```yaml
server.address: 127.0.0.1
management.server.address: 127.0.0.1
```
2. Add a command line argument to the JVM : `-Djava.net.preferIPv4Stack=true`

I know it's not ideal, but this may help while waiting for a better solution.

**Comment by rstoyanchev** [comment] 2023-03-01 12:38
Thanks for the sample @msosa. I can't load the `index.html` page, probably because I'm not running an API server, but the problem is easy to see anyway. The Reactor Netty `request.hostAddress()` resolves to an IPv6 address while the "Host" header, which we used before has a host name. That's one of the issues.

The other one is that with and "X-Forwarded-Host" that has host and port. Probably Reactor Netty can be enhanced to take care of that.

@abelsromero yes [we know it's linked](https://github.com/spring-projects/spring-framework/issues/30033#issuecomment-1446861090) to that change, but it isn't as simple as reverting it, and we need to understand the scenarios in order for a fix.

**Comment by violetagg** [comment] 2023-03-01 15:33
For the issue with `X-Forwarded-Host`, are you able to test Reactor Netty `1.0.29-SNAPSHOT`/`1.1.4-SNAPSHOT`
(https://repo.spring.io/snapshot)

**Comment by rstoyanchev** [comment] 2023-03-01 21:15
I've scheduled this for 6.0.6, as we are expecting a change in Reactor Netty to provide a `serverName` and `serverPort`, and we are going to build on it.

The `X-Forwarded-Host` issue should already have a fix in the latest Reactor Netty 1.1.4 snapshot. @msosa, I've checked with your sample but if you can also confirm from your end, that would be great.

**Comment by msosa** [comment] 2023-03-02 01:18
Yes, the enhancement works on my project as well, thank you!

Something to note though, when I set my UI port to 80 and go to `http://localhost` the OAuth redirect URI is generated with `http://localhost:80` instead of `http://localhost`. Not sure if this is something that needs to be looked at or not, but if you would like a repo for this I can post one.

**Comment by violetagg** [comment] 2023-03-02 06:03
> Yes, the enhancement works on my project as well, thank you!
> 
> Something to note though, when I set my UI port to 80 and go to `http://localhost` the OAuth redirect URI is generated with `http://localhost:80` instead of `http://localhost`. Not sure if this is something that needs to be looked at or not, but if you would like a repo for this I can post one.

This will be address with the changes that we are preparing for the other issue.

**Comment by rstoyanchev** [comment] 2023-03-02 10:29
We now have https://github.com/reactor/reactor-netty/issues/2711 and https://github.com/spring-projects/spring-framework/pull/30062 in place, and #30062 which takes advantage of the new `hostName` and `hostPort` request properties. So in effect this is superceded by #30062.

**Comment by rstoyanchev** [comment] 2023-03-02 10:53
There is now a 6.0.6 snapshot available with the changes. If you have the option to test, please give it a try together with Reactor-Bom 2022.0.4 snapshot.

I'll close this as superseded, but please feel free to add more comments.

**Closed by rstoyanchev** 2023-03-02 10:53 UTC
Labels: in: web, type: regression, status: superseded

**Comment by rstoyanchev** [comment] 2023-03-02 11:12
Thanks @msosa and @abelsromero for confirming the changes.
