### ISSUE TITLE
5.3.27 spring-aop modified classLoader not work for osgi classloader

### ISSUE THREAD

**Issue by pymBupt** [spring-projects/spring-framework#30626] opened 2023-06-09 11:23 UTC
spring version: 5.3.27
code work with 5.3.26 but 5.3.27 throw exception
```
java.lang.IllegalArgumentException: interface com.xx.XxReadService is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:131)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
```

5.3.27, org.springframework.aop.framework.JdkDynamicAopProxy#getProxy(java.lang.ClassLoader)
![image](https://github.com/spring-projects/spring-framework/assets/13072392/c21b8954-20c3-4be1-8fe3-85d360331421)
why modify classLoader? my self defined classLoader's parent is null，and my self defined classLoader import Spring classes (use osgi tech), but not import com.xx.XxReadService class.

5.3.26, org.springframework.aop.framework.JdkDynamicAopProxy#getProxy(java.lang.ClassLoader)
![image](https://github.com/spring-projects/spring-framework/assets/13072392/79d2bbf3-8fed-4d03-83b2-7122a5c7bf05)

**Comment by sbrannen** [comment] 2023-06-09 11:42
- duplicate of  #30389

**Closed by sbrannen** 2023-06-09 11:42 UTC
Labels: status: waiting-for-triage
