### ISSUE TITLE
Release a version to Jakarta EE 9

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-framework#26224] opened 2020-12-06 08:38 UTC
Before the Spring framework moving to the Jakarta EE 9/10 stack. I hope Spring can consider releasing a Jakarta EE 9.0 version alongside the Jakarta EE 8.0 release(eg. a Maven artifact classifier **jakartaee9** or a specific version number) at the same time.
There are several projects that used [Eclipse Transformer tooling](https://projects.eclipse.org/projects/technology.transformer) to convert the existing work to Jakarta EE 9 automatically, such as Apache TomEE, WildFly 22.0.0 Jakarta EE preview.

**Comment by hantsy** [comment] 2020-12-06 08:51
Similar to https://github.com/spring-projects/spring-framework/issues/25354

**Comment by rwinch** [comment] 2021-06-01 14:30
Closing as duplicate of gh-25354

**Closed by rwinch** 2021-06-01 14:30 UTC
Labels: status: waiting-for-triage
