### ISSUE TITLE
Unable to compile spring native executable: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by KaeYan93** [spring-projects/spring-framework#31593] opened 2023-11-11 07:19 UTC
Hi, the details as shown below:

Graalvm jdk: JDK 17.0.8, JDK17.0.9
OS building spring native: Windows 10
Causes: Import any opensaml 5.0.0 libraries will cause this compile issue
```
<dependency>
  <groupId>org.opensaml</groupId>
  <artifactId>opensaml-xmlsec-api</artifactId>
  <version>${opensaml.version}</version>
</dependency>
```

This is the error printout:
```
[2/8] Performing analysis...  [******]                                                                 (151.0s @ 4.24GB)
  37,312 (93.35%) of 39,969 types reachable
  62,887 (70.25%) of 89,523 fields reachable
 197,000 (65.91%) of 298,905 methods reachable
  12,296 types, 1,938 fields, and 14,886 methods registered for reflection
      85 types,    78 fields, and    70 methods registered for JNI access
       5 native libraries: crypt32, ncrypt, psapi, version, winhttp
[3/8] Building universe...                                                                              (18.4s @ 4.42GB)
[4/8] Parsing methods...      [*******]                                                                 (52.5s @ 3.76GB)
[5/8] Inlining methods...     [****]                                                                     (5.0s @ 3.40GB)
[6/8] Compiling methods...    [*************]                                                          (173.0s @ 3.48GB)

Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.StackOverflowError
        at method: void org.bouncycastle.pqc.crypto.falcon.FalconKeyGen.poly_sub_scaled(int[], int, int, int, int[], int, int, int, int[], int, int, int, int)  [Direct call from int FalconKeyGen.solve_NTRU_intermediate(int, byte[], int, byte[], int, int, int[], int)]
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1297)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1226)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:300)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.StackOverflowError
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.b(stripped:372)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.a(stripped:364)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:338)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
        at com.oracle.graal.graal_enterprise/com.oracle.graal.vector.phases.ConditionalMoveOptimizationPhase.c(stripped:341)
------------------------------------------------------------------------------------------------------------------------
                       31.4s (7.4% of total time) in 151 GCs | Peak RSS: 7.95GB | CPU load: 6.42
========================================================================================================================
Finished generating 'starter' in 7m 4s.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:38 min
[INFO] Finished at: 2023-11-11T15:06:16+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.27:compile (default-cli) on project starter: Execution of C:\Users\d1311295\dev\GraalVM\graalvm-jdk-17.0.8+9.1\bin\native-image.cmd @target\tmp\native-image-310120471704715510.args returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by KaeYan93** [comment] 2023-11-11 07:20
The reproducer is here:
https://drive.google.com/file/d/1Yq_GvXtth8wBnjuJ09sTyyv8B4J_w8NG/view?usp=sharing

**Comment by bclozel** [comment] 2023-11-11 08:03
Closing as a duplicate of https://github.com/oracle/graal/issues/7801

**Closed** 2023-11-11 08:04 UTC
Labels: status: waiting-for-triage
