### ISSUE TITLE
DefaultMultipartMessageReader Not Parsing MultiPart Form Message Correctly

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-projects/spring-framework#23003] opened 2019-05-20 18:40 UTC
It seems like the introduction of `DefaultMultipartMessageReader` may not be parsing the message correctly.

https://github.com/spring-projects/spring-framework/commit/fb642ce7235d390323081d6b158a7a74b623a595

After the introduction of this class, a test in Spring Cloud Gateway that was working started failing.  All the test does is use WebClient to create a multipart form request.  When Netty receives this request it fails with 

```
java.lang.IllegalArgumentException: text is empty (possibly HTTP/0.9)
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:65) ~[netty-codec-http-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87) ~[netty-codec-http-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:210) ~[netty-codec-http-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:103) ~[netty-codec-http-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

The test can be found here 
https://github.com/spring-cloud/spring-cloud-gateway/blob/master/spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/test/FormIntegrationTests.java#L73

**Comment by rstoyanchev** [comment] 2019-05-20 20:00
The `DefaultMultipartMessageReader` was added in 5.2 M2 so presumably if you change to M1 it works?

**Comment by ryanjbaxter** [comment] 2019-05-20 20:16
@rstoyanchev it is hard to tell because switching back to previous Boot releases causes other errors so I can't test it out.

**Comment by poutsma** [comment] 2019-05-21 14:27
I've tried reproducing that same test case in Spring Framework (i.e. without Spring Cloud Gateway) and it works fine there. So whatever the problem is, it is somewhere higher in the stack.

One major difference between the new `DefaultMultipartMessageReader` and the `SynchronossPartHttpMessageReader` (which was used before) is that we no longer cache the part bodies. This means that if Cloud Gateway (or something else) inspects the multipart data (for instance in order to do routing), that data is no longer available for the controller to read. I don't know enough about Spring Cloud Gateway to know if that is happening.

One thing that I've noticed while debugging this issue, which seems odd and might be related: for some reason, in a Spring Cloud Gateway app `HttpWebHandlerAdapter.handle(ServerHttpRequest, ServerHttpResponse)` is invoked *twice*, while in a Spring Framework test it is invoked only once. This might be related, because that same `handle` method creates a `DefaultServerWebExchange`, which in turn calls `DefaultServerWebExchange.initMultipartData`, which of course uses the `DefaultMultipartMessageReader`.

**Comment by spencergibb** [comment] 2019-05-21 17:53
@poutsma I think the reason it is called twice is because the gateway is proxying to itself (ie the endpoint is in the same application as the gateway).

**Comment by spencergibb** [comment] 2019-05-21 18:19
Also, I can create a standalone gateway application and submit multipart/form-data, so it must be something with the test.

**Comment by spencergibb** [comment] 2019-05-21 18:20
see https://github.com/spring-cloud/spring-cloud-gateway/issues/1071

**Comment by poutsma** [comment] 2019-05-28 09:14
Closing as this does not seem to be a `DefaultMultipartMessageReader` issue, but rather an issue with this particular Cloud Gateway test (see https://github.com/spring-cloud/spring-cloud-gateway/issues/1071).

**Closed by poutsma** 2019-05-28 09:14 UTC
Labels: in: web
