### ISSUE TITLE
Allow applications to specify a custom set of beans rather than the default for EventListener candidates [SPR-17343]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21877] opened 2018-10-05 01:53 UTC
**[Rahul Shinde](https://jira.spring.io/secure/ViewProfile.jspa?name=rsjira22)** opened **[SPR-17343](https://jira.spring.io/browse/SPR-17343?redirect=false)** and commented

While benchmarking an application that has more than 10K+ beans, around 8 - 10 seconds was spent in identifying just the EventListener candidates during startup. 

Since we have the information for EventListener implementations beforehand, would like to provide that to avoid introspection of all other beans in the registry.

Applications can then extend EventListenerMethodProcessor and provide their own implementation that specifies subset of bean names to inspect.

 

---

**Affects:** 5.0.9, 5.1 GA

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1980

**Comment by snicoll** [comment] 2021-11-24 14:41
Duplicate of #1980

**Closed by snicoll** 2021-11-24 14:41 UTC
Labels: status: waiting-for-triage, in: core
