### ISSUE TITLE
Binder  Nesting of the same entity class is not supported 

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-framework#23139] opened 2019-06-14 16:33 UTC
org.springframework.boot.context.properties.bind.Binder 
Nesting of the same entity class is not supported !!! please see my demo 
https://github.com/brucelwl/demo.git

![image](https://user-images.githubusercontent.com/13413715/59524158-bf622700-8f05-11e9-943e-5df31bb34b2c.png)
![image](https://user-images.githubusercontent.com/13413715/59524203-d9036e80-8f05-11e9-8b32-ddc5f2afae59.png)

**Comment by sbrannen** [comment] 2019-06-15 13:09
Closing as a duplicate of https://github.com/spring-projects/spring-boot/issues/17207

**Closed by sbrannen** 2019-06-15 13:09 UTC
Labels: status: waiting-for-triage

**Comment by brucelwl** [comment] 2019-06-15 13:22
@sbrannen Yes, I found it belongs to Springboot and forgot to close it.
