### ISSUE TITLE
Execution failed for task ':distZip'.

### ISSUE THREAD

**Issue by WangHanHong** [spring-projects/spring-framework#25484] opened 2020-07-28 08:11 UTC
I want to Install spring-framework-5.2.1.RELEASE in local Maven repository,
command is gradlew publishToMavenLocal -x javadoc -x dokka -x asciidoctor ,but failed
> Task :distZip FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distZip'.
> Failed to create MD5 hash for file 'D:\study\spring-framework-5.2.1.RELEASE\build\distributions\spring-framework-5.2.1.RELEASE-schema.zip' as it does not exist.

**Comment by sbrannen** [comment] 2020-07-28 08:29
The `distZip` Gradle task was fixed for MS Windows in Spring Framework 5.2.2 (see #23933).

If you want to execute `distZip` on Windows for versions prior to 5.2.2., copy what was done in 4e5ae54417bbdf1e2e0f37ae3663151df39a70f4 for your local build.

Otherwise, you should be able to disable that task by adding `-x distZip` to the Gradle command line arguments.

I am therefore closing this issue as a duplicate of #23933.

**Closed by sbrannen** 2020-07-28 08:29 UTC
Labels: status: waiting-for-triage
