### ISSUE TITLE
Spring WebClient reading JSON from Wiremock (newer than 2.17) sometimes freezes

### ISSUE THREAD

**Issue by frzme** [spring-projects/spring-framework#22441] opened 2019-02-20 12:47 UTC
Using WireMock 2.21 (2.18-2.21 seem to be affected) when repeatedely sending http requests which request and decode JSON using the spring WebClient to WireMock the requests sometimes freezes and fail to reply. 
The issue does not occur when using Wiremock 2.17 and it does not occur when requesting Strings (and not decoding JSON).
I'm not entirely certain whether this is a WireMock or a Spring WebClient issue, I'm therefore raising this issue with both projects.

The failing test setup can be found here: https://github.com/FrzMe/wiremock-spring-webclient-block/blob/master/src/test/java/webclientblock/WebClientBlockTest.java#L49

Reasons why it could be a spring issue:

* when requesting "String" via the WebClient the issue does not occur (-> it occurs only when json decoding) (see https://github.com/FrzMe/wiremock-spring-webclient-block/blob/master/src/test/java/webclientblock/WebClientBlockTest.java#L102)
* when using the RestTemplate instead of the WebClient the issue does not occur (see https://github.com/FrzMe/wiremock-spring-webclient-block/blob/master/src/test/java/webclientblock/WebClientBlockTest.java#L80 )

Reasons why it could be a WireMock issue:

* when requesting from other sources (local nginx, other spring service, etc.) the issue does not occur.
* the issue does not occur in WireMock 2.17

The Issue can be reproduced when running the WebClientBlockTest from https://github.com/FrzMe/wiremock-spring-webclient-block - there the test testWiremockServiceGetJsonDecode fails consistently for me (no later than ~8000 iterations - sometimes much earlier) 
The test also shows that the same problem can not be reproduced when making http requests using the spring RestTemplate.

Both WireMock and WebClient are set up completely self contained within the test.

**Comment by frzme** [comment] 2019-02-20 14:24
@tomakehurst of WireMock found out that WireMock does indeed write the response here https://github.com/tomakehurst/wiremock/issues/1084

**Comment by rstoyanchev** [comment] 2019-03-12 14:22
I was able to pair ot down to just Reactor Netty:

```java
public static void main(String[] args) {
  HttpClient client = HttpClient.create().compress(true).baseUrl("http://localhost:" + 8080 + "/");
  WireMockServer server = new WireMockServer(WireMockConfiguration.wireMockConfig().port(8080));
  server.start();
  try {
    stubFor(get(urlPathEqualTo("/")).willReturn(okJson("{}")));
    for (int i = 0; i < 25_000; i++) {
      client.get()
          .response((res, bufFlux) -> bufFlux.flatMap(buf -> {
            List<String> s = Collections.singletonList(buf.toString(UTF_8));
            return Flux.fromIterable(s);
          }))
          .blockLast(Duration.of(5, ChronoUnit.SECONDS));
    }
  }
  finally {
    server.stop();
  }
  System.exit(0);
}
```
Note that `.compress(true)` and `flatMap` for the response seem to be key to reproducing the issue. I'm not sure if that is related to the cause or just affects the timing. The other thing is that when I switch to Reactor Netty 0.8.6.BUILD-SNAPSHOT I can no longer reproduce the issue with the above. @violetagg anything recently fixed in 0.8.6 that could account for this?

Back to the original sample with `WebClient`, it works with the latest Reactor Netty and Spring:

```
<properties>
    <spring.version>5.1.6.BUILD-SNAPSHOT</spring.version>
    <reactor-bom.version>Californium-BUILD-SNAPSHOT</reactor-bom.version>
</properties>
```

**Closed** 2019-03-12 14:24 UTC
Labels: status: declined

**Comment by violetagg** [comment] 2019-03-12 14:36
@rstoyanchev It might be this issue https://github.com/reactor/reactor-netty/issues/628?

**Comment by tomakehurst** [comment] 2019-03-13 12:38
I found some useful things out about this problem today:
https://github.com/tomakehurst/wiremock/issues/914#issuecomment-472365051
