### ISSUE TITLE
Rest Template is not thread safe for headers when there are lot of concurrent threads

### ISSUE THREAD

**Issue by rahulrastogi8** [spring-projects/spring-framework#25317] opened 2020-06-25 14:17 UTC
**Affects:** Spring Boot 2.2.6

---

When we use a shared RestTemplate across multiple threads, there are issues when lot of concurrent threads are setting different headers while sending the request.

We could see that RestTemplate is sending wrong headers (set by another request thread) in outgoing request for a request thread.

Our code is simply autowiring and using a single common instance using @Bean and rest template builder.

**Config Class**
```java
@Configuration
public class MyRestTemplateConfig {
  @Autowired
  private RestTemplateBuilder restTemplateBuilder;

  @Bean
  public RestTemplate myRestTemplate() {
    return restTemplateBuilder.build();
  }
}
```

**Client where it's injected**
```java
  @Autowired
  @Qualifier("myRestTemplate")
  public RestTemplate myRestTemplate;
```

**Code where it's used**
```java
HttpEntity<Object> requestEntity = new HttpEntity<>(payload, headers);
myRestTemplate.exchange(url, method, requestEntity, responseType);
```

Someone else also ran into this issue:
https://stackoverflow.com/questions/59621966/spring-resttemplate-seems-to-not-be-thread-safe-wrt-headers

This problem can be reproducible by sending multiple concurrent requests (with different headers) with JMeter.
Add unique IDs to those requests to trace.
You can check the incoming headers in target server. RestTemplate is mismatching headers sometimes.

**Comment by bclozel** [comment] 2020-06-25 15:46
Could you provide us with a sample application that reproduces this problem?
Note that it's critical to provide a minimal application: the issue could be from RestTemplate, JMeter's threading model, they way you're generating those unique IDs, the underlying HTTP client library, etc. Removing as much as possible from the picture is really important to find the problem.

Thanks!

**Comment by rstoyanchev** [comment] 2020-06-25 16:58
Also are the `headers` passed into `HttpEntity` the same instance for all requests involved? We generally expect that the headers you use for a request are separate from those for other requests and we don't make a copy.

**Comment by rahulrastogi8** [comment] 2020-06-25 17:27
@rstoyanchev Yes we were creating new object of HttpHeaders for each request:
HttpHeaders headers = new HttpHeaders();

Though one of the value was picked from a cached map. But it should not impact IMO.

**Comment by rahulrastogi8** [comment] 2020-06-25 17:30
@bclozel 
It happened in our enterprise code which can't be shared.
I'll try to build a sample application. But it may take time.

The original internal issue was not reported via JMeter. It came with custom test code.
But I could repro this easily with JMeter.

The unique IDs are generated as requestIds and set via MDC context. So those IDs were proper.

**Comment by rstoyanchev** [comment] 2020-06-26 08:13
If you're creating separate `HttpHeaders` instances then the issue likely is not in the Spring Framework as those are simply passed through as arguments and used to populate the request object for the underlying HTTP client. Perhaps also review the application code that populates the headers for any potential concurrency issues.

If not we really will need a sample.

**Comment by mdeinum** [comment] 2020-06-29 08:57
> The unique IDs are generated as requestIds and set via MDC context. So those IDs were proper.

The MDC is a stored in a `ThreadLocal` which should be cleared after a request. If you don't values will leak into other threads. Make sure you clear those values after the request ends. This is especially the case when using a pool of threads, like Tomcat does for request handling!

**Comment by spring-issuemaster** [comment] 2020-07-07 07:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-07-14 07:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-07-14 07:31 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
