### ISSUE TITLE
illegal reflective access on SpringBoot 2.1.2

### ISSUE THREAD

**Issue by xbaker** [spring-projects/spring-framework#24317] opened 2020-01-08 13:46 UTC
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.springframework.cglib.core.ReflectUtils (file:/home/user/.m2/repository/org/springframework/spring-core/5.1.4.RELEASE/spring-core-5.1.4.RELEASE.jar) to class java.lang.Object
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Spring boot : 2.1.2**
**java : OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)**

**Comment by bclozel** [comment] 2020-04-01 19:44
Closing as a duplicate of #22674, see [this comment for more details](https://github.com/spring-projects/spring-framework/issues/22674#issuecomment-589116539).

**Closed by bclozel** 2020-04-01 19:44 UTC
Labels: status: duplicate

**Comment by buckett** [comment] 2020-04-11 08:04
You should read the linked comment @bclozel mentioned, https://github.com/spring-projects/spring-framework/issues/22674#issuecomment-589116539 . If you have a Spring Boot application and have enabled devtools using an optional dependency:

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>

Then running the application while in development (`mvn spring-boot:run` or through the IDE) will cause this dependency to be on the classpath and you will see this warning, however when you build a JAR/WAR for production, this dependency is not pulled in and so you won't see this warning in production.
