### ISSUE TITLE
`ConstructorResolver` cannot find correct constructor with Set argument

### ISSUE THREAD

**Issue by liujunlou** [spring-projects/spring-framework#29795] opened 2023-01-10 13:13 UTC
**Affects:**

- Spring Framework 6.0.3
- JDK 17

## Overview

Bean with 2 constructors cannot find the correct one in `org.springframework.beans.factory.support.ConstructorResolver`

## Demo

```java
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.beans.factory.support.*;
import org.springframework.util.Assert;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

public class Demo {
    public static void main(String[] args) {
        Set<String> set = Collections.singleton("dfsdfsd");
        BeanDefinitionBuilder builder = BeanDefinitionBuilder.rootBeanDefinition(Pojo.class);
        builder.addConstructorArgValue(set);
        builder.setRole(BeanDefinition.ROLE_INFRASTRUCTURE);
        AbstractBeanDefinition beanDefinition = builder.getBeanDefinition();

        try {
            Class<?> clazz = Class.forName("org.springframework.beans.factory.support.ConstructorResolver");
            Constructor<?> constructor = clazz.getDeclaredConstructor(AbstractAutowireCapableBeanFactory.class);
            constructor.setAccessible(true);
            Object obj = constructor.newInstance(new DefaultListableBeanFactory());
            Method method = clazz.getMethod("resolveConstructorOrFactoryMethod", String.class, RootBeanDefinition.class);
            method.setAccessible(true);
            Object res = method.invoke(obj, "xx", beanDefinition);
            Assert.notNull(res, "Should not be null");
        } catch (Exception e) {
            System.out.println("Catch reflection fail for " + e.getMessage());
        }
    }

    public class Pojo {
        Set<String> a;
        public Pojo(String... a) {
            this(new LinkedHashSet<>(Arrays.asList(a)));
        }
        public Pojo(Set<String> a) {
            this.a = a;
        }
        public Set<String> getA() {
            return this.a;
        }
    }
}
```

Throws IllegalStateException:

```
java.lang.IllegalStateException: No constructor or factory method candidate found for Root bean: class [com.tuya.demo.Demo$Pojo]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null and argument types [java.util.Collections$SingletonSet<?>]
```

**Comment by tw11509** [comment] 2023-01-12 04:03
Because one of constructor argument is Set with parameterized type:

`        
public Pojo(Set<String> a) {
    this.a = a;
}
`

When ConstructorResolver tried to resolve type of given set in ConstructorArgumentValues, it would get ResolvableType with type "class java.util.Collections$SingletonSet<?>".

Because of type erasure, we cannot get really parameterized type of set is at runtime.

Then ConstructorResolver tried to resolve whether any constructors on Pojo match valueTypes from argument values, it would find nothing, because construct with parameter type "java.util.Set<java.lang.String>" not match "java.util.Collections$SingletonSet<?>".

Finally, Exception be thrown.

**Comment by liujunlou** [comment] 2023-01-12 07:24
> ...
> Because of type erasure, we cannot get really parameterized type of set is at runtime.
> 
> Then ConstructorResolver tried to resolve whether any constructors on Pojo match valueTypes from argument values, it would find nothing, because construct with parameter type "java.util.Set<java.lang.String>" not match "java.util.Collections$SingletonSet<?>".
> ...

first, thx for reply
I find `ConstructorResolver.FallbackMode` in spring-beans `ConstructorResolver`, I think `ASSIGNABLE_ELEMENT` is used for type erasure of Set , but I found the type of element is Object which should be String.

**Comment by simonbasle** [comment] 2023-01-18 11:03
hi @liujunlou, can you clarify your use case and perhaps provide a reproducer that is a little bit higher-level (like an integration test using the Spring TestContext Framework)?

**Comment by sbrannen** [comment] 2023-01-18 11:15
I've created two integration tests that demonstrate typical use cases for constructor resolution.

----

```java
@SpringJUnitConfig
class ConstructorResolutionTests1 {

	@Test
	void test(@Autowired Pojo pojo) {
		assertThat(pojo.getA()).containsExactlyInAnyOrder("enigma", "puzzle");
		assertThat(pojo.setConstructorInvoked).isTrue();
	}

	@Configuration
	@Import(Pojo.class)
	static class Config {

		@Bean
		Set<String> set() {
			return Set.of("enigma", "puzzle");
		}
	}

	@Component
	public static class Pojo {
		boolean setConstructorInvoked = false;
		Set<String> a;

		public Pojo(String... a) {
			this(new LinkedHashSet<>(Arrays.asList(a)));
		}

		@Autowired
		public Pojo(Set<String> a) {
			this.a = a;
			this.setConstructorInvoked = true;
		}

		public Set<String> getA() {
			return this.a;
		}
	}

}
```

`ConstructorResolutionTests1` passes unmodified due to the presence of `@Autowired` on the desired `Pojo` constructor. If you remove `@Autowired` from the `Pojo(Set)` constructor the test will fail because Spring cannot infer which constructor to invoke, and that's the expected behavior.

----

```java
@SpringJUnitConfig
class ConstructorResolutionTests2 {

	@Test
	void test(GenericApplicationContext context) {
		AutowireCapableBeanFactory beanFactory = context.getAutowireCapableBeanFactory();
		Pojo pojo = (Pojo) beanFactory.autowire(Pojo.class, AutowireCapableBeanFactory.AUTOWIRE_CONSTRUCTOR, false);
		assertThat(pojo.getA()).containsExactlyInAnyOrder("enigma", "puzzle");
		assertThat(pojo.setConstructorInvoked).isTrue();
	}

	@Configuration
	static class Config {

		@Bean
		Set<String> set() {
			return Set.of("enigma", "puzzle");
		}
	}

	@Component
	public static class Pojo {
		boolean setConstructorInvoked = false;
		Set<String> a;

		public Pojo(String... a) {
			this(new LinkedHashSet<>(Arrays.asList(a)));
		}

		public Pojo(Set<String> a) {
			this.a = a;
			this.setConstructorInvoked = true;
		}

		public Set<String> getA() {
			return this.a;
		}
	}

}
```

`ConstructorResolutionTests2` also passes and demonstrates that constructor resolution works _without_ `@Autowired` on the `Pojo(Set)` constructor.

----

As @simonbasle pointed out, we need to know your concrete use case in order to assess if anything should be done to support it.

**Comment by spring-projects-issues** [comment] 2023-02-01 11:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-02-01 11:07 UTC
Labels: status: waiting-for-feedback, in: core, status: feedback-reminder
