### ISSUE TITLE
Mocking MockMultipartFile no longer working in 5.3.2

### ISSUE THREAD

**Issue by austinarbor** [spring-projects/spring-framework#26324] opened 2020-12-29 06:54 UTC
Mocking a `MockMultipartFile` does not work in multipart request in spring-test 5.3.2
**Affects:** spring-test 5.3.2

See sample project [here](https://github.com/austinarbor/spring-framework-exception-handler-issue)

If you check out the test, you can see I am spying a `MockMultipartFile` to force it to throw an `IOException` on `getInputstream()` [here](https://github.com/austinarbor/spring-framework-exception-handler-issue/blob/main/src/test/java/dev/aga/controller/UploadControllerTest.java#L32)

This works fine in spring-test 5.3.1 but does not work in 5.3.2. I confirmed this by excluding spring-test from spring-boot-starter-test and directly importing spring-test 5.3.1, which resolves the issue.

Throwing a breakpoint in the controller method you can see that the `MockMultipartFile` is not a mock when on 5.3.2

Possibly caused by https://github.com/spring-projects/spring-framework/commit/d82cb15439c1c9d4100daabb275e0eb102a877bc as fix for https://github.com/spring-projects/spring-framework/issues/26166

**Comment by rstoyanchev** [comment] 2021-01-04 15:18
This is a duplicate of #26261. I tried with the sample and switching to 5.3.3 snapshots makes the test pass.

**Comment by austinarbor** [comment] 2021-01-04 21:22
@rstoyanchev i tried adding `http://repo.spring.io/libs-snapshot` to the `build.gradle` but can't seem to get `5.3.3-SNAPSHOT` imported. is there anything else i need to do?

**Comment by rstoyanchev** [comment] 2021-01-05 18:11
I also added:
```
ext['spring-framework.version'] = "5.3.3-SNAPSHOT"
```

**Comment by austinarbor** [comment] 2021-01-05 23:17
Looks like using `http` was my problem. Confirming bug is fixed in 5.3.3-SNAPSHOT

**Comment by izeye** [comment] 2021-01-08 01:12
This seems to be meant to be closed with the "status: duplicate" label.

**Comment by snicoll** [comment] 2021-01-08 07:14
Thanks for the nudge Johnny.

**Closed by snicoll** 2021-01-08 07:14 UTC
Labels: status: duplicate
