### ISSUE TITLE
R2DBC  Postgresql: Creating new Transactions org.springframework.transaction.reactive.AbstractReactiveTransactionManager Struck

### ISSUE THREAD

**Issue by madhav1306** [spring-projects/spring-framework#28840] opened 2022-07-19 04:17 UTC
With the recent upgrade of sprint boot version 2.7.1, we are unable to obtain the database connection from the r2dbc pool. The code strucks at the below line until we restart. Once restarted, the issues occurrence takes 2 to 3 days. No detailed logs printed

** DEBUG o.s.t.r.AbstractReactiveTransactionManager [reactor-http-nio-4]   Creating new transaction with name [com.authenticate.service.UserService.fetchUserWithRoles]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT,readOnly **

#application.properties
======================
Below is the db connection pool configuration

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=10
spring.r2dbc.pool.max-idle-time=10m
spring.r2dbc.pool.max-acquire-time=30s
spring.r2dbc.pool.max-create-connection-time=30s
spring.r2dbc.pool.validation-query=SELECT 1

#application.yml
=======================
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb
    username: postgres

**Comment by snicoll** [comment] 2022-07-19 07:53
@madhav1306 your application configuration is unfortunately nowhere near enough for us to figure out what can go wrong in your project. If you want support, please share a small sample that we can run ourselves to reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-07-26 07:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-08-02 07:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-08-02 07:55 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
