### ISSUE TITLE
XmlBeansMarshaller should be brought back, as Xmlbeans is unretired by Apache.

### ISSUE THREAD

**Issue by chirag519086** [spring-projects/spring-framework#24130] opened 2019-12-04 11:28 UTC
XmlBeansMarshaller class was deperecated and removed because of retirement of Xmlbeans by Apache.

However, Xmlbeans is unretired and active development is also happening. 
Shouldn't Marshaller be reintroduced to support Xmlbeans ?

Update about Xmlbeans unretirement is published in below link.
http://xmlbeans.apache.org/news

**Comment by mdeinum** [comment] 2019-12-05 06:44
Duplicate of #22403

**Comment by sbrannen** [comment] 2019-12-05 15:41
Closing as a duplicate of #22403 which was declined.

**Closed by sbrannen** 2019-12-05 15:41 UTC
Labels: status: duplicate
