### ISSUE TITLE
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response

### ISSUE THREAD

**Issue by RB2601** [spring-projects/spring-framework#27861] opened 2021-12-27 17:44 UTC
While consuming a flux which contains 40,000 records I am getting "Connection prematurely closed during response".
Tried changing response timeout but still the issue persists.

**Comment by rstoyanchev** [comment] 2022-01-04 14:38
There can be different reasons for why the connection is getting closed, and you need to determine the cause. Please, read [How can I debug "Connection prematurely closed BEFORE response"?](https://projectreactor.io/docs/netty/snapshot/reference/index.html#faq.connection-closed).

**Comment by spring-projects-issues** [comment] 2022-01-11 14:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-01-18 14:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-01-18 14:42 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, in: web, status: feedback-reminder
