### ISSUE TITLE
Support `RequestHeader|Param` as meta-annotations

### ISSUE THREAD

**Issue by efemoney** [spring-projects/spring-framework#28950] opened 2022-08-11 06:49 UTC
**Affects:** 5.3.18

---

Within my project, almost all endpoints receive the user-agent header like so:

```kt
@RequestHeader("User-Agent", defaultValue = "") userAgent: String,
```

I would like to reduce this declaration to the following:

```kt
@UserAgentHeader userAgent: String,
```

I think handler methods support meta annotations (via reading the docs of `org.springframework.core.annotation.SynthesizingMethodParameter`) but the annotations (`RequestParam`, `RequestHeader` etc) have an annotation target of only `PARAMETER` so cannot be used as meta annotations.

**Comment by sbrannen** [comment] 2022-08-11 16:13
Closing as a duplicate of #21829.

**Closed by sbrannen** 2022-08-11 16:13 UTC
Labels: status: waiting-for-triage
