### ISSUE TITLE
@Valid annotation can't establish dependency relationship between beans 

### ISSUE THREAD

**Issue by uphy** [spring-projects/spring-framework#29730] opened 2022-12-22 09:35 UTC
We can't call `@Validated` bean's method on application shutdown because `defaultValidator` bean is destroyed first even though we are referring it.

## Sample Application

- `MyBean` with `@Validated` depends on `defaultValidator` implicitly through `MethodValidationInterceptor`
- `MyService` depends on `MyBean`
- `MyService` takes a while to destroy and it calls `MyBean` at last
- But the call fails due to `BeanCreationNotAllowedException`

```java
package com.example.demo;

import javax.annotation.PreDestroy;

import org.springframework.beans.factory.BeanCreationNotAllowedException;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Service
    static class MyService {
        private final MyBean myBean;

        MyService(MyBean myBean) {
            this.myBean = myBean;
        }

        @PreDestroy
        void destroy() {
            System.out.println("MyService.destroy");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            try {
                myBean.method();
            } catch (BeanCreationNotAllowedException ex) {
                // This is thrown because defaultValidator has already been closed.
                ex.printStackTrace();
            }
        }

    }

    @Component
    @Validated
    // This is a workaround for this issue:
    // @DependsOn("defaultValidator")
    static class MyBean {

        void method() {
            System.out.println("MyBean.method");
        }

        @PreDestroy
        void destroy() {
            System.out.println("MyBean.destroy");
        }
    }

}

```

See the following link for the complete demo app code:
https://github.com/uphy/20231010_BeanCreationNotAllowedExceptionDemo

## Workaround

- Add `@DependsOn("defaultValidator")` to `MyBean`
- Add `@ConfigurationProperties` annotation to `MyBean` (ref https://github.com/spring-projects/spring-boot/commit/f60f3cb38eeb40f6863d86b8ef91fa395c513a82)
- Use `MethodValidationExcludeFilter` to exclude method validation from `MyBean`

## Environment

- Spring Boot 2.7.6
- Java 11

**Comment by vishalsingh2972** [comment] 2023-04-16 15:12
@uphy @sbrannen can you assign this to me if it's still open ?

**Comment by uphy** [comment] 2023-04-17 02:30
@vishalsingh2972 Thank you!  I am not authorized to assign, so I will wait for @sbrannen's response.

**Comment by snicoll** [comment] 2023-10-05 14:18
@vishalsingh2972 thanks for the offer but we haven't triage the issue yet so nobody can really work on it really. Except if you've found what the issue was?

**Comment by snicoll** [comment] 2023-10-05 14:23
@uphy I can't reproduce the issue that you have described. Both with framework 5.3 and 6.x, the shutdown is initiated with the sleep there and it ends up with:

```
2023-10-05 16:22:08.799  INFO 22703 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.558 seconds (JVM running for 0.744)
MyService.destroy
MyBean.method
MyBean.destroy
```

I am going to close this but we can reopen if you manage to reproduce. Please provide more instructions in that case.

**Comment by uphy** [comment] 2023-10-10 01:44
@snicoll Thank you for checking.  I could reproduce the issue again with latest environment.

See the following link for the complete demo project:
https://github.com/uphy/20231010_BeanCreationNotAllowedExceptionDemo

Could you reopen this issue?

**Comment by snicoll** [comment] 2023-10-12 07:20
Thanks, I've reproduced it now. This is similar to #22526

**Closed** 2024-03-04 16:21 UTC
Labels: in: core, type: enhancement
