### ISSUE TITLE
Support for annotating multiple arguments with @RequestBody

### ISSUE THREAD

**Issue by adityas71094** [spring-projects/spring-framework#24894] opened 2020-04-10 12:39 UTC
I am using `spring-webmvc` 5.2.3.

I want to use Spring's Default MethodArgumentResolver to resolve the json payload into multiple beans. But I am not able to do that right now because `AbstractMessageConverterMethodArgumentResolver.EmptyBodyCheckingHttpInputMessage(httpRequest)`is passed the HttpRequest object and is used directly. While attempting to resolve the second argument the HttpRequest's inputStream is closed, so I get an exception saying that the input stream is closed. Ergo I am able to annotate only one argument with `@RequestBody`.

```java
    @PostMapping("/endpoint")
    public void  method(@Valid @RequestBody CustomBean bean1, 
                                @Valid @RequestBody CustomBean2 bean2) 
    {
        // using both beans.
    }
```

Why not use a `ContentCachingRequestWrapper` instead of the actual HttpRequest for argument resolution ?

**Comment by juzerali** [comment] 2020-04-13 11:59
I think the problem is in [`AbstractJackson2HttpMessageConverter#readJavaType`](https://github.com/spring-projects/spring-framework/blob/73e39726cd1c17563e29d97a5ebe69f6491890d0/spring-web/src/main/java/org/springframework/http/converter/json/AbstractJackson2HttpMessageConverter.java#L235).

The converter passes `requestBody` of type `InputStream` directly to Jackson's `ObjectReader#readValue`, which closes the stream after parsing the JSON literal.

A temporary fix for you could be disabling the global `JsonParser.Feature.AUTO_CLOSE_SOURCE` flag in your env.

This can be fixed in Spring by adding `.without(JsonParser .Feature.AUTO_CLOSE_SOURCE)` in the call chain mentioned above. I can contribute with a PR.

**Comment by adityas71094** [comment] 2020-04-13 12:41
@juzerali , Agreed that marking JsonParser.Feature.AUTO_CLOSE_SOURCE as false will prevent the inputStream from being closed. But data that has been read once from a stream cannot be read again, right?  How will adding AUTO_CLOSE_SOURCE = false help with this?

**Comment by sbrannen** [comment] 2020-04-13 13:04
> I want to use Spring's Default MethodArgumentResolver to resolve the json payload into multiple beans. 

When you say "multiple beans", do you perhaps mean multiple beans of different types?

I ask, because your example shows two beans of the exact same type (`CustomBean`) which doesn't seem to make much sense.

**Comment by adityas71094** [comment] 2020-04-13 16:09
@sbrannen , yes I mean multiple beans of different types.
I'll change the code snippet for better clarity.

**Comment by juzerali** [comment] 2020-04-14 10:21
You are right, it was a lame attempt. What do you think could be a solution?

**Comment by rstoyanchev** [comment] 2020-04-14 10:54
So presumably the input is a JSON object that contains the data for both CustomBean1 and CustomBean2, in which case could create one top-level object that contains both. Using a caching request wrapper could be another way to go but that is not something we are going to do out of the box.

**Closed by rstoyanchev** 2020-04-14 10:54 UTC
Labels: in: web, status: waiting-for-triage
