### ISSUE TITLE
spring r2dbc ColumnMapRowMapper wrong mapping

### ISSUE THREAD

**Issue by wangxing-git** [spring-projects/spring-framework#26124] opened 2020-11-20 02:03 UTC
**Affects:** 5.3.1

---

```kotlin
var collectList = r2dbcEntityTemplate.databaseClient.sql("""
            select * from pending_message
        """.trimIndent())
//                .map(EntityRowMapper(PendingMessage::class.java,r2dbcConverter))
                .fetch()
                .all()
                .collectList().block()
```
When I use `DatabaseClient`, the `fetch` method is mapped incorrectly.

For example: 
the order of returned field values is: a -> a, b -> b, c -> c, d -> d,
But the final map obtained is: c -> a, a -> b, d -> c, b -> d.

**Comment by sbrannen** [comment] 2020-11-20 17:26
@mp911de, does this sound familiar to you?

Is this something we should investigate within the `spring-r2dbc` module in Spring Framework?

**Comment by mp911de** [comment] 2020-11-20 18:05
Thanks for the ping. We've seen a similar issue in Spring Data R2DBC (https://github.com/spring-projects/spring-data-r2dbc/issues/478) that was caused by the Postgres driver. It was fixed in the driver (https://github.com/pgjdbc/r2dbc-postgresql/issues/337) in version 0.8.6.RELEASE. 

@wangxing-git which driver and version of the driver are you using?

The underlying cause is a difference in column metadata iteration order vs. the result column order.

**Comment by wangxing-git** [comment] 2020-11-21 01:11
> Thanks for the ping. We've seen a similar issue in Spring Data R2DBC ([spring-projects/spring-data-r2dbc#478](https://github.com/spring-projects/spring-data-r2dbc/issues/478)) that was caused by the Postgres driver. It was fixed in the driver ([pgjdbc/r2dbc-postgresql#337](https://github.com/pgjdbc/r2dbc-postgresql/issues/337)) in version 0.8.6.RELEASE.
> 
> @wangxing-git which driver and version of the driver are you using?
> 
> The underlying cause is a difference in column metadata iteration order vs. the result column order.

The mysql driver I use, the version is 8.0.22.

**Comment by mp911de** [comment] 2020-11-21 07:54
In that case, this problem should be fixed in the MySQL driver. Paging @mirromuth.

**Comment by sbrannen** [comment] 2020-11-21 14:16
@mp911de, shall we close this issue in favor of an issue raised against `r2dbc-mysql`?

**Comment by mp911de** [comment] 2020-11-21 15:13
Yes, please. I created mirromutth/r2dbc-mysql#149.

**Closed** 2020-11-23 14:06 UTC
Labels: in: data, status: feedback-provided, status: waiting-for-triage

**Comment by pophils** [comment] 2021-07-09 12:39
This issue still exist with mysql driver. Got invalid mapping too. version 0.82

**Comment by IsoqHakimov** [comment] 2021-09-15 11:08
Same situation with me. version 0.82
