### ISSUE TITLE
Parameter binding in Spring MVC results in ConcurrentModificationException

### ISSUE THREAD

**Issue by sdd1989** [spring-projects/spring-framework#24843] opened 2020-04-02 06:39 UTC
**Affects:**  `spring-web` version is 5.1.6

**Comment by sdd1989** [comment] 2020-04-02 06:40
exception is
category:news-feed-api-springboot exceptionInfo.exceptionName:java.util.ConcurrentModificationException methodInfo.methodName:onError methodInfo.clazz:com.xiaomi.browser.newsfeed.controllers.ErrHandler logType:Exception exceptionInfo.stackTrace:java.util.ConcurrentModificationException at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) at java.util.Collections$3.nextElement(Collections.java:5216) at org.springframework.web.util.WebUtils.getParametersStartingWith(WebUtils.java:697) at org.springframework.web.bind.ServletRequestParameterPropertyValues.<init>(ServletRequestParameterPropertyValues.java:80) at org.springframework.web.bind.ServletRequestParameterPropertyValues.<init>(ServletRequestParameterPropertyValues.java:53) at org.springframework.web.bind.ServletRequestDataBinder.bind(ServletRequestDataBinder.java:101) at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.bindRequestParameters(ServletModelAttributeMethodProcessor.java:157) at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:160) at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:126) at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:166) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) at org.springframework.w exceptionInfo.nameLine:java.util.ConcurrentModificationException exceptionInfo.originLine:atjava.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) context.threadId:http-nio-8134-exec-185 context.traceId:c3-miui-bw-fe23.bj bizInfo.message:Failed to response, url: /api/v4/task/sign/data bizInfo.level:ERROR bizInfo.code:0 bizInfo.latency:0 bizInfo.cost:0 bizInfo.__isset_bit_vector: timestamp:Apr 1, 2020 @ 20:41:57.868 _id:h97DNXEBh2gMni3EiSTW _type:_doc _index:base_log_online_srv-2020.04.01 _score: -

**Comment by sdd1989** [comment] 2020-04-02 06:43
![image](https://user-images.githubusercontent.com/46336083/78218411-52e60200-74f0-11ea-9b1d-bc49bbb6442e.png)

**Comment by sbrannen** [comment] 2020-04-02 14:39
If you would like for us to look into this issue, please provide a minimal example that reproduces the problem.

In addition, please do **not** provide screenshots of stack traces. Instead, please copy and paste the stack trace as plain text.

**Comment by sdd1989** [comment] 2020-04-03 09:09
ok，it mybe is not spring‘s is issues but i don’t know why Parameter binding in Spring MVC occasionally occur ConcurrentModificationException？can you help me？thank you
my stack trace is below
java.util.ConcurrentModificationException at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) at java.util.Collections$3.nextElement(Collections.java:5216) at org.springframework.web.util.WebUtils.getParametersStartingWith(WebUtils.java:697) at org.springframework.web.bind.ServletRequestParameterPropertyValues.(ServletRequestParameterPropertyValues.java:80) at org.springframework.web.bind.ServletRequestParameterPropertyValues.(ServletRequestParameterPropertyValues.java:53) at org.springframework.web.bind.ServletRequestDataBinder.bind(ServletRequestDataBinder.java:101) at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.bindRequestParameters(ServletModelAttributeMethodProcessor.java:157) at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:160) at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:126) at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:166) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) at org.springframework.w exceptionInfo.nameLine:java.util.ConcurrentModificationException exceptionInfo.originLine:atjava.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)

**Comment by sdd1989** [comment] 2020-04-03 09:11
> If you would like for us to look into this issue, please provide a minimal example that reproduces the problem.
> 
> In addition, please do **not** provide screenshots of stack traces. Instead, please copy and paste the stack trace as plain text.

ok，thank you, it mybe not spring‘s issues but I don’t know why parameter binding in Spring MVC occasionally occur ConcurrentModificationException？can you help me？
my stack trace is below
java.util.ConcurrentModificationException at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) at java.util.Collections$3.nextElement(Collections.java:5216) at org.springframework.web.util.WebUtils.getParametersStartingWith(WebUtils.java:697) at org.springframework.web.bind.ServletRequestParameterPropertyValues.(ServletRequestParameterPropertyValues.java:80) at org.springframework.web.bind.ServletRequestParameterPropertyValues.(ServletRequestParameterPropertyValues.java:53) at org.springframework.web.bind.ServletRequestDataBinder.bind(ServletRequestDataBinder.java:101) at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.bindRequestParameters(ServletModelAttributeMethodProcessor.java:157) at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:160) at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:126) at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:166) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) at org.springframework.w exceptionInfo.nameLine:java.util.ConcurrentModificationException exceptionInfo.originLine:atjava.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)

**Comment by sbrannen** [comment] 2020-04-03 17:56
Again, please provide a minimal example that reproduces the problem.

Otherwise it is very difficult for us to assist you.

**Comment by sdd1989** [comment] 2020-04-04 07:49
The code belongs to my company，can't put it in GitHub，so I would like to have a look first，
Thank you anyway !

**Comment by sdd1989** [comment] 2020-04-09 03:03
> Again, please provide a minimal example that reproduces the problem.
> 
> Otherwise it is very difficult for us to assist you.

Hello, I didn't find the answer to the question, Ask for your help, See if it's a issues, a minimal example hat reproduces the problem below
`
@SpringBootApplication()
@ImportResource("classpath:applicationContext.xml")
@ComponentScan(value = {"***", "***",
        "***", "***"},
    excludeFilters = {
    @ComponentScan.Filter(type = FilterType.REGEX, pattern = "***"),
    @ComponentScan.Filter(type = FilterType.REGEX, pattern = "***"),
    @ComponentScan.Filter(type = FilterType.REGEX, pattern = "***")})
@MapperScan(basePackages = {"***"})
@EnableEurekaClient
@EnableFeignClients(basePackages = {"***"})
public class NewsFeedApiSpringbootApplication {
    public static void main(String[] args) {
        SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
    }
}


@Slf4j
@RequestMapping("/v4/task")
@RestController
public class TaskController {

	@GetMapping("/tab/label")
    public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
                               @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
        //...
    }

}
`
My package name omit，Replace with ***.  My springboot version is 2.1.4.RELEASE

Thank you very much!

**Comment by sdd1989** [comment] 2020-04-09 03:05
> Again, please provide a minimal example that reproduces the problem.
> 
> Otherwise it is very difficult for us to assist you.

Hello, I didn't find the answer to the question, Ask for your help, See if it's a issues, a minimal example hat reproduces the problem below
`@SpringBootApplication()
@ImportResource("classpath:applicationContext.xml")
@componentscan(value = {"", "",
"", ""},
excludeFilters = {
@componentscan.Filter(type = FilterType.REGEX, pattern = ""),
@componentscan.Filter(type = FilterType.REGEX, pattern = ""),
@componentscan.Filter(type = FilterType.REGEX, pattern = "")})
@MapperScan(basePackages = {""})
@EnableEurekaClient
@EnableFeignClients(basePackages = {"***"})
public class NewsFeedApiSpringbootApplication {
public static void main(String[] args) {
SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
}
}

@slf4j
@RequestMapping("/v4/task")
@RestController
public class TaskController {

@GetMapping("/tab/label")
public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
                           @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
    //...
}
}
`
My package name omit，Replace with ***. My springboot version is 2.1.4.RELEASE

Thank you very much!

**Comment by sdd1989** [comment] 2020-04-09 03:06
> Again, please provide a minimal example that reproduces the problem.
> 
> Otherwise it is very difficult for us to assist you.

Hello, I didn't find the answer to the question, Ask for your help, See if it's a issues, a minimal example hat reproduces the problem below
`@SpringBootApplication()
@ImportResource("classpath:applicationContext.xml")
@componentscan(value = {"", "",
"", ""},
excludeFilters = {
@componentscan.Filter(type = FilterType.REGEX, pattern = ""),
@componentscan.Filter(type = FilterType.REGEX, pattern = ""),
@componentscan.Filter(type = FilterType.REGEX, pattern = "")})
@MapperScan(basePackages = {""})
@EnableEurekaClient
@EnableFeignClients(basePackages = {"***"})
public class NewsFeedApiSpringbootApplication {
public static void main(String[] args) {
SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
}
}

@slf4j
@RequestMapping("/v4/task")
@RestController
public class TaskController {

@GetMapping("/tab/label")
public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
                           @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
    //...
}
}`
My package name omit，Replace with ***. My springboot version is 2.1.4.RELEASE

Thank you very much!

**Comment by sdd1989** [comment] 2020-04-09 03:09
> Again, please provide a minimal example that reproduces the problem.
> 
> Otherwise it is very difficult for us to assist you.

Hello, I didn't find the answer to the question, Ask for your help, See if it's a issues, a minimal example hat reproduces the problem below
`@SpringBootApplication()
@ImportResource("classpath:applicationContext.xml")
@componentscan(value = {"*"},
excludeFilters = {
@componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
@componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
@componentscan.Filter(type = FilterType.REGEX, pattern = "*")})
@MapperScan(basePackages = {"*"})
@EnableEurekaClient
@EnableFeignClients(basePackages = {"*"})
public class NewsFeedApiSpringbootApplication {
public static void main(String[] args) {
SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
}
}`
`@slf4j
@RequestMapping("/v4/task")
@RestController
public class TaskController {

@GetMapping("/tab/label")
public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
                           @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
    //...
}
}`

My package name omit，Replace with *. My springboot version is 2.1.4.RELEASE

Thank you very much!

**Comment by sdd1989** [comment] 2020-04-09 03:10
> Again, please provide a minimal example that reproduces the problem.
> 
> Otherwise it is very difficult for us to assist you.

Hello, I didn't find the answer to the question, Ask for your help, See if it's a issues, a minimal example hat reproduces the problem below


@SpringBootApplication()
@ImportResource("classpath:applicationContext.xml")
@componentscan(value = {"*"},
excludeFilters = {
@componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
@componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
@componentscan.Filter(type = FilterType.REGEX, pattern = "*")})
@MapperScan(basePackages = {"*"})
@EnableEurekaClient
@EnableFeignClients(basePackages = {"*"})
public class NewsFeedApiSpringbootApplication {
public static void main(String[] args) {
SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
}
}

@slf4j
@RequestMapping("/v4/task")
@RestController
public class TaskController {

@GetMapping("/tab/label")
public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
                           @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
    //...
}
}

My package name omit，Replace with *. My springboot version is 2.1.4.RELEASE

Thank you very much!

**Comment by sdd1989** [comment] 2020-04-09 03:19
> Again, please provide a minimal example that reproduces the problem.
> 
> Otherwise it is very difficult for us to assist you.

Hello, I didn't find the answer to the question,but I find before request and after request the parameters not be changed，So I don't know why it occur the ConcurrentModificationException Ask for your help, See if it's a issues, a minimal example that reproduces the problem below


@SpringBootApplication()
@ImportResource("classpath:applicationContext.xml")
@componentscan(value = {"*"},
excludeFilters = {
@componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
@componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
@componentscan.Filter(type = FilterType.REGEX, pattern = "*")})
@MapperScan(basePackages = {"*"})
@EnableEurekaClient
@EnableFeignClients(basePackages = {"*"})
public class NewsFeedApiSpringbootApplication {
public static void main(String[] args) {
SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
}
}

@slf4j
@RequestMapping("/v4/task")
@RestController
public class TaskController {

@GetMapping("/tab/label")
public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
                           @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
    //...
}
}

My package name omit，replace with *. My springboot version is 2.1.4.RELEASE

Thank you very much!

**Comment by sdd1989** [comment] 2020-04-09 03:22
> > Again, please provide a minimal example that reproduces the problem.
> > Otherwise it is very difficult for us to assist you.
> 
> Hello, I didn't find the answer to the question,but I find before request and after request the parameters not be changed，So I don't know why it occur the ConcurrentModificationException Ask for your help, See if it's a issues, a minimal example that reproduces the problem below
> 
> @SpringBootApplication()
> @ImportResource("classpath:applicationContext.xml")
> @componentscan(value = {"_"}, excludeFilters = { @componentscan.Filter(type = FilterType.REGEX, pattern = "_"),
> @componentscan.Filter(type = FilterType.REGEX, pattern = "_"), @componentscan.Filter(type = FilterType.REGEX, pattern = "_")})
> @MapperScan(basePackages = {"_"}) @EnableEurekaClient @EnableFeignClients(basePackages = {"_"})
> public class NewsFeedApiSpringbootApplication {
> public static void main(String[] args) {
> SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
> }
> }
> 
> @slf4j
> @RequestMapping("/v4/task")
> @RestController
> public class TaskController {
> 
> @GetMapping("/tab/label")
> public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean, @RequestParam(required = false, value = "test") String test,
> @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
> //...
> }
> }
> 
> My package name omit，replace with *. My springboot version is 2.1.4.RELEASE
> 
> Thank you very much!

It's not 100% reproducible, it's occasionally！

**Comment by sdd1989** [comment] 2020-04-10 01:55
> > Again, please provide a minimal example that reproduces the problem.
> > Otherwise it is very difficult for us to assist you.
> 
> Hello, I didn't find the answer to the question, but I find before request and after request the parameters are not changed. So I don't know why the `ConcurrentModificationException` occurs.
> 
> Ask for your help, See if it's a issues, a minimal example that reproduces the problem below
> 
> ```java
> @SpringBootApplication()
> @ImportResource("classpath:applicationContext.xml")
> @componentscan(value = {"*"},
> excludeFilters = {
> @componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
> @componentscan.Filter(type = FilterType.REGEX, pattern = "*"),
> @componentscan.Filter(type = FilterType.REGEX, pattern = "*")})
> @MapperScan(basePackages = {"*"})
> @EnableEurekaClient
> @EnableFeignClients(basePackages = {"*"})
> public class NewsFeedApiSpringbootApplication {
>     public static void main(String[] args) {
>       SpringApplication.run(NewsFeedApiSpringbootApplication.class, args);
>     }
> }
> ```
> 
> ```java
> @slf4j
> @RequestMapping("/v4/task")
> @RestController
> public class TaskController {
> 
>   @GetMapping("/tab/label")
>   public Result getTaskLabel(HttpServletRequest request, RequestContextBean bean,     
>             @RequestParam(required = false, value = "test") String test,
>             @RequestParam(required = false, defaultValue = "0", value = "ts") long timestamp) {
>     //...
>   }
> }
> ```
> 
> My package name omit，replace with *. My springboot version is 2.1.4.RELEASE
> 
> Thank you very much!

It's not 100% reproducible, it's occasionally！

**Comment by rstoyanchev** [comment] 2020-04-22 07:10
@sdd1989 what we need is some way to reproduce the issue. We can't begin to debug the problem without that. The snippet you have provided does not help.

You'll need to to do further debugging in your own environment in order to narrow down the cause. It appears to be some concurrent modification of the Servlet request parameter map. That is unusual but this is why only you can debug it in your own environment. For example you might try to put breakpoints or print statements to see what's accessing or modifying the parameters.

I'm closing this for now, but if you find more information please feel free to provide it.

**Closed by rstoyanchev** 2020-04-22 07:10 UTC
Labels: in: web, status: feedback-provided, status: waiting-for-triage

**Comment by sdd1989** [comment] 2020-04-22 11:10
> @sdd1989 what we need is some way to reproduce the issue. We can't begin to debug the problem without that. The snippet you have provided does not help.
> 
> You'll need to to do further debugging in your own environment in order to narrow down the cause. It appears to be some concurrent modification of the Servlet request parameter map. That is unusual but this is why only you can debug it in your own environment. For example you might try to put breakpoints or print statements to see what's accessing or modifying the parameters.
> 
> I'm closing this for now, but if you find more information please feel free to provide it.

OK，Thank you anyway!
