### ISSUE TITLE
War deployment in Tomcat - Content-Type response header differences with and without index.html

### ISSUE THREAD

**Issue by sandipchitale** [spring-projects/spring-framework#26784] opened 2021-04-07 20:18 UTC
Steps:

- Created a simple Springboot 2.4.4 application with with War packaging with Spring Web dependency.
- Added a simple index.html page in the src/main/resource/static/index.html.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example</title>
</head>
<body>
    <h1>Encoding should be UTF-8</h1>
</body>
</html>
```
- Built the .war file with bootWar - say example.war
- Deployed the war to external Tomcat 9.x by dropping the .war file to webapps folder of Tomcat (running at localhost:8090)
- In the browser access the application using the following URL:

http:// localhost:8090/example

**NOTE** This internally gets forwarded to index.html by Springboot.

The returned Content-Type response header is set to:

Content-Type: text/html;**charset=ISO-8859-1**

**NOTE** Debugging shows that the Tomcat code injects this charset based on a Locale-based map because the response from the application did not have the charset specified.

- Now access the application using the following URL:

http:// localhost:8090/example/**index.html**

The returned Content-Type response header is set to:

Content-Type: text/html

NOTE: The **charset=ISO-8859-1** is now missing.

- Now run the same app as a Springboot standalone app with embedded Tomcat.

- In the browser access the application using the following URL:

http:// localhost:8080/

The returned Content-Type response header is set to:

Content-Type: text/html;**charset=UTF-8**

- Now access the application using the following URL:

http:// localhost:8080/index.html

The returned Content-Type response header is set to:

Content-Type: text/html

NOTE: The **charset=UTF-8** is now missing.

Expected behavior:

The Content-Type header value should be consistent in all 4 cases - preferably with **charset=UTF-8**

**Comment by imanhn** [comment] 2021-04-10 17:15
Just to double check,

are you sure you have saved your static html file with UTF8 encoding? Cause if your locale is iso8859-1 and you have saved the file with that encoding, the meta tag does not change it to UTF8.

**Comment by sandipchitale** [comment] 2021-04-10 18:40
@imanhn I will have to check that, but most likely the file was saved in UTF-8. In any case this issue is about the Content-Type response header.

**Comment by OSC-LimJaesung** [comment] 2021-04-27 04:02
> @rajanjha786 was there a specific reason you thought this issue should be closed?

asdf

**Comment by sandipchitale** [comment] 2021-07-09 02:06
Any updates?

**Comment by sandipchitale** [comment] 2021-11-12 18:58
Any updates?

**Comment by SentretC** [comment] 2022-04-16 04:02
Seems that it results from the default locale-encoding-mapping setting of Tomcat.
The embedded Tomcat that Spring Boot creates [has this setting overridden](https://github.com/spring-projects/spring-boot/blob/aecb035e99467c1cdcb86c814209416ca5fe8352/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/tomcat/TomcatServletWebServerFactory.java#L234) to use UTF-8 instead.

You can add the following to your web.xml file (inside the `web-app` element) to achieve the same effect, however I don't know whether this can be done programmatically.
```
<locale-encoding-mapping-list>
    <locale-encoding-mapping>
        <locale>en</locale>
        <encoding>UTF-8</encoding>
    </locale-encoding-mapping>
    <locale-encoding-mapping>
        <locale>fr</locale>
        <encoding>UTF-8</encoding>
    </locale-encoding-mapping>
    <locale-encoding-mapping>
        <locale>ja</locale>
        <encoding>UTF-8</encoding>
    </locale-encoding-mapping>
</locale-encoding-mapping-list
```

The application property [server.servlet.encoding.force-response](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.servlet.encoding.force-response) can be used to force response encoding, however setting it to true (while leaving [server.servlet.encoding.charset](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.servlet.encoding.charset) to default) results in ";charset=UTF-8" being added even for images, while [server.servlet.encoding.mapping.*](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.servlet.encoding.mapping) works for the embedded container only

**Comment by SentretC** [comment] 2022-04-19 03:57
Even though it's not a bug of Spring, I don't think a lot of people want to rely on their container to map between locale and encoding. Maybe it's better to provide an option to simply set encoding explicitly along with locale, and have Spring Boot enable it by default? (than the current behavior which is to reset specific mappings when configuring an embedded container)

**Comment by jhoeller** [comment] 2024-01-23 14:55
Since there is nothing we can do about this at the core Spring Framework level, I'm closing this issue. For any concrete improvements in Spring Boot, please create a dedicated enhancement request there.

**Closed by jhoeller** 2024-01-23 14:55 UTC
Labels: status: waiting-for-triage, in: web, status: feedback-provided
