### ISSUE TITLE
Reactive `HttpComponentsClientHttpResponse` ignores `Expires` cookie attribute

### ISSUE THREAD

**Issue by renetrefft** [spring-projects/spring-framework#33157] opened 2024-07-07 15:04 UTC
A cookie has the optional attributes `Expires` and `Max-Age`. If both are set, the latter takes precedence. 

In method `adaptCookies()` of class `org.springframework.http.client.reactive.HttpComponentsClientHttpResponse` each HttpComponents `Cookie` is converted to a Spring `ResponseCookie`.

Given is an HttpComponents `Cookie` which has set `Expires` only, since `adaptCookies()` just reads `Max-Age` from `Cookie`, the resulting `ResponseCookie` has lost its expiration information.

Note: I have also checked `ReactorClientHttpResponse`, and it is not affected. Netty internally converts `Expires` to `Max-Age`. Thus, its `Cookie` class supports `Max-Age` only.

**Comment by sbrannen** [comment] 2024-07-08 09:14
Good catch.

`ResponseCookie#toString()` actually includes `Expires` in `Max-Age` is set, but you're right: if `Expires` is set without `Max-Age`, then the `Expires` attribute is not included in the generated Cookie string.

So, in general, it's `org.springframework.http.ResponseCookie` that does not have support for a stand-alone `Expires` attribute.

**Comment by imvtsl** [comment] 2024-07-12 17:45
Hi @sbrannen 
Is it okay if i take a look at this one and contribute?

**Comment by imvtsl** [comment] 2024-07-16 00:19
@sbrannen 
I reproduced this issue [here](https://github.com/imvtsl/spring-framework-reactive-issue-33157/blob/main/src/test/java/com/vatsal/reactive/issue33157/MainTests.java).

Netty: io.netty.handler.codec.http.cookie.ClientCookieDecoder.mergeMaxAgeAndExpires() merges Max-Age and expires into Max-Age. Netty merges these two attributes using logic defined in [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.3). Point 3 of section 5.3 in this RFC gives higher precedence to Max-Age over Expires. And org.springframework.http.client.reactive.ReactorClientHttpResponse.getCookies() only considers maxAge which is okay for this case as Max-Age and Expires is already merged internally by Netty. So, no issues in org.springframework.http.client.reactive.ReactorClientHttpResponse.

Apache: Unlike Netty, Apache is not merging max age and expires. Since org.springframework.http.client.reactive.HttpComponentsClientHttpResponse is an implementation of Apache HttpComponents HttpClient 5.x, I believe it's adaptCookies() method should process both Max-Age and Expires in ResponseCookie just like Apache.

For fix, we can add Expires attribute to ResponseCookie. And in case of  org.springframework.http.client.reactive.HttpComponentsClientHttpResponse.adaptCookies(), we set expires attribute if present. 

Can I go ahead and raise a PR with this?

**Comment by sbrannen** [comment] 2024-08-08 11:52
Hi @imvtsl,

We discussed this within the team and decided to update the logic in `org.springframework.http.client.reactive.HttpComponentsClientHttpResponse.adaptCookies(HttpClientContext)` to set `maxAge()` in the `ResponseCookie` to the converted value of the `Expires` attribute if `Expires` is present and `Max-Age` is not present, and we would otherwise process `Max-Age` as we currently do, thereby giving precedence to `Max-Age`.

We will also need to ensure that we have `Max-Age`/`Expires` tests in place for all `org.springframework.http.client.reactive.ClientHttpResponse` implementations -- for example, `HttpComponentsClientHttpResponse`, `JettyClientHttpResponse`, `ReactorClientHttpResponse`, and `ReactorNetty2ClientHttpResponse`.

If any of those other implementations lack support for handling `Max-Age` and `Expires` as previously stated, we would need to update their processing logic as well.

If you would like to submit a PR for this, feel free to do so. Otherwise, I will get to it in the coming weeks.

Cheers,

Sam

**Comment by imvtsl** [comment] 2024-08-11 05:47
Hey @sbrannen 
Thanks for the response. I will raise a PR with this approach and add tests for all `org.springframework.http.client.reactive.ClientHttpResponse` implementations.

Out of curiosity, why do we deviate from  from the approach of Apache HttpComponents HttpClient 5.x where they do not merge `Max-Age` and `Expires`. Is it to maintain uniformity across all `org.springframework.http.client.reactive.ClientHttpResponse` implementations?

**Comment by sbrannen** [comment] 2024-08-11 15:21
Hi @imvtsl,

> Hey @sbrannen Thanks for the response.

You're very welcome.

> I will raise a PR with this approach and add tests for all `org.springframework.http.client.reactive.ClientHttpResponse` implementations.

That would be much appreciated. 👍 

> For fix, we can add Expires attribute to ResponseCookie.

We do not wish to modify the API for `ResponseCookie` to achieve this.

> Out of curiosity, why do we deviate from the approach of Apache HttpComponents HttpClient 5.x where they do not merge `Max-Age` and `Expires`. Is it to maintain uniformity across all `org.springframework.http.client.reactive.ClientHttpResponse` implementations?

Yes, that's correct. We want the handling to be internal and transparent to the user, without changes to the current public APIs.

Cheers,

Sam

**Comment by imvtsl** [comment] 2024-08-12 06:46
Hi @sbrannen 
Thank you for the explanation, appreciate it.
I have written tests for `org.springframework.http.client.reactive.ClientHttpResponse` implementations -- for example, `HttpComponentsClientHttpResponse`, `JettyClientHttpResponse`, `ReactorClientHttpResponse`, and `ReactorNetty2ClientHttpResponse` [here](https://github.com/spring-projects/spring-framework/pull/33369/files).

It fails for Reactor Netty 2 and HttpComponents. I will raise the fix very soon.

Thanks!

**Comment by imvtsl** [comment] 2024-08-13 02:05
I have raised the [PR](https://github.com/spring-projects/spring-framework/pull/33369) with fix and tests.

**Comment by imvtsl** [comment] 2024-08-14 05:14
Hey @sbrannen 

Please let me know if there is anything required from my end. I will be on vacation from Thursday to Monday. I will be available to do changes until tomorrow, otherwise I can do them after I come back on Tuesday.

Thanks!
Vatsal

**Closed** 2024-09-13 13:56 UTC
Labels: in: web, type: bug
