### ISSUE TITLE
Invalid packet in WebSocket ping

### ISSUE THREAD

**Issue by mmikkone** [spring-projects/spring-framework#26922] opened 2021-05-10 08:41 UTC
**Affects:** \<5.3.6>

---

When setting server ping in Spring WebSocket, a text packet (opcode 1) with payload '\n' (0xA) is sent to the client. As a result the client doesn't understand the packet and doesn't send pong. I think the packet opcode should be 0x9 (ping).

Background info:

There was also another issue: ping sent by client does not update session timeout (doesn't push timeout timestamp further). I'm getting session expiration despite of client sending pings. But because of this problem, I'm now trying out server pings. 

My session maximum idle interval is 30 seconds.

I'm establishing the session through a separate REST login endpoint. I use the received session cookie in the header when establishing a WebSocket connection. I've tried using embedded Hazelcast session repository and embedded Redis, too.

This is my WebSocket configuration:

```java
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig extends AbstractSessionWebSocketMessageBrokerConfigurer<Session> {
    @Override
    public void configureMessageBroker(MessageBrokerRegistry config) {
        ThreadPoolTaskScheduler pingScheduler = new ThreadPoolTaskScheduler();
        pingScheduler.setPoolSize(1);
        pingScheduler.setThreadNamePrefix("wss-heartbeat-thread-");
        pingScheduler.initialize();

        config.enableSimpleBroker("/topic").setHeartbeatValue(new long[]{10000, 0}).setTaskScheduler(pingScheduler);
        config.setApplicationDestinationPrefixes("/messages");
        config.setUserDestinationPrefix("/user");
    }

    @Override
    protected void configureStompEndpoints(StompEndpointRegistry registry)
    {
        registry.addEndpoint("/stomp").withSockJS();
    }

    @Override
    public void configureClientInboundChannel(ChannelRegistration registration) {
        super.configureClientInboundChannel(registration);
        registration.interceptors(new TopicSubscriptionInterceptor());
    }
}
```

**Comment by rstoyanchev** [comment] 2021-05-26 09:27
What is the client, and is it possible to provide a repro project?

**Comment by mmikkone** [comment] 2021-05-26 10:40
Unfortenately repro project is not possible, because I have a deadline and
I've already moved on to embedded ActiveMQ which seems to fulfill our
needs.

The client was a python client using websockets.py and stomper.py. I
verified the issue by debugging the python client and WireShark.

-Marko


ke 26. toukokuuta 2021 klo 12.27 Rossen Stoyanchev ***@***.***>
kirjoitti:

**Comment by rstoyanchev** [comment] 2021-05-26 13:07
The heartbeat [is defined](https://stomp.github.io/stomp-specification-1.2.html#Heart-beating) in the protocol as an EOL character, and the [BNF section](https://stomp.github.io/stomp-specification-1.2.html#Augmented_BNF) says that's an optional CR (0x13) followed by LF (0x10). I'm not sure where you get that it should be 0x9 which is HT (horizontal tab).

We send `\n` which should be fine according to the protocol. It works with the stomp.js client and our own Java STOMP client. We also use the same codecs to parse heartbeats from and external brokers and from clients, which hasn't brought up any issues. Hence my question about which client you experience this with. 

As far as I can see [ActiveMQ sends](https://github.com/apache/activemq/blob/fc80b86ac68432f71a1015ee9588a0b6fcb5fbae/activemq-stomp/src/main/java/org/apache/activemq/transport/stomp/StompWireFormat.java#L100) a `\n` character as well. Do you know why that has made a difference?

**Comment by rstoyanchev** [comment] 2021-05-26 13:10
Also looking to version 1.1 of the protocol, in case the client is built for that, it says a [single newline byte](https://stomp.github.io/stomp-specification-1.1.html#Heart-beating).

**Comment by mmikkone** [comment] 2021-05-27 14:03
I was under impression that setting a heartbeat sets a keepalive mechanism for the underlying WebSocket: https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2 -Marko  Lähettäjä: Rossen StoyanchevLähetetty: keskiviikko 26. toukokuuta 2021 16.11Vastaanottaja: spring-projects/spring-frameworkKopio: mmikkone; AuthorAihe: Re: [spring-projects/spring-framework] Invalid packet in WebSocket ping (#26922) Also looking to version 1.1 of the protocol, in case the client is built for that, it says a single newline byte.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rstoyanchev** [comment] 2021-09-07 15:54
STOMP has its own heartbeat mechanism which is at a level above the transport (WebSocket, TCP). I'm closing this as there is not enough information to understand the root cause of the issue.

**Closed by rstoyanchev** 2021-09-07 15:54 UTC
Labels: status: waiting-for-triage, in: messaging, in: web, status: feedback-provided
