### ISSUE TITLE
RequestMapping produces not overriding at method level

### ISSUE THREAD

**Issue by vgrazi** [spring-projects/spring-framework#25391] opened 2020-07-14 20:25 UTC
We upgraded from Spring Boot 1.5.9.RELEASE to 2.1.8.RELEASE.

Previously we had this annotation on the controller:
```java
@Controller
@RequestMapping(value = "/allocation", produces = {APPLICATION_JSON_VALUE})
```

And we had the same on our "execute" method.
(This method downloads a csv file.)
```java
    public List<Map<String, Object>> execute(
            HttpServletRequest request,
            HttpServletResponse response,
```

This was working fine before the Spring Boot upgrade.
However after the upgrade it was returning a 406.

We added produces text/csv to the method level, but still getting the 406.
Then we added produces text/csv to the controller, and now it works.

(this never used to be required, there is no Spring Framework Media Type for text/csv.)

According to the documentation, the produces at the method level is supposed to override the one at the controller level. This is not happening. (Also, why are we now enforcing the JSON type, where before we did not?)

**Comment by rstoyanchev** [comment] 2020-07-20 08:26
@vgrazi, method level `produces` should be overriding so I'm not sure yet what's going on. 

Can you show the method level mapping? I'm also a little puzzled by the execute method signature which implies that it may write to the response but it also returns a value. If the response is rendered by through a converter, is it `StringHttpMessageConverter`  that does that or is there a custom custom converter? 

I'm trying to understand enough to reproduce the issue. Ideally if it is possible to create a sample that would be best.

**Comment by spring-issuemaster** [comment] 2020-07-27 08:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-08-03 08:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-08-03 08:30 UTC
Labels: in: web, status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
