### ISSUE TITLE
commonDatabaseName returns MySql for MariaDB

### ISSUE THREAD

**Issue by cppwfs** [spring-projects/spring-framework#28994] opened 2022-08-22 15:13 UTC
When using `commonDatabaseName` from `JdbcUtils` to obtain the common db name for "MariaDB" it returns "MySql".
https://github.com/spring-projects/spring-framework/blob/main/spring-jdbc/src/main/java/org/springframework/jdbc/support/JdbcUtils.java#L458-L461

With MariaDB 5.5 and below this works.    But with MariaDB 10.0+ the db's no longer align with some of their behaviors.   Should `commonDatabaseName` return "MariaDB"?

**Comment by snicoll** [comment] 2022-08-22 16:01
Duplicate of #28305

**Closed by snicoll** 2022-08-22 16:01 UTC
Labels: status: waiting-for-triage
