### ISSUE TITLE
Spring 2.3.5.RELEASE tries too flush closed OutputStream on HTTP response

### ISSUE THREAD

**Issue by pkunk** [spring-projects/spring-framework#26045] opened 2020-11-07 22:57 UTC
**Affects:** \<Spring Framework 5.2.10.RELEASE>

---
Starting from version 5.2.10.RELEASE on HTTP response AbstractGenericHttpMessageConverter (Jackson) tries too flush already closed stream .

Seems Tomcat handles this gracefully, even if `org.apache.catalina.connector.OutputBuffer.closed == true` on the last flush.
But this causes problems for OpenLiberty: [https://github.com/OpenLiberty/open-liberty/issues/14875](https://github.com/OpenLiberty/open-liberty/issues/14875)
Here is repository with example for OL: https://github.com/pkunk/wlp-spring

**Comment by bclozel** [comment] 2020-11-07 23:15
This is a duplicate of #25989 which has been fixed already. Feel free to check out SNAPSHOTs and validate the fix before our next release.

Thanks for getting in touch!

**Closed** 2020-11-07 23:15 UTC
Labels: status: duplicate

**Comment by pkunk** [comment] 2020-11-08 00:32
Confirm. Cannot reproduce on SNAPSHOT build. Thank you for your work.
