### ISSUE TITLE
Use CompletionService to replace ExecutorSerive in the method org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.submit(Callable<T>) [SPR-17219]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21752] opened 2018-08-27 09:47 UTC
**[qudh1](https://jira.spring.io/secure/ViewProfile.jspa?name=qudh1)** opened **[SPR-17219](https://jira.spring.io/browse/SPR-17219?redirect=false)** and commented

The CompletionService is basically a Queue which returns the Futures in the order which they complete.It would be better to use CompletionService to replace ExecutorSerive in the method org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.submit(Callable\<T>).

Current code is 

```java
@Override @Override public <T> Future<T> submit(Callable<T> task) { ExecutorService executor = getThreadPoolExecutor(); try { return executor.submit(task); } catch (RejectedExecutionException ex) { throw new TaskRejectedException("Executor [" + executor + "] did not accept task: " + task, ex); } }
```

Code implement by CompletionService is 

```java
 @Override @Override public <T> Future<T> submit(Callable<T> task) { ExecutorService executor = getThreadPoolExecutor(); CompletionService<T> completionService = new ExecutorCompletionService<>(executor);
 try { return completionService.submit(task); } catch (RejectedExecutionException ex) { throw new TaskRejectedException("Executor [" + executor + "] did not accept task: " + task, ex); } }

```

---

**Affects:** 5.0.8

**Referenced from:** pull request https://github.com/spring-projects/spring-framework/pull/1945

**Comment by snicoll** [comment] 2021-11-24 14:44
Duplicate of #1945

**Closed by snicoll** 2021-11-24 14:44 UTC
Labels: status: waiting-for-triage, in: core
