### ISSUE TITLE
Support transactions across multiple DataSources

### ISSUE THREAD

**Issue by zhb-github** [spring-projects/spring-framework#26959] opened 2021-05-20 03:03 UTC
I install Multi dataSource.
but you can't support transaction.

When an exception occurs, roll back the last one,because the current thread is bound to a last transaction.

current thread Whether you can bind multiple TransactionInfo. When an exception occurs, roll back all transaction;

**Comment by sbrannen** [comment] 2021-05-20 13:59
Hi @zhb-github,

Thanks for raising your first issue with the Spring Framework!

Spring's transaction management supports a single transactional resource by design.

If you wish to support transactions across multiple transactional resources (like the multiple databases in your use case), you have several options which are outlined in @dsyer's excellent article on [Distributed transactions in Spring, with and without XA](https://www.javaworld.com/article/2077963/open-source-tools/distributed-transactions-in-spring--with-and-without-xa.amp.html).

In light of that, I am closing this issue.

**Closed by sbrannen** 2021-05-20 13:59 UTC
Labels: in: data, status: declined
