### ISSUE TITLE
Default content type in ContentNegotiationConfigurer not taken into account

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-framework#29300] opened 2022-10-11 13:30 UTC
I have a `@GetMapping` `@RestController` that could produce both xml and json.
If `Content-Type` is missing in the clients' request, by default `json` should be returned.

I therefor tried to set `ContentNegotiationConfigurer`, but without any effect:

> .w.s.m.s.DefaultHandlerExceptionResolver : 
> Resolved [org.springframework.http.converter.HttpMessageNotWritableException:
> No converter for [class java.util.ImmutableCollections$Set12] with preset Content-Type 'null']

```java
@Configuration
public class WebConfig implements WebMvcConfigurer {
	@Override
	public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
		configurer.defaultContentType(MediaType.APPLICATION_JSON);
	}
}

@RestController
public class ExampleServlet {
	@GetMapping(value = "/test", produces = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE})
	public Set<String> test() {
		return Set.of("test");
	}
}
```

When I change the code to `produces=APPLICATION_JSON_VALUE` only, everything works as expected. So the servlet in general should be fine.

spring-boot-2.7.4

**Comment by bclozel** [comment] 2023-01-30 15:47
I can't reproduce the behavior you're describing with Spring Boot 2.7.8. Please provide a sample application that behaves as described.

**Comment by membersound** [comment] 2023-01-31 10:46
Okay, I think `Content-Type` is wrong in this issue, I probably ment `Accept-Encoding`.

While I cannot reproduce exactly, let me ask: does setting `configurer.defaultContentType()` forcibly exclude or prohibit any other content type? Or is it just a "favor", and other content types are still allowed?

Because when I set `configurer.defaultContentType(APPLICATION_JSON)` or `configurer.defaultContentType(APPLICATION_JSON, APPLICATION_XML)`, I'm unable to let spring produce `xml` output:

```
@Configuration
public class WebConfig implements WebMvcConfigurer {
    @Override
    public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
        configurer.defaultContentType(MediaType.APPLICATION_JSON);
        //configurer.defaultContentType(MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML);
    }
}
```

```
@RestController
public class ExampleServlet {
    @GetMapping(
            value = "/both",
            produces = {
                    MediaType.APPLICATION_XML_VALUE,
                    MediaType.APPLICATION_JSON_VALUE
            })
    public Set<String> both() {
        return Set.of("both");
    }

    @GetMapping(
            value = "/xml",
            produces = {
                    MediaType.APPLICATION_XML_VALUE
            })
    public Set<String> xml() {
        return Set.of("both");
    }
}
```
Both can't produce xml:

`curl --location --request GET 'localhost:8080/test' --header 'Accept-Encoding: application/xml'`:
```
[test]

```
`curl --location --request GET 'localhost:8080/both' --header 'Accept-Encoding: application/xml'`:
```
2023-01-31 11:45:47.436  WARN 38445 --- [nio-8080-exec-3] .w.s.m.s.DefaultHandlerExceptionResolver :
Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]
```

spring-boot.2.7.8

**Comment by bclozel** [comment] 2023-01-31 12:52
> Okay, I think Content-Type from clients perspective is wrong in this issue, I probably ment Accept-Encoding.

I think you meant the [`Accept` request header instead](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept), as using this header with your sample application behaves as expected.

I'm closing this issue now.

**Closed by bclozel** 2023-01-31 12:52 UTC
Labels: status: waiting-for-triage, in: web, status: feedback-provided

**Comment by membersound** [comment] 2023-01-31 18:25
So I'd have to open a new issue, targeting that if `xml` in accept header or format is requested, then spring still renders json output? I don't think this is correct...

**Comment by bclozel** [comment] 2023-01-31 18:48
I don't understand. Running your sample application, here's the behavior.

With `configurer.defaultContentType(MediaType.APPLICATION_JSON);`

```
$ http :8080/both Accept:"*/*"
HTTP/1.1 200
Connection: keep-alive
Content-Type: application/json
Date: Tue, 31 Jan 2023 18:36:36 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

[
    "both"
]
```

```
$ http :8080/both Accept:"application/xml"
HTTP/1.1 200
Connection: keep-alive
Content-Type: application/xml
Date: Tue, 31 Jan 2023 18:37:01 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

<Set>
  <item>both</item>
</Set>
```

```
$ http :8080/both Accept:"application/json"
HTTP/1.1 200
Connection: keep-alive
Content-Type: application/json
Date: Tue, 31 Jan 2023 18:37:05 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

[
    "both"
]
```

Same behavior applies for `configurer.defaultContentType(MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML);`, as ordering is taken into account (see javadoc).

For example, changing the order with `configurer.defaultContentType(MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON);` result in a single behavior change:

```
$ http :8080/both Accept:"*/*"
HTTP/1.1 200
Connection: keep-alive
Content-Type: application/xml
Date: Tue, 31 Jan 2023 18:39:41 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

<Set>
  <item>both</item>
</Set>
```

Using the following configuration properties (which are mentioned in this issue but missing from the sample:

```
spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.media-types.json=application/json
spring.mvc.contentnegotiation.media-types.xml=application/xml
```

We can see the parameter used for content negotiation:

```
$ http -v :8080/both format==json
GET /both?format=json HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/3.2.1



HTTP/1.1 200
Connection: keep-alive
Content-Type: application/json
Date: Tue, 31 Jan 2023 18:44:59 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

[
    "both"
]
```

```
$ http -v :8080/both format==xml
GET /both?format=xml HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/3.2.1



HTTP/1.1 200
Connection: keep-alive
Content-Type: application/xml
Date: Tue, 31 Jan 2023 18:45:23 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

<Set>
  <item>both</item>
</Set>
```


This is all working as expected from my point of view.
Could you explain precisely what the problem is with this behavior?

**Comment by membersound** [comment] 2023-01-31 19:06
Your explanation is exactly what I would have expected, but was not when adding the sample app.
Maybe this is a local machine issue. Will try tomorrow and report back!

**Comment by membersound** [comment] 2023-02-01 08:20
Omg, I didn't notice the difference between `Accept` vs `Accept-Encoding`.
Of course it works using `Accept=application/xml`, ty!
