### ISSUE TITLE
Support of jakarta.xml.bind-api v3.0.0

### ISSUE THREAD

**Issue by drz0910** [spring-projects/spring-framework#26439] opened 2021-01-25 10:13 UTC
From jakarta.xml.bind-api **v3.0.0,** the namespace has been changed to `jakarta.xml.bind.*` instead of `javax.xml.bind`
The last working version is jakarta.xml.bind-api **v2.7.8**

The org.springframework.http.codec.support.BaseDefaultCodecs file hardcoded `javax.xml.bind` namespace with 
`jaxb2Present = ClassUtils.isPresent("javax.xml.bind.Binder", classLoader);`
So it's not working for the newer version of jakarta.xml.bind-api.

Would the support be considered to add in any near future release? Thanks!

**Affects:** \<5.3.2>

---

**Comment by andrei-ivanov** [comment] 2021-01-25 10:16
See #25354

**Comment by sbrannen** [comment] 2021-01-25 10:21
Closing as a duplicate of #25354.

**Closed by sbrannen** 2021-01-25 10:21 UTC
Labels: status: waiting-for-triage
