### ISSUE TITLE
TransactionAspectSupport: perform a commit on mono cancelation

### ISSUE THREAD

**Issue by deblockt** [spring-projects/spring-framework#26550] opened 2021-02-15 13:47 UTC
**Affects:** spring-tx 5.2.8.RELEASE

---

Actually, The TransactionAspectSupport commit the transaction on a mono cancel.
This can happen on a timeout on an HTTP call.

This is problematic if the treatment perform multiple insertions, If we have two tables `customer` and `address` and the following treatment: 
   - insert the customer
   - insert the address

If the mono is canceled between the two operations, the commit is performed on a partial transaction. 
This is not an intuitive behavior for a transaction. 

Can we update the transaction behaviour to perform a rollback in case of cancel?

**Comment by jhoeller** [comment] 2021-02-15 13:52
This seems to be a duplicate of #25256. We changed this behavior for 5.3, so please give it a try there!

**Closed by jhoeller** 2021-02-15 13:52 UTC
Labels: in: data, status: duplicate
