### ISSUE TITLE
Proxy method（cglib.proxy.MethodInterceptor:intercept()） takes too long to execute.

### ISSUE THREAD

**Issue by c00451707** [spring-projects/spring-framework#30199] opened 2023-03-26 08:28 UTC
See the picture below for details.

![image](https://user-images.githubusercontent.com/37258740/227764261-75adaee6-c926-47f0-9fbe-690bd95b7d52.png)

**Comment by bclozel** [comment] 2023-03-27 07:39
Could you provide a sample, minimal application that reproduces this problem?
Screenshots aren't enough for us to understand what's going on.

**Comment by c00451707** [comment] 2023-04-01 12:14
> Could you provide a sample, minimal application that reproduces this problem? Screenshots aren't enough for us to understand what's going on.

After a preliminary analysis, it is a problem caused by Spring transactions. 7 concurrent requests call the interface of this service, causing the database access of the system to be stuck.

**Comment by c00451707** [comment] 2023-04-02 14:22
Call a method with transactions concurrently, which uses feign to call an interface of this service, which also has transactions.
The problem phenomenon is: the set concurrency degree is clearly 20, but the actual concurrency degree becomes 7. And the methods are blocked where the feign interface is called.
If I remove the transaction of the method, the actual concurrency can be changed to 20, and the feign call will not block.

**Comment by c00451707** [comment] 2023-04-02 14:25
![image](https://user-images.githubusercontent.com/37258740/229358978-4aed9d70-5c33-4ce7-98f4-561b60601933.png)

![image](https://user-images.githubusercontent.com/37258740/229359013-733ffbf9-6431-4120-8ad0-21e9ac925aa1.png)

**Comment by c00451707** [comment] 2023-04-03 02:11
I suspect that it is affected by the related configuration of the database transaction, causing Spring to block when executing the Aop aspect of the transaction.

**Comment by bclozel** [comment] 2023-04-03 07:40
Since it seems to be a configuration issue, I'm closing this issue for now. We can reopen it if you can provide a sample application showing this is a bug. Thanks!

**Closed by bclozel** 2023-04-03 07:40 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by c00451707** [comment] 2023-04-04 01:51
This problem is solved. The problem is that the transaction caused by concurrency has not been released, and the database connection has not been released. Causes new requests to be blocked while obtaining a database connection (maxWait is the default value -1)
