### ISSUE TITLE
spring-jcl in SpringApplicationShutdownHook Unreliable logging during execution, resulting in missing exception messages

### ISSUE THREAD

**Issue by syrm-ll** [spring-projects/spring-framework#28946] opened 2022-08-10 11:56 UTC
### Preconditions
 A normal Spring Boot web project with `module-info.java`, using `slf4j` `logback` logging, see the last section for environment information

### 问题
When I shut down the Java process (kill <PID>), **occasionally** the following error stack appears:
```log
Exception in thread "SpringApplicationShutdownHook" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.log(Logger.java:765)
        at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.warn(LogAdapter.java:447)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1070)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
        at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
        ... 12 more
```

It looks like the problem occurs in `org.springframework.context.support.AbstractApplicationContext#doClose` (AbstractApplicationContext.java:1070)

## Environmental information

org.springframework:*:5.3.20

openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing

---

### 前提条件
 一个普通的Spring Boot Web 项目, 含有 `module-info.java`, 使用 `slf4j` `logback` 日志记录, 环境信息见最后一节

### 问题
当我关闭 Java 进程时 (kill <PID>), **偶尔**会出现如下错误堆栈:
```log
Exception in thread "SpringApplicationShutdownHook" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.log(Logger.java:765)
        at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.warn(LogAdapter.java:447)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1070)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
        at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
        ... 12 more
```

看起来问题发生在 `org.springframework.context.support.AbstractApplicationContext#doClose` 方法 (AbstractApplicationContext.java:1070) 

## 环境信息
org.springframework:*:5.3.20

openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing

**Comment by bclozel** [comment] 2023-01-30 14:25
Is the JAR being updated or removed while the shutdown hook is being executed?

I'm closing this issue as a duplicate of #27118 spring-projects/spring-boot#6151. If you can provide a sample app that reproduces the issue, please provide it and we'll reopen this issue.

**Closed by bclozel** 2023-01-30 14:25 UTC
Labels: status: waiting-for-triage, in: core
