### ISSUE TITLE
No qualifying bean of type 'xxx' available

### ISSUE THREAD

**Issue by aispringli** [spring-projects/spring-framework#29209] opened 2022-09-27 02:02 UTC
I meet some problems when attempt to use Spring Boot 3.0 M5 , there are "No qualifying bean of type 'xxx' available", it can work well in Spring6-M5, i think this is Spring Bean cause problems, dont know how to solve, who also meet this?
someone like this: 

`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.openfeign.FeignContext' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340) ~[spring-beans-6.0.0-M6.jar:6.0.0-M6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-6.0.0-M6.jar:6.0.0-M6]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:411) ~[spring-cloud-openfeign-core-4.0.0-M4.jar:4.0.0-M4]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:402) ~[spring-cloud-openfeign-core-4.0.0-M4.jar:4.0.0-M4]
	at org.springframework.cloud.openfeign.FeignClientsRegistrar.lambda$registerFeignClient$0(FeignClientsRegistrar.java:235) ~[spring-cloud-openfeign-core-4.0.0-M4.jar:4.0.0-M4]`

**Comment by bclozel** [comment] 2022-09-27 05:16
Could you share a minimal application that reproduces the problem? Ideally something we can git clone or download.
This might be due to a subtle change somewhere and it is hard to guess without a way to reproduce the behavior. Thanks!

**Comment by aispringli** [comment] 2022-09-27 05:57
[a simple demo ](https://github.com/aispringli/demo)

**Comment by bclozel** [comment] 2022-09-27 06:45
I think this is a duplicate of spring-cloud/spring-cloud-openfeign#755, the project catching up with spring-projects/spring-boot#29699.
You will need to wait for the next cloud feign release for the fix (or try the snapshots).

**Closed** 2022-09-27 06:46 UTC
Labels: status: invalid, for: external-project
