### ISSUE TITLE
spring webflux with undertow cause org.xnio.channels.FixedLengthOverflowException on benchmark

### ISSUE THREAD

**Issue by UserTerry** [spring-projects/spring-framework#22690] opened 2019-03-27 11:46 UTC
OS:mac os 10.13.6
JDK:11.0.2 x64 

Hello

I want to try using the spring webflux, so I did some tests comparing different containers when I made a mistake when using the spring webflux with undertow

```
2019-03-27 19:23:10.290 ERROR 923 --- [   XNIO-1 I/O-8] o.s.w.s.adapter.HttpWebHandlerAdapter    : [7758abf3] Error [java.lang.UnsupportedOperationException] for HTTP GET "/test", but ServerHttpResponse already committed (200 OK)
org.xnio.channels.FixedLengthOverflowException
	at io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.write(AbstractFixedLengthStreamSinkConduit.java:100)
	at org.xnio.conduits.ConduitStreamSinkChannel.write(ConduitStreamSinkChannel.java:150)
	at io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:240)
	at io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2103)
	at org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.writeByteBuffer(UndertowServerHttpResponse.java:217)
	at org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.write(UndertowServerHttpResponse.java:193)
	at org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.write(UndertowServerHttpResponse.java:153)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor$State$3.onWritePossible(AbstractListenerWriteProcessor.java:353)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor.onWritePossible(AbstractListenerWriteProcessor.java:143)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor.writeIfPossible(AbstractListenerWriteProcessor.java:282)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor.changeStateToReceived(AbstractListenerWriteProcessor.java:261)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor.access$300(AbstractListenerWriteProcessor.java:45)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor$State$2.onNext(AbstractListenerWriteProcessor.java:336)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor.onNext(AbstractListenerWriteProcessor.java:107)
	at org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.emitCachedSignals(ChannelSendOperator.java:283)
	at org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.request(ChannelSendOperator.java:265)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor$State$3.onWritePossible(AbstractListenerWriteProcessor.java:362)
	at org.springframework.http.server.reactive.AbstractListenerWriteProcessor.onWritePossible(AbstractListenerWriteProcessor.java:143)
	at org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.lambda$new$0(UndertowServerHttpResponse.java:170)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:285)
	at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:272)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.writeReady(WriteReadyHandler.java:65)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:93)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
2019-03-27 19:23:10.361 ERROR 923 --- [   XNIO-1 I/O-8] o.s.w.s.adapter.HttpWebHandlerAdapter    : [5a32eeb7] Error [java.lang.UnsupportedOperationException] for HTTP GET "/test", but ServerHttpResponse already committed (200 OK)
```

Reproduction steps:
Repository: https://github.com/UserTerry/spring-webflux-with-undertow

**Comment by ehiggs** [comment] 2019-03-29 08:34
FWIW, I've seen this using raw undertow when I don't set the content length in the reply or transfer encoding. This means that the client will hang up too early since it's not aware that a body will be following.

**Comment by alfred-thomas** [comment] 2019-04-03 02:07
I have been getting the same error in our Production applications after switching from Netty to Undertow
`{
"message": "[720ea9e9] Error [java.lang.UnsupportedOperationException] for HTTP GET \"/xxx/xxx/xxx\", but ServerHttpResponse already committed (500 INTERNAL_SERVER_ERROR)",
  "event_source": "org.springframework.web.server.adapter.HttpWebHandlerAdapter",
  "thread_name": "XNIO-1 I/O-3",
  "log_level": "ERROR"
}`
I have been able to replicate this by running a load test against the server. On the client side, the client always gets a valid 200 response even though the error on the server side is 500. 
We use: 
SpringBoot 2.1.3
Undertow 2.0.17

**Comment by rstoyanchev** [comment] 2019-04-10 17:25
@alfred-thomas it looks like what you're getting is `java.lang.UnsupportedOperationException` while this issue is for a `org.xnio.channels.FixedLengthOverflowException`. So I think they're different root causes but both occur after the response is already committed.

**Comment by alfred-thomas** [comment] 2019-04-11 00:52
@rstoyanchev, oh yes correct. However we do also get the `FixedLengthOverflowException` as per below

    Caused by: org.xnio.channels.FixedLengthOverflowException: null
        io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.write(AbstractFixedLengthStreamSinkConduit.java:100)
        org.xnio.conduits.ConduitStreamSinkChannel.write(ConduitStreamSinkChannel.java:150)
        io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:240)
        io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2103)
        org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.writeByteBuffer(UndertowServerHttpResponse.java:217)
        org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.write(UndertowServerHttpResponse.java:193)
        org.springframework.http.server.reactive.UndertowServerHttpResponse$ResponseBodyProcessor.write(UndertowServerHttpResponse.java:153)
        org.springframework.http.server.reactive.AbstractListenerWriteProcessor$State$3.onWritePossible(AbstractListenerWriteProcessor.java:353)
    ... 18 common frames omitted

**Comment by gongmingbin** [comment] 2019-04-13 15:00
@UserTerry  @rstoyanchev  Though  I do not known why. But if I remove the line:
  .subscribeOn(Schedulers.fromExecutor(ForkJoinPool.commonPool()))
then no FixedLengthOverflowException throw in my pc. Maybe it,s a thread safe issue?

```
  @Override
    public Mono<Void> filter(ServerWebExchange serverWebExchange, WebFilterChain webFilterChain)
    {
        return webFilterChain
                .filter(serverWebExchange)
//                .subscribeOn(Schedulers.single())
//                .subscribeOn(Schedulers.parallel())
                .subscribeOn(Schedulers.fromExecutor(ForkJoinPool.commonPool())) // remove this line no FixedLengthOverflowException
                ;
    }
```

**Comment by rstoyanchev** [comment] 2019-09-11 11:04
See https://github.com/spring-projects/spring-framework/issues/22467#issuecomment-530326104. I believe the same applies here and this issue has the same underlying cause as for #22467 and #23096. The same exception was also observed under #22467. I updated the sample app to use Spring Framework `5.1.10.BUILD-SNPASHOT` and verified the exception no longer occurs.

**Closed by rstoyanchev** 2019-09-11 11:04 UTC
Labels: status: waiting-for-triage
