### ISSUE TITLE
spring-web UriComponentsBuilder fails to parse URI where domain starts with a digit

### ISSUE THREAD

**Issue by hertzsprung** [spring-projects/spring-framework#27733] opened 2021-11-25 09:09 UTC
**Affects:** spring-web 5.3.13

---
spring-web `UriComponentsBuilder` cannot parse a URI such as `http://my-host.1domain:1234/path` because the domain starts with a digit:

```java
URI uri = new URI("http", "my-host.1domain:1234", "/path", null, null);
System.out.println(uri); // parses correctly

UriComponentsBuilder.fromUriString("http://my-host.1domain:1234/path")
    .build()
    .toUri();
```

```
java.lang.IllegalStateException: Could not create URI object: Illegal character in hostname at index 15: http://my-host.1domain:1234/path
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:521)
	at com.thefloow.ephemeral.Cheese.main(Cheese.java:12)
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 15: http://my-host.1domain:1234/path
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3517)
	at java.base/java.net.URI$Parser.parseServer(URI.java:3358)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3277)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3219)
	at java.base/java.net.URI$Parser.parse(URI.java:3175)
	at java.base/java.net.URI.<init>(URI.java:708)
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:517)
	... 1 more
```

**Comment by poutsma** [comment] 2021-11-25 14:06
The core exception is from `java.net.URI`, so it seems to be a Java issue. It can be reproduced without Spring code:

```java
URI uri = new URI("http", null, "my-host.1domain", 1234, "/path", null, null);
```

Interestingly, the following result prints `null`, which does not seem correct either:

```java
System.out.println(new URI("http", "my-host.1domain:1234", "/path", null, null).getHost());
```

**Comment by poutsma** [comment] 2021-11-25 14:09
Resolving as invalid, as this is not a Spring bug.

**Closed by poutsma** 2021-11-25 14:09 UTC
Labels: in: web, status: invalid

**Comment by hertzsprung** [comment] 2021-11-26 11:52
Thanks for triaging so quickly.  I've asked a [StackOverflow question](https://stackoverflow.com/questions/70123940/java-net-uri-cannot-parse-domain-starting-with-a-number) to determine if this is a problem-between-chair-and-keyboard or a JDK bug.
