### ISSUE TITLE
WebFlux: Mono does not invoke onComplete(), but instead cancel()

### ISSUE THREAD

**Issue by RobWin** [spring-projects/spring-framework#22952] opened 2019-05-13 09:49 UTC
**Affects:** 5.1.6.RELEASE
---
Hello,

**How to reproduce**: 
When I have a simple `@RestController`:

```
@GetMapping("monoSuccess")
public Mono<String> monoSuccess(){
    return Mono.just("test").log();
}
```

I can see in the Reactor logs the following:

```
[ctor-http-nio-3] reactor.Mono.Just.1 : | onSubscribe([Synchronous Fuseable] Operators.ScalarSubscription)
[ctor-http-nio-3] reactor.Mono.Just.1 : | request(unbounded)
[ctor-http-nio-3] reactor.Mono.Just.1 : | onNext(test)
[ctor-http-nio-3] reactor.Mono.Just.1 : | cancel()
```

This behavior does not match the bahavior of Flux.

```
@GetMapping("fluxSuccess")
public Flux<String> fluxSuccess(){
        return Flux.just("test") .log();
}
```

```
reactor.Flux.Just.1 : | onSubscribe([Fuseable] FluxJust.WeakScalarSubscription)
reactor.Flux.Just.1 : | request(1)
reactor.Flux.Just.1 : | onNext(test)
reactor.Flux.Just.1 : | request(32)
reactor.Flux.Just.1 : | onComplete()
```

**My expectation**: 
- I would expect that Mono and Flux behavior similar.
- I would expect that `onComplete()` is invoked instead of `ScalarSubscription.cancel()` after `onNext`.

**My problem** :
When I do a simple test with my Resilience4j CircuitBreaker operator I can see the expected behavior of Reactor.

``` 
 StepVerifier.create(
    Mono.just("Event")
      .log()
      .transform(CircuitBreakerOperator.of(circuitBreaker))
      .log())
    .expectNext("Event")
    .verifyComplete();
```

```
reactor.Mono.Just.1 - | onSubscribe([Synchronous Fuseable] Operators.ScalarSubscription)
reactor.Mono.CircuitBreaker.2 - onSubscribe(CircuitBreakerSubscriber)
reactor.Mono.CircuitBreaker.2 - request(unbounded)
reactor.Mono.Just.1 - | request(unbounded)
reactor.Mono.Just.1 - | onNext(Event)
reactor.Mono.CircuitBreaker.2 - onNext(Event)
reactor.Mono.Just.1 - | onComplete()
reactor.Mono.CircuitBreaker.2 - onComplete()
```

My custom CircuitBreaker operator handles `onComplete` as a successful call and `onError` as a failed call. But `onEvent` is just forwarded to the downstream subscriber.
With the current unexpected behavior I have to handle `onEvent` specially when a `Mono` is decorated.

Kind regards,

Robert

**Comment by smaldini** [comment] 2019-05-13 17:25
I need to check where the cancel comes from but it could be an operator doing that as part of a generic conversion from any Publisher/Flux to mono.

**Comment by rstoyanchev** [comment] 2019-05-13 20:42
I didn't see your comment @smaldini but in the mean time I did some checking. I added `.log()` to the Publisher passed into Reactor Netty (i.e. [right here](https://github.com/spring-projects/spring-framework/blob/e0654a5b3dcf55a7840cd29d25c55854a071202c/spring-web/src/main/java/org/springframework/http/server/reactive/ReactorServerHttpResponse.java#L126-L127)) and I can confirm the cancel comes from Reactor Netty's side.

This is more specifically what I see for `Mono` with Californium-SR8 and SR-7:
```
[reactor-http-epoll-2] 38:30 1: | onSubscribe([Fuseable] FluxMapFuseable.MapFuseableSubscriber)
[reactor-http-epoll-2] 38:30 1: | request(unbounded)
[reactor-http-epoll-2] 38:30 1: | onNext(PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 12))
[reactor-http-epoll-2] 38:30 1: | cancel()
```

For Californium-SR6 and below, strangely both onComplete and cancel:
```
[reactor-http-epoll-2] 39:44 1: | onSubscribe([Fuseable] FluxMapFuseable.MapFuseableSubscriber)
[reactor-http-epoll-2] 39:44 1: | request(32)
[reactor-http-epoll-2] 39:44 1: | onNext(PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 12))
[reactor-http-epoll-2] 39:44 1: | request(1)
[reactor-http-epoll-2] 39:44 1: | onComplete()
[reactor-http-epoll-2] 39:44 HttpWebHandlerAdapter: [c8a27a36] Completed 200 OK, headers=[Content-Type:"text/plain;charset=UTF-8", Content-Length:"4"]
[reactor-http-epoll-2] 39:44 HttpLogging: [c8a27a36] Handling completed
[reactor-http-epoll-2] 39:44 1: | cancel()
```

For `Flux` in SR-6 and lower I see both onComplete and cancel, but for SR-7 and SR-8 correctly only onComplete.

**Comment by rstoyanchev** [comment] 2019-05-13 21:03
And here is the output with `.doOnCancel(() -> new Exception().printStackTrace())`:

```
java.lang.Exception
	at org.springframework.http.server.reactive.ReactorServerHttpResponse.lambda$toByteBufs$1(ReactorServerHttpResponse.java:126)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.cancel(FluxPeekFuseable.java:146)
	at reactor.core.publisher.Operators.terminate(Operators.java:1044)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:180)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.cancel(FluxContextStart.java:137)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1931)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1900)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1712)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.cancel(MonoIgnoreElements.java:96)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.cancel(FluxContextStart.java:137)
	at reactor.core.publisher.Operators.terminate(Operators.java:1044)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.cancel(MonoFlatMap.java:264)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:181)
	at reactor.core.publisher.Operators.terminate(Operators.java:1044)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.cancel(MonoFlatMap.java:264)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:181)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1931)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1900)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1712)
	at reactor.core.publisher.Operators.terminate(Operators.java:1044)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.cancel(MonoFlatMap.java:264)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:181)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1931)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1900)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1712)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1931)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1900)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1712)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:1931)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1900)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1712)
	at reactor.core.publisher.Operators.terminate(Operators.java:1044)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.cancel(MonoIgnoreThen.java:244)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.cancel(MonoIgnoreThen.java:184)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.cancel(FluxPeekFuseable.java:435)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136)
	at reactor.core.publisher.Operators.terminate(Operators.java:1044)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:395)
	at reactor.netty.http.server.HttpServerOperations.cleanHandlerTerminate(HttpServerOperations.java:519)
	at reactor.netty.http.server.HttpTrafficHandler.operationComplete(HttpTrafficHandler.java:313)
	at reactor.netty.http.server.HttpTrafficHandler.operationComplete(HttpTrafficHandler.java:54)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:715)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:270)
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:350)
	at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:361)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:269)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:480)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:438)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:939)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:517)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:906)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1370)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
	at reactor.netty.http.HttpOperations.lambda$send$0(HttpOperations.java:104)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2066)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:138)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:172)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoSubscriberContext.subscribe(MonoSubscriberContext.java:47)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:146)
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60)
	at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37)
	at reactor.core.publisher.MonoSubscriberContext.subscribe(MonoSubscriberContext.java:47)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2066)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.request(FluxContextStart.java:132)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onSubscribe(FluxContextStart.java:97)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoSubscriberContext.subscribe(MonoSubscriberContext.java:47)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:102)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1874)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1748)
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:64)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1510)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:204)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1510)
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2066)
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onSubscribe(MonoIgnoreThen.java:285)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:161)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:275)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:849)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2066)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1874)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1748)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:442)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:212)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:70)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.netty.http.server.HttpServerHandle.onStateChange(HttpServerHandle.java:64)
	at reactor.netty.tcp.TcpServerBind$ChildObserver.onStateChange(TcpServerBind.java:226)
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:442)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RobWin** [comment] 2019-05-14 06:47
It's happening here?

```
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:136)
at reactor.core.publisher.Operators.terminate(Operators.java:1044)
at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:395)
at reactor.netty.http.server.HttpServerOperations.cleanHandlerTerminate(HttpServerOperations.java:519) 
at reactor.netty.http.server.HttpTrafficHandler.operationComplete(HttpTrafficHandler.java:313)
```

**Comment by RobWin** [comment] 2019-05-14 08:21
@smaldini might be right :)
I debugged my Resilience4j Spring Boot 2 demo.

It's [MonoNext](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/MonoNext.java#L75) which seems to invoke cancel. It's a `MonoFromFluxOperator`.

**Comment by rstoyanchev** [comment] 2019-05-15 18:51
@smaldini has pointed out that our `EncoderHttpMessageWriter` uses [Mono.from(flux)](https://github.com/spring-projects/spring-framework/blob/a30a134c2397a7482bfd8c895f7ec1dc633e2067/spring-web/src/main/java/org/springframework/http/codec/EncoderHttpMessageWriter.java#L122) which also issues cancels after reading 1 element. So for 5.1.8 we can do `flux.singleOrEmpty()` which avoids cancel if there is single value. For 5.2 we could use the new `Encoder#encodeValue` to do better.

**Comment by smaldini** [comment] 2019-05-15 18:59
In my test I actually see 2 cancels:
- one mentioned by @rstoyanchev above
- one that is caused by the promise success of the single response send (optimized in reactor-netty 0.8.7+ and so spring framework 5.1.7+). I am investigating that separately and I have opened an issue for reactor-netty (https://github.com/reactor/reactor-netty/issues/741)

**Comment by rstoyanchev** [comment] 2019-05-15 21:33
After the change I see:
```
[reactor-http-epoll-2] 49:58 1: | onSubscribe([Synchronous Fuseable] Operators.ScalarSubscription)
[reactor-http-epoll-2] 49:58 1: | request(unbounded)
[reactor-http-epoll-2] 49:58 1: | onNext(test)
[reactor-http-epoll-2] 49:58 HttpLogging: [d16c919f] Writing "test"
[reactor-http-epoll-2] 49:58 1: | onComplete()
[reactor-http-epoll-2] 49:58 1: | cancel()
```

whereas before it was:
```
[reactor-http-epoll-2] 48:18 1: | onSubscribe([Synchronous Fuseable] Operators.ScalarSubscription)
[reactor-http-epoll-2] 48:18 1: | request(unbounded)
[reactor-http-epoll-2] 48:18 1: | onNext(test)
[reactor-http-epoll-2] 48:18 HttpLogging: [6bafe99d] Writing "test"
[reactor-http-epoll-2] 48:18 1: | cancel()
[reactor-http-epoll-2] 48:18 1: | cancel()
```

The remaining cancel should be fixed in Reactor Netty.

**Closed** 2019-05-15 21:34 UTC
Labels: in: web, type: enhancement
