### ISSUE TITLE
Table of contents in documentation is broken

### ISSUE THREAD

**Issue by iluuu1994** [spring-projects/spring-framework#24254] opened 2019-12-23 22:23 UTC
**Affects:** 5.2.2

---

Excuse me if I'm reporting this issue in the wrong place.

https://docs.spring.io/spring/docs/5.2.2.RELEASE/spring-framework-reference/core.html

The first ~20% of the page is fine but afterwards all the titles aren't correctly parsed any more. The first title that is broken is `Using Generics as Autowiring Qualifiers`. After that point all titles are parsed as plain text with the `=` as part of the text. This makes it very hard to navigate through the document.

Thanks!

**Comment by snicoll** [comment] 2019-12-24 07:39
Thanks for the report but this is already fixed. You can use [the snapshot doc](https://docs.spring.io/spring/docs/5.2.3.BUILD-SNAPSHOT/spring-framework-reference/core.html) in the meantime.

Duplicate of #24132,

**Closed by snicoll** 2019-12-24 07:39 UTC
Labels: status: waiting-for-triage

**Comment by iluuu1994** [comment] 2019-12-24 10:50
Nice, thanks @snicoll!
