### ISSUE TITLE
SpEL: Propose a way to access properties with Set type?

### ISSUE THREAD

**Issue by limingho456** [spring-projects/spring-framework#29475] opened 2022-11-13 15:04 UTC
**Affects:** 5.0.8.RELEASE

Context: 
We built a library to validate Java bean with use of Spring's expression interface. 
Currently, it supported accessing properties with arrays, lists and maps but some of our Java beans' properties are Set.
Extra workaround converting Set type to Map / List before querying the value and validating is required.

Problem: Is there a more direct way evaluating expression on Set properties?

**Comment by sbrannen** [comment] 2022-11-13 16:04
I am closing this as a duplicate of #26409.

If you feel this is not a duplicate, please provide additional information here.

**Closed by sbrannen** 2022-11-13 16:04 UTC
Labels: status: waiting-for-triage
