### ISSUE TITLE
ReflectionUtils behavior change in 6.2.0

### ISSUE THREAD

**Issue by welovelain** [spring-projects/spring-framework#34082] opened 2024-12-12 14:20 UTC
After upgrading to Spring 6.2.0 (spring boot 3.4.0) my tests with io.rest-assured mock mvc started to be flaky.

I discovered that the issue might be connected to `ReflectionUtils`.

In `RestAssuredMockMvc` there is call to
https://github.com/spring-projects/spring-framework/blob/main/spring-test/src/main/java/org/springframework/test/web/servlet/request/MockHttpServletRequestBuilder.java through `ReflectionUtils`.

When

```java
public static Method findMethod(Class<?> clazz, String name, @Nullable Class<?>... paramTypes)
```

is called, then method returns.

Sometimes, `method.isVarArgs` returns `true`, sometimes `false` (when `method.isBridge()` is `true`).

Here's some test example to show the behavior:

```java
    @Test
    void testMethod() {
        var method = ReflectionUtils.findMethod(MockHttpServletRequestBuilder.class, "cookie", Cookie[].class);
        System.out.println("IsBridge: " + method.isBridge());
        System.out.println("IsVarArgs: " + method.isVarArgs());

        assertTrue(method.isVarArgs());
    }
 ```

If you run the test multiple times, it will fail, but not always. In previous spring version `method.isVarArgs` always returned `true`. (At least I think so, it would explain why tests never failed before)

**Comment by facewise** [comment] 2024-12-13 01:31
It's so intersting. I found that `java.lang.Class#getDeclaredMethods()` sometimes returns methods in a different order. `ReflectionUtils` is innocent because it just copies the result😥

**Comment by simonbasle** [comment] 2024-12-13 10:22
@welovelain I see that you have opened an issue in `rest-assured`. I think this is a better avenue to explore, perhaps evolving the code there to use `BridgeMethodResolver.findBridgedMethod(method)`?

Unless you've investigated further and found an issue in `ReflectionUtils`?

@facewise thanks for the offer, but filtering out bridge methods in `findMethod` is a no-go as it is supposed to include such methods.

**Comment by welovelain** [comment] 2024-12-13 10:24
@simonbasle Yes, I created it there also, but it looks like the behavior still was changed, it might affect other libs too.
Because earlier it worked.
If the behavior was changed and you think that it must  have been changed, then ok. But to me it looks like a bug, when such method returns undetermined results

**Comment by sbrannen** [comment] 2024-12-13 12:49
Hi @welovelain,

> If you run the test multiple times, it will fail, but not always. In previous spring version method.isVarArgs always returned true. (At least I think so, it would explain why tests never failed before)

I cannot reproduce the failure you've described.

Although `method.isBridge()` sometimes returns `false` and sometimes returns `true`, `method.isVarArgs()` always returns `true` for me with Spring Framework `6.2.x` on JDK 17, JDK 21, and JDK 22.

What version of the JDK are you using?

And how are you running your test? From a Gradle or Maven build? Within an IDE (and if so, which one)?

If you would like us to investigate this further, we will need a minimal sample that reproduces the issue in the form of something that we can download and run (for example, a public Git repository or a ZIP file).

**Comment by sbrannen** [comment] 2024-12-13 14:29
@welovelain, can you confirm whether the following modified version of your test case consistently passes for you?

```java
@Test
void testMethod() {
	Method method = ReflectionUtils.findMethod(MockHttpServletRequestBuilder.class, "cookie", Cookie[].class);
	Method bridgedMethod = BridgeMethodResolver.findBridgedMethod(method);
	assertTrue(bridgedMethod.isVarArgs());
}
```

**Comment by welovelain** [comment] 2024-12-13 16:10
I checked it on Eclipse Temurin Adopt Open JDK for HotSpot 17.03 and Amazon Coretto 17.0.3, their results come true/false.
JetBrains runtime consistently returns false for initial test.

Provided BridgeMethodResolver test consistently works ok. 

I can see you wrote in Rest Assured issue as well. It seems that them changing the code will be the most correct way to address it. I still wonder why it worked previously.

What for me, I will migrate tests using MockMvcTester, it doesn't have such issues. 

If you still think there is need for some example, please let me know, I think I could prepare some docker image, but it looks like you have already figured out the compiler differences.

**Comment by sbrannen** [comment] 2024-12-13 16:28
> I checked it, using gradle 8.11, on Eclipse Temurin Adopt Open JDK for HotSpot 17.03 and Amazon Coretto 17.0.3, their results come true/false. JetBrains runtime consistently returns false for initial test.
> 
> Provided BridgeMethodResolver test consistently works ok.

Thanks for testing all of that, @welovelain. 👍 

> I still wonder why it worked previously.

@simonbasle researched this and noticed that the bridge method was introduced due to the introduction of `AbstractMockHttpServletRequestBuilder` in 6.2: 

https://github.com/spring-projects/spring-framework/blob/5024bb72279188f1d0dcfe19e8abdd4bdb9887c8/spring-test/src/main/java/org/springframework/test/web/servlet/request/AbstractMockHttpServletRequestBuilder.java#L451

Thus, prior to 6.2, there was only one _declared_ `cookie(Cookie...)` method in `MockHttpServletRequestBuilder`, and now there are two: the actual method and the bridge method.

> If you still think there is need for some example, please let me know, I think I could prepare some example with dockerfile, but it looks like you have already figured out the compiler differences.

Thanks for the offer, but you're right: I don't think we need a "reproducer" anymore.

> I can see you wrote in Rest Assured issue as well. It seems that them changing the code will be the most correct way to address it.

Indeed, in light of that I am closing this issue.

Cheers,

Sam

**Closed by sbrannen** 2024-12-13 16:28 UTC
Labels: for: external-project
