### ISSUE TITLE
Provide a mechanism to configure integration tests with a dynamic property source

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-framework#24540] opened 2020-02-17 13:36 UTC
In Spring Boot, we'd like to make it easier to set configuration properties from something else that's bootstrapped as part of running an integration test. The main use case that we have for this is setting [configuration properties based on the IP address and port on which a Testcontainers container is listening](https://github.com/spring-projects/spring-boot/issues/16886).

The current solution requires using an `ApplicationContextInitializer` to  manipulate the `Environment`:

```java
@Testcontainers
@ContextConfiguration(initializers = DataRedisTestIntegrationTests.Initializer.class)
@DataRedisTest
public class DataRedisTestIntegrationTests {

    @Container
    public static RedisContainer redis = new RedisContainer();

    // …

    static class Initializer
            implements ApplicationContextInitializer<ConfigurableApplicationContext> {

        @Override
        public void initialize(
                ConfigurableApplicationContext configurableApplicationContext) {
            TestPropertyValues.of(
                "spring.redis.host=" + redis.getContainerIpAddress(),
                "spring.redis.port=" + redis.getMappedPort()
            ).applyTo(configurableApplicationContext.getEnvironment());
        }

    }

}
```

We'd like to make this more of a first-class concept. One proposal is to achieve that via a method on the test class that can provide a property source:

```java
@Testcontainers
@DataRedisTest
class DataRedisTestIntegrationTests {

   @Container
   static RedisContainer redis = new RedisContainer();

    // …

    @DynamicPropertySource
    static PropertySource redisProperties() {
        return TestPropertyValues.of(
            "spring.redis.host=" + redis.getContainerIpAddress(),
            "spring.redis.port=" + redis.getMappedPort()
        ).asPropertySource();
    }

}
```

There are some interesting ordering considerations here. It requires the `RedisContainer` to have been started and assigned to `redis` before the `redisProperties()` method is called. To some extent at least, this is already a solved problem as the more cumbersome `ApplicationContextInitializer` approach shown above works today.

**Comment by philwebb** [comment] 2020-03-04 00:42
I'm not sure if it will help with the ordering issue, but perhaps we could use method references in the actual property source itself. That way they wouldn't actually get evaluated until they are read. I also wonder if we can reuse the existing `@TestPropertySource` annotation?

```java
@TestPropertySource
static TestPropertyValues redisProperties() {
    return TestPropertyValues.under("spring.redis.").of((values) -> {
        values.add("host", redis::getContainerIpAddress)
        values.add("port", redis::getMappedPort)
    });
}
```

**Comment by philwebb** [comment] 2020-03-04 15:49
Another thought. We could use an callback interface that's injected into a `@TestPropertySource` annotated method. That would allow us to extend the functionality of the existing annotation in a relatively logical way:

```java
@TestSource
static void redisProperties(DynamicProperties properties) {
        properties.add("spring.redis.host", redis::getContainerIpAddress)
        properties.add("spring.redis.port", redis::getMappedPort)
}
```

**Comment by wilkinsona** [comment] 2020-03-04 16:20
I thought about reusing `@TestPropertySource` but decided I didn't like it. None of its attributes made sense to me when I thought about what they'd mean when it was used on a method. `inheritLocations` and `inheritProperties` in particular seemed problematic if the annotation was to be permitted on methods.

**Comment by philwebb** [comment] 2020-03-04 16:37
Oh yeah. The ordering would also be really complicated to understand. The combination of annotated methods and class level values will be hard to reason about. I still quite like the callback idea, so perhaps:

```java
@DynamicPropertySource
static void redisProperties(DynamicPropertyValues values) {
        values.add("spring.redis.host", redis::getContainerIpAddress)
        values.add("spring.redis.port", redis::getMappedPort)
}
```

**Comment by wilkinsona** [comment] 2020-03-04 16:47
> I still quite like the callback idea

Me too.

@sbrannen Any news on whether this might be able to squeeze into a 5.2.x release?

**Comment by philwebb** [comment] 2020-03-04 17:08
I can try to work on a PR of it helps?

**Comment by bsideup** [comment] 2020-03-05 07:16
I think the callback approach will work very well for the Testcontainers use case 👍 

Also, keep in mind that sometimes the containers will be manually started, and the initializer was a good place to call `.start()` on them because SF calls it when the context starts / being initialized.
The expectation would be that `@DynamicPropertySource` annotated methods are called during the context initialization as well.

**Comment by sbrannen** [comment] 2020-03-17 18:48
> > I still quite like the callback idea

Seems plausible.

Thanks for all of the brainstorming! 👍 

> @sbrannen Any news on whether this might be able to squeeze into a 5.2.x release?

I'll see if I can put together a spike in the coming days.

As for whether it will land in 5.2.x or 5.3, I'll discuss that with @jhoeller once I have something working.

**Comment by philwebb** [comment] 2020-03-18 01:54
I've pushed some code [here](https://github.com/philwebb/spring-framework/tree/gh-24540) for review.

**Comment by sbrannen** [comment] 2020-03-19 16:57
@philwebb, I think your spike looks very promising!

Do you want to submit a PR that can be _reviewed_?

Or shall I pull down your branch, polish on top of it as necessary, and go from there?

**Comment by sbrannen** [comment] 2020-03-20 13:52
**Update**: I've reviewed and slightly revised the work from @philwebb (Thanks!). The diff can be viewed [here](https://github.com/spring-projects/spring-framework/compare/issues/gh-24540-dynamic-property-source).

@wilkinsona and @bsideup, if you could give a 👍 or 👎 on the current approach/API/implementation, that would be greatly appreciated.

**Comment by bsideup** [comment] 2020-03-20 15:03
@sbrannen looks good 👍  Just maybe one minor thought - since it is for testing, I would replace `Supplier` with `Callable` because it allows throwing from it.

**Comment by wilkinsona** [comment] 2020-03-20 15:53
👍 LGTM too.

+1 for `Callable` rather than `Supplier`.

**Comment by sbrannen** [comment] 2020-03-20 17:45
Thanks for the feedback, @bsideup and @wilkinsona.

> Just maybe one minor thought - since it is for testing, I would replace `Supplier` with `Callable` because it allows throwing from it.

Indeed. Good catch! I'll address that.

**Comment by sbrannen** [comment] 2020-03-23 13:29
### Original proposal

```java
public @interface DynamicPropertySource {
}
```

```java
public interface DynamicPropertyValues {

	void add(String name, Supplier<Object> value);
}
```

Usage:

```java
	@Container
	static GenericContainer<?> redis = new GenericContainer<>(
			"redis:5.0.3-alpine").withExposedPorts(6379);

	@DynamicPropertySource
	static void redisProperties(DynamicPropertyValues values) {
		values.add("test.redis.ip", redis::getContainerIpAddress);
		values.add("test.redis.port", redis::getFirstMappedPort);
	}
```

We later switched from `Supplier<Object>` to `Callable<Object>` to allow the _supplier_ to throw `Exception`, but the usage looks identical.

### New proposal based on the notion of a registry

```java
@FunctionalInterface
public interface DynamicPropertyRegistar {

	void register(String name, DynamicPropertyResolver dynamicPropertyResolver);

	@FunctionalInterface
	interface DynamicPropertyResolver {

		Object resolve() throws Exception;
	}
}
```

Usage:

```java
	static DemoContainer container = new DemoContainer();

	@DynamicPropertySource
	static void containerProperties(DynamicPropertyRegistar registrar) {
		registrar.register("test.container.ip", container::getIpAddress);
		registrar.register("test.container.port", container::getPort);
	}
```

**Issues**

- Should it be called `DynamicPropertyResolverRegistar` instead of `DynamicPropertyRegistar`?
- Should it be a "registrar" or "registry"?
- Spring already has `org.springframework.core.env.PropertyResolver` which serves an entirely different purpose than the proposed `DynamicPropertyResolver` functional interface above. In other words, you cannot say a `DynamicPropertyResolver` _is-a_ `PropertyResolver`.
  - So, should this new functional interface rather be something like a `DynamicPropertySupplier`?

**Feedback welcome!**

**Comment by jhoeller** [comment] 2020-03-23 13:57
Since we'd have to wrap checked exceptions in some kind of runtime exceptions ourselves in order to get rid of that hack, without an obvious wrapper candidate to use, and since the existing `PropertySource` interface does not expose checked exceptions, I'd rather ask for wrapping checked exceptions in your `Supplier` implementations wherever necessary...

**Comment by philwebb** [comment] 2020-03-23 15:02
It looks like test containers doesn't generally use checked exceptions for `Container` implementations, so I'd be `+1` on moving back to a `Supplier`.

**Comment by bsideup** [comment] 2020-03-23 15:05
@sbrannen when I was suggesting `Callable` I thought it would be trivial to change, but if it will require some more work (including introducing a new concept of `DynamicPropertyResolver` and the jack), it is okay by me to have it as `Supplier` 👍 

We (Testcontainers) indeed don't have many methods that throw checked exceptions, but I was thinking about some other, non-Testcontainers use cases.

Looking forward to having it merged, looks great!

**Comment by wilkinsona** [comment] 2020-03-23 15:12
Me too. I have no problem with `Supplier`, particularly now I understand what the alternative looks like.

**Comment by wilkinsona** [comment] 2020-03-23 15:16
FWIW, I like `DynamicPropertyRegistry` and `DynamicPropertySupplier`.

**Comment by philwebb** [comment] 2020-03-23 15:18
> Should it be a "registrar" or "registry"?

This is an interesting question, and it's making me wonder if the registry change is worthwhile or not. It really feels like the method itself is the `registrar` and it should be passed a `registry`. The problem is, that doesn't really feel very natural:

```java
static DemoContainer container = new DemoContainer();

@DynamicPropertyRegistrar
static void containerProperties(DynamicPropertyRegistry registry) {
	registry.register("test.container.ip", container::getIpAddress);
	registry.register("test.container.port", container::getPort);
}
```

I guess my current preference would be 

```java
@DynamicPropertySource
static void redisProperties(DynamicPropertyRegistry registry) {
        registry.addDynamicProperty("spring.redis.host", redis::getContainerIpAddress)
        registry.addDynamicProperty("spring.redis.port", redis::getMappedPort)
}
```

**Comment by sbrannen** [comment] 2020-03-23 15:23
Thanks everybody for the feedback!

Status quo in the feature branch:

```java
@DynamicPropertySource
static void containerProperties(DynamicPropertyRegistry registry) {
	registry.register("test.container.ip", container::getIpAddress);
	registry.register("test.container.port", container::getPort);
}
```

`registry.register(...)` aligns with existing things like `BeanDefinitionRegistry.registerBeanDefinition(...)`. So that was my inspiration.

So I guess the debate is between the following:

- `registry.register(...)`
- `registry.registerDynamicProperty(...)`
- `registry.addDynamicProperty(...)`

**Comment by philwebb** [comment] 2020-03-23 15:30
`FormatterRegistry` has `add..` methods.

**Comment by wilkinsona** [comment] 2020-03-23 15:32
I prefer something short, and given that only one type is being registered or added, I think `add` or `register` would be ok. I think there's sufficient context from the `DynamicPropertyRegistry` that's passed in to avoid the need for the method name to reference dynamic properties as well. If someone wants more context that could name the variable `dynamicPropertyRegistry` rather than just `registry`.

If we think there may be multiples kinds of registration in the future (as `FormatterRegistry` has with printers and formatters) then a longer method name would provide some future proofing.

**Comment by sbrannen** [comment] 2020-03-23 15:38
**Team Decision**: go with the following simplified API.

```java
public interface DynamicPropertyRegistry {

	/**
	 * Add a {@link Supplier} for the given property name to this registry.
	 * @param name the name of the property for which the supplier should be added
	 * @param valueSupplier a supplier that will provide the property value on demand
	 */
	void add(String name, Supplier<Object> valueSupplier);

}
```

**Closed** 2020-03-23 16:26 UTC
Labels: in: test, type: enhancement
