### ISSUE TITLE
Which spring framework release version do we plan to support GraalVM with native image?

### ISSUE THREAD

**Issue by guanchao-yang** [spring-projects/spring-framework#22951] opened 2019-05-13 09:11 UTC
Spring Framework can work in [GraalVM](https://www.graalvm.org/) mode will be excited. And Which spring framework release version do we plan to support GraalVM with native image? 5.X Or ? Thanks

**Comment by sdeleuze** [comment] 2019-05-13 18:32
Initial support was provided via #21529, other issues were mostly on GraalVM side and are almost all fixed, the remaining step to be usable is to be able to run Spring Framework without manual reflection and proxy configuration, so I close this issue as a duplicate of #22968.

**Closed by sdeleuze** 2019-05-13 18:32 UTC
Labels: status: waiting-for-triage
