### ISSUE TITLE
Spring MVC @RequestHeader value is ignored [SPR-17617]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#22149] opened 2018-12-21 13:12 UTC
**[zsenyeg](https://jira.spring.io/secure/ViewProfile.jspa?name=zsenyeg)** opened **[SPR-17617](https://jira.spring.io/browse/SPR-17617?redirect=false)** and commented

`RequestHeaderMethodArgumentResolver` creates `RequestHeaderNamedValueInfo` information from annotation using only name value of RequestHeader annotation.

In generated codes for example swagger codegen 3, only the value attribute is filled, and because of that in the rest interface the name of the method argument will be used, that is might be different than the name (or value) of the RequestHeader annotation.

For example:
```java
@RequestHeader(value = "Consent-ID",required = false) String consentId
```

 

Name attribute of annotation is not filled, because of that method argument name consentId will be used, and won't found among the http request headers.

 

---

**Affects:** 5.1.2

**Attachments:**
- [RequestHeaderMethodArgumentResolverTest.java](https://jira.spring.io/secure/attachment/26165/RequestHeaderMethodArgumentResolverTest.java) (_2.61 kB_)

**Comment by rstoyanchev** [comment] 2019-01-18 23:07
The example doesn't help. The original description says the value attribute is filled out, the test uses a mock which does not do that. Please, provide an example with an actual annotated controller, or a snippet that shows what that declaration looks like.

**Comment by spring-issuemaster** [comment] 2019-01-25 23:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by zsenyeg** [comment] 2019-01-29 14:42
Hey,

I just made a little runnable example, that fail as the previous unit test. The attached zip file contains a maven idea project, you can start it with the usual mvn spring-boot:run command.

The sample rest service provides two get endpoints:
http://localhost:8080/test/good
http://localhost:8080/test/bad

Test both endpoints with the following http request header: Consent-ID with any value.

cheers,
zsenyeg
[springrest.zip](https://github.com/spring-projects/spring-framework/files/2808152/springrest.zip)

**Comment by rstoyanchev** [comment] 2019-03-11 14:33
Thanks for the sample. 

It looks like when `@RequestHeader(value="...")` is declared on the class method, both the value and the name attributes are filled out. When the same is declared on an interface, only the value attribute is filled out. @sbrannen any idea why?

**Comment by sbrannen** [comment] 2019-03-11 14:55
> It looks like when `@RequestHeader(value="...")` is declared on the class method, both the value and the name attributes are filled out. When the same is declared on an interface, only the value attribute is filled out. @sbrannen any idea why?

I'll have to look into it before I can comment on that.

**Comment by sbrannen** [comment] 2019-03-11 15:07
At a glance, it appears that the infrastructure there is using `MethodParameter` instead of `SynthesizingMethodParameter`, and the lookup is via `RequestHeader.name()` in `RequestHeaderMethodArgumentResolver.RequestHeaderNamedValueInfo`.

**Comment by sbrannen** [comment] 2019-03-11 17:09
I don't yet have a test in place, but I _assume_ it's due to the fact that `org.springframework.web.method.HandlerMethod.getInterfaceParameterAnnotations()` does not synthesize annotations retrieved from methods in interfaces.

I'll add a test and fix it. 😉

**Comment by rstoyanchev** [comment] 2019-03-11 17:12
@sbrannen it's using the `MethodParameter` that's passed in which was initialized as a `SynthesizingMethodParameter` in `HandlerMethod`. I don't think that's the issue.

Switching to 5.1.5 I can no longer reproduce the issue, most likely thanks to recent changes by @jhoeller in `HandlerMethod`.

**Comment by sbrannen** [comment] 2019-03-11 17:17
OK. I see that `adaptAnnotation()` eventually gets called on annotations merged from the results of `getInterfaceParameterAnnotations()` (thereby synthesizing them).

So perhaps @jhoeller has indeed already _fixed_ this.

**Comment by sbrannen** [comment] 2019-03-11 17:25
Yep, this was the fix: https://github.com/spring-projects/spring-framework/commit/c58da71006cbc37c6bf062693c2d96a8fafab6f4#diff-4e35372004bab14ceec2182f61179bafL497

Closing this issue as as duplicate of #21992.

**Closed by sbrannen** 2019-03-11 17:25 UTC
Labels: in: web, status: feedback-provided, type: bug
