### ISSUE TITLE
Classpath scanning does not work in tests using the module path [SPR-16977]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21515] opened 2018-06-26 14:50 UTC
**[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson)** opened **[SPR-16977](https://jira.spring.io/browse/SPR-16977?redirect=false)** and commented

It appears the classpath scanning doesn't work when Surefire launches the JVM configured to use the module path. `target/classes` is placed on the module path and `target/test-classes` is patched into this module but classpath scanning only finds classes in `target/test-classes`.

I have attached a minimal sample that should reproduce the problem when built (`mvn test`) with Java 10. The sysout from the test should show that only the test class has been found:

```
[INFO] Running com.example.ScanningTest
[file [/Users/awilkinson/dev/temp/module-path-scanning/target/test-classes/com/example/ScanningTest.class]]
```

To my rather untrained eye, building with `-X` and examining the arguments that Surefire uses to launch the forked JVM (in `target/surefire`) suggests that Surefire's configuration of the JVM is correct.

When the sample is modified to work with Java 8 (remove `module-info.java` and change the compiler plugin configuration to remove `<release>10</release>`) the class in `target/classes` is also found:

```
[INFO] Running com.example.ScanningTest
[file [/Users/awilkinson/dev/temp/module-path-scanning/target/test-classes/com/example/ScanningTest.class], file [/Users/awilkinson/dev/temp/module-path-scanning/target/classes/com/example/One.class]]
```

---

**Affects:** 5.0.7

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/13581

**Attachments:**
- [module-path-scanning.zip](https://jira.spring.io/secure/attachment/25754/module-path-scanning.zip) (_3.66 kB_)

**Issue Links:**
- #20937 Compatibility with JDK 11

2 votes, 7 watchers

**Comment by wimdeblauwe** [comment] 2019-09-09 13:58
Is there a workaround for this? I have a JavaFx project that I added Spring Boot to which works really great, but I am unable to run my `@JsonTest`.

As a workaround, I need to manually specify the application class + the json deserializers I want to test:

```
@JsonTest
class MyJsonDeserializerTest {
   ...
}
```

needs to become:
```
@JsonTest
@ContextConfiguration(classes = {MyApplication.class, MyJsonDeserializerTest.TestConfig.class})
class MyJsonDeserializerTest {
   ...

    @TestConfiguration
    static class TestConfig {
        @Bean
        public MyJsonDeserializer deserializer() {
            return new MyJsonDeserializer();
        }
    }

}
```

(Note: It seems I only need to do this for Maven, IntelliJ seems to run the test fine, but I have to assume that IntelliJ is somehow "cheating" given this issue and the related https://github.com/spring-projects/spring-boot/issues/13581 )

**Comment by eiswind** [comment] 2019-12-28 15:11
Another year has passed.
To me this still is a showstopper.

**Comment by tgolden-andplus** [comment] 2020-02-19 23:35
I have the opposite problem currently. Failsafe works just fine, apparently because they point to the packaged JAR instead of the exploded `target/classes` directory. However, IntelliJ wants to use the exploded directory when running integration tests in the IDE, so this fails unless I uncheck the module-path option (which I have to do for every run configuration separately).

Is this truly a JDK issue or a Spring issue? It doesn't seem that the core JDK team plans on changing behavior, thus it seems incumbent on the Spring team to work around this somehow (or at the very least, document that component scanning will break unexpectedly when using exploded classes versus packaged in JAR classes....)

**Comment by tomdw** [comment] 2020-02-25 20:12
@jhoeller @wilkinsona could this be fixed inside spring by making the component scanning code be more module path aware? Especially for running spring tests on module path using the surefire plugin or in intellij this is a problem.

**Comment by petermylemans** [comment] 2020-03-07 20:11
@tgolden-andplus I'm having the same issue.

For future reference; the only work around I found was to uncheck "use module path" in **Templates** > JUnit in your Run/Debug Generations to make sure it is unchecked for every new junit run config you create.

**Comment by manosbatsis** [comment] 2020-03-11 14:51
For me the workaround was using a `org.springframework.core.io.ClassPathResource` instead of `ClassLoader.getResource`

**Comment by tomdw** [comment] 2020-03-11 15:05
@manosbatsis and how dit you make sure that spring uses this ClassPathResource for its component scanning? 

@tgolden-andplus problem with that workaround is that you then no longer have the module checking which is important. Also stops working when using e.g. serviceloader to load services from other modules in your code under test

Probably the only fix is a fix in the code of spring itself, solving the way it does component scanning to handle modules better.

**Comment by manosbatsis** [comment] 2020-03-11 15:13
@tomdw to be clear, i had trouble when trying to "manually" load a classpath resource from within tests using `ClassLoader.getResource`. After a search landed me here, i figured out a workaround was needed to bypass the bug and `ClassPathResource` did the trick for me, so i thought it might be useful.

**Comment by retheesh-mr** [comment] 2020-04-14 18:57
I am facing similar issue when writing junit5 cases with spring boot and java 11. As the jdk [bug ](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8206162) raised is in resolved status, what is further action on this? How can this be resolved?
It seems module-info cannot be used together with junit and spring due to this issue. As it is blocking for me in my project I have no other way than to fall back to java 8 version.

**Comment by kopper** [comment] 2020-06-30 10:05
I had the same (or very similar) issue running tests with maven-failsafe-plugin 3.0.0-M5 on AdoptOpen JDK 11. The work around is to disable using module path in plugin's configuration
`<useModulePath>false</useModulePath>`

**Comment by oscarhaglund** [comment] 2020-10-05 07:19
I should mention that I am also suffering from this issue and it would really be appreciated if this could be solved by Spring if it is not going to be solved by Java itself.

**Comment by prakash0409** [comment] 2021-01-12 08:37
We upgraded to a new version of spring boot  2.3.4 and all our integration tests started failing. All our integration test cases were earlier working on AdoptOpen JDK 11 with the older version. I guess this should be an issue at Spring end. As mentioned above the classpath scanning is only finding only "target/test-classes".

I was able to use the workaround as suggested by @kopper

**Comment by msche** [comment] 2021-01-30 06:33
FYI, I had similar classpath issues when I introduced java modules in my project and executed the Spring Boot unit tests.

```
07:28:35.820 [main] ERROR - o.s.test.context.TestContextManager - prepareTestInstance - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@63e5b8aa] to prepare test instance [...]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '...': Unsatisfied dependency expressed through field '...'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type '...' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

I eventually got the test executed successfully by including within the configuration of SureFire version 2.22.x `<forkCount>0</forkCount>`.

**Comment by yuyuchen09** [comment] 2021-03-01 22:25
Is this fixed? Is this the recommended workaround as described in https://github.com/spring-projects/spring-boot/issues/18516?

**Comment by barbarosalp** [comment] 2021-04-05 17:00
Is there any proper solution, we are also stuck with this?

**Comment by OleksandrGavryliukTR** [comment] 2021-04-23 13:53
> FYI, I had similar classpath issues when I introduced java modules in my project and executed the Spring Boot unit tests.
> 
> ```
> 07:28:35.820 [main] ERROR - o.s.test.context.TestContextManager - prepareTestInstance - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@63e5b8aa] to prepare test instance [...]
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '...': Unsatisfied dependency expressed through field '...'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type '...' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
> ```
> 
> I eventually got the test executed successfully by including within the configuration of SureFire version 2.22.x `<forkCount>0</forkCount>`.

This has fixed it for me. With a warning:
`[WARNING] useSystemClassloader setting has no effect when not forking`
Which must be removing the cause of this problem.

**Comment by sbrannen** [comment] 2022-05-22 16:34
Current work on this issue can be viewed in the following feature branch.

https://github.com/sbrannen/spring-framework/commits/module-path-scanning

**Comment by sbrannen** [comment] 2022-05-23 16:54
Hi everybody,

Thanks for all of the feedback over the years!

I am now closing this issue since it has been superseded by the following issues.

- #28506 
- #28507

Please follow those issues for additional updates on module path scanning and resource support.

**Closed by sbrannen** 2022-05-23 16:54 UTC
Labels: in: test, type: bug, in: core
