### ISSUE TITLE
BeanDefinitionParserDelegate.getEnvironment causes NoSuchMethodError

### ISSUE THREAD

**Issue by prakashbxr85** [spring-projects/spring-framework#28076] opened 2022-02-19 00:26 UTC
**[Chris Beams](https://jira.spring.io/secure/ViewProfile.jspa?name=cbeams)** commented

Worked around this issue prior to the M1 release with the following:

> commit 1a751de04fe4bc5691a31fb25254ac6064d334b0
> Author: Chris Beams <cbeams@vmware.com>
> Date:   Thu Feb 10 00:30:30 2011 +0000
>     
>     Further compensations for STS; binary compat fixes
>     
>     Defensively catch NoSuchMethodError when calling BDPD.getEnvironment()
>     and supply a DefaultEnvironment if not available.
>     
>     Replace the single-arg constructor for BDPD and deprecate, preserving
>     binary compat particularly for Spring Integration who instantiates
>     this class directly, which is unusual.
>     
>     git-svn-id: https://src.springframework.org/svn/spring-framework/trunk@3982 50f2f4bb-b051-0410-bef5-90022cba6387
> 
> ```
> diff --git org.springframework.beans/src/main/java/org/springframework/beans/factory/xml/BeanDefinitionParserDelegate.java org.springframework.beans/src/main/java/org/springframe
> index 7236aa6..8cdd39f 100644
> --- org.springframework.beans/src/main/java/org/springframework/beans/factory/xml/BeanDefinitionParserDelegate.java
> +++ org.springframework.beans/src/main/java/org/springframework/beans/factory/xml/BeanDefinitionParserDelegate.java
> @@ -27,6 +27,7 @@ import java.util.Set;
>  
>  import org.apache.commons.logging.Log;
>  import org.apache.commons.logging.LogFactory;
> +
>  import org.w3c.dom.Element;
>  import org.w3c.dom.NamedNodeMap;
>  import org.w3c.dom.Node;
> @@ -58,6 +59,7 @@ import org.springframework.beans.factory.support.ManagedProperties;
>  import org.springframework.beans.factory.support.ManagedSet;
>  import org.springframework.beans.factory.support.MethodOverrides;
>  import org.springframework.beans.factory.support.ReplaceOverride;
> +import org.springframework.core.env.DefaultEnvironment;
>  import org.springframework.core.env.Environment;
>  import org.springframework.util.Assert;
>  import org.springframework.util.ClassUtils;
> @@ -266,6 +268,17 @@ public class BeanDefinitionParserDelegate {
>         }
>  
>         /**
> +        * Create a new BeanDefinitionParserDelegate associated with the
> +        * supplied {@link XmlReaderContext} and a new {@link DefaultEnvironment}.
> +        * @deprecated since Spring 3.1 in favor of
> +        * {@link #BeanDefinitionParserDelegate(XmlReaderContext, Environment)}
> +        */
> +       @Deprecated
> +       public BeanDefinitionParserDelegate(XmlReaderContext readerContext) {
> +               this(readerContext, new DefaultEnvironment());
> +       }
> +
> +       /**
>          * Get the {@link XmlReaderContext} associated with this helper instance.
>          */
>         public final XmlReaderContext getReaderContext() {
> diff --git org.springframework.context/src/main/java/org/springframework/context/config/AbstractSpecificationBeanDefinitionParser.java org.springframework.context/src/main/java/o
> index 61756a9..58472b5 100644
> --- org.springframework.context/src/main/java/org/springframework/context/config/AbstractSpecificationBeanDefinitionParser.java
> +++ org.springframework.context/src/main/java/org/springframework/context/config/AbstractSpecificationBeanDefinitionParser.java
> @@ -24,6 +24,7 @@ import org.springframework.beans.factory.parsing.ProblemReporter;
>  import org.springframework.beans.factory.parsing.ReaderContext;
>  import org.springframework.beans.factory.xml.BeanDefinitionParser;
>  import org.springframework.beans.factory.xml.ParserContext;
> +import org.springframework.core.env.DefaultEnvironment;
>  import org.w3c.dom.Element;
>  
>  /**
> @@ -54,11 +55,19 @@ public abstract class AbstractSpecificationBeanDefinitionParser implements BeanD
>                 specContext.setRegistry(parserContext.getRegistry());
>                 specContext.setRegistrar(new ComponentRegistrarAdapter(parserContext));
>                 specContext.setResourceLoader(parserContext.getReaderContext().getResourceLoader());
> -               specContext.setEnvironment(parserContext.getDelegate().getEnvironment());
> +               try {
> +                       // again, STS constraints around the addition of the new getEnvironment()
> +                       // method in 3.1.0 (it's not present in STS current spring version, 3.0.5)
> +                       // TODO 3.1 GA: remove this block prior to 3.1 GA
> +                       specContext.setEnvironment(parserContext.getDelegate().getEnvironment());
> +               } catch (NoSuchMethodError ex) {
> +                       specContext.setEnvironment(new DefaultEnvironment());
> +               }
>                 try {
>                         // access the reader context's problem reporter reflectively in order to
>                         // compensate for tooling (STS) constraints around introduction of changes
>                         // to parser context / reader context classes.
> +                       // TODO 3.1 GA: remove this block prior to 3.1 GA
>                         Field field = ReaderContext.class.getDeclaredField("problemReporter");
>                         field.setAccessible(true);
>                         ProblemReporter problemReporter = (ProblemReporter)field.get(parserContext.getReaderContext());
> ```

_Originally posted by @spring-projects-issues in https://github.com/spring-projects/spring-framework/issues/12706#issuecomment-453357685_

**Comment by bclozel** [comment] 2022-02-19 07:57
Linking an 11 years old issue and pasting a POM doesn't qualify as a bug report.

Please provide the complete stacktrace as well as a minimal sample application that reproduces the problem (something we can git clone or download and run locally - for that you can use start.spring.io as a starting point).

**Comment by spring-projects-issues** [comment] 2022-02-26 08:01
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-03-05 08:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-03-05 08:01 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, in: core, status: feedback-reminder
