### ISSUE TITLE
WebClient subscribing twice

### ISSUE THREAD

**Issue by Sam-Kruglov** [spring-projects/spring-framework#23365] opened 2019-07-26 07:23 UTC
### Expected behavior
Only hit `reactor.netty.channel.FluxReceive#startReceiver` once

### Actual behavior
Hits twice, where second time throws silently the `"Only one connection receive subscriber allowed."`

In production, sometimes this exception is reported from `reactor.core.publisher.Operators : Operator called default onErrorDropped ...`.
Locally I could only see this exception at the point of throwing inside `FluxReceive#startReceiver` with a debugger. Later in `reactor.core.publisher.MonoFlatMap.FlatMapMain#onError` it was `done = false`, so the exception was never shown anywhere.

### Steps to reproduce
My calling code is the following:
```java
webClient.get()
      .uri("myUri")
      .retrieve()
      .onStatus(HttpStatus::isError, response ->
                          response.bodyToMono(ErrorResponse.class)
                                  .log("response.bodyToMono")
                                  .flatMap(error -> Mono.error(
                                          new MyException(
                                                  MyErrorType.ofCode(error.getCode()).orElse(null),
                                                  error.getDescription()
                                          )
                                  ))
        )
      .bodyToMono(MyDto.class)
```

the logs:
```
client.bodyToMono                        : | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
client.bodyToMono                        : | request(unbounded)
response.bodyToMono                      : | onSubscribe([Fuseable] MonoSingle.SingleSubscriber)
response.bodyToMono                      : | request(unbounded)
response.bodyToMono                      : | onNext(ErrorResponse(code=500, description=message))
response.bodyToMono                      : | cancel()
client.bodyToMono                        : | onError(com.bla.MyException: message)
client.bodyToMono                        :  the exception stacktrace
```

### Reactor Core version
`org.springframework:spring-webflux:5.1.6.RELEASE`
### JVM version (e.g. `java -version`)
`openjdk version "11.0.1" 2018-10-16`

========

The workaround for me is using an ExchangeFilterFunction https://stackoverflow.com/a/48984852/6166627 instead of `onStatus`. With this approach, I only hit the start receiver once with a debugger. Hopefully, it's gonna fix itself. 

Anyway, this ERROR log seems to not affect anything actually, the code still throws MyException

---
originally posted in reactor but it's off-topic there https://github.com/reactor/reactor-core/issues/1747
Similar: #22096 #22284

**Comment by poutsma** [comment] 2019-11-19 09:30
I wrote a test to reproduce this problem (see https://github.com/spring-projects/spring-framework/commit/9f7dd9f35260368cafbc405b52f90ef72a9d0686), but it seems to work fine. Closing this for now, but let us now how we can improve the test to reproduce this issue.

**Closed by poutsma** 2019-11-19 09:30 UTC
Labels: status: waiting-for-triage

**Comment by gmuth** [comment] 2020-06-23 09:31
I'd like to confirm the behaviour reported by Sam (my used version is 5.1.7.RELEASE).
To be more precise: the logging message appears twice.
This happens within the IDE (IntelliJ). There might be an issue with annotation processing - it's just a guess. We use a Lombok injected Logger  via @Slf4j.
Als long as the onStatus-lambda (called twice) does not change state this is not an issue (like in my case).

**Comment by rstoyanchev** [comment] 2020-06-25 15:56
@gmuth please provide a sample if you'd like us to look further. As you can see above we did try the above snippet, a test was written, but could not reproduce it.

**Comment by DurgeshAlex** [comment] 2020-12-29 11:50
I am also facing the same issue with spring-webflux  5.2.9.RELEASE  and using on spring boot version 2.1.11 and it seems to call the the endpoint twice. Below is the dependencies i am using 
 <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webflux</artifactId>
            <version>5.2.9.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.3.10.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>0.9.12.RELEASE</version>
        </dependency>

**Comment by gmuth** [comment] 2020-12-29 11:58
good point I haven't checked. Maybe the onStatus() lambda calls are handled correct by according endpoint calls.
1. some should confirm that indeed the endpoint is called twice (by checking the server side).
2. we should find out why the "call-endpoint" operation is called multiple times.

**Comment by DurgeshAlex** [comment] 2020-12-30 05:36
Yeahh i created dummy endpoint in local server itself which is being called by webclient and kept the log and debug point in the endpoint i created. And as result debug point got invoked twice and log printed twice . That concluded that endpoint is being called twice.

**Comment by DurgeshAlex** [comment] 2020-12-30 05:55
Yeahh i created dummy endpoint in local server itself which is being called by webclient and kept the log and debug point in the endpoint i created. And as result debug point got invoked twice and log printed twice . That concluded that endpoint is being called twice.
And also i added a filter while creating the the WebClient instance. Some thing like this
![image](https://user-images.githubusercontent.com/26843771/103332822-98405b80-4a91-11eb-8d01-3c8a3d48b0c0.png)

And it seems that filter got invoked only once.
This is the log i am seeing

![image](https://user-images.githubusercontent.com/26843771/103332849-b1e1a300-4a91-11eb-8d3b-23a6746e0428.png)

Hope it helps you.

**Comment by DurgeshAlex** [comment] 2020-12-30 06:57
Twice calling got fixed by removing the **subscribe()** i think issue is their with subscribe function.

**Comment by ShimelesT** [comment] 2021-05-28 14:57
I am having similar issue. I have list of Mono<T> waiting response from multiple servers. And collectively block them after I subscribed to each of them individually. And I have to subscribe.

1. For each server
        create client
        make a get request
        subscribe to the mono
2. block all mono
3. generate status summary from each server

**Comment by bclozel** [comment] 2021-05-28 16:16
You should (almost) never `subscribe()` to a publisher in a Spring application.

1. if you're writing a non-reactive application, you can call `block()` on publisher instances and get the value directly
2. if you're writing a reactive application, `subscribe` and `block` should never be called and you should use reactor operators instead to compose publishers if necessary

If you're reading this issue and you're still confused, I'd suggest writing a new question on StackOverflow showing a code snippet and explaining what you're trying to achieve.

**Comment by jesus9508** [comment] 2022-06-10 14:53
I have the same problem, but is a little hard to reply the error in dev environment, but in prod is sending a request twice at same 

this is my implementation, Can someone tellme if I have some wrong whit this.
![image](https://user-images.githubusercontent.com/50775456/173092230-20fd2fe5-3edb-468c-86b7-b17bede6d3ea.png)


![image](https://user-images.githubusercontent.com/50775456/173092116-14d784f4-438a-45fa-96c8-038eb3a422f2.png)

the problem happend when it tryed to send information to other app, the provider noticed that there are same request sent twice at same hour, minute and sec.

**Comment by skyblackhawk** [comment] 2025-04-14 17:55
And what happening when you have all calls that are not blocking and you need to send an OTP SMS to verify sim phone number?
You can't use block!

**Comment by skyblackhawk** [comment] 2025-04-15 02:55
Why was added hidden to my scenario about the question?

Is it normal in GitHub from when?

In scenario exposed (hidden) somebody can tell us and community when you are working in webflux reactive application how to write a webclient that do only one request to a SMS service sender or developers need to use ExecutorService to force mono thread use to avoid multiple SMS to the customer?

**Comment by bclozel** [comment] 2025-04-15 04:49
@skyblackhawk Using WebClient with a Mono return type does not result in double execution. There was probably a user error in cases where this happened.

Your question seems somewhat related but commenting on an invalid issue makes it irrelevant. Please ask your question on StackOverflow and paste the link here. We will be happy to take a look.

**Comment by skyblackhawk** [comment] 2025-04-15 12:55
We are a team of over 50 developers and we see in the log of SMS server receiving multiple request from the same webclient. We have verified it step by step enabling log on concurrent jakarta and netty component and in the SMS server log that receive multiple request!

I'm not joking.

I'm sure about what I wrote before.
For this reason we are using ExecutorService with a single thread in webclient to avoid SMS server will send multiple OTP SMS to the customer.

**Comment by skyblackhawk** [comment] 2025-04-15 13:08
Other question, why with retrieve it doesn't work and in exchange it works fine.

Thanks for your reply.

**Comment by skyblackhawk** [comment] 2025-04-15 13:15
Please see the real situation of [Baeldung](https://www.baeldung.com/spring-webclient-limit-requests-per-second)

**Comment by skyblackhawk** [comment] 2025-04-16 16:43
This problem we have see happen for some server with api rest not reactive.
My hypothesis is that when arrive datagram to the server not reply immediatly and to respect reactive manifesto webclient try to do another request but we are talking about 100-300 ms.

**Comment by skyblackhawk** [comment] 2025-04-16 18:39
I end to work, i will do it in this weekend if for you is goood before I can't.
I think that the tests must be done for example by Artillery or Jmeter to simulate a server that is under pressure of request but not reactive called by webclient.
If you will use a simple one request this behaviour you can't see.

**Comment by skyblackhawk** [comment] 2025-04-16 18:58
WebFlux is actually my favorite framework, you have created a really excellent concurrent multi-threaded framework.
If we compare it to the Go language, it's the only language with these performances.

**Give compliments to all the guys in the team who worked on it**, they really deserve it, maybe we who use it do not often say it to all of you, but share these compliments from me too.

You all have developed a serious framework that in my opinion will explode in artificial intelligence, (Are you working on a Springboot WebFlux for IA?) to reduce electricity consumption and with an eye on the environment that we are literally destroying for the sake of future generations.

**Comment by bclozel** [comment] 2025-04-16 19:38
@skyblackhawk thanks for the kind words, this means a lot!
No rush on that sample application, we will be releasing maintenance versions tomorrow and the next opportunity is next month. Plenty of time to work on a sample and a fix. Cheers!
