### ISSUE TITLE
Performance Degradation in getBean method after upgrade

### ISSUE THREAD

**Issue by Srikalpana** [spring-projects/spring-framework#22537] opened 2019-03-07 06:33 UTC
Hi Team,

We have a requirement where we generate java classes dynamically and register them using Spring `registerBean`.  When we upgraded Spring framework, 4.2.3 to 4.3.18,  there was a severe performance degradation  while retrieving the registered bean.  

To fix the issue, we are planning to use the following code instead of using `getBean` method.  My question is: does the below API provide same initialization (like autowiring / pre & post processing capacity) or not? Will there be any repercussion with this API?

```java
AutowireCapableBeanFactory factory = applicationContext.getAutowireCapableBeanFactory();
return ( T )factory.autowire( clazz, AutowireCapableBeanFactory.AUTOWIRE_BY_TYPE, false );
```

**Comment by sdeleuze** [comment] 2019-03-07 08:18
Could be a duplicate of #22425.

**Comment by jhoeller** [comment] 2019-03-07 14:36
Programmatically creating an autowired instance that way works in principle. However, if you want post-processors (including annotation-driven injection) to work, you should rather use the `AutowireCapableBeanFactory.createBean` method: simply `createBean(clazz)` will be sufficient, no need to pass in any autowiring constants (unless you actually want property-driven autowiring rather than annotation-driven autowiring, along the lines of the old `autowire` setting for an XML bean definition).

That said, any details on the performance regression in your scenario? I assume it is about `getBean(Class)` (which goes through a type-based resolution algorithm) rather than `getBean(String)` (which performs a straight map lookup by key)? Does the issue actually look like a duplicate of #22425 to you? Are you seeing the performance degradation on first retrieval or on repeated retrieval of a bean?

**Comment by Srikalpana** [comment] 2019-03-13 13:05
Thank you for the response.  Both getBean(Class) & getBean(String) methods are showing performance degradations.  We badly need a work around for this issue, as it is taking more than 3 min during initialization.

**Comment by Srikalpana** [comment] 2019-03-13 13:54
AutowireCapableBeanFactory.createBean(clazz) also did not give us any benefit , it is taking > 3 min.

**Comment by sdeleuze** [comment] 2019-03-13 14:19
@Srikalpana Could you provide us a repro project or even a private access to the project sources in order to allow us to analyze what's going on?

**Comment by jhoeller** [comment] 2021-01-19 12:51
Closing due to the lack of reproducibility and the EOL of the 4.3.x line. To be reopened or followed up if concrete suggestions for a refinement come in.

**Closed by jhoeller** 2021-01-19 12:51 UTC
Labels: in: core, status: feedback-provided, type: regression
