### ISSUE TITLE
Spring Boot 3.1.0-RC1 > Spring ORM uses PostgreSQL95Dialect which has been deleted from hibernate-core

### ISSUE THREAD

**Issue by GwennaelLonvert** [spring-projects/spring-framework#30386] opened 2023-04-27 14:14 UTC
Hello,

I'm facing an issue when upgrading to Hibernate 6.2 (through Spring Boot 3.1.0-RC1). The application raises an error at start up : 
![image](https://user-images.githubusercontent.com/46742834/234887355-94a76fb6-124a-42f1-8eb5-073f56c9413d.png)

I have no specific configuration concerning dialect because I want Hibernate to detect it automatically as it is recommended. 
Indeed, the `HibernateJpaVendorAdapter` determine the postgre dialect as `PostgreSQL95Dialect` **which does not exist anymore in `hibernate-core`** because `PostgreSQLDialect` should be use. 

Sources : 
- https://github.com/spring-projects/spring-framework/blob/main/spring-orm/src/main/java/org/springframework/orm/jpa/vendor/HibernateJpaVendorAdapter.java#L181
- https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html#database-versions
- https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/PostgreSQL95Dialect.20deleted.20in.20Hibernate.206.2E2

Would it be possible to change this Dialect please ?

As a workaround, I guess I can just add the property `spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect`.

Versions : 
- Spring boot 3.1.0-RC1 (with spring-orm 6.0.8)
- Hibernate 6.2.1.Final

**Comment by sdeleuze** [comment] 2023-04-27 14:27
Duplicate of those issues on other projects:
 - https://github.com/spring-projects/spring-boot/issues/35103
 - https://github.com/oracle/graalvm-reachability-metadata/issues/273

Will be fixed via https://github.com/oracle/graalvm-reachability-metadata/issues/62.

**Closed by sdeleuze** 2023-04-27 14:27 UTC
Labels: status: waiting-for-triage
