### ISSUE TITLE
Make length limit for SpEL expressions configurable

### ISSUE THREAD

**Issue by tpoeppke** [spring-projects/spring-framework#30548] opened 2023-05-25 13:44 UTC
In https://github.com/spring-projects/spring-framework/issues/30325 a hard length limit of 10.000 characters was introduced for SpEL expressions.

We are currently using SpEL expressions in a context where this limit could be exceeded. Unfortunately, I couldn't find an explanation as to why this change happened. As the limit was not enforced before either, I would propose to make it configurable and only set the default limit to 10.000.

Are there any reasons that I missed which made it necessary to introduce this limit and would not allow to make it configurable?

**Comment by sbrannen** [comment] 2023-05-25 14:01
Hi @tpoeppke,

This is a duplicate of #30380.

The maximum expression length was made configurable in aefcb9d2d6ee385c14d83852bee50b0307b42ce4, and that feature was released in 6.0.9.

Please review that commit and the discussions in #30380, and if you have any further questions let us know.

Thanks,

Sam

**Closed by sbrannen** 2023-05-25 14:01 UTC
Labels: status: waiting-for-triage
