### ISSUE TITLE
WebClient retry() doesn't re-run filters

### ISSUE THREAD

**Issue by Anusien** [spring-projects/spring-framework#23909] opened 2019-11-01 19:48 UTC
Calling `retry()` on a `Mono<>` produced by calling `WebClient.exchange()` won't re-run the filters. This means any modifications made to the request by filters (like changing the URL for load-balancing purposes) won't be repeated.

`DefaultWebClient` seems to run all the filters synchronously, including generating the URL. Then `DefaultExchangeFunction` calls `ClientHttpConnection`. It's the http connection that does the actual connection asnychronously, producing a `Mono<>`. Specifically, filters get run when you call `exchange()` or `retrieve()`, not when you actually subscribe.

Related: https://github.com/spring-cloud/spring-cloud-commons/issues/579

**Comment by rstoyanchev** [comment] 2019-11-04 12:34
It looks like this might be a duplicate of #22375 which was fixed in 5.2 but was not backported to 5.1.x. We should backport that fix in any case, but can you confirm the version of the Spring Framework you are on just to be sure?

**Comment by Anusien** [comment] 2019-11-04 22:26
`org.springframework:spring-webflux:5.1.7.RELEASE`

**Comment by rstoyanchev** [comment] 2019-11-05 09:50
Okay, you shouldn't experience the issue with 5.2.1 if you want to try and confirm. I've scheduled this to backport the same fix to 5.1.12.

**Comment by spring-issuemaster** [comment] 2019-11-06 21:59
Fixed via 1a057654b2daa461ddbf0979bd450f8a6fd65a01

**Closed by spring-issuemaster** 2019-11-06 21:59 UTC
Labels: in: web, type: enhancement
