### ISSUE TITLE
Spring not injecting the configured conversionService into the DataBinder.

### ISSUE THREAD

**Issue by n0thinghs** [spring-projects/spring-framework#23617] opened 2019-09-11 08:28 UTC
I was trying to add some converters to be used while binding a form.
Spring version : 4.3.17
when adding some converters to conversionService, we add a bean with the custom converters i, the xml file, then we add the following tag <mvc:annotation-driven conversion-service="conversionService"> and our configured bean will be injected, but if we have another config xml file, having the following tag <mvc:annotation-driven />, spring will inject the default conversionService, the one without our custom converters.

**Comment by rstoyanchev** [comment] 2019-09-11 09:38
There shouldn't be multiple `annotation-driven` elements. That results in duplicating or overriding already declared infrastructure beans.

**Comment by n0thinghs** [comment] 2019-09-11 10:07
I have multiple java modules (spring boot projects), some of them depend on others module( called extension in Hybris Platform), each have it's own spring configuration (beans config, mvc config, ...).

**Comment by rstoyanchev** [comment] 2019-09-11 11:16
It's fine for modules to have their own bean config, but specifically the `<mvc:annotation-driven>` element is not intended to be declared multiple times in a single running app (JVM). In turn it declares `HandlerMapping`'s, `HandlerAdapater`'s and others that shouldn't be re-declared. Depending on whether those beans have fixed or dynamically generated names, it results in either overriding or duplication, and neither is the right outcome. In the case of `ConversionService` the bean uses a well-known name so there can only be one, and the second declaration essentially overrides the first.

**Comment by rstoyanchev** [comment] 2019-09-11 11:16
I'm closing the issue as it is expected behavior.

**Closed by rstoyanchev** 2019-09-11 11:16 UTC
Labels: status: feedback-provided, status: waiting-for-triage
