### ISSUE TITLE
405 Method is not Allowed exception: "Request Method 'T' not supported" for GET call  and "Request Method 'ST' not supported" for POST

### ISSUE THREAD

**Issue by manuj20** [spring-projects/spring-framework#25023] opened 2020-05-07 04:46 UTC
Hi Team,
I am facing a very strange issue in my project. It is related to rest API call using spring reactive webclient bulider. It is working fine on local and prod as well but abnormally giving  below error  after 3 or 4 request to same endpoint.
"org.springframework.web.server.MethodNotAllowedException: 405 METHOD_NOT_ALLOWED "Request method 'T' not supported"
This is valid exception as method going to "T" for Get method and "ST" for Post method .I am not able to understand why two starting charcter truncating from method name

Please help me resolve this error.

**Comment by manuj20** [comment] 2020-05-08 03:48
It is not reproducible on Local .We are getting this abnormal behaviour on production sometime not everytime .For 1 request out of 5 for same during load testing. We try to reproduce it on local.But We can't.

**Comment by bclozel** [comment] 2020-05-08 08:14
From your description, it’s not clear if the issue comes from the client or the server.
Spring is not involved directly in writing or reading the HTTP protocol, so this might be a problem with the server/client library, or more likely a concurrency issue with your own code.

I’m closing this issue for now as there is no way to make progress with so little information.
Feel free to reopen this issue when you’ll manage to reproduce the problem in a minimal (this is important) application. To reproduce this locally, maybe you could try and simulate concurrency with multiple concurrent requests to your service (try the « ab » tool for example).

Thanks!

**Closed by bclozel** 2020-05-08 08:14 UTC
Labels: in: web, status: feedback-provided, status: waiting-for-triage

**Comment by rohan-new** [comment] 2022-01-22 20:44
@manuj20  Were you able to resolve the issue ? As I am facing the same issue of getting 405 method not allowed on subsequent api calls using webclient.

**Comment by manuj20** [comment] 2022-01-23 04:35
We are not able to resolve this issue as per my knowledge...as it was happening with probability 1 out 20...so reproduce it difficult we carry forward this error by customised webclient connection pool  configuration...We did just this but that doesn't seems to me solution . . So you can carry forward with this thread by reopening it

**Comment by mdzhigarov** [comment] 2022-06-23 12:48
We have stumbled upon the same exact issue. No workarounds so far, currently trying to enable netty trace logging to gather more information

**Comment by rohan-new** [comment] 2022-06-24 10:53
`@mdzhigarov I was able to solve the issue by doing the following, u could do the same.
HttpClient httpClient = HttpClient.create()
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 2000)
                .responseTimeout(Duration.ofMillis(5000))
                .wiretap("reactor.netty.http.client.HttpClient",
                        LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)
                .doOnConnected(conn ->
                        conn.addHandlerLast(new ReadTimeoutHandler(5000, TimeUnit.MILLISECONDS))
                                .addHandlerLast(new WriteTimeoutHandler(5000, TimeUnit.MILLISECONDS)));

        WebClient.Builder webClientBuilder = WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(httpClient));

        testWebClient = webClientBuilder
                .baseUrl(baseUrl)
                .build();`

**Comment by mdzhigarov** [comment] 2022-07-04 14:08
Reproduced the issue by creating a web client that sends GET request with content-length: 2 header and no body.
The first GET request is successful - it returns a valid result. 
The second GET request fails with 	"message": "405 METHOD_NOT_ALLOWED \"Request method 'T' not supported\""

It seems that Netty is doing the right thing - dropping the first 2 bytes of the second request - 'GE' because the channel expects 2 bytes from the first request.

Should we fix the Spring WebClient to drop such invalid requests - having content-length with no actual body?
I can easily workaround this but I feel that Spring should guard me if I try to create such malicious request

**Comment by lyzzz0101** [comment] 2024-09-24 02:41
got same issue here but with POST methods

[container_ip：10.10.33.205
container_name： ish-intelligence-store-platform-admin-web
image_name：tastien-registry-vpc.cn-shanghai.cr.aliyuncs.com/tst-uat/ish-intelligence-store-platform-admin-web:5322
pod_name：ish-intelligence-store-platform-admin-web-6d8d47d954-h8g76
pod_uid：4a8cb38e-fe5c-4e10-b139-e4bf9c140f42
source：stdout
time：2024-09-24T01:16:53.710284065Z
app_id：intelligence-store-platform-admin-web
content：2024-09-24 09:16:53.709 ERROR [intelligence-store-platform-admin-web] [http-nio-8080-exec-187] [07452746a8fbdc11402d448032ddef1f] [||] c.s.i.a.a.WebExceptionHandler -  系统异常 原因：null uri:/intelligence/member/login,堆栈：Request method 'O' not supported
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'O' not supported
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:197)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:379)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:318)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:62)
	at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:350)
	at org.springfram
log_level：ERROR
logger_class：c.s.i.a.a.WebExceptionHandler
message：null
thread：http-nio-8080-exec-187
time：2024-09-24 09:16:53.709
trace_id：07452746a8fbdc11402d448032ddef1f](url)
