### ISSUE TITLE
Dynamically change the application properties defined in the YAML file while running Springboot tests

### ISSUE THREAD

**Issue by raahool** [spring-projects/spring-framework#25145] opened 2020-05-27 20:57 UTC
My Use case is,

organisation wide all our microservies are using `YAML`, so we cannot move from `YAML `to `.properties`.
In one of my recent app, I am using testcontainers for Unit tests, where testcontainers randomly selects any available port to start the container. So before running the tests I have to dynamically change the PORT property which is defined in the YAML file.
For .properties file, it was straightforward with `ApplicationContextInitializer `& `TestPropertyValues `- like
`TestPropertyValues.of("spring.rabbitmq.port" + container.getMappedPort(5672)).applyTo(applicationContext);`

Not able to achieve this, being the port property is defined in the YAML file.

Any workaround / suggestions ?

**Comment by quaff** [comment] 2020-05-28 00:38
Please refer to https://github.com/spring-projects/spring-framework/issues/24540

**Comment by bsideup** [comment] 2020-05-28 09:16
Also see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-testcontainers

**Comment by sbrannen** [comment] 2020-05-28 10:26
Closing this issue as a duplicate of #24540.

If you find that `@DynamicPropertySource` does not meet your needs, feel free to post back here.

**Closed by sbrannen** 2020-05-28 10:26 UTC
Labels: status: waiting-for-triage

**Comment by raahool** [comment] 2020-05-29 18:31
Which version of Spring has this annotation. Currently our enterprise is on SpringBoot 2.2.4.RELEASE version.
