### ISSUE TITLE
Add viewController-like support in WebFlux [SPR-17389]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21922] opened 2018-10-16 09:56 UTC
**[Brian Clozel](https://jira.spring.io/secure/ViewProfile.jspa?name=bclozel)** opened **[SPR-17389](https://jira.spring.io/browse/SPR-17389?redirect=false)** and commented

This is something that's often requested by the community, especially for static pages support - see [here](https://github.com/spring-projects/spring-boot/issues/9785).

We could add a `viewController`-like support on the `WebFluxConfigurer` to help Spring Boot support that requested feature.

---

**Affects:** 5.1.1

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/9785

**Comment by rstoyanchev** [comment] 2019-01-29 17:39
This is a duplicate of #21569.

**Closed by rstoyanchev** 2019-01-29 17:39 UTC
Labels: in: web, type: enhancement
