### ISSUE TITLE
Seems like XmlBeans has risen from the grave - so should XmlBeansMarshaller be reintroduced?

### ISSUE THREAD

**Issue by rasmuslund** [spring-projects/spring-framework#27394] opened 2021-09-13 09:27 UTC
**Affects:** \<Spring Framework version>

---

Seems like XmlBeansMarshaller was first deprecated and then removed. But now that XmlBeans seems to have risen from the grave, should XmlBeansMarshaller then also be reintroduced?

**Comment by mdeinum** [comment] 2021-09-13 13:04
Duplicate #22403 and #24130. Which provides the answer from @jhoeller himself

> Like with Velocity, we do not intend to reintroduce XMLBeans support out of the box anymore. If such integration is still desirable, our former marshalling adapter classes should be a fine starting point and could easily be part of the XMLBeans project itself, co-maintained along with its own further evolution.
>
> In the end, we only aim for JAXB2 and XStream to be supported out of the box, with JiBX being deprecated as well in the meantime. This is in alignment with our abstractions in other places, e.g. only EclipseLink and Hibernate as out-of-the-box JPA vendor adapters.

**Comment by bclozel** [comment] 2021-09-13 13:16
Closing as a duplicate of #22403 and #24130.

**Closed by bclozel** 2021-09-13 13:16 UTC
Labels: status: duplicate
