### ISSUE TITLE
Hazelcast requestMappingHandlerAdapter run error

### ISSUE THREAD

**Issue by iron2414** [spring-projects/spring-framework#22996] opened 2019-05-20 08:58 UTC
I'm trying to use hazelcast with webflux. I checked the spring docs, hazelcast docs, and some online articles. They all write basically the same, i tried everything that was there, but i can't run the applicaton. I'm using:

-  spring-boot-starter-webflux
-  hazelcast, hazelcast-spring
- spring-boot-starter-web
- spring-boot-starter-security

 When i try to run the application i get the following error: 

`"The bean 'requestMappingHandlerAdapter', defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class], could not be registered. A bean with that name has already been defined in org.springframework.web.reactive.config.DelegatingWebFluxConfiguration and overriding is disabled."`

I'm assuming even if i override it somehow, then the webflux handler wouldn't work.

**Comment by snicoll** [comment] 2019-05-20 12:44
@iron2414 if you have a question, please ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements.

If you are reporting a bug, we will need a small sample app (zip or github repo) that reproduces the problem you've described. Based on the sample, we might have to move this to a more relevant issue tracker. Let's have a look to it first.

**Comment by spring-issuemaster** [comment] 2019-05-27 12:46
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-03 12:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-03 12:48 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
