### ISSUE TITLE
ConfigurationClasses has userless data

### ISSUE THREAD

**Issue by Evanhelovex** [spring-projects/spring-framework#28085] opened 2022-02-21 07:34 UTC
Sorry to bother you, I mentioned this issue a few days ago, but it was closed by you without an explanation at that time. I think it is necessary to explain to you again that the configurationClasses container does have data that should not exist. Through my modification, the existing functions will not be damaged after testing, and it is indeed helpful to read the source code.
![image](https://user-images.githubusercontent.com/34882843/154908857-27a38569-abb0-40e9-8f46-bde18b7ba5fa.png)

**Comment by Evanhelovex** [comment] 2022-02-21 07:47
configurationClasses contains mainly for processing here (org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader#loadBeanDefinitions), the components scanned by @CoponentScan have been registered with the BeanDefinitionRegistry (org.springframework.context.annotation.ComponentScanAnnotationParser#parse
), so these components should not exist in the configurationClasses container.
![image](https://user-images.githubusercontent.com/34882843/154910624-d94d87af-d72e-4e3e-b357-a2182e6cbdeb.png)
![image](https://user-images.githubusercontent.com/34882843/154910717-981f5dae-77d0-4937-981a-7f87f26d502d.png)

**Comment by snicoll** [comment] 2022-02-21 08:09
Duplicate of #28072 

@Evanhelovex As I've tried to indicate on several occasions, there is nothing in your report that I think it worth pursuing. Sharing a code snippet and screenshots is not how we determine that a change in the core container should be made. Rather, you should provide a sample that showcases a problem (a unit test) or a benchmark that reproduces the memory leak you're claiming. 

Also, the `configurationClasses` map is used to validate configuration classes down the road and this has nothing to do with the bean registry.

**Closed by snicoll** 2022-02-21 08:09 UTC
Labels: status: waiting-for-triage

**Comment by Evanhelovex** [comment] 2022-02-21 09:06
Thanks a lot for your answer, I see.
