### ISSUE TITLE
resourceUrlProvider cause cycle dependency

### ISSUE THREAD

**Issue by zjengjie** [spring-projects/spring-framework#22700] opened 2019-03-28 10:23 UTC
I create a [repo](https://github.com/zjengjie/dep-issue) reproduce this issue.

I have opened an issue on https://github.com/spring-cloud/spring-cloud-openfeign/issues/142 , but they think it's not cause by spring cloud.

I test just remove
```java
@Bean
public ResourceUrlProvider resourceUrlProvider() {
	return new ResourceUrlProvider();
}
```
in `WebFluxConfigurationSupport` will avoid this error.

I really don't know which spring project should put the issue, any advice?

**Comment by rstoyanchev** [comment] 2019-03-31 16:21
I think the root cause is likely related to what Sencer said:

> You are referencing a feign client from a class that is used by spring security.

It is possible that something in the Spring Boot autoconfiguration did change recently that exposes this issue but I would first ask on the Spring Cloud Feign ticket you opened if what you're trying to do is possible or if there is an inherent circular dependency. I'm actually surprised the ticket was resolved without a discussion of that.

In any case the Spring Framework is at a lower level of all these dependencies. There is no way the `resourceUrlProvider` bean is at fault.

**Closed by rstoyanchev** 2019-03-31 16:21 UTC
Labels: status: waiting-for-triage
