### ISSUE TITLE
Duplicated Invoke when onApplicationEvent called from ApplicationListener

### ISSUE THREAD

**Issue by freezingWu** [spring-projects/spring-framework#25649] opened 2020-08-24 15:35 UTC
Running with springboot 2.2.5 ,which contains spring version: spring-core-5.2.4  and spring-aop-5.2.4.

Scenario:
My Listener as below:

```java
@Service
public class UserJoinRoomListener implements ApplicationListener<UserJoinRoomEvent> {
  @Override
  @TraceSource(sampler = RoomEntrySampler.class) //AOP here to trigger #{RoomEntrySampler#process} after current funtion invoked
  public void onApplicationEvent(UserJoinRoomEvent event) {
    System.out.println("Hello ");
  }
}
```

RoomEntrySampler code as below:

```java
public class RoomEntrySampler{
  @Override
  public void process(UserJoinRoomEvent event) {
	System.out.println("World");
  }
}
```

when i call `ApplicationContext.publishEvent(new UserJoinRoomEvent(xxx,xxx))` 

Expectation: 
it should print "Hello World".

Actually:
it print "Hello Hello World"

Question:
to my understanding,  Function "onApplicationEvent"(the proxy object ) should only be invoked at just one time and run at one go.  but it's not eventually ,, can i consider this situation as a  "Bug"?

**Comment by philwebb** [comment] 2020-08-27 01:17
@freezingWu No need to re-raise it. We were able to transfer the issue. The Spring Framework team will need to triage it to determine if they consider it a bug or not.

**Comment by snicoll** [comment] 2023-11-12 10:13
I did upgrade the sample to a supported version of the framework and got the following running the test:

```
Enter Aop counter:1
onApplicationEvent counter:1
```

(with no `counter: 2`). Sorry this got overlooked but it looks like this was fixed in the meantime. If you can reproduce with a supported version of the framework, please update the sample and we can reopen.

**Closed by snicoll** 2023-11-12 10:13 UTC
Labels: status: waiting-for-triage, in: core
