### ISSUE TITLE
Unwrap CompletionException for MVC handlers that return CompletableFuture

### ISSUE THREAD

**Issue by sviperll** [spring-projects/spring-framework#22475] opened 2019-02-26 12:20 UTC
CompletableFuture exceptions are always wrapped into CompletionException.
We need to unwrap CompletionException to properly handle exceptions in MVC handlers that return CompletableFuture.
Otherwise it's impossible to implement `@ExceptionHandler` in `@ControllerAdvice` to handle underlying exception.
See https://stackoverflow.com/questions/49676889/spring-controller-advice-does-not-correctly-handle-a-completablefuture-completed

**Comment by snicoll** [comment] 2019-02-26 12:27
Duplicate of #22475

@sviperll if you intend to submit a PR, an issue is no necessary anymore.

**Closed by snicoll** 2019-02-26 12:27 UTC
Labels: status: waiting-for-triage
