### ISSUE TITLE
Regression in SpringWeb 6.1.4 causes ContentType to be missing if ShallowEtagHeaderFilter is used and HTTP response is streamed

### ISSUE THREAD

**Issue by j-be** [spring-projects/spring-framework#32363] opened 2024-03-04 14:28 UTC
**Affects:** \6.1.4

Upgrading from SpringBoot 3.2.2 to 3.2.3 broke some of our APIs. After thorough examination we were able to narrow the issue down to the SpringWeb going from 6.1.3 to 6.1.4.

Further investigation showed, that the issue only appears if `ShallowEtagHeaderFilter` is enabled and `disableContentCaching` is called on it, which seems to be happening if the HTTP response is streamed.

I created a minimal reproducer at https://github.com/j-be/spring-web-contentType-issue

**Comment by snicoll** [comment] 2024-03-04 15:30
Thanks for the report. I believe this is a duplicate of #32317. Please test against `6.1.5-SNAPSHOT` and report back if that doesn't fix the problem.

**Closed by snicoll** 2024-03-04 15:30 UTC
Labels: status: waiting-for-triage
