### ISSUE TITLE
Reconsider fallback date formats for ISO variants in DateTimeFormatterRegistrar

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-framework#28130] opened 2022-03-03 09:18 UTC
`spring-boot-starter-webflux-2.6.4`

The following controller can take a date in `yyyy-MM-dd` format in a `@PostMapping` request without problems, but fails for a `@GetMapping` query parameter.

```java
@RestController
public class DateTimeServlet {    
    static class DateTimeDto {
        private LocalDate date;
        //getter, setter
    }

    @PostMapping("/datetime")
    public Mono<String> datetimePost(@RequestBody DateTimeDto dto) {
        return Mono.just("OK");
    }

    @GetMapping("/datetime")
    public Mono<String> datetimeGet(DateTimeDto dto) {
        return Mono.just("OK);
    }
}
```

Works:

```
POST localhost:8080/datetime
{
    "date": "2022-02-02"
}
```

Does not work:

```
GET localhost:8080/datetime?date=2022-02-02
```

Result:

```json
{
    "timestamp": "2022-03-03T08:57:56.248+00:00",
    "status": 400,
    "message": "'date': : Parse attempt failed for value [2022-02-02]. rejectedValue: 2022-02-02"
}
```

Why are get and post requests behaving that differently? Shouldn't either both succeed, or both fail?

Update: while I discovered that POST bodies are converted using `jackson`, and GET parameters using Spring Conversation Service, I wonder if it wouldn't be better that both could have the same behavior?

**Comment by bclozel** [comment] 2022-03-03 10:13
Looking at this issue transferred from Spring Boot, we could reconsider in the 6.0 timeline the date time fallback formats to use ISO variants instead of `FormatStyle.SHORT`.

**Comment by sbrannen** [comment] 2022-03-03 14:13
- Closing as a duplicate of #26985.

**Closed by sbrannen** 2022-03-03 14:13 UTC
Labels: for: team-attention, status: waiting-for-triage, in: core
