### ISSUE TITLE
Method-level @RequestMapping is inconsistent regarding trailing slashes with request params

### ISSUE THREAD

**Issue by AdamBeddoe** [spring-projects/spring-framework#23440] opened 2019-08-09 13:50 UTC
Version: Spring Boot v2.1.6.RELEASE

A class-level `@RequestMapping` paired with a method-level `@RequestMapping` with `value=""` and `@RequestParam` requires a trailing slash in the URI; whereas, any other string works as expected. Removing the `value` attribute also works as expected.

For example in the following:

```Java
@RestController
@RequestMapping("/foo")
public class controller {
    @GetMapping("")
    public String bar1(@RequestParam String bazz) {
        return "this doesn't work";
    }

    @GetMapping("/test")
     public String bar2(@RequestParam String bazz) {
        return "but this does work";
     }
}
```

A request such as ``/foo?bazz=x`` will not match, requiring `/foo/?bazz=x`; however, `/foo/test?bazz=x` will.

This seems like an inconsistency.

Replacing `@GetMapping("")` with `@GetMapping` works correctly.

**Comment by sbrannen** [comment] 2019-08-10 12:52
Out of curiosity, why would you intentionally declare `@GetMapping("")` instead of `@GetMapping` if you don't want to further augment the class-level path mapping?

As a side note, I imagine `@GetMapping({})` is actually what you intended with `@GetMapping("")`, but that is merely overriding the default with the default.

**Comment by rstoyanchev** [comment] 2019-08-21 12:28
> request such as `/foo?bazz=x` will not match

I can't reproduce this behavior.

```java
RequestMappingInfo info1 = paths("/foo").build();
RequestMappingInfo info2 = paths("").build();
System.out.println(info1.combine(info2));

// Prints { /foo}
```

**Comment by spring-issuemaster** [comment] 2019-09-04 12:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-09-04 12:35 UTC
Labels: in: web, status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
