### ISSUE TITLE
excludeFilters of @ComponentScan ignored since version 2.2.0 

### ISSUE THREAD

**Issue by rob-valor** [spring-projects/spring-framework#24263] opened 2019-12-24 23:29 UTC
Since Spring Boot 2.2.0 the `excludeFilters` of `@ComponentScan` is ignored when loading the Spring Boot application context.

When using a configuration class, loaded with `spring.factories` which does a `@ComponentScan` for the "framework" it provides, the application context is loading configuration classes which should be excluded (added to the `excludeFilters`). In version 2.1.11 all works fine. Starting from 2.2.0 the excluded class is loaded causing the context to fail.

I added a small maven project to reproduce the issue. Switch parent pom version to 2.2.0 (or later) and maven build will fail. It looks like a Spring Boot (test context?) issue. Tests using a standard Spring context are not affected (`common-framework-boot-support`module), the `@SpringBootTest` tests are (`application` module).
[spring-componentscan-issue.zip](https://github.com/spring-projects/spring-boot/files/3999184/spring-componentscan-issue.zip)

**Comment by rob-valor** [comment] 2019-12-25 21:20
Indeed, sometimes the most basic things tend to be skipped when facing/solving a software issue 😊 . Yes, also`@SpringBootApplication` also does a _classic_ `@ComponentScan`. I modified the example to (1) not fail the context having a cleaner test failure instead of blowing up and (2) build a _classic_ spring context by also adding a `@ComponentScan` to the `common-framework-boot-support` module which, without having Spring Boot on the classpath, also fails to properly apply the `excludeFilters`.
[spring-componentscan-issue_update.zip](https://github.com/spring-projects/spring-framework/files/4000813/spring-componentscan-issue_update.zip)

**Comment by rob-valor** [comment] 2019-12-25 23:23
The issue seems to be in [AnnotationTypeFilter#matchSelf](https://github.com/spring-projects/spring-framework/blob/v5.2.0.RELEASE/spring-core/src/main/java/org/springframework/core/type/filter/AnnotationTypeFilter.java#L100). The `AnnotationMetadata` implematation is completely different (5.2: `SimpleAnnotationMetadata`, 5.1: `AnnotationMetadataReadingVisitor`) and apparently missing valuable class level annotation information. `AnnotationMetadata#hasAnnotation` returns false when looking for my `excludeFilters` _marker_ annotation which it does not in Spring 5.1.

Hope this helps.

**Comment by snicoll** [comment] 2019-12-26 08:57
@rob-valor great detective work! I suspected indeed the new annotation API retrieval to have a regression in this area. Thanks for the updated sample.

**Comment by sbrannen** [comment] 2019-12-26 17:56
The solution is to ensure that your annotation is properly retained at runtime.

If you declare `@DoNotScan` as follows, your test passes as expected.

```java
@Retention(RetentionPolicy.RUNTIME)
public @interface DoNotScan {
}
```

This is effectively a duplicate of #23901.

See https://github.com/spring-projects/spring-framework/issues/23901#issuecomment-549144453 for details, specifically:

> **As of Spring Framework 5.2, all annotations are now required to be annotated with `@Retention(RetentionPolicy.RUNTIME)` in order for Spring to _see_ them.**

I am therefore closing this issue.

**Closed by sbrannen** 2019-12-26 17:56 UTC
Labels: type: regression

**Comment by rob-valor** [comment] 2019-12-26 18:02
We'll update our code then. Thanks.

**Comment by plum117** [comment] 2020-01-10 16:21
Thanks I had the same issues, adding `@Retention(RetentionPolicy.RUNTIME)` solved it!
