### ISSUE TITLE
Bean definition extending FactoryBean with generics is not injected

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-framework#27383] opened 2021-09-10 12:36 UTC
See spring-projects-experimental/spring-native#1022 for background.

While working on spring-native, we've found a behavior that might be a bug in the core container support for the functional registration of beans (through instance suppliers).

Some of our samples are failing with `org.springframework.beans.factory.NoSuchBeanDefinitionException`. The missing bean is of type `PluginRegistry<T,S>` and is contributed through a `PluginRegistryFactoryBean<T,S>` (with `T` and `S` being concrete types: 'org.springframework.plugin.core.PluginRegistry<org.springframework.hateoas.server.LinkRelationProvider, 
org.springframework.hateoas.server.LinkRelationProvider$LookupContext>').

While debugging the issue, we've found that the current code generation process in spring-native contributes that definition to the context with: 

```java
BeanDefinitionRegistrar.of("relProviderPluginRegistry", ResolvableType.forClassWithGenerics(PluginRegistryFactoryBean.class, LinkRelationProvider.class, LinkRelationProvider.LookupContext.class)).withFactoryMethod(HateoasConfiguration.class, "relProviderPluginRegistry")
            .instanceSupplier(() -> context.getBean(HateoasConfiguration.class).relProviderPluginRegistry()).register(context);
```

The important part is that we're declaring the `PluginRegistryFactoryBean` type as the `ResolvableType` target type in the definition; this seems to confuse the core container in the `org.springframework.beans.factory.support.DefaultListableBeanFactory#doResolveDependency` and especially the `org.springframework.beans.factory.support.DefaultListableBeanFactory#findAutowireCandidates` sequence. Instead of considering the generic type of the bean produced by the `FactoryBean` and if it's assignable to the required type for the injection point, this seems to only consider the provided target type.

This might be linked with the fact that we're heavily using the `instanceSupplier` mechanism instead of factory methods.

We've validated that providing the type produced by the Factory directly as the target `ResolvableType` (so 'PluginRegistry<LinkRelationProvider, LookupContext>' instead of 'PluginRegistryFactoryBean<LinkRelationProvider, LookupContext>' solves the issue.

We need to consider this case and know whether this behavior is expected or if this shows a problem with the current suport of instance suppliers.

**Comment by bclozel** [comment] 2021-09-14 11:35
Closing in favor of spring-projects-experimental/spring-native#1030

**Comment by snicoll** [comment] 2021-09-15 11:16
Discussing this topic further, we'd still like to experiment how we can check the `FactoryBean` type in `GenericTypeAwareAutowireCandidateResolver`.

**Comment by snicoll** [comment] 2021-09-15 12:34
The following bean definition fails to inject the plugin registry:

```java
BeanDefinitionRegistrar.of("relProviderPluginRegistry", ResolvableType.forClassWithGenerics(PluginRegistryFactoryBean.class, LinkRelationProvider.class, LinkRelationProvider.LookupContext.class)).withFactoryMethod(HateoasConfiguration.class, "relProviderPluginRegistry")
            .instanceSupplier(() -> context.getBean(HateoasConfiguration.class).relProviderPluginRegistry()).register(context);
```

If we move the target type to the actual type produced by the `BeanFactory`, injection is successful: 

```java
BeanDefinitionRegistrar.of("relProviderPluginRegistry", ResolvableType.forClassWithGenerics(PluginRegistry.class, LinkRelationProvider.class, LinkRelationProvider.LookupContext.class)).withFactoryMethod(HateoasConfiguration.class, "relProviderPluginRegistry")
            .instanceSupplier(() -> context.getBean(HateoasConfiguration.class).relProviderPluginRegistry()).register(context);
```

**Comment by jhoeller** [comment] 2024-04-08 22:06
As far as I can tell, this is effectively a duplicate of #29385 where we determine the nested generic from a FactoryBean target type. And as of the recent revision in #32489 and in particular #32590, I see no such cases left uncovered anymore.

**Closed by jhoeller** 2024-04-08 22:06 UTC
Labels: status: duplicate, in: core, type: enhancement
