### ISSUE TITLE
getHandlerInternal repeated lookup for HandlerMethod

### ISSUE THREAD

**Issue by ShijunDeng** [spring-projects/spring-framework#29591] opened 2022-11-28 03:59 UTC
when `spring-boot-starter-actuator` imported to my project ：

![image](https://user-images.githubusercontent.com/19890044/204190419-835b3242-cabd-4f1f-93d5-e8e005058803.png)

there are 6 members in org.springframework.web.reactive.DispatcherHandler#handlerMappings. Part of those HandlerMappings are subclass of `org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping`, which caused repeated call of `org.springframework.web.reactive.result.method.AbstractHandlerMethodMapping#getHandlerInternal` to lookup `HandlerMethod`.

- AdditionalHealthEndpointPathsWebFluxHandlerMapping

![image](https://user-images.githubusercontent.com/19890044/204190949-d32fcbee-d168-4c91-a97e-1bc4ef8dbb37.png)

- WebFluxEndpointHandlerMapping

![image](https://user-images.githubusercontent.com/19890044/204191046-b11f2bc4-6380-4f43-8b90-39cafbbb876f.png)

- ControllerEndpointHandlerMapping

![image](https://user-images.githubusercontent.com/19890044/204191128-b2797657-80ba-42bd-9c4d-4ea8cbb84beb.png)

and so on.

this is my solution: https://github.com/spring-projects/spring-framework/pull/29589

**Comment by rstoyanchev** [comment] 2022-12-02 13:56
I don't understand what the problem is. Each `HandlerMapping` has its own registrations, and `HandlerMapping`s are invoked in order until one of them returns a match. If the second is called, it means the ones before didn't find a match. Or, if the first one finds a match, then the second one is not called.

**Comment by spring-projects-issues** [comment] 2022-12-09 13:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-12-16 13:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-12-16 13:58 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
