### ISSUE TITLE
Application hangs on startup after upgrading to Spring Boot 3.2.1 with spring-data-redis and micrometer-prometheus dependencies

### ISSUE THREAD

**Issue by Zernov-A** [spring-projects/spring-framework#32996] opened 2024-01-18 19:34 UTC
After upgrading spring-boot to 3.2.1, I encountered an issue where the application hangs on startup. This occurs specifically when using spring-data-redis with enabled keyspace events on startup, in conjunction with the micrometer-prometheus dependencies.

### Steps to Reproduce
I have prepared minimal code to reproduce this issue. Below is a simplified version of the build.gradle and DemoApp.java files:

#### **`build.gradle`**
```
plugins {
    id 'java'
    id 'org.springframework.boot' version "3.2.1"
}

repositories {
    mavenLocal()
    mavenCentral()
}

apply plugin: 'io.spring.dependency-management'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    runtimeOnly 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    runtimeOnly 'io.micrometer:micrometer-tracing-bridge-brave'
}

wrapper {
    gradleVersion = "8.5"
}
```

#### **`DemoApp.java`**
```
@SpringBootApplication
@EnableRedisRepositories(enableKeyspaceEvents = RedisKeyValueAdapter.EnableKeyspaceEvents.ON_STARTUP)
public class DemoApp {

    public static void main(String[] args) {
        new SpringApplication(DemoApp.class).run(args);
        System.out.println("Complete!");
    }
}
```

### Observations

- The issue persists across both Spring Boot versions 3.2.1 and 3.2.0.
- The application starts normally without hanging when using Spring Boot version 3.1.7 and below.

### Additional Information

In a typical scenario, the project includes entity and repository classes, along with other dependencies. However, the provided code is a minimal representation.

- Removing `enableKeyspaceEvents = RedisKeyValueAdapter.EnableKeyspaceEvents.ON_STARTUP` or changing its value to `ON_DEMAND` or `OFF` allows the application to start correctly.

- Removing any of the dependencies results in the application starting correctly.
- Disabling Prometheus metrics export by setting `management.prometheus.metrics.export.enabled=false` in `application.properties` also allows the application to start correctly.

**Comment by jhoeller** [comment] 2024-06-10 14:52
Given that we revised the core container towards lenient locking for 6.2 already (#23501), does this scenario work against 6.2.0-M3? I'm afraid there is nothing we can do in 6.1.x as a quick measure, I rather recommend working around this through not waiting for the result of any asynchronous steps in the bean initialization method itself. I recommend doing so wherever possible even when running against 6.2, actually.

**Comment by wilkinsona** [comment] 2024-06-10 15:03
>  does this scenario work against 6.2.0-M3?

I'm not sure. Upgrading the sample to 6.2.0-M3 results in the following failure:

```
Caused by: org.springframework.context.ApplicationContextException: Component scan could not be used with conditions in REGISTER_BEAN phase: [org.springframework.boot.autoconfigure.condition.OnBeanCondition@629ae7e]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:325)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:267)
        at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:409)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:294)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:267)
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:599)
        ... 18 common frames omitted
```

@snicoll may be able to give us a feel for it with his branch of Spring Boot that contains the necessary changes for Framework 6.2 compatibility. I say "a feel for it", as whether or not the problem occurs is quite delicate. For example, it does not occur in the supplied sample when the seemingly unrelated `org.springframework.cloud:spring-cloud-stream-binder-kafka` dependency is removed.

> not waiting for the result of any asynchronous steps in the bean initialization method itself

This would require a change in Spring Data Redis where creating the instance of `ReactiveRedisMessageListenerContainer` gets a connection from Lettuce which blocks the main thread until the connection has been established on a Netty-managed thread.

**Comment by jhoeller** [comment] 2024-06-10 15:09
> This would require a change in Spring Data Redis where creating the instance of ReactiveRedisMessageListenerContainer gets a connection from Lettuce which blocks the main thread until the connection has been established on a Netty-managed thread.

Alternatively, the arrangement may also enforce all of the required singleton beans to be initialized beforehand. Accessing an existing singleton bean does not require the singleton lock, that's just necessary for creating it on demand.

**Comment by wilkinsona** [comment] 2024-06-10 15:17
>  enforce all of the required singleton beans to be initialized beforehand

That would require changes in Micrometer (Tracing). Boot currently defers the creation of the `Tracer` using `ObjectProvider` and a singleton supplier as there's a cycle when Prometheus Examplars are involved because the MeterRegistry can depend on the `Tracer` (Exemplars) and the `Tracer` can depend on the `MeterRegistry` (recording metrics).

/cc @jonatan-ivanov

**Comment by snicoll** [comment] 2024-06-11 06:11
I can confirm the sample fails as Andy describe with Spring Boot `3.3.1-SNAPSHOT` and [the modifications](https://github.com/snicoll/spring-boot/tree/compat-6.2.x) I've added to make it build cleanly with Spring Framework `6.2.0-SNAPSHOT`. The exception is thrown from an area that was [changed in `6.2.x`](https://github.com/spring-projects/spring-framework/issues/23206) so it might not be totally related and perhaps the lock still holds once we're past that.

Let me first investigate this new exception and revisit things accordingly.

**Comment by snicoll** [comment] 2024-06-11 06:23
@jhoeller with `ContextFunctionCatalogAutoConfiguration` excluded, the application starts cleanly with Spring Framework `6.2.0-SNAPSHOT`.

**Comment by jhoeller** [comment] 2024-06-11 06:42
Thanks, @snicoll! From a Spring Framework perspective, we seem to have a strategic solution for these kinds of scenarios as of 6.2 then.

Against 6.1.x, it will have to be on the workarounds suggested above, either in Spring Data or in Micrometer. As mentioned, it is generally recommendable to relax such asynchronous init method arrangements and not rely on the container's locking behavior there. Any such change made in Spring Data or Micrometer will make sense against 6.2 as well, even if not strictly necessary there.

**Comment by wilkinsona** [comment] 2024-06-11 09:34
@jonatan-ivanov @mp911de, can you please take a look at this? With https://github.com/spring-projects/spring-data-redis/issues/2814 having previously been closed in favor of a Boot issue, we're in danger of going round in circles without identifying a fix.

**Comment by mp911de** [comment] 2024-06-11 09:58
Spring Data Redis isn't involved much. Tracing is configured on the Lettuce driver through `MicrometerCommandLatencyRecorder` that holds an instance of an object that circles back into the Spring context.
My envisioned fix would be moving observability bits into an earlier phase and a facility, that isn't related to context bootstrapping, similar to `ApplicationStartup`.

Any asynchronous database activity can suffer from that arrangement; Database activity during the container bootstrap happens on a regular basis and the number of drivers utilizing netty or any other async approach is growing.

From that perspective, I would welcome anything that removes the need for asynchronously fetching beans from a container that is being started.

**Comment by wilkinsona** [comment] 2024-06-11 16:25
Until a fix in Framework is available, I think we may have to make changes in several areas to get things working fully.

> Maybe we can move key expiration listener initialization from bean initialization step (in [RedisKeyValueAdapter](https://github.com/spring-projects/spring-data-redis/blob/aa7045ab95b86f1e361b5fb4c8690aee02e4e3be/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L701)) to phase when application context will be fully configured? This should prevent deadlock. The current scenario, if we use the EnableKeyspaceEvents.ON_STARTUP option, leads to the creation of the key expiration listener and the initiation of requests to Redis during bean initialization, and as a result we have deadlock with lazy Tracer initializing.

Is this suggestion from https://github.com/spring-projects/spring-data-redis/issues/2814 not viable? Similarly, avoiding the connection retrieval in the constructor of `ReactiveRedisMessageListenerContainer` would also help I think.

**Comment by wilkinsona** [comment] 2024-06-11 16:28
From a Framework perspective, I think this issue can be closed. There's a fix coming in 6.2 and nothing, AIUI, that can be done in 6.1.x.

We've got https://github.com/spring-projects/spring-boot/issues/40972 that's tracking the problem on the Boot side (although it may need to move to Micrometer (Tracing) as Boot's code is just trying to work around the `MeterRegistry <-> Tracer` cycle), and I'd welcome the re-opening of https://github.com/spring-projects/spring-data-redis/issues/2814 to track adoption of the suggestion to "relax such asynchronous init method arrangements and not rely on the container's locking behavior there".

**Comment by snicoll** [comment] 2024-06-11 17:00
Thanks for the summary, Andy.

**Closed by snicoll** 2024-06-11 17:00 UTC
Labels: status: waiting-for-triage, in: core

**Comment by wilkinsona** [comment] 2024-06-11 17:21
@jhengy, judging by your reproducer, you may be able to work around the problem by defining an eager `SpanContextSupplier`:

```java
	@Bean
	TracerSpanContextSupplier spanContextSuppler(Tracer tracer) {
		return new TracerSpanContextSupplier(tracer);
	}
	
	static class TracerSpanContextSupplier implements SpanContextSupplier {

		private final Tracer tracer;

		TracerSpanContextSupplier(Tracer tracer) {
			this.tracer = tracer;
		}

		@Override
		public String getTraceId() {
			Span currentSpan = currentSpan();
			return (currentSpan != null) ? currentSpan.context().traceId() : null;
		}

		@Override
		public String getSpanId() {
			Span currentSpan = currentSpan();
			return (currentSpan != null) ? currentSpan.context().spanId() : null;
		}

		@Override
		public boolean isSampled() {
			Span currentSpan = currentSpan();
			if (currentSpan == null) {
				return false;
			}
			Boolean sampled = currentSpan.context().sampled();
			return sampled != null && sampled;
		}

		private Span currentSpan() {
			return this.tracer.currentSpan();
		}

	}
```

It starts up successfully with this bean in place.

**Comment by rethab** [comment] 2024-08-21 15:14
For spring boot 3.3, since the `SpanContextSupplier` bean was replaced with a `SpanContext` bean, it looks like we need to do the same trick, but then with the `SpanContext`?

This seems to work for me:


```java
    @Bean
    SpanContext spanContext(Tracer tracer) {
        return new LazyTracingSpanContext(tracer);
    }

    static class LazyTracingSpanContext implements SpanContext {

        private final Tracer tracer;

        LazyTracingSpanContext(Tracer tracer) {
            this.tracer = tracer;
        }

        @Override
        public String getCurrentTraceId() {
            Span currentSpan = currentSpan();
            return (currentSpan != null) ? currentSpan.context().traceId() : null;
        }

        @Override
        public String getCurrentSpanId() {
            Span currentSpan = currentSpan();
            return (currentSpan != null) ? currentSpan.context().spanId() : null;
        }

        @Override
        public boolean isCurrentSpanSampled() {
            Span currentSpan = currentSpan();
            if (currentSpan == null) {
                return false;
            }
            Boolean sampled = currentSpan.context().sampled();
            return sampled != null && sampled;
        }

        @Override
        public void markCurrentSpanAsExemplar() {
        }

        private Span currentSpan() {
            return this.tracer.currentSpan();
        }
    }
```

**Comment by rethab** [comment] 2024-08-23 14:55
Would it be possible to allow disabling exemplar support entirely @jonatan-ivanov ?

I see `PrometheusExemplarsAutoConfiguration` has the `@ConditionalOnClass({ Tracer.class, SpanContext.class })`, which made me think I could just exclude the dependency `io.prometheus:prometheus-metrics-tracer-common`, but then `PrometheusMetricsExportAutoConfiguration` fails.

**Comment by jonatan-ivanov** [comment] 2024-08-23 19:57
In Micrometer, if you [don't provide `SpanContext`](https://github.com/micrometer-metrics/micrometer/blob/c7d16cd332dfb9046d205195293f1ccea0589b8b/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheusmetrics/PrometheusMeterRegistry.java#L97-L98) it will not sample Exemplars. I guess the feature you are asking could be a Boot property to not auto-configure it.

You can also create your own `@Bean` of `PrometheusMeterRegistry` where you don't inject any `SpanContext` which disables Exemplars.

You can also create your own `@Bean` of `SpanContext` where you return `false` in `isCurrentSpanSampled` and `null` in the getters.

It's a hack but Micrometer and Boot also [supports some of the Prometheus Client Properties](https://docs.micrometer.io/micrometer/reference/implementations/prometheus.html#_prometheus_client_properties), if you set `sampleIntervalMilliseconds` high enough you effectively disable Exemplars. Also, this will not solve the bean creation issue mentioned above since auto-configuration will do the same.
