### ISSUE TITLE
Duplicate @PropertySource declaration is not processed

### ISSUE THREAD

**Issue by olevitt** [spring-projects/spring-framework#22963] opened 2019-05-13 16:08 UTC
**Affects: `spring-core` 5.1.7** 

`@PropertySource` appears to be read only once even if specified multiple times (probably for performance reasons ?). This leads to some strange behavior.

Consider this code : 

```java
@PropertySource("classpath:dev2.properties")
@PropertySource("classpath:dev.properties")
@Configuration
public class MyProperties {

}
```

Here `dev.properties` wins and overrides `dev2.properties`. As expected.  

But this code : 

```java
@PropertySource("classpath:dev.properties")
@PropertySource("classpath:dev2.properties")
@PropertySource("classpath:dev.properties")
@Configuration
public class MyProperties {

}
```

`dev2.properties` overrides `dev.properties`. Which is kind of unexpected. That's because the second `dev.properties` is ignored because it has already been read.  

I would expect the other way around, that the last specified `@PropertySource` always "wins".

**Comment by sbrannen** [comment] 2019-05-13 16:34
The reason the duplicate `@PropertySource` annotation appears not to be read is that `org.springframework.context.annotation.AnnotationConfigUtils.attributesForRepeatable(...)` uses a `LinkedHashSet` for tracking all repeatable annotations processed.

So, the duplicate `@PropertySource` annotation is in fact read but not taken into consideration since an identical declaration has already been stored in the `Set`.

In general, I don't think the use case you have presented was ever expected to occur.

Can you explain why you have this particular setup?

**Comment by olevitt** [comment] 2019-05-13 16:52
Thanks for the explanation, that makes sense.  

My setup is the following one : 
We maintain multiple webapps that share a common "basewebapp" lib. In that lib, we already have a @propertysource with value file:$catalina_base/a.properties so that ops can override it (legacy compatibility).  
In the webapp, we have a configuration class with @propertysource(classpath:b.properties) followed by the same @propertysource(file:$catalina_base/a.properties).  
Which results in spring parsing it as a + (b,a) which, as you said results in a,b (the last a being ignored due to set behaviour) while both configurations explicitly defines a as the last propertysource.  
There are obviously many different workarounds / quickfixes available for my own use-case but I found the bevahiour quite unexpected and noteworthy.

**Comment by sbrannen** [comment] 2019-05-14 10:12
The class-level Javadoc for `@PropertySource` states the following for a different but similar use case.

> if overriding is important - it is recommended that the user fall back to using the programmatic `PropertySource` API. See `ConfigurableEnvironment` and `MutablePropertySources` javadocs for details.

In light of that and the previous comments in this issue, I am closing this as "works as designed".

**Closed by sbrannen** 2019-05-14 10:12 UTC
Labels: in: core, status: feedback-provided
