### ISSUE TITLE
StackOverflow exception if Filter is registered for all DispatcherTypes

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-framework#23712] opened 2019-09-25 20:06 UTC
As discussed in the spring-boot gitter channel I have a spring-boot web application that uses JSPs, and has this bean defined:
```
 @Bean(name = { "defaultRequestContextFilterRegistration", "requestContextFilterRegistration" })
    public FilterRegistrationBean requestContextFilterRegistration(RequestContextFilter requestContextFilter) {
        FilterRegistrationBean<RequestContextFilter> bean = new FilterRegistrationBean<>(requestContextFilter);
        bean.setDispatcherTypes(EnumSet.allOf(DispatcherType.class));
        bean.setOrder(SessionRepositoryFilter.DEFAULT_ORDER + 1);
        return bean;
    }
```

now whenever there's an exception on the server side, the execution flow goes through the ErrorController and then a stack-overflow is produced:
```
Caused by: java.lang.StackOverflowError: null
    at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
    at org.apache.catalina.connector.Request.getAttribute(Request.java:869) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
    at org.apache.catalina.connector.RequestFacade.getAttribute(RequestFacade.java:282) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
    at org.apache.catalina.core.ApplicationHttpRequest.getAttribute(ApplicationHttpRequest.java:245) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
    at org.apache.catalina.core.ApplicationHttpRequest.getAttribute(ApplicationHttpRequest.java:245) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
    at org.springframework.web.context.request.async.WebAsyncUtils.getAsyncManager(WebAsyncUtils.java:48) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.isAsyncDispatch(OncePerRequestFilter.java:147) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.skipDispatch(OncePerRequestFilter.java:128) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:99) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilterNestedErrorDispatch(OncePerRequestFilter.java:250) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.9.RELEASE.ja
```
works fine with Spring-boot 2.0.6 (<spring.version>5.1.8.RELEASE</spring.version>), fails with 2.0.7+ ( <spring.version>5.1.9.RELEASE</spring.version>)

I found out that it is caused by this line:

```
bean.setDispatcherTypes(EnumSet.allOf(DispatcherType.class));
```
`RequestContextFilter` now overrides this method:
```
    @Override
    protected boolean shouldNotFilterErrorDispatch() {
        return false;
    }
```
and if mapped to `DispatcherType.ERROR` causes it to loop over-and-over again in the `OncePerRequestFilter`.

I have a demo-project generated from start.spring.io if you are interested

**Comment by rstoyanchev** [comment] 2019-09-26 05:44
This is a duplicate of #23596.

**Closed by rstoyanchev** 2019-09-26 05:44 UTC
Labels: status: waiting-for-triage
