### ISSUE TITLE
@Transactional's noRollbackFor attribute ignored from caller's TransactionAttributeSource

### ISSUE THREAD

**Issue by kurenchuksergey** [spring-projects/spring-framework#26715] opened 2021-03-23 09:55 UTC
https://github.com/spring-projects/spring-framework/blob/5b2ace57423148bc9fd6af864e4c7c1eb04d515b/spring-tx/src/main/java/org/springframework/transaction/interceptor/TransactionAspectSupport.java#L341

Hi, I have two services:

```java
      class ServiceA {
          @Autowired 
          public serviceB serviceB;
          
          @Transactional(propagation = Propagation.REQUIRES_NEW, noRollbackFor = {IllegalArgumentException.class})
          public void methodA(){
             ....
             serviceB.methodB()
          }
     }
```

```java
     class ServiceB {
         @Transactional(propagation = Propagation.REQUIRED)
         public void methodB(){
           ....
           throw new IllegalArgumentException();
         }
     }
```

Unfortunately, my transaction is rolled back.

Can I change something in this behavior? Can we check to exist transaction info before checking this info by class and method?

Or is it correct at all?

**Comment by kongwu-** [comment] 2021-05-24 08:13
You should write `noRollbackFor` on `ServiceB`

**Comment by sbrannen** [comment] 2021-05-25 12:46
@kongwu-'s answer is correct.

You need to either redeclare `noRollbackFor = IllegalArgumentException.class` in service B or move the declaration completely to service B.

This is by design: `@Transactional` defines the transaction attributes for the given transactional scope, and transaction attributes are not _inherited_ by enclosed scopes. In your example, service A is the surrounding transactional scope, and service B is the enclosed transactional scope. So, although service B participates in the transaction started for service A, service A's `noRollbackFor` rollback rule does not apply to exceptions thrown within service B's scope. When an `IllegalArgumentException` is thrown within service B's transactional scope, `TransactionAspectSupport#completeTransactionAfterThrowing(TransactionInfo, Throwable)` will indirectly set the "rollback only" flag to `true` for the surrounding transaction (i.e., the transaction started for service A).

In light of that, I am closing this issue.

**Closed by sbrannen** 2021-05-25 12:46 UTC
Labels: in: data, status: invalid

**Comment by denis111** [comment] 2022-01-27 11:53
I had the same problem but the solution was inverse!. It had noRollbackFor on serviceB and it didn't work, I put the same noRollbackFor on serviceA and it worked! Did this behavior change then?
