### ISSUE TITLE
MergedAnnotationReadingVisitor should ignore annotation types that cannot be loaded

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#27797] opened 2021-12-10 14:08 UTC
Backport of gh-27772

**Comment by jhoeller** [comment] 2021-12-15 12:11
Closing this backport ticket since there does not seem to be an easy regression fix to apply, at least not for 5.2.x.

**Closed by jhoeller** 2021-12-15 12:11 UTC
Labels: type: regression, in: core, type: backport
