### ISSUE TITLE
 BeanPropertyRowMapper's support for direct column name matches is missing in DataClassRowMapper

### ISSUE THREAD

**Issue by madorb** [spring-projects/spring-framework#29187] opened 2022-09-21 22:41 UTC
This is a follow-on to [closed ticket](https://github.com/spring-projects/spring-framework/issues/28243) (that I'm unable to reopen) which I believe did not fully address the problem.

After the update the `BeanPropertyRowMapper`'s behavior still does not match the documentation from `BeanPropertyRowMapper` which states: 

> The names are matched either directly or by transforming a name separating the parts with underscores to the same name using "camel" case.

The "directly" part of the mapping does not occur. Instead it only attempts to match fully lower-cased values. 

Given data class:

```kotlin
data class MyClass(
    @Id
    val someId: Long?,
    val fooValue String?,
    val barValue: String?,
    val updateTimestamp: LocalDateTime?
)
```

and query:

```sql
SELECT someId, fooValue, barValue, updateTimestamp FROM ...
```

the fields are _not_ mapped. 

Mapping happens successfully if either the query is changed to:

```sql
SELECT someId as some_id, fooValue as foo_value, barValue as bar_value, updateTimestamp as update_timestamp FROM ...
```

OR the data class is changed to:

```kotlin
data class MyClass(
    @Id
    val someid: Long?,
    val foovalue String?,
    val barvalue: String?,
    val updatetimestamp: LocalDateTime?
)
```

It seems either the documentation or the behavior of this class should be changed.

**Comment by sbrannen** [comment] 2023-02-03 13:33
@madorb, what databases did you test this against?

**Comment by madorb** [comment] 2023-02-06 20:54
This was SQL server, i haven't touched this project for a while, but if i can find the time i'll try to get a minimal example

**Comment by sbrannen** [comment] 2023-02-07 15:32
Thanks for the reply, @madorb.

> This was SQL server, 

Based on a quick glance at the [implementation of the JDBC driver for SQL server](https://github.com/microsoft/mssql-jdbc/blob/4a27a0d1081bb3f0e9bba6112576c49f1776358f/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java#L698), it appears that column name lookups are performed as exact matches and then case-insensitive as a fallback. 

In light of that, it is a bit unexpected that `foovalue` would not return a positive match for `fooValue`; however, we really need a _reproducer_ to analyze exactly what it going on.

> i haven't touched this project for a while, but if i can find the time i'll try to get a minimal example

That would be great.

----

> the fields are _not_ mapped.

As a side note, what exactly do you mean by that?

Was there an actual error -- for example, in the form of an `SQLException`?

Or did the `DataClassRowMapper` complete its mapping without actually mapping values to the constructor arguments in your data class?

**Comment by spring-projects-issues** [comment] 2023-02-14 15:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-02-21 15:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-02-21 15:32 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, in: data, status: feedback-reminder
