### ISSUE TITLE
MockMVC is not triggering Javax.Constraint.Validation for List of Objects

### ISSUE THREAD

**Issue by SumithraPrasad** [spring-projects/spring-framework#24260] opened 2019-12-24 11:41 UTC
```
@RestController
@Validated
@Slf4j
public class TestController {

  @PostMapping(value = "/v1/test", produces = "application/json", consumes = "application/json")
  @ResponseStatus(HttpStatus.CREATED)
  public void postTest(@Valid @RequestBody List<TestDTO> testList) {
  }
}
```

MockMVC is not throwing BadRequest but when service is hit from postman we get BadRequest

**Comment by snicoll** [comment] 2019-12-24 13:37
Duplicate of #16917

**Closed by snicoll** 2019-12-24 13:37 UTC

**Comment by SumithraPrasad** [comment] 2019-12-26 03:32
@snicoll Its not working for mockmvc when parameter is of type List, it works from postman but from mockmvc its not working

**Comment by snicoll** [comment] 2019-12-26 09:00
The linked issue I've referenced does seem to indicate otherwise and I can see you've added a comment there anyway.
