### ISSUE TITLE
spring-context-indexer: spring.components has a timestamp, makes builds not reproducible

### ISSUE THREAD

**Issue by the4yeast** [spring-projects/spring-framework#22445] opened 2019-02-21 05:57 UTC
**Affects:** 5.1.5

A very similar issue to https://github.com/spring-projects/spring-boot/issues/14494.

The _spring.components_ file contains a timestamp in the header comment, this leads to [non-reproducible builds](https://reproducible-builds.org).

A very similar workaround as well:
```
compileJava {
    // https://github.com/spring-projects/spring-framework/issues/22445
    doLast {
        File f = new File(destinationDir, 'META-INF/spring.components')
        f.text = f.filterLine { !it.startsWith('#') }
    }
}
```

**Comment by vpavic** [comment] 2019-02-21 06:09
See #22383.

**Comment by snicoll** [comment] 2019-02-21 07:52
Duplicate of #22383, thanks @vpavic

**Closed by snicoll** 2019-02-21 07:52 UTC
Labels: status: waiting-for-triage
