### ISSUE TITLE
Native builds fail to start when using Querydsl

### ISSUE THREAD

**Issue by ManfredTremmel** [spring-projects/spring-framework#29529] opened 2022-11-19 18:50 UTC
**Affects:** spring-boot 3.0.0-rc2

---
I've a little [example application](https://gitlab.com/ManfredTremmel/gwt-bean-validators-example/) which I've ported to spring-boot 3.0.0 (rc2 at the moment) and it works fine in Bytcode mode. Now I've also tried to build a native docker image using `mvn -Pnative spring-boot:build-image` (what works after a solving a view problems) and start it.
Starting the application fails with a IllegalStateException because it "Did not find a static field of the same type in class de.knightsoftnet.validationexample.shared.models.QPerson". QPerson is the class generated by Querydsl for the really simple [Person](https://gitlab.com/ManfredTremmel/gwt-bean-validators-example/-/blob/master/shared/src/main/java/de/knightsoftnet/validationexample/shared/models/Person.java) entity. 
Here you can find the [stacktrace.txt](https://github.com/spring-projects/spring-framework/files/10047714/stacktrace.txt)

PS: Working with [AbstractPersistable](https://docs.spring.io/spring-data/data-jpa/docs/current/api/org/springframework/data/jpa/domain/AbstractPersistable.html) also fails in native mode, there is no id found

**Comment by sbrannen** [comment] 2022-11-20 18:31
It sounds to me like this would need to be addressed in the Spring Data project.

@odrotbohm, @mp911de: can one of you transfer this?

**Comment by sbrannen** [comment] 2022-12-13 15:11
Thanks for the feedback, @christophstrobl. 👍 

Closing as a duplicate of https://github.com/spring-projects/spring-data-commons/issues/2721.

**Closed by sbrannen** 2022-12-13 15:11 UTC
Labels: status: waiting-for-triage
