### ISSUE TITLE
Low level cache failure for sync/reactive/future Cacheable get is not handled by CacheErrorHandler

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#21590] opened 2018-07-17 13:32 UTC
**[Jens Wilke](https://jira.spring.io/secure/ViewProfile.jspa?name=cruftex)** opened **[SPR-17052](https://jira.spring.io/browse/SPR-17052?redirect=false)** and commented

Code from `CacheAspectSupport`:

```java
// Special handling of synchronized invocation
if (contexts.isSynchronized()) {
...
	try {
		return wrapCacheValue(method, cache.get(key, () -> {
			return unwrapReturnValue(invokeOperation(invoker));
		}));
	}
	catch (Cache.ValueRetrievalException ex) {
		// The invoker wraps any Throwable in a ThrowableWrapper instance so we
		// can just make sure that one bubbles up the stack.
		throw (CacheOperationInvoker.ThrowableWrapper) ex.getCause();
	}
}
```

* In the code path for `@Cachable(sync=true)` `CacheErrorHandler` is not visited.
* cast to (CacheOperationInvoker.ThrowableWrapper) is not totally sane, it could be omitted since then the unwrapping would happen in `CacheInterceptor.invoke`

---

**Affects:** 5.0.7

**Comment by roborobo2** [comment] 2019-04-15 10:06
I have the same problem in spring v4.3.13

**Comment by danielmzak** [comment] 2019-06-14 00:54
and the same problem in Spring ver. 5.1.6

**Comment by snicoll** [comment] 2019-06-19 10:04
Things aren't as easy to implement I am afraid. The purpose of the listener is to determine if the exception should bubble up the stack or if we should always call the underlying method and ignore it.

With a sync call, the cache library is responsible to check its internal state and call the underlying method if necessary (and sync other threads attempting to lookup the same value). If we call the error handler on get and your custom implementation decides to ignore it, then we should call the method and the value will not be stored in the cache. So the next thread waiting for that key (potentially) is likely to call the method again if the cache hadn't recover. There is also the odd situation that we rely on `CacheRetrievalException` to identify if the exception was thrown by the caller or the cache provider.

All in all, we are less in control and less likely to provide the right semantics. I've pushed some initial work that would call the error handler in such case, flagging for team attention to see what the rest of the team thinks.

**Comment by rmustard** [comment] 2020-07-22 16:08
same problem in 5.2.1

I'm using error handler to ignore scenarios where Redis is unavailable.

Is there a recommended workaround for sync=true and handling get errors?

**Comment by trim09** [comment] 2020-12-29 18:56
I would like to use an error handler to invalidate cache on deserialization exception during a new deployment even though Cacheable has sync=true attribute. 

```
    @Override
    public void handleCacheGetError(RuntimeException e, Cache cache, Object o) {
        if (e instanceof HazelcastSerializationException) {
            log.error(e.getMessage(), e);
            cache.invalidate();
        }
    }
```

**Comment by mstawick** [comment] 2023-06-07 19:11
A lot of digging until I discovered that it's `sync=true` that's the cause of my trouble. Have you guys found any viable workaround, or is disabling sync the only way?

**Comment by chrisirhc** [comment] 2023-11-25 08:04
> I've pushed [some initial work](https://github.com/snicoll/spring-framework/commit/68e365644f61183d03df39ad780d081afd3b5d75) that calls the error handler in such case, flagging for team attention to see what the rest of the team thinks.

This seems like a reasonable fix for this issue. Are there any downsides of this approach?
Or arguments against the fix in this state?

**Comment by adamcamp** [comment] 2024-08-08 16:43
Is there any update on this one? It seems like a pretty common use case to ignore cache failures and continue with the method call, but that is currently not possible with sync=true setting. 

The only workaround I've found while still using Cacheable annotation is to set sync=false, but that is also not ideal from performance perspective.

**Closed** 2024-08-12 13:03 UTC
Labels: in: core, type: enhancement
