### ISSUE TITLE
Consider making @Value consistent for resource arrays and collections

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-framework#22868] opened 2019-05-01 16:44 UTC
For `Resource` arrays, the `ResourceArrayPropertyEditor` will convert the location pattern to an array of resources. However, if `@Value` is present on a `Collection<Resource>`, you get a `Resource` that you then probably have to call `getPath()` on and use a `ResourcePatternResolver` to resolve that. It seems like it would be useful to make `@Value` consistent for resource collections and arrays. 

This was originally raised in [Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/15835)  for `@ConfigurationProperties`. We'd like to be consistent with what Framework does for `@Value`.

**Comment by jhoeller** [comment] 2023-08-02 19:30
This is effectively a duplicate of #24845 which we intend to address for 6.1.

**Closed** 2023-08-02 20:14 UTC
Labels: status: duplicate, in: core, type: enhancement
