### ISSUE TITLE
SimpleJdbcInsert doesn't support "keyword" column  [SPR-17097]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-framework#21634] opened 2018-07-27 08:24 UTC
**[lmtoo](https://jira.spring.io/secure/ViewProfile.jspa?name=lmtoo)** opened **[SPR-17097](https://jira.spring.io/browse/SPR-17097?redirect=false)** and commented

I have a table, defined as follows:

```sql
create table im.t_process_instance_attributescreate table im.t_process_instance_attributes( ownerId int default '0' not null, `key` varchar(50) default '' not null, value varchar(200) null, primary key (ownerId, `key`));
```

While `SimpleJdbcInsert` generated insert sql is:

```
INSERT INTO t_process_instance_attributes (ownerId, key, value) VALUES(?, ?, ?)
```
 
Key column doesn't have escape symbol, and `BadSqlGrammarException` is thrown.

---
No further details from [SPR-17097](https://jira.spring.io/browse/SPR-17097?redirect=false)

**Comment by leolee192** [comment] 2019-04-14 08:27
Duplicate of #13874

**Comment by sbrannen** [comment] 2019-04-14 10:28
@ledoyen, thanks for pointing that out.

Closing this issue as a duplicate of #13874.

**Closed by sbrannen** 2019-04-14 10:28 UTC
Labels: in: data, status: waiting-for-triage

**Comment by ledoyen** [comment] 2019-04-14 14:08
> @sbrannen 

I think you wanted to mention @leolee192 :wink:

**Comment by sbrannen** [comment] 2019-04-14 14:10
Indeed. Sorry about the noise. I'll just blame that on auto-correct.

**Comment by sadafzohra19** [comment] 2023-05-09 07:09
One workaround is to enclose the column name in quotes or brackets, depending on the database vendor. This will tell the database to treat the column name as a literal string and not as a keyword. For example, in MySQL, you can use backticks to enclose the column name, like this:

`SimpleJdbcInsert insert = new SimpleJdbcInsert(jdbcTemplate); insert.withTableName("my_table").usingColumns("`select`", "other_column");`
