### ISSUE TITLE
HtmlUnit WebClient configuration with MockMvcWebClientBuilder  behaves differently than manually creating WebClient [SPR-17632]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22163] opened 2019-01-01 13:10 UTC
**[Patrick Adler](https://jira.spring.io/secure/ViewProfile.jspa?name=616slayer616)** opened **[SPR-17632](https://jira.spring.io/browse/SPR-17632?redirect=false)** and commented

"Logging out" by removing the jsessionid  cookie in with HtmlUnits WebClient seems to behave differently, depending on how the WebClient is created.

I have created an example project [here](https://github.com/616slayer616/Spring-htmlunit-problem)

There are 3 tests (NoRememberMeLoginAutoconfigured, NoRememberMeLoginMockMvcWebClientBuilder and NoRememberMeLoginManually) and only the manually configured WebClient behaves as expected.

 

The problem is that the WebClient stays "logged in" although the session cookie has been deleted.
This does not happen when configuring it manually (new WebClient) or when accessing the  page with a browser.

I used an HandlerInterceptorAdapter to verify that the cookies are not sent for the second request. Feel free to check this again (HandlerInterceptorAdapter is included in the example project) because I might have overlooked something.

 

I have also explained the problem on [stackoverflow](https://stackoverflow.com/questions/53958957/htmlunit-stays-logged-in-after-removing-jsessionid-cookie) and the [Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/issues/15592) on GitHub. Where I was told that the relevant code probably lies within the spring framework.

 

I think the example project demonstrated the problem very obviously but I would be glad to further explain any uncertainties abotu my issue.

 

---

**Affects:** 5.1.2

**Reference URL:** https://github.com/spring-projects/spring-boot/issues/15592

**Comment by 616slayer616** [comment] 2019-02-04 09:04
Mit seems the Problem ist @WithAnonymousUser.
When I set it the SecurityContext will always have an AnonymousAuthenticationToken.
Everything works fine when I omit the annotation. But the secured page should normally not be accessible by an anonymous (not logged in) User. There is even a mockMvc test asserting that @WithAnonymousUser is redirected to login.

**Comment by snicoll** [comment] 2023-11-02 18:29
@616slayer616 apologizes for the delay here. I was trying to run the sample to get an idea about what you were describing (and whether to move the issue to Spring Security) but the link above does not work. Do you still have the sample around?

**Comment by 616slayer616** [comment] 2023-11-07 08:46
Hi
I checked everywhere but unfortunately I don't have the code sample anymore.
It has been a while so there have been many spring releases in between so maybe the issue doesn't exist anymore

**Comment by snicoll** [comment] 2023-11-07 08:52
Alright, if you manage to find it we can reopen for consideration but it might be that this has been fixed in the meantime, indeed. Sorry again for the delay.

**Closed by snicoll** 2023-11-07 08:52 UTC
Labels: status: waiting-for-triage, in: test, in: web, status: feedback-provided
