### ISSUE TITLE
WebClient blocks on JDK 8

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-framework#23361] opened 2019-07-25 14:13 UTC
[BlockHound](https://github.com/reactor/BlockHound) detects a blocking I/O on JDK 8 in this simple test using `WebClient`. It's related to how the JDK initializes the `java.lang.Package.getSystemPackage()`. This error occurs in JDK 8, however, is not an issue with JDK 10.

I'm wondering if there is a fix that can be applied within WebFlux to resolve this error under JDK 8?

There has been earlier discussions with @rstoyanchev and @rwinch around this issue.

Here is a link to the [reproducer](https://github.com/jgrandja/oauth2-client-nonblock/blob/master/ui-app/src/test/java/sample/SimpleTests.java#L43).

**Comment by poutsma** [comment] 2019-11-20 12:56
I can't reproduce this issue anymore. Perhaps `getSystemPackage()` has been whitelisted somewhere? Closing as invalid for now.

**Closed by poutsma** 2019-11-20 12:56 UTC
Labels: status: waiting-for-triage
