### ISSUE TITLE
Cannot start new transaction with parallel execution of JUnit integration tests

### ISSUE THREAD

**Issue by mufasa1** [spring-projects/spring-framework#30972] opened 2023-08-01 12:25 UTC
Hi, here is my scenario: 

Using spring-test & junit for unit test, I added `@transactional` for each test cases to make sure each cases is independent from each other. It works well when running tests with single thread.

However this exception occurs after I added parallel execution to speed up unit tests :

> "java.lang.IllegalStateException: Cannot start new transaction without ending existing transaction" in  TransactionalTestExecutionListener

I really cannot figure it out, I spent a week trying to solve it, but it wasn't successful.

Could you please give me some advice for this?

Here is the details about my code:

each test class will extend this abstract test

![image](https://github.com/spring-projects/spring-framework/assets/22904776/64a0bc63-63a0-4b0f-ab29-e8c2cc3cfe04)

No other special, just `@Test` for each test cases.

- spring-framwork version: 5.3.23
- junit version: 5.9.1

one kindly remind is that, it seems that the first case for each thread will occurs the exception, for example: junit open 50 thread to run tests, the exception will occurs when each thread running the first test case.

Looking forward for your feedback! Thank you very much!

**Comment by mufasa1** [comment] 2023-08-08 08:34
@sbrannen 
[spring-test-junit-demo.zip](https://github.com/spring-projects/spring-framework/files/12288988/spring-test-junit-demo.zip)

hi, apologise for the delay... here is the sample, please use JDK8 to run all tests, and you will see "Cannot start new transaction with parallel execution" error msg.

One kindly reminder, it seems that JDK14 works well, I really cannot figurre it out why JDK8 cannot work. Looking forward to your reply, thanks.

**Comment by mufasa1** [comment] 2023-08-11 02:16
@sbrannen  Hi, any progress or investigation for this?

**Comment by sbrannen** [comment] 2023-08-12 11:30
Hi @mufasa1,

Thanks for providing the ZIP file.

I tried it out with JDK 8 and JDK 17 and could not reproduce the error.

However, since I don't have Redis installed locally, I commented out the `stringRedisTemplate.keys("*");` line in `SuperTest`.

Can you confirm that the error goes away with that change?

And, if the error persists without that change, can you please provide your setup for Redis -- or preferably automatic Redis setup with Testcontainers?

Cheers,

Sam

**Comment by mufasa1** [comment] 2023-08-15 07:58
@sbrannen Hi, thanks for your investigation. 
You don't need to install redis locally, I have 'MockRedisServer' in the project, it will mock a redis server. 
And please do not comment out the stringRedisTemplate.keys("*"); line in SuperTest, it is the line which will cause the exception: 'Cannot start new transaction without ending existing transaction' as below.

It seems that the redis call will add extral threads to run tests, and it is the added threads which will cause the exception.

Is there any other unknown exception with the line  'stringRedisTemplate.keys("*")' in your machine?

**Comment by mufasa1** [comment] 2023-08-29 01:06
@sbrannen Hi, did you reproduce the error? or do you need me to provide any other info?

**Comment by sbrannen** [comment] 2023-08-29 08:27
Hi @mufasa1,

Thanks for the feedback!

I haven't gotten a chance to look into this again, but I've got it on my radar and should be able to take another look in the next week or so.

**Comment by sbrannen** [comment] 2023-09-26 09:28
Hi @mufasa1,

I tried your application again but without success.

> You don't need to install redis locally, I have 'MockRedisServer' in the project, it will mock a redis server.

Yes, I see that you have a `MockRedisServer`, but you never invoke `start()` on the `RedisServer` that you create. So, there is no server to connect to.

I tried to modify your sample application to start the `RedisServer`, but it always throws an exception:

```
java.lang.RuntimeException: Can't start redis server. Check logs for details.
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:61)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
```

I'm sorry, but I cannot afford to spend any more time on this.

If you can provide an updated version of your sample application that starts and connects to the embedded `RedisServer` (without any modification), I would be willing to take another look.

**Comment by mufasa1** [comment] 2023-10-08 02:01
> Hi @mufasa1,
> 
> I tried your application again but without success.
> 
> > You don't need to install redis locally, I have 'MockRedisServer' in the project, it will mock a redis server.
> 
> Yes, I see that you have a `MockRedisServer`, but you never invoke `start()` on the `RedisServer` that you create. So, there is no server to connect to.
> 
> I tried to modify your sample application to start the `RedisServer`, but it always throws an exception:
> 
> ```
> java.lang.RuntimeException: Can't start redis server. Check logs for details.
> 	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:61)
> 	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39)
> 	at redis.embedded.RedisServer.start(RedisServer.java:9)
> ```
> 
> I'm sorry, but I cannot afford to spend any more time on this.
> 
> If you can provide an updated version of your sample application that starts and connects to the embedded `RedisServer` (without any modification), I would be willing to take another look.

@sbrannen 
Thanks for taking time, sorry I just took a vacation and didn't reply in time, I am going to work on it in and provide a new demo for you, thank you so much.

**Comment by mufasa1** [comment] 2023-11-07 11:47
@sbrannen Hi, just want to know if the new demo works well ?

**Comment by mufasa1** [comment] 2023-12-21 09:22
@sbrannen  
![0AF5261A](https://github.com/spring-projects/spring-framework/assets/22904776/dddfa3be-ce68-4aae-a036-f4bc85f9c71a)
Do you still have the energy to pay attention to this issue? I am still continuously tracking it

**Comment by sbrannen** [comment] 2024-02-05 16:35
Hi @mufasa1,

Sorry for the belated reply. This one fell through the cracks.

I tried your updated example you provided in https://github.com/spring-projects/spring-framework/issues/30972#issuecomment-1759080835.

However, I still get the following error whenever I attempt to run `ServiceCTest` -- both within the IDE and via `mvn clean test` from the command line.

```
Caused by: java.lang.RuntimeException: Can't start redis server. Check logs for details.
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:61) ~[embedded-redis-0.6.jar:na]
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39) ~[embedded-redis-0.6.jar:na]
	at redis.embedded.RedisServer.start(RedisServer.java:9) ~[embedded-redis-0.6.jar:na]
	at com.example.junit5demo.service.MockRedisServer.startMockRedisServer(MockRedisServer.java:26) ~[test-classes/:na]
```

In light of that, I am closing this issue.

However, as previously mentioned...

If you can provide an updated version of your sample application that starts and connects to the embedded `RedisServer` (without any modification), I would be willing to take another look.

**Closed by sbrannen** 2024-02-05 16:35 UTC
Labels: status: waiting-for-triage, in: data, in: test, status: feedback-provided

**Comment by kajh** [comment] 2024-02-15 22:37
We are also experiencing this issue. I would like to attempt creating a demo project to reproduce it. If successful, I will share it here.

It appears that the number of tests failing with this error message is directly correlated with the number of available cores. I wanted to share this information in case it proves useful for further investigation.

**Comment by mufasa1** [comment] 2024-03-04 08:00
> We are also experiencing this issue. I would like to attempt creating a demo project to reproduce it. If successful, I will share it here.
> 
> It appears that the number of tests failing with this error message is correlated with the number of available cores. I wanted to share this information in case it proves useful for further investigation.
> 
> edit: After posting this, I see that you already have stated the same in another way in the following:
> 
> > one kindly remind is that, it seems that the first case for each thread will occurs the exception, for example: junit open 50 thread to run tests, the exception will occurs when each thread running the first test case.

Hi, do you have any further solutions, bro?

**Comment by Tradorini** [comment] 2024-03-15 09:56
I'm also facing this issue

**Comment by Cenovis** [comment] 2024-04-29 12:52
Same here. Unfortunatelly it seams we cannot limit the number of methods called in parallel with junit5 :(

**Comment by sgrimm** [comment] 2024-08-14 00:22
https://github.com/spring-projects/spring-framework/issues/33383 was the root cause of this in my application, in case it's useful information for anyone here.
