### ISSUE TITLE
RuntimeException inside TaskDecorator prevents thread from terminating

### ISSUE THREAD

**Issue by yp-palF** [spring-projects/spring-framework#22607] opened 2019-03-17 21:38 UTC
**Affects:** 5.1.5.RELEASE

If a `RuntimeException` is thrown inside `TaskDecorator`'s `Runnable`, instead of application getting shut down, it logs the exception and gets hung forever.

```java
public class AsyncExecutor {

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        runWithDecorator();
        System.out.println("Execution complete");
        System.exit(0);
    }

    private static void runWithDecorator() throws ExecutionException, InterruptedException {
        getExecutorWithDecorator()
                .submit(() -> System.out.println("Executing async task"))
                .get();

    }

    private static ThreadPoolTaskExecutor getExecutorWithDecorator() {
        ThreadPoolTaskExecutor threadPoolTaskExecutor = new ThreadPoolTaskExecutor();
        threadPoolTaskExecutor.setTaskDecorator(new AsyncTaskDecorator());
        threadPoolTaskExecutor.initialize();
        return threadPoolTaskExecutor;
    }

    private static class AsyncTaskDecorator implements TaskDecorator {

        @Override
        public Runnable decorate(Runnable runnable) {
            return () -> {
                if (true) {
                    throw new RuntimeException();
                }
                runnable.run();
            };
        }
    }
}
```

---

**Comment by sbrannen** [comment] 2019-03-17 22:57
Thanks for raising the issue.

Can you please verify that the sample application works as expected if your `TaskDecorator` invokes the decorated `Runnable` _before_ throwing an exception?

In other words, what is the result if you change your `AsyncTaskDecorator` as follows?

> ```java
>     private static class AsyncTaskDecorator implements TaskDecorator {
> 
>         @Override
>         public Runnable decorate(Runnable runnable) {
>             return () -> {
>                 runnable.run();
>                 if (true) {
>                     throw new RuntimeException();
>                 }
>             };
>         }
>     }
> }
> ```

**Comment by Flap-Py** [comment] 2019-03-18 04:05
Yes, you are right. If the `Runnable` is invoked before throwing `Exception`, the application works normally (gets shutdown)

**Comment by sbrannen** [comment] 2019-03-18 14:54
If you want to ensure that the application shuts down properly without modifications to your `TaskDecorator`, you can request the value from the `Future` with a timeout and `shutdown()` the task executor as follows.

```java
public static void main(String[] args) throws Exception {
	ThreadPoolTaskExecutor executorWithDecorator = getExecutorWithDecorator();
	try {
		executorWithDecorator.submit(() -> System.out.println("Executing async task")).get(1, TimeUnit.SECONDS);
	}
	finally {
		executorWithDecorator.shutdown();
		System.out.println("Execution complete");
		System.exit(0);
	}
}
```

That results in the following output:

```
Exception in thread "ThreadPoolTaskExecutor-1" java.lang.RuntimeException
	at org.example.AsyncExecutor$AsyncTaskDecorator.lambda$0(AsyncExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Execution complete
```

**Comment by Flap-Py** [comment] 2019-03-18 19:37
Definitely, timed waiting will solve my purpose. But I wonder if this is expected behavior. I mean why are there such differences :
• Exception in Decorator (before `runnable.run()`) VS Exception inside runnable itself
• Exception in Decorator before `runnable.run()` VS Exception in Decorator after `runnable.run()`
Should the behavior be same for all of these cases?

**Comment by sbrannen** [comment] 2019-03-20 15:26
@Flap-Py, thanks for the feedback.

> Definitely, timed waiting will solve my purpose. 

I'm glad to hear that that solved your problem!

> But I wonder if this is expected behavior. I mean why are there such differences :
> • Exception in Decorator (before `runnable.run()`) VS Exception inside runnable itself
> • Exception in Decorator before `runnable.run()` VS Exception in Decorator after `runnable.run()`
> Should the behavior be same for all of these cases?

I'm not sure why we see different behavior in those cases, though I assume it has something to do with how Spring manages the `TaskDecorator` within `ThreadPoolTaskExecutor`.

@jhoeller and @snicoll, can either of you shed some light on this?

**Comment by lgxbslgx** [comment] 2019-04-05 21:37
@yp-palF ，thank you for asking such a good question. The following analysis is so long that it may take you a lot of time to read. But I think it's worth it.

When we use `ThreadPoolExecutor.submit` to submit a task(a task is a implement of `Runnable`), a object of `Futrue` would be returned so that we can get the result of the task. 
In detail, it performs the follow steps.
1.  `ThreadPoolExecutor.submit` encapsulates the task to create a object of the class `FutureTask`, name `dftask` and the initial value of the field `FutureTask.state` is `NEW`. The `FutureTask` is a implement of `RunnableFuture`, which extends `Runnable` and `Future`. 
2. `ThreadPoolExecutor.submit` calls `ThreadPoolExecutor.execute` , taking `dftask` as a patameter, to execute the task in another thread. 
3. `ThreadPoolExecutor.submit` returns `dftask` to the user immediately, even if the return type of `ThreadPoolExecutor.submit` is `Future` and the task is not over. ( I will use `FutureTask` later instead of `Futrue`)

The field `FutureTask.state` will get changed to different value as the task performs. As shown below.
```Java
    /* 
     * Possible state transitions:
     * NEW -> COMPLETING -> NORMAL
     * NEW -> COMPLETING -> EXCEPTIONAL
     * NEW -> CANCELLED
     * NEW -> INTERRUPTING -> INTERRUPTED
     */
    private volatile int state;
    private static final int NEW          = 0;
    private static final int COMPLETING   = 1;
    private static final int NORMAL       = 2;
    private static final int EXCEPTIONAL  = 3;
    private static final int CANCELLED    = 4;
    private static final int INTERRUPTING = 5;
    private static final int INTERRUPTED  = 6;
```
When the task is over, the value of the field `FutureTask.state` will be bigger than 1. 
When we use `FutureTask.get` to get the result of the task, we can't get it until the task is over. It means `FutureTask.get` will wait the task to finish, which includes normally finishing or throwing a exception or being cancelled or being interrupted. In other words, `FutureTask.get`  doesn't return and will continuously wait if the  `FutureTask.state` is `NEW` or `COMPLETING`.

What's more, if the task throw a `ExecutionException`, the `FutureTask` will hold it and throw it when we use `FutureTask.get`, so that we can do something to catch it. It is different from the exception thrown by directly using `ThreadPoolExecutor.execute`. When we directly use `ThreadPoolExecutor.execute` instead of  `ThreadPoolExecutor.submit`, the `ExecutionException` will be thrown directly and the thread will terminate.

Then it is time for spring-framework. 

If we set the `TaskDecorator` of the `ThreadPoolTaskExecutor`, `ThreadPoolTaskExecutor.initialize` will create a `ThreadPoolExecutor` with the `ThreadPoolExecutor.execute` method to be overridden.  When we call `ThreadPoolTaskExecutor.submit` to execute a task,  it performs the follow steps.

1. Get the `ThreadPoolExecutor`
2. Call `ThreadPoolExecutor.submit`
    1. Encapsulate the task to create a object of the class `FutureTask`
    2. Call `ThreadPoolExecutor.execute`, which is overridden
            1. Decorate the `FutureTask` using `TaskDecorator`
            2. Call `super.execute`, which is the old method to execute a task
    3. Return the `FutureTask`
3. Return the `FutureTask`

The steps with retract are the substeps of the corresponding step.

As we can see, the task is Encapsulated to create the `FutureTask` before decorating. In other words, the task firstly "becomes a simple `FutureTask`", and then "becomes a decorated `Runnable`" to execute. More importantly, the result of the `ThreadPoolExecutor.submit` is the simple `FutureTask`, not the decorated `Runnable`.

Let see the code below.
```Java
private static class AsyncTaskDecorator implements TaskDecorator {
        @Override
        public Runnable decorate(Runnable runnable) {
            return () -> {
                // point 1, some code
                runnable.run();   // this 'runnable' is a FutureTask
                // point 2, some code
            };
        }
    }
}
```
Only the code in `runnable.run()` can change the value of the field `FutureTask.state`, which can influence the return time of the `FutureTask.get`. The code in point 1 and point 2 can change the value of  of the field `FutureTask.state`. Because the `FutureTask` returned by `ThreadPoolTaskExecutor.submit` is the `runnable`, which is a parameter of the method `TaskDecorator.decorate`. 

Now, we can get a conclusion that if the `runnable.run` is called normally, the `FutureTask.state` will change and the `FutureTask.get` will get a returned value.

Next, we can analysis the following situation.

1. Nothing to do in `TaskDecorator.decorate`
```Java
private static class AsyncTaskDecorator implements TaskDecorator {
        @Override
        public Runnable decorate(Runnable runnable) {
            return () -> {
            };
        }
    }
}
```
In this situation, the `runnable.run` can't be called, so the `FutureTask.state` is always `NEW` and the `FutureTask.get` is always wait `FutureTask.state` to change so that the application gets hung forever.

2. Only the `runnable.run`  in `TaskDecorator.decorate`
```Java
private static class AsyncTaskDecorator implements TaskDecorator {
        @Override
        public Runnable decorate(Runnable runnable) {
            return () -> {
                runnable.run(); 
            };
        }
    }
}
```
In this situation,  the `FutureTask.state` will become `NORMAL` or `EXCEPTIONAL` , so the `FutureTask.get` get a result to let the application continue. Note that if the task throw a `ExecutionException`, the `FutureTask` will hold it and throw it again when we use `FutureTask.get`. You'd better catch the `ExecutionException` instead of throw it to the jvm layer by layer. Because it could cause the exit code `System.exit(0);` can't be called and the destroyJavaVM thread can't cut off the non daemon thread which makes the the application gets hung again.

3. Exception before the `runnable.run` in `TaskDecorator.decorate`
```Java
private static class AsyncTaskDecorator implements TaskDecorator {
        @Override
        public Runnable decorate(Runnable runnable) {
            return () -> {
                if (true) {
                    throw new RuntimeException();
                }
                runnable.run(); 
            };
        }
    }
}
```
It is like situation 1. The `runnable.run` can't be called, so the `FutureTask.state` is always `NEW` and the `FutureTask.get` is always wait `FutureTask.state` to change so that the application gets hung forever.


4. Exception after the `runnable.run` in `TaskDecorator.decorate`
```Java
private static class AsyncTaskDecorator implements TaskDecorator {
        @Override
        public Runnable decorate(Runnable runnable) {
            return () -> {
                if (true) {
                    throw new RuntimeException();
                }
                runnable.run(); 
            };
        }
    }
}
```
It is like situation 2,  the `FutureTask.state` will become `NORMAL` or `EXCEPTIONAL` , so the `FutureTask.get` get a result to let the application continue. 

In conlusion, I think that it is not a question about the order of the Exception, but the order of the `runnable.run()`. The Exception could only cut off the current thread and the task, but it generally doesn't influence the `main` thread. The execute and termination of  the `main` thread depend on its code, which is the `FutureTask.get` and `System.exit(0)` in our example.

**Comment by yp-palF** [comment] 2019-04-06 07:19
Totally worth reading, thanks @lgxbslgx 
Now I have another question (kind of use case), suppose I have an SpringBoot app, with an **API** which takes lets say a **file name** as input, and its job is to write **some huge data on file and upload it somewhere (suppose a s3 bucket)**. Since the user won't wait for response, until the file is uploaded fully so internally the API returns a transactionId immediately to the user (which user can use later to know status) and besides, it **opens an async task to do the upload work on the background.** 
So now I can't use `Future.get()` since that would mean to wait for task to complete. And if I don't do that, I have a risk that if exception occurs in `TaskDecorator` (before runnable.run()) then my my thread pool will keep exhausting.

**Comment by lgxbslgx** [comment] 2019-04-06 08:56
>  my thread pool will keep exhausting.
Do you mean that all the thread in the thread pool will be used and never end so that other task can't be done, or many threads are created so that the memory is exhausted.

**Comment by lgxbslgx** [comment] 2019-04-06 09:02
In my opinion, a `ExecutionException` can cut off the current thread and the task. It means **the thread would not be blocked** and **the thread is gone**.

The thread pool will create a new thread to replace it and to do other task, if the configuration of the thread pool allow it to create. If the configuration not allow, the thread pool will do nothing and the number of the thread in the thread pool will be reduced by one. It depends on the configuration when you create your thread pool. 

We don't need to worry about it, because the thread pool could keep a number of threads for us to do the task we submit. What we should worry about is that the threads are blocked abnormally and never be killed. It would make all the threads of the thread pool are used up and all the tasks can't be done if the problem became serious.

Another point you should pay attention to is that you should do something to make your application more robust. Because your task has not begun so that you may lose the data.

**Comment by yp-palF** [comment] 2019-04-06 15:54
Alright, I misunderstood that the async thread will be blocked permanently too. Thanks alot!

**Comment by sbrannen** [comment] 2019-04-21 16:40
@lgxbslgx, thank you for providing such a thorough analysis.

In light of the above suggestions and explanations, I am closing this as "works as designed".

**Closed by sbrannen** 2019-04-21 16:40 UTC
Labels: in: core, status: feedback-provided
