### ISSUE TITLE
DelegatingWebFluxConfiguration could be marked as proxyTargetBean=false

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-framework#23024] opened 2019-05-24 07:18 UTC
`DelegatingWebFluxConfiguration` still doesn't have the `proxyTargetBean=false` flag, and I can't see any internal method calls to `@Bean` methods.

**Comment by wilkinsona** [comment] 2019-05-24 07:37
I think this is a duplicate of #23004.

**Closed** 2019-05-24 07:53 UTC
Labels: status: waiting-for-triage
