### ISSUE TITLE
@SendTo doesn't use MessageConverter

### ISSUE THREAD

**Issue by b-dzoba** [spring-projects/spring-framework#23886] opened 2019-10-29 12:57 UTC
**Affects:** 5.2.0

---

I configured `MappingJackson2MessageConverter`, however the app still fails with `MessageConversionException`.

When I replace `@SendTo` with `template.convertAndSend()`, everything works as expected.

Code to reproduce:

```java
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.jms.annotation.EnableJms;
import org.springframework.jms.annotation.JmsListener;
import org.springframework.jms.annotation.JmsListenerConfigurer;
import org.springframework.jms.config.JmsListenerEndpointRegistrar;
import org.springframework.jms.core.JmsMessagingTemplate;
import org.springframework.messaging.converter.MappingJackson2MessageConverter;
import org.springframework.messaging.converter.MessageConverter;
import org.springframework.messaging.handler.annotation.SendTo;
import org.springframework.messaging.handler.annotation.support.DefaultMessageHandlerMethodFactory;

@SpringBootApplication
@EnableJms
@RequiredArgsConstructor
@Slf4j
public class TestApp implements CommandLineRunner, JmsListenerConfigurer {

  private final JmsMessagingTemplate template;

  @JmsListener(destination = "queue1")
  @SendTo("queue2")
  public Payload handle(Payload payload) {
    log.info("Handling message {}", payload);
    return payload;
  }

  @Bean
  public MessageConverter messageConverter() {
    return new MappingJackson2MessageConverter();
  }

  @Bean
  public DefaultMessageHandlerMethodFactory handlerMethodFactory() {
    DefaultMessageHandlerMethodFactory factory = new DefaultMessageHandlerMethodFactory();
    factory.setMessageConverter(messageConverter());
    return factory;
  }

  @Override
  public void configureJmsListeners(JmsListenerEndpointRegistrar registrar) {
    registrar.setMessageHandlerMethodFactory(handlerMethodFactory());
  }

  @Override
  public void run(String... args) {
    template.setMessageConverter(messageConverter());
    template.convertAndSend("queue1", new Payload("test"));
  }

  public static void main(String[] args) {
    SpringApplication.run(TestApp.class, args);
  }

  @Data
  @AllArgsConstructor
  @NoArgsConstructor
  private static class Payload {

    private String value;
  }
}
```

**Comment by sbrannen** [comment] 2019-10-29 13:19
@b-dzoba, did this work for you on a previous version of the Spring Framework, and if so which version?

**Comment by b-dzoba** [comment] 2019-10-29 13:25
@sbrannen I haven't tried with different versions. Is there something wrong with my configuration?

**Comment by sbrannen** [comment] 2019-10-29 15:32
> @sbrannen I haven't tried with different versions. 

I was asking about that, because I wanted to know if you were experiencing a regression possibly introduced in 5.2.

> 5.1.2. doesn't work too.

OK. Thanks for letting us know.

> Is there something wrong with my configuration?

I'm not sure off the top of my head. One of us will have to look into it in greater detail to determine that.

**Comment by b-dzoba** [comment] 2019-10-30 20:22
Seems like the problem is with MessagingMessageListenerAdapter which doesn't call messageConverter before sending reply. Workaround is to override handleResult() in MessagingMessageListenerAdapter like this
```
public static class CustomMessagingMessageListenerAdapter extends MessagingMessageListenerAdapter {
    private final MessageConverter messageConverter = new MappingJackson2MessageConverter();
    private final JmsHeaderMapper jmsHeaderMapper = new SimpleJmsHeaderMapper();
    @Override
    protected void handleResult(Object result, javax.jms.Message request, Session session) {
        Message<?> resultMessage;
        if (result instanceof org.springframework.messaging.Message) {
            resultMessage = messageConverter.toMessage(((org.springframework.messaging.Message) result).getPayload(), ((org.springframework.messaging.Message) result).getHeaders());
        } else {
            resultMessage = messageConverter.toMessage(result, jmsHeaderMapper.toHeaders(request));
        }
        super.handleResult(resultMessage, request, session);
    }
}
```

**Comment by rstoyanchev** [comment] 2019-11-01 10:49
@b-dzoba, I think [this is where](https://github.com/spring-projects/spring-framework/blob/3858a69c4292189391860f3cd58782846aa80bd5/spring-jms/src/main/java/org/springframework/jms/listener/adapter/AbstractAdaptableMessageListener.java#L306-L325) it should be applying message conversion on the return value. Can you try a breakpoint to see if it has the right converter and if so what actually happens there? The converter should be getting set [over here](https://github.com/spring-projects/spring-framework/blob/3858a69c4292189391860f3cd58782846aa80bd5/spring-jms/src/main/java/org/springframework/jms/config/MethodJmsListenerEndpoint.java#L171).

**Comment by b-dzoba** [comment] 2019-11-03 15:40
@rstoyanchev 
> Can you try a breakpoint to see if it has the right converter 

The converter is null, but this is a org.springframework.jms.support.converter.MessageConverter. And I configured a org.springframework.messaging.converter.MessageConverter, because it's required for `@JmsListener` (DefaultMessageHandlerMethodFactory). Shouldn't `@SendTo` be able to use the same converter as `@JmsListener`?

**Comment by snicoll** [comment] 2019-11-06 18:28
@b-dzoba the converter is shared for incoming messages and replies but it's `null` so that's a sign of an inconsistent setup. Why don't you configure the  `messageConverter` on the `JmsListenerContainerFactory` as [indicated in the documentation](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#jms-annotated-support)? 

A Spring Boot application does most of the heavy lifting for you anyway, see [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-using-jms-receiving). 

I don't understand why that `DefaultMessageHandlerMethodFactory` bean is defined. If the above doesn't help, please share a sample we can actually run (rather than code in text).

**Comment by b-dzoba** [comment] 2019-11-08 12:15
>  Why don't you configure the messageConverter on the JmsListenerContainerFactory as indicated in the documentation?

@snicoll Because I use `org.springframework.messaging.converter.MappingJackson2MessageConverter` for conversion and it doesn't extend `org.springframework.jms.support.converter.MessageConverter`. This configuration 
 works with `@JmsListener` but stops working when I add `@SendTo`

> org.springframework.jms.support.converter.MessageConverter bean, it's going to be detected and used automatically

yes, but it doesn't detect `org.springframework.messaging.converter.MessageConverter` bean, so I have to set it manually on the factory

> please share a sample we can actually run

https://github.com/b-dzoba/spring-jms-demo/blob/master/src/main/java/com/example/demo/Issue23886.java

**Comment by mbolis** [comment] 2022-06-23 14:18
I bumped into the same issue, is this being taken care of?

**Comment by snicoll** [comment] 2022-08-02 07:46
Unfortunately, https://github.com/b-dzoba/spring-jms-demo is no longer accessible.

**Comment by spring-projects-issues** [comment] 2022-08-09 08:01
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-08-16 08:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-08-16 08:01 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, in: messaging, status: feedback-reminder
