### ISSUE TITLE
can we add default convert list for ConvertService

### ISSUE THREAD

**Issue by lazyfighter** [spring-projects/spring-framework#24256] opened 2019-12-24 09:20 UTC
you know some times ,when we write some business code ,we offten need POJO convert, but convertService only support class convert ,if we want to convert list,we need use `	Object convert(@Nullable Object source, @Nullable TypeDescriptor sourceType, TypeDescriptor targetType);
` this method ,i dont think this is a good way to me 。so can we add default impl to convert list
```java

public interface ConversionService {

	default <T> List<T> convert(List<?> objectList, Class<T> targetType) {
		return objectList.stream().map(ob -> convert(ob, targetType)).collect(Collectors.toList());
	}

}

```

**Comment by snicoll** [comment] 2019-12-24 09:29
Thanks for the suggestion. This is a duplicate of #23254

**Closed by snicoll** 2019-12-24 09:29 UTC
Labels: status: waiting-for-triage
