### ISSUE TITLE
MergedAnnotation does not consider plain annotations

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-framework#22744] opened 2019-04-05 11:28 UTC
When introspecting `AnnotatedElement`, we are required to work with different APIs to obtain annotation values. Before `MergedAnnotations` was introduced, we used `AnnotationUtils.getAnnotationAttributes(…)` and `AnnotatedElementUtils.getAllAnnotationAttributes(…)`.

From a caller perspective, it would be decent if `MergedAnnotations` would consider also non-meta annotations when creating `MergedAnnotations` from `Annotation` or `AnnotatedElement`. The introspecting code would not need to distinguish whether the annotation is a meta-annotation or directly the annotation being searched for and ideally `MergedAnnotations` is created once to benefit from lookup optimizations.

Using `AnnotatedElementUtils` and `AnnotationUtils` independently loses context of `MergedAnnotations`.

Example code of a class that is typically introspected:

```java
public interface NullableAnnotatedType {

	@org.springframework.lang.Nullable
	String nullableReturn();

	@javax.annotation.Nullable
	String jsr305NullableReturn();

	@javax.annotation.Nonnull(when = When.MAYBE)
	String jsr305NullableReturnWhen();
}
```

**Comment by jhoeller** [comment] 2019-04-05 11:48
As per #22743, I'm afraid this is by design. Since the JSR-305 arrangement is the only case out of the ordinary here, I'd like to keep this as a non-goal for `MergedAnnotations`, as a measure towards lookup optimizations for all other cases. Please simply avoid using `MergedAnnotations` for JSR-305 lookups.

FWIW, there is nothing wrong with  `AnnotationUtils` and `AnnotatedElementUtils` for such purposes. They explicitly support plain annotations as well, not least of it all for backwards compatibility.

**Closed by jhoeller** 2019-04-05 11:48 UTC
Labels: status: waiting-for-triage

**Comment by odrotbohm** [comment] 2019-04-05 12:42
> which are pointless for lang annotations.

Can you elaborate on why do you think that is? I'd totally agree if you look at them as a sole IDE supporting declaration, but in Spring Data we have code that alters the behavior of repository methods if they're used, e.g. if a repository query method is declared as non-null and the query execution returns a null value (due to some error in the query definition) we now throw an exception instead of returning `null` from that method.

With that I don't see anything fundamentally different in those annotations compared to other ones we e.g. use for request mapping or object mapping.

**Comment by jhoeller** [comment] 2019-04-05 13:07
From my perspective, the key difference is that the `MergedAnnotations` API is designed to handle our `@AliasFor` model and correspondingly synthesized annotation proxies. There is no way to get a raw annotation instance out of that API, just a synthesized proxy... which is a waste if the underlying annotation doesn't follow Spring's composable annotation model to begin with. None of this overhead makes sense with plain annotations, and even Spring's own nullability annotations are effectively plain.

JSR-305 has its own meta-annotation model but effectively a much simpler one, with no aliasing and no attribute overriding. Direct annotation and meta-annotation lookups against the JVM-provided annotation instances are totally sufficient there, just like they are for regular plain lang annotations. That said, I am aware that JSR-305 is a bit of a special case inbetween... but it's pretty much the only one, and it's not even a finished spec. While we can keep up compatibility with it in `AnnotationUtils` and co, I'm not inclined to make compromises for it in our rather specifically purposed `MergedAnnotations` API.

**Comment by odrotbohm** [comment] 2019-04-05 13:17
Thanks for the extended information! Makes sense to me.
