### ISSUE TITLE
MimeTypeUtils over-occupy the cpu 

### ISSUE THREAD

**Issue by com-poorbar** [spring-projects/spring-framework#24710] opened 2020-03-17 09:41 UTC
In Spring-core-5.2.2-Release
Inner class ConcurrentLruCache,
When the LRU cache is full, it over-occupt the cpu.  Because of the excess CAS and locks

**Comment by mdeinum** [comment] 2020-03-17 12:37
Isn't this related (or a duplicate of) #24671

**Comment by bclozel** [comment] 2020-03-17 15:10
Closing as a duplicate of #24671, thanks @mdeinum !

**Closed by bclozel** 2020-03-17 15:10 UTC
Labels: status: waiting-for-triage
