### ISSUE TITLE
webflux sometime slow

### ISSUE THREAD

**Issue by cjdxhjj** [spring-projects/spring-framework#26741] opened 2021-03-29 07:13 UTC
i have a service, which invoke a external service and do a query from db, and a insert operation to db, 
in normal times， the response is fast,  avg time is about 200ms(the magor cost is invoke external service), and the service is not busy（about ten thousand per day）,although there is no request in time, it always appear slow request, i have deploy the pinpoint, but it can't show any useful information
![image](https://user-images.githubusercontent.com/5616997/112796827-1c0fe100-909d-11eb-9801-ee4ea8fbcee6.png)
pinpoint result
![image](https://user-images.githubusercontent.com/5616997/112798755-f33d1b00-909f-11eb-967e-b8497a012933.png)
and my server log is
![image](https://user-images.githubusercontent.com/5616997/112798962-4b741d00-90a0-11eb-9580-fa96954513c9.png)

pinpoint's other request is heath check
![image](https://user-images.githubusercontent.com/5616997/112799167-93933f80-90a0-11eb-877e-ab523908d247.png)

my code is here
![image](https://user-images.githubusercontent.com/5616997/112799238-adcd1d80-90a0-11eb-95aa-2acdf022b070.png)
wxOauthManager.getOauthResp is a async request to external service 
![image](https://user-images.githubusercontent.com/5616997/112799366-d35a2700-90a0-11eb-9bcd-61bf6cbbf658.png)
![image](https://user-images.githubusercontent.com/5616997/112799987-a5291700-90a1-11eb-9b46-cc8cacade1c7.png)
loginService.getOauthLoginUser is a db query, done in 3ms
redis op is async use lettuce, final i log the request, it wrap an event post to application event listener, and async execute it
**Affects:** \<Spring Framework version>
spring version: 5.3.3
---

**Comment by cjdxhjj** [comment] 2021-03-29 07:19
how can i figure out the reason, and how to fix it, my server status is below
![image](https://user-images.githubusercontent.com/5616997/112800294-0a7d0800-90a2-11eb-8733-ef49da5af201.png)
![image](https://user-images.githubusercontent.com/5616997/112800356-208ac880-90a2-11eb-9d4b-3bacf6f3c298.png)
![image](https://user-images.githubusercontent.com/5616997/112800415-326c6b80-90a2-11eb-9c69-a3bad4c18500.png)

**Comment by cjdxhjj** [comment] 2021-03-29 07:24
the app is upgrade from spring mvc, it work fine, i have two node, when i found that sence, i had rollback one
![image](https://user-images.githubusercontent.com/5616997/112800855-c6d6ce00-90a2-11eb-86fa-45f1255128b1.png)

**Comment by cjdxhjj** [comment] 2021-03-29 07:36
the health check url is not exist in system, it alaways return 404

**Comment by cjdxhjj** [comment] 2021-04-02 05:03
is any way to solve the poblem, because it occur random. and i can't figure any hard env cause the problem,

**Comment by bclozel** [comment] 2021-04-02 07:21
Thanks for reaching out, but the scope of this issue is just too broad; it involves the particular context of your application, external services, network, redis, a database, etc.
Reading this issue, I'm not sure where time is being spent for those outlier requests (is it GC, network latency, synchronization issue?).

Unless you've found a very specific performance issue we can solve in Spring Framework (in this case, we need a minimal sample application that reproduces the problem), I think you'll need  to keep digging for the cause of this issue. [Spring](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-logging), [Reactor Netty](https://projectreactor.io/docs/netty/release/reference/index.html#server-tcp-level-configurations-event-wire-logger) and [Lettuce](https://lettuce.io/core/release/reference/index.html#faq.timeout) all provide ways to increase logging and get a better picture of what's happening.

I'm closing this issue for now, feel free to reopen it if you manage to find a particular performance issue in Spring Framework.

**Closed by bclozel** 2021-04-02 07:21 UTC
Labels: status: waiting-for-triage
