### ISSUE TITLE
illegal reflective access operation

### ISSUE THREAD

**Issue by xbaker** [spring-projects/spring-framework#24414] opened 2020-01-22 12:24 UTC
**java version : adoptOpenJdk 11.0.5
spring-boot : 2.1.2.release**

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.springframework.cglib.core.ReflectUtils (file:/home/tarik/.m2/repository/org/springframework/spring-core/5.1.4.RELEASE/spring-core-5.1.4.RELEASE.jar) to class java.lang.Object
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by bclozel** [comment] 2020-04-01 19:44
Closing as a duplicate of #22674, see [this comment for more details](https://github.com/spring-projects/spring-framework/issues/22674#issuecomment-589116539).

**Closed by bclozel** 2020-04-01 19:44 UTC
Labels: status: duplicate
