### ISSUE TITLE
Bean validation doesn't work with Kotlin coroutine controller

### ISSUE THREAD

**Issue by FearlessHyena** [spring-projects/spring-framework#23152] opened 2019-06-19 08:37 UTC
**Affects:Spring 5.2.0.M2** 

---

Same issue as mentioned [here](https://github.com/konrad-kaminski/spring-kotlin-coroutine/issues/38)

Adding a `@Validated` annotation  to a coroutine `@RestController` throws an `ArrayIndexOutOfBoundsException`

Using Spring Boot 2.2.0.M3 and Coroutines 1.3.0-M1

```java
java.lang.ArrayIndexOutOfBoundsException: 2
	at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[na:1.8.0_181]
	at org.hibernate.validator.internal.metadata.aggregated.ParameterMetaData$Builder.build(ParameterMetaData.java:169) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.findParameterMetaData(ExecutableMetaData.java:435) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.build(ExecutableMetaData.java:388) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BuilderDelegate.build(BeanMetaDataImpl.java:788) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BeanMetaDataBuilder.build(BeanMetaDataImpl.java:648) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:192) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.lambda$getBeanMetaData$0(BeanMetaDataManager.java:160) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324) ~[na:1.8.0_181]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getBeanMetaData(BeanMetaDataManager.java:159) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.engine.ValidationContext$ValidationContextBuilder.forValidateParameters(ValidationContext.java:619) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:254) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateParameters(ValidatorImpl.java:224) ~[hibernate-validator-6.0.12.Final.jar:6.0.12.Final]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:97) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.kotlin.experimental.coroutine.web.CoroutineController$$EnhancerBySpringCGLIB$$220f8cfd.delayedMultiply(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar:8.5.34]`
```

**Comment by sdeleuze** [comment] 2019-06-19 09:46
In Spring official support, Coroutines are not supported with Spring MVC, and I have not been able to reproduce the issue with WebFlux, so I close this issue as invalid. Feel free to reopen with a repro project using WebFlux if you can reproduce it.

**Comment by a8t3r** [comment] 2019-08-17 20:34
Hello!
This bug has the same nature as https://github.com/spring-projects/spring-framework/issues/21470, but relates to _kotlin.coroutines.Continuation_
A possible workaround is just disable _KotlinReflectionParameterNameDiscoverer_:
```kotlin
@Configuration
class ValidationConfig {

    object ValidationConfig {

        @Bean
        @Primary
        fun validator(): LocalValidatorFactoryBean {
            val factoryBean = LocalValidatorFactoryBean()
            factoryBean.setParameterNameDiscoverer(StandardReflectionParameterNameDiscoverer())
            return factoryBean
        }
    }
}
```

**Comment by sergey-volkov-lm** [comment] 2020-12-23 14:04
Why is this closed? I bumped into this bug with webflux environment

**Comment by snicoll** [comment] 2020-12-23 14:36
@sergey-volkov-lm please review the history of the issue before commenting. In his comment that closed the issue, Sébatien mentioned that:

>  have not been able to reproduce the issue with WebFlux, so I close this issue as invalid. Feel free to reopen with a repro project using WebFlux if you can reproduce it.

If you can share such project (either as a zip attached to this issue or by sharing a link to a GitHub repository) we can reopen the issue as already mentioned.

**Comment by sergey-volkov-lm** [comment] 2020-12-23 15:35
[spring-issue-23152-demo.zip](https://github.com/spring-projects/spring-framework/files/5735915/spring-issue-23152-demo.zip)

**Comment by snicoll** [comment] 2020-12-23 15:44
Thank you very much for the sample @sergey-volkov-lm.

**Comment by sergey-volkov-lm** [comment] 2021-01-27 08:43
Probably same problem: https://github.com/spring-projects/spring-framework/issues/23499

**Comment by yuri-li** [comment] 2021-02-06 11:13
> [spring-issue-23152-demo.zip](https://github.com/spring-projects/spring-framework/files/5735915/spring-issue-23152-demo.zip)

My Solution:
```
@Component
@Validated
class DemoControllerValidator{
    fun validate(@Positive positiveNumber: Int) = positiveNumber
}

@Validated
@RestController
class DemoController(val validator:DemoControllerValidator) {
    @GetMapping("test")
    suspend fun test(@RequestParam @Positive positiveNumber: Int): MessageResponse {
        val validatedParam = validator.validate(positiveNumber)
        delay(1000L)
        return MessageResponse(UUID.randomUUID().toString().take(5))
    }
}
```

**Comment by swapnil-gawali** [comment] 2021-04-03 14:09
Any update on this?

**Comment by sdeleuze** [comment] 2021-04-07 07:50
This issue is indeed a duplicate of #23499, [Hibernate Validator needs to supports Coroutines](https://github.com/spring-projects/spring-framework/issues/23499#issuecomment-716363011) to avoid this issue. If you care please create a related issue in Hibernate Validator and reference it in #23499.

**Closed by sdeleuze** 2021-04-07 07:50 UTC
Labels: status: duplicate
