### ISSUE TITLE
Mockito cannot mock AspectJ-based @Cacheable method

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-framework#24735] opened 2020-03-08 22:19 UTC
Spring Boot 2.2.5.RELEASE

Mocking a `@Cacheable` method with `@SpyBean` results in `null` when calling method.
Example:
```
@Service
public class SomeService{
    @Cacheable("somecache")
    public String method() {
        return "not";
    }
}
```
```
@SpringBootTest
@TestExecutionListeners(MockitoTestExecutionListener.class)
public class TestClass extends AbstractTestNGSpringContextTests {
    @SpyBean SomeService spybean;

    @Test
    public void test(){
       doReturn( "expected" ).when( spybean ).method();
       assertEquals( spybean.method(), "expected" ); //fails
    }
}

```

**Comment by snicoll** [comment] 2023-09-25 12:19
Closing as a duplicate of https://github.com/spring-projects/spring-framework/issues/24724. I'll drop a note there to make sure to review the reproducer above.

**Closed by snicoll** 2023-09-25 12:19 UTC
Labels: status: waiting-for-triage, in: test
