### ISSUE TITLE
Retry mechanism for system connection to remote message broker fails [SPR-17548]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-framework#22080] opened 2018-11-29 09:44 UTC
**[ori v](https://jira.spring.io/secure/ViewProfile.jspa?name=orivid)** opened **[SPR-17548](https://jira.spring.io/browse/SPR-17548?redirect=false)** and commented

Hello,

I am using the spring websocket relay broker feature, where ActiveMQ is my message broker.

I have encountered a critical issue where my server gets disconnected from the ActiveMQ, the retry mechanism for the "system" connection with activemq kicks in, trying to reconnect to ActiveMQ, and while performing the reconnection experiences the following exception:

 org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler - Transport failure: java.lang.IllegalStateException: No TcpConnection available 

causing that attempt to fail.

After that  retry attempt, the retry mechanism **stops** and does not try to reestablish the connection with ActiveMQ ever again.

 

From looking at the StompBrokerRelayMessageHandler.java file in the spring-framework project, I can see that this error originates from the initHeartbeats flow, after the CONNECTED frame was received from ActiveMQ.

If there is a disconnection between the spring relay broker and ActiveMQ, the expectation is that the retry mechanism will continue to try and establish connection with the message broker, even if encountering errors, until successfully establishing the "system" connection with the message broker (in my case ActiveMQ)

 

In my project I am using the following libraries (together with all the relevant spring libraries)

\<groupId>io.projectreactor.ipc\</groupId>
\<artifactId>reactor-netty\</artifactId>
\<version>0.7.11.RELEASE\</version>

\<groupId>io.netty\</groupId>
\<artifactId>netty-all\</artifactId>
\<version>4.1.30.Final\</version>

 

If you need any more information/details, i will be happy to supply them.

Thank you, and looking forward to your response.

 

 

---

**Affects:** 5.0.7

**Reference URL:** https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/simp/stomp/StompBrokerRelayMessageHandler.java

**Attachments:**
- [Partial Logs.txt](https://jira.spring.io/secure/attachment/26125/Partial+Logs.txt) (_18.33 kB_)

**Comment by krm1312** [comment] 2019-03-20 17:42
I am also having reconnect issues, in this case with RabbitMQ.  It does _not_ seem to have issues when I do not change the TcpClient.  But, afaik, to enable TLS you have to do something like:

```
public static ReactorNettyTcpClient create(String host, int port,
                                               boolean useTls, String tlsVersion,
                                               boolean ignoreInvalidCerts) {

        log.info("Configuring Stomp Client {}:{}, tls: {}", host, port, useTls);

        return new ReactorNettyTcpClient<>(options -> {
            if (!useTls) {
                return options.host(host).port(port);
            } else {
                try {
                    SslContextBuilder sslBuilder = SslContextBuilder.forClient();

                    if (!StringUtils.isEmpty(tlsVersion)) {
                        sslBuilder.protocols(tlsVersion);
                    }

                    if (ignoreInvalidCerts) {
                        sslBuilder.trustManager(InsecureTrustManagerFactory.INSTANCE);
                    }
                    SslContext sslContext = sslBuilder.build();
                    return options
                        .host(host)
                        .port(port)
                        .secure(sslProviderBuilder -> sslProviderBuilder.sslContext(sslContext));
                } catch (Exception e) {
                    throw new IllegalArgumentException("Unable to establish sslAlgorithm for " + tlsVersion, e);
                }
            }

        }, new StompReactorNettyCodec());


    }
```
elsewhere:
`relayRegistration.setTcpClient(TlsTcpStompClient.create(rabbitHost, rabbitPort, useTls, tlsVersion, true));`

When using tls is behaves very oddly.  On OS X, I don't seem to have an issue.  On linux, it appears to try to reconnect a somewhat low and inconsistent number of times.  Each connect attempt logs:


```
2019-03-20 17:14:37.732  INFO 40370 --- [tcp-client-loop-nio-8] o.s.m.s.s.StompBrokerRelayMessageHandler : TCP connection failure in session _system_: Failed to connect: null
2019-03-20 17:14:37.913  INFO 40370 --- [tcp-client-loop-nio-2] o.s.m.s.s.StompBrokerRelayMessageHandler : TCP connection failure in session _system_: Failed to connect: null
2019-03-20 17:14:42.744  INFO 40370 --- [tcp-client-loop-nio-4] o.s.m.s.s.StompBrokerRelayMessageHandler : TCP connection failure in session _system_: Failed to connect: null
2019-03-20 17:14:42.923  INFO 40370 --- [tcp-client-loop-nio-6] o.s.m.s.s.StompBrokerRelayMessageHandler : TCP connection failure in session _system_: Failed to connect: null
2019-03-20 17:14:47.751  INFO 40370 --- [tcp-client-loop-nio-8] o.s.m.s.s.StompBrokerRelayMessageHandler : TCP connection failure in session _system_: Failed to connect: null
```

...Then just stops.  No more log entries and the connection is never established again.

**Comment by krm1312** [comment] 2019-03-20 19:18
Sample project (fork of spring example): https://github.com/krm1312/gs-messaging-stomp-websocket/

Log with debug
[boot-log.txt](https://github.com/spring-projects/spring-framework/files/2989739/boot-log.txt)
 attached.

**Comment by krm1312** [comment] 2019-03-20 21:07
I suspect this is a bug in reactor-netty, but, not really familiar with the code.  Some observations:

It stops when this happens in the log:

Immediately aborted pooled channel, re-acquiring new channel

https://github.com/reactor/reactor-netty/blob/v0.8.5.RELEASE/src/main/java/reactor/netty/resources/PooledConnectionProvider.java#L621
(That comment doesn't give me much confidence either ;)).

Our connection actually goes app -> haproxy -> rabbitmq.

Haproxy will accept the tcp connection and terminate it before performing the TLS handshake if all backends are down.

Interestingly if no health checks are setup for the backend in haproxy it will not terminate the connection as quickly and things seem ok.  But, if it closes the connection quickly (as it does if health checks exist) eventually that happens and it stops trying to reconnect.

Not sure if there is a way to workaround this in spring or if it needs a fix in reactor-netty.

**Comment by krm1312** [comment] 2019-03-20 22:21
Patching reactor-netty PooledConnectionProvider to remove that block referenced above, seems to fix the issue.  Not sure of other implications.  Will open an issue there.  Sorry for hijacking this issue.  Seems like it is probably not the same root cause.

**Comment by badjo-tech** [comment] 2019-07-15 10:01
Hi, Is there any update on this?

I am facing the same issue.

Dependencies:

```
 <dependency>
       <groupId>io.netty</groupId>
     <artifactId>netty-all</artifactId>
     <version>4.1.36.Final</version>
 </dependency>
```
```
<dependency>
     <groupId>io.projectreactor</groupId>
     <artifactId>reactor-core</artifactId>
     <version>3.2.10.RELEASE</version>
</dependency>
```

```
<dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
     <version>0.8.9.RELEASE</version>
 </dependency>
```
```
<dependency>
      <groupId>org.apache.activemq</groupId>
     <artifactId>activemq-stomp</artifactId>
    <version>5.15.9</version>
</dependency>
```

Part of the log file
[error.txt](https://github.com/spring-projects/spring-framework/files/3391750/error.txt)

I would appreciate any help.

**Comment by snieguu** [comment] 2019-09-18 11:40
We have the same problem using the following stack:
```
org.springframework:spring-jms:jar:5.1.8.RELEASE
org.springframework:spring-messaging:jar:5.1.8.RELEASE
io.projectreactor:reactor-core:jar:3.2.8.RELEASE
io.projectreactor.netty:reactor-netty:jar:0.8.6.RELEASE
io.netty:netty-all:jar:4.1.34.Final
```
ActiveMQ is in version 5.13.2

And in tomcat catalina.out we can see:
```
2019-08-21 13:38:58,891 [tcp-client-scheduler-5] ERROR com.*.websocket.stomp.SimpMessagingSender  - BrokerAvailabilityEvent[available=false, StompBrokerRelay[ReactorNettyTcpClient[reactor.netty.tcp.TcpClientDoOn@219abb46]]]
2019-08-21 13:38:58,965 [tcp-client-scheduler-1] ERROR org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler  - Transport failure: java.lang.IllegalStateException: No TcpConnection available
```

**Comment by snieguu** [comment] 2019-09-23 04:58
After the error occurred when we check TCP with netstat we have:
```
netstat -an | grep 61613
tcp6       0      0 :::61613                :::*                    LISTEN
tcp6       2      0 127.0.0.1:49084         127.0.0.1:61613         CLOSE_WAIT
```

**Comment by rstoyanchev** [comment] 2019-09-26 10:07
Up above, @krm1312 narrowed down a change in Reactor Netty that makes a difference for which he created https://github.com/reactor/reactor-netty/issues/653 and that was fixed in 0.8.7. So @snieguu please try with the latest Reactor bom `Californium-SR12` (reactor-netty 0.8.12).

**Comment by snieguu** [comment] 2019-09-30 07:43
@rstoyanchev but @badjo-tech use `io.projectreactor.netty:reactor-netty:jar:0.8.9.RELEASE` and face the issue. Also @krm1312 use TLS to connect, we not. Few days ago, I updated to `io.projectreactor.netty:reactor-netty:jar:0.8.10.RELEASE`, I will check this and back with feedback.

**Comment by jhoeller** [comment] 2024-01-17 14:02
Closing this issue due to lack of final feedback and referring to outdated versions in the meantime.

**Closed by jhoeller** 2024-01-17 14:02 UTC
Labels: in: web, status: feedback-provided
