### ISSUE TITLE
SimpleJdbcInsert Uses Incorrect Catalog for Metadata

### ISSUE THREAD

**Issue by geoffreywiseman** [spring-projects/spring-framework#22432] opened 2019-02-19 15:27 UTC
**Affects:** 5.1.4

I have a local MySQL database, and that database has catalogs for different environments: dev, qa, staging ...

Each of these has a relatively similar set of tables, but there are differences due to different versions of the schema.

I have a Spring app that is configured to connect to a particular database / catalog, which it is doing just fine. I added a SimpleJdbcInsert in a test and it fails because it's trying to insert into a database column that isn't there.

After some digging around in the internals, I can see that if I don't specify the Catalog in the SimpleJdbcInsert setup, it leaves that null all the way down to the database metadata retrieval, which returns all of the matching tables. Then in `locateTableAndProcessMetaData`, Spring-JDBC stores each of those tables into a map by table name, and each successive table with the same name overwrites the others.

I guess what I expected is that if SimpleJdbcInsert needs table metadata, it would use the current catalog's table if I haven't specified another catalog. As it stands, the only way I can use SimpleJdbcInsert is to specify the table name to avoid it picking a random table from another catalog when deciding what columns to use.

**Comment by snicoll** [comment] 2019-02-19 15:38
That looks like a duplicate of #22015. There is a note about recent MySQL updates there, can you please have a look and let us know if that fixes the problem for you?

**Comment by geoffreywiseman** [comment] 2019-02-19 15:45
Ah, this does look like the same issue, yes.

Yes, that property does seem to be a significant factor, I agree -- although if that's the default in MySQL 8.x and it's staying that way, it may be something that will require mitigation in Spring.

**Comment by snicoll** [comment] 2019-02-19 15:56
Thanks for the quick reply. Please follow-up over there if needed.

Duplicate of #22015

**Closed by snicoll** 2019-02-19 15:56 UTC
Labels: status: feedback-provided, status: waiting-for-triage
