### ISSUE TITLE
`ApplicationListener` no longer invoked for generic `ApplicationEvent` with 6.2.0

### ISSUE THREAD

**Issue by denAbramoff** [spring-projects/spring-framework#33982] opened 2024-11-28 09:12 UTC
Hello!

I have simple interface like this:

```java
public interface ITest
{
}
```

and the simple event:

```java
public class TestEvent<T extends ITest> extends ApplicationEvent
{
    public TestEvent(Object source)
    {
        super(source);
    }
}
```

and two listeners:

1. 
```java
@Component
public class MethodListener
{
    @EventListener
    public void handleTestEvent(TestEvent<ITest> iTest)
    {
        System.out.println(this.getClass() + " DONE!");
    }
}
```
2.
```java
@Component
public class SimpleTestListener implements ApplicationListener<TestEvent<ITest>>
{
    @Override
    public void onApplicationEvent(TestEvent<ITest> event)
    {
        System.out.println(this.getClass() + " DONE!");
    }
}
```

and when i trying to send an event via the spring context like this:

```java
public class MySpringApplication
{
    public static void main(String[] args)
    {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        context.publishEvent(new TestEvent<>(""));
    }
}
```
i have different result in depends on the version Spring. When i use Spring 6.2 i can see in the log this:

```
class ... MethodListener DONE!
```

when i use Spring 6.1.15 i see both results:

```
class ...SimpleTestListener DONE!
class ...MethodListener DONE!
```

I guess it's a bug.

**Comment by sbrannen** [comment] 2024-11-28 10:31
The following all-in-one test class demonstrates this.

```java
@SpringJUnitConfig
class GenericApplicationEventListenerTests {

	@Autowired
	ApplicationContext context;

	@Test
	void test() {
		context.publishEvent(new TestEvent<ITest>("") {
		});
	}


	@Configuration
	@Import({MethodListener.class, SimpleTestListener.class})
	static class Config {
	}

	interface ITest {
	}

	static class TestEvent<T extends ITest> extends ApplicationEvent {

		TestEvent(Object source) {
			super(source);
		}
	}

	static class MethodListener {

		@EventListener
		public void handleTestEvent(TestEvent<ITest> iTest) {
			System.err.println(this.getClass() + " DONE!");
		}
	}

	static class SimpleTestListener implements ApplicationListener<TestEvent<ITest>> {

		@Override
		public void onApplicationEvent(TestEvent<ITest> event) {
			System.err.println(this.getClass() + " DONE!");
		}
	}

}
```

**Comment by anaconda875** [comment] 2024-11-28 12:11
Hi @sbrannen, I'm a Java developer who want to contribute to the framework. How can I get the task assigned (to me)? Thanks

**Comment by denAbramoff** [comment] 2024-11-29 02:39
@sbrannen thanks for your reaction! Yep, this version works:

```java
context.publishEvent(new TestEvent<ITest>("") {});
```

But it's not convenient and there are a lot of places where old version works. 

And there is also one weird case, if i add "? extends" my listenerer will work:

```java
@Configuration
public class WildcardSimpleTestListener implements ApplicationListener<TestEvent<? extends ITest>>
{
    @Override
    public void onApplicationEvent(TestEvent<? extends ITest> event)
    {
        System.out.println(this.getClass() + " DONE!");
    }
}
```

It works on Spring 6.2! 

class ...WildcardSimpleTestListener$$SpringCGLIB$$0 DONE!

**Comment by theigl** [comment] 2024-11-29 19:02
Probably related to #33968.

**Comment by sbrannen** [comment] 2024-11-30 14:45
Thanks for the feedback, @denAbramoff.

In light of the above, I believe this is a regression, and we'll look into it.

@jhoeller, I have tentatively assigned this to you due to your work on related issues.

### Potentially Related Issues

- #20727
- #22902
- #32327
- #33968

**Comment by sbrannen** [comment] 2024-11-30 14:48
> Hi @sbrannen, I'm a Java developer who want to contribute to the framework. How can I get this issue/task assigned (to me)? Thanks

Hi @anaconda875,

Thanks for the offer!

As you can see above, I've assigned to this @jhoeller, since he has done the most recent work in this area. However, if you feel confident in fixing this regression, please post your ideas here first before submitting a PR.

**Comment by anaconda875** [comment] 2024-12-01 11:52
Hi @sbrannen ,
In Spring Core , `ResolvableType.isAssignableFrom` line 336-337:
```java
WildcardBounds ourBounds = WildcardBounds.get(this);    //ourBounds IS NULL SINCE this PASSED TO WildcardBounds.get() IS A ResolvableType OF ITest
WildcardBounds typeBounds = WildcardBounds.get(other);  //typeBounds IS NOT NULL SINCE other PASSED TO WildcardBounds.get() IS ResolvableType OF <T extends ITest>
```
My proposal:
![image](https://github.com/user-attachments/assets/04a82542-67bf-4d4a-9319-cc4e7b656250)
Inside red circle is newly added.
Plz take a look!! Thanks

**Comment by jhoeller** [comment] 2024-12-05 16:41
This turned out to be rather involved, a consequence of the partial generics matching that we do as of 6.2 now where we also take the bounds of an unresolvable type variable into account. The solution that I went with is a rather minimal tweaking of the existing `strict` flag when we go into nested generics. I hope that this covers the reported case here. @denAbramoff please give an upcoming 6.2.1 snapshot an early try...

@anaconda875 I ended up with a different approach but thanks for the PR in any case!

**Closed** 2024-12-05 16:47 UTC
Labels: type: regression, in: core

**Comment by sbrannen** [comment] 2024-12-06 09:27
> I hope that this covers the reported case here.

I tested with `context.publishEvent(new TestEvent<>(""));` on `main`, and that now works as expected.

Thanks, Juergen!

**Comment by denAbramoff** [comment] 2025-01-10 09:58
Hi! This fix doesn't fix all cases. For example:

1. Add to our project new interface 

```java
public interface ITest2
{
}
```

2. Add new listener

```java
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;

@Component
public class DoubleListener<T extends ITest & ITest2> implements ApplicationListener<TestEvent<T>>
{
    @Override
    public void onApplicationEvent(TestEvent<T> event)
    {
        System.out.println(this.getClass() + " DONE!");
    }
}
```

and on Spring 6.2.1 i can see in the log:

class ....SimpleTestListener DONE!
class ....WildcardSimpleTestListener$$SpringCGLIB$$0 DONE!
class ....MethodListener DONE!

but on Spring 6.1.16 other result:

class ....DoubleListener DONE!
class ....SimpleTestListener DONE!
class ....WildcardSimpleTestListener$$SpringCGLIB$$0 DONE!
class ....MethodListener DONE!

**Comment by bclozel** [comment] 2025-01-10 10:39
@denAbramoff this issue is already fixed and released. Please create a new issue with your sample.

**Comment by denAbramoff** [comment] 2025-01-10 10:52
@bclozel but the bad behavior it's the same ...

**Comment by bclozel** [comment] 2025-01-10 11:00
Thanks for creating a new issue. We have 26K+ closed issues and people comment on them all the time. If you have a clear case and the relevant issue has been closed and released already, creating a new one is the best course of action.
