### ISSUE TITLE
WebClient overrides exchange strategies

### ISSUE THREAD

**Issue by samarprakash** [spring-projects/spring-framework#24373] opened 2020-01-16 04:12 UTC
**Affects:** \<spring-webflux-5.2.2.RELEASE>

WebClient doesn't retain existing exchange strategies while mutating. it seems similar bug was filed here - https://github.com/spring-projects/spring-hateoas/issues/867 and that was corrected but in spring Hateoas version 1.0.0.M1. 
We can still notice this behaviour in spring-webflux-5.2.2.RELEASE. Not sure why the fix was not ported into web flux package. is it intentional/desired behaviour?
Attached screenshot for same(w/o web client mutate)

**Comment by rstoyanchev** [comment] 2020-01-16 10:12
Duplicate of #24329.

**Closed by rstoyanchev** 2020-01-16 10:12 UTC
Labels: status: waiting-for-triage
