### ISSUE TITLE
Consider generics on ApplicationListener `@Bean` methods

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23178] opened 2019-06-21 16:23 UTC
See https://github.com/spring-projects/spring-boot/pull/17291 for background.

Currently using this pattern to define an ApplicationListener:

```java
@Bean
public ApplicationListener<ClassPathChangedEvent>  someListener() {
    // ...
}
```

Will result in a lot of cast class exception because the listener is called for every event. It would be nice if we could consider the generic signature of the bean method and only call listeners that match it.

**Comment by sdeleuze** [comment] 2019-06-21 17:03
Linked to #21411?

**Comment by philwebb** [comment] 2019-06-21 17:19
No so much since these are actual `@Bean` methods. Probably somewhat related to #23056 and the general problem of determining type details from a bean definition.

**Comment by odrotbohm** [comment] 2019-06-21 22:10
#15303 looks like a duplicate of this.

**Comment by sdeleuze** [comment] 2019-06-23 16:55
@odrotbohm Good point, that's the one I was trying to find.

**Closed** 2019-07-20 13:07 UTC
Labels: in: core, type: enhancement
