### ISSUE TITLE
Memory leak in MediaType.parseMediaType()

### ISSUE THREAD

**Issue by radhakrishnanch** [spring-projects/spring-framework#25043] opened 2020-05-10 18:11 UTC
We have 40 VMs (8 core,  27 GB RAM) running with Spring Webflux (version given below). Randomly facing performance issue at 2-5 VMs i.e. normal response time is 3-10 ms and in the problematic VMs response time is ~1000 ms. 

I have analysed the API flow with Dynatrace and found that performance issue at MediaType.parseMediaType(), more than 75% of the response time contribution is from MediaType.parseMediaType. 

Spring WebFlux Version
--------------------------
<dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-bom</artifactId>
        <version>Dysprosium-SR4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

Embedded Server:
----------------------
 <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-jetty</artifactId>
        <version>${spring-boot.version}</version>
      </dependency>

**Comment by radhakrishnanch** [comment] 2020-05-10 18:33
Dynatrace snapshot

![image](https://user-images.githubusercontent.com/31764107/81507381-a2eb8c00-931a-11ea-8286-feeecb038e71.png)

![image](https://user-images.githubusercontent.com/31764107/81507396-c4e50e80-931a-11ea-86b1-2b9aee0b97de.png)

**Comment by radhakrishnanch** [comment] 2020-05-10 18:49
Thread Dump

[thread_dump.txt](https://github.com/spring-projects/spring-framework/files/4606554/thread_dump.txt)

**Comment by radhakrishnanch** [comment] 2020-05-10 20:36
Heap Dump - 

I could see java.util.concurrent.ConcurrentLinkedQueue inside MimeTypeUtils.cachedMimeTypes  consumes 37.12mb. This queue contains 1,621,030 items. I assue this is the root cause of the slowness.

 I can not attach the heap dump since it is a big file.

**Comment by bclozel** [comment] 2020-05-10 21:25
Which Spring Framework version are you using?

**Comment by bclozel** [comment] 2020-05-10 21:28
This looks like a duplicate of #24886

**Comment by radhakrishnanch** [comment] 2020-05-10 21:45
> Which Spring Framework version are you using?

Spring Boot 2.2.4.RELEASE

**Comment by radhakrishnanch** [comment] 2020-05-10 21:53
> #24886

I could see we have a **StringUtils.hasLength(mimeType)** check before adding the value to the cache. Still how the null values are added to the queue?

**Comment by bclozel** [comment] 2020-05-10 21:56
Spring Boot 2.2.4 depends on Spring Framework 5.2.3. I think this issue is a duplicate of #24886 and I’ll close it as one.

Please upgrade to Spring Boot 2.2.7 or override the Spring Framework version to 5.2.6 in the Spring Boot dependency management.

Thanks!

**Closed by bclozel** 2020-05-10 21:56 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by xbj110825** [comment] 2022-06-28 11:00
> > #24886
> 
> I could see we have a **StringUtils.hasLength(mimeType)** check before adding the value to the cache. Still how the null values are added to the queue?

jdk(1.8.0_60) ConcurrentLinkedQueue.remove method has bug: https://bugs.openjdk.org/browse/JDK-8137185

You can use the following code to test whether ConcurrentLinkedQueue has bug
```java
public class CLQBug
{
    public static void main(String[] args)
    {
        ConcurrentLinkedQueue<String> queue = new ConcurrentLinkedQueue<>();
        queue.add("x");

        Method first = getNonPublicFirstMethod();
        Method succ = getNonPublicSuccMethod();

        long start = System.currentTimeMillis();
        long end;

        for (long iterations = 0; iterations < Long.MAX_VALUE; iterations++) {
            queue.add("" + iterations);
            queue.remove("" + iterations);

            if (iterations % 10000 == 0) {
                end = System.currentTimeMillis();
                System.out.println("actualSize = " + actualSize(queue, first, succ) + ", elapsed time = " + (end - start));
                start = end;
            }
        }
    }

    public static long actualSize(ConcurrentLinkedQueue<String> queue, Method first, Method succ) {
        long b = 0;
        try {
            for (Object node = first.invoke(queue); node != null; node = succ.invoke(queue, node)) {
                ++b;
            }
        } catch (IllegalAccessException | InvocationTargetException e) {
            throw new RuntimeException(e);
        }
        return b;
    }

    public static Method getNonPublicFirstMethod() {
        Method first;
        try {
            first = ConcurrentLinkedQueue.class.getDeclaredMethod("first");
        } catch (NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
        first.setAccessible(true);
        return first;
    }

    public static Method getNonPublicSuccMethod() {
        Method succ = null;
        for (Method declaredMethod : ConcurrentLinkedQueue.class.getDeclaredMethods()) {
            if (declaredMethod.getName().equals("succ")) {
                succ = declaredMethod;
                break;
            }
        }
        if (succ == null) {
            throw new RuntimeException("not found");
        }
        succ.setAccessible(true);
        return succ;
    }
}
```

if ConcurrentLinkedQueue has bug
```bash
[root@0bcfb0e0e13e work]# /home/work/1.8.0_60/bin/java -jar main.jar
elapsed time = 0
elapsed time = 331
elapsed time = 654
elapsed time = 1085
elapsed time = 1536
```
else
```bash
[root@0bcfb0e0e13e work]# /usr/bin/java -jar main.jar
elapsed time = 0
elapsed time = 10
elapsed time = 4
elapsed time = 4
elapsed time = 62
elapsed time = 4
elapsed time = 4
elapsed time = 4
```

You can also test MimeTypeUtils.parseMimeType
```java
public class ServerApplication {

    public static void main(String[] args) {
        String last = "";
        for (int i = 0; i < 64; i++) {
            last = "video/h" + i;
            MimeTypeUtils.parseMimeType(last);
        }

        long start = System.currentTimeMillis();
        long end;
        for (int i = 0; i < Integer.MAX_VALUE; i++) {
            MimeTypeUtils.parseMimeType(last);
            if (i % 10000 == 0) {
                end = System.currentTimeMillis();
                System.out.println("elapsed time = " + (end - start));
                start = end;
            }
        }
    }
}
```
