### ISSUE TITLE
No way to sort all known outstanding issues (and only these) by importance

### ISSUE THREAD

**Issue by Chealer** [spring-projects/spring-framework#28692] opened 2022-06-23 21:39 UTC
**Affects:** All

---

The Spring community manages numerous projects and sub-projects, affected by an even larger number of issues. It is difficult to grasp the importance of these issues, both individually and as a whole. For example, the lack of discussion forums documentation is tracked by ticket #27599, which stands among something in the order of 100 000 other tickets, hopefully much less important on average.

Allowing to list all known (reported) issues, and only those which are not solved, would already be a huge improvement. Supporting listings ordered by issue importance would be incredibly better. While allowing to list issues from all Spring projects together would be very useful, individual lists would also be useful, and this issue can be considered solved even if the implementation allows only per-project rankings, only a global ranking, or both. I let those familiar with the ITS(-s) decide which approach they prefer. In case it is decided to work on a per-project basis, some work has been started, as can be seen in [Spring Data Common's ticket #2458](https://github.com/spring-projects/spring-data-commons/issues/2458).

Importance is of course relative and I do not expect a perfect ranking. A field tracking it with 5 possible values (like YouTrack's default) would already suffice for our needs.
Reaching this goal may involve several jobs (enabling ranking, [fixing search](https://github.com/spring-projects/spring-framework/issues/27532#event-5433281528) and enabling marking of resolved issues), which may require considerable work, but each step of the path can be deployed individually and will considerably facilitate evaluation and the other use cases.

**Comment by snicoll** [comment] 2022-06-24 01:45
Duplicate of #27532

**Closed by snicoll** 2022-06-24 01:45 UTC
Labels: status: waiting-for-triage
