### ISSUE TITLE
Incorrect displaying of Spring official reference docs for some build versions

### ISSUE THREAD

**Issue by GeorgeVelev** [spring-projects/spring-framework#24290] opened 2020-01-03 17:22 UTC
Found issues with displaying correctly some chapters in the [official ](https://docs.spring.io/spring/docs/current/spring-framework-reference)spring-framework core docs.

Some versions of the reference docs are **not** displaying correctly everything after **1.9. Annotation-based Container Configuration** chapter in the docs. The rest chapters/parts are missing in the bookmarks section in the left, while the actual content is available and obviously missing some formatting. Affected versions 
- [current](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers)
- [5.2.x](https://docs.spring.io/spring/docs/5.2.x/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers)
- [5.2.2.BUILD-SNAPSHOT](https://docs.spring.io/spring/docs/5.2.2.BUILD-SNAPSHOT/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers)
- [5.2.2.RELEASE](https://docs.spring.io/spring/docs/5.2.2.RELEASE/spring-framework-reference/core.html#beans-autowired-annotation-qualifiers)

The difference is obvious and can be seen after simply comparing the same docs with these versions (which are not affected):
- [5.2.0.RELEASE](https://docs.spring.io/spring/docs/5.2.0.RELEASE/spring-framework-reference/core.html)
- [5.2.1.BUILD-SNAPSHOT](https://docs.spring.io/spring/docs/5.2.1.BUILD-SNAPSHOT/spring-framework-reference/core.html)
- [5.2.1.RELEASE](https://docs.spring.io/spring/docs/5.2.1.RELEASE/spring-framework-reference/core.html)
- [5.2.3.BUILD-SNAPSHOT](https://docs.spring.io/spring/docs/5.2.3.BUILD-SNAPSHOT/spring-framework-reference/core.html)

Example screenshots:
![spring-docs-1](https://user-images.githubusercontent.com/40799709/71738088-448b3a00-2e5e-11ea-9608-513398a266f2.PNG)
![spring-docs-2](https://user-images.githubusercontent.com/40799709/71738089-448b3a00-2e5e-11ea-84d8-6560e3eab002.PNG)

**Comment by bclozel** [comment] 2020-01-03 21:06
Closing as a duplicate of #24138

**Closed by bclozel** 2020-01-03 21:06 UTC
Labels: status: duplicate
