### ISSUE TITLE
Endpoints at Reactive routes require a prefix "/" but @RequestMapping and others works even without it.

### ISSUE THREAD

**Issue by CODINGSAINT** [spring-projects/spring-framework#23722] opened 2019-09-27 16:53 UTC
**Affects:** \<Spring Framework 5>

---
If we have use `@GetMapping ("hello")` or `@GetMapping("/hello")` both works seamlessly .Example: -

```java
@GetMapping("user/{userId}")
public Optional<User> getUser(@PathVariable("userId") Long id) {
	logger.info(" User id {}", id);
	return userRepository.findById(id);
}
```

With Reactive Routes it is not same, it accepts only with prefix "/" which is counter intuitive. Example  : - 
 
```java
@Bean
    public RouterFunction userRoutes() {
        return RouterFunctions.route(
                RequestPredicates.GET("/users"), userHandler::getAll)
                .andRoute(RequestPredicates.POST("/user"), userHandler::add)
                .andRoute(RequestPredicates.PUT("/user"), userHandler::update)
                .andRoute(RequestPredicates.GET("/user/{id}"), userHandler::get)
                .andRoute(RequestPredicates.DELETE("/user/{id}"), userHandler::delete);
    }
```

It might not be a bug but certainly can be an enhancement.

**Comment by StevenPG** [comment] 2019-10-13 23:50
Can you reproduce this? Looking through the source, it seems the missing / is accounted for in the 5.2.0 release tag. (https://github.com/spring-projects/spring-framework/blob/v5.2.0.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/function/RequestPredicates.java)
```
public static RequestPredicate POST(String pattern) {
	return method(HttpMethod.POST).and(path(pattern));
}
public static RequestPredicate path(String pattern) {
	Assert.notNull(pattern, "'pattern' must not be null");
	if (!pattern.isEmpty() && !pattern.startsWith("/")) {
		pattern = "/" + pattern;
	}
	return pathPredicates(DEFAULT_PATTERN_PARSER).apply(pattern);
}
```

**Comment by rstoyanchev** [comment] 2019-10-15 10:42
Resolving as duplicate of #22795.

**Closed by rstoyanchev** 2019-10-15 10:42 UTC
Labels: status: waiting-for-triage
