### ISSUE TITLE
Dynamic registerBeanDefinition in DefaultListableBeanFactory,something weird

### ISSUE THREAD

**Issue by Joker1995** [spring-projects/spring-framework#22554] opened 2019-03-10 06:56 UTC
Spring version:5.0.10.RELEASE

---

Sometime I tried to register some bean dynamically, but something weird. When I tried to use the method `getBeansOfType()` to get the bean, it returned `null`, but I got the bean when using the method `getBean()`.

This follow is my code:

```java
ConfigurableApplicationContext configurableApplicationContext = (ConfigurableApplicationContext) contextUtil.getApplicationContext();
DefaultListableBeanFactory defaultListableBeanFactory = (DefaultListableBeanFactory) configurableApplicationContext.getBeanFactory();
Map<String, HikariDataSource> dataBaseList = defaultListableBeanFactory.getBeansOfType(HikariDataSource.class);
log.info("DataBaseList:{}", dataBaseList);
BeanDefinitionBuilder beanDefinitionBuilder = BeanDefinitionBuilder.genericBeanDefinition(HikariDataSource.class);
beanDefinitionBuilder.addPropertyValue("driverClassName", "com.mysql.jdbc.Driver");
beanDefinitionBuilder.addPropertyValue("jdbcUrl","jdbc:mysql://localhost:3306/ssm_shiro?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true");
beanDefinitionBuilder.addPropertyValue("password", "123");
beanDefinitionBuilder.addPropertyValue("username", "root");
defaultListableBeanFactory.registerBeanDefinition("second-Database",
beanDefinitionBuilder.getRawBeanDefinition());
dataBaseList = defaultListableBeanFactory.getBeansOfType(HikariDataSource.class);
log.info("DataBaseList:{}", dataBaseList);
HikariDataSource secondDatabase=defaultListableBeanFactory.getBean("second-Database", HikariDataSource.class);
log.info("secondDatabase:{},jdbcUrl:{}", secondDatabase,secondDatabase.getJdbcUrl());
```

and the result:

![小Q截图-20190310145023](https://user-images.githubusercontent.com/12840349/54081719-25a63f00-4344-11e9-974a-3a0d2a897195.png)

the source code of `DefaultListableBeanFactory`:

```java
// Still in startup registration phase
this.beanDefinitionMap.put(beanName, beanDefinition);
this.beanDefinitionNames.add(beanName);
this.manualSingletonNames.remove(beanName);
```

I can see `beanDefinitionNames` saves the `beanName`, but why can I not get the bean by type? 

Something wrong in my code?

**Comment by sbrannen** [comment] 2019-03-10 16:52
> Something wrong in my code?

Yes, you are attempting to register beans after the context has been started (i.e., _refreshed_).

```java
public class BeanFactoryTests {

	@Test
	public void test() {
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
		context.register(Config.class);

		DefaultListableBeanFactory beanFactory = (DefaultListableBeanFactory) context.getBeanFactory();
		System.out.println("People (before refresh): " + beanFactory.getBeansOfType(Person.class));

		BeanDefinitionBuilder beanDefinitionBuilder = BeanDefinitionBuilder.genericBeanDefinition(Person.class);
		beanDefinitionBuilder.addPropertyValue("name", "Jane");
		beanFactory.registerBeanDefinition("jane", beanDefinitionBuilder.getRawBeanDefinition());
		context.refresh();

		System.out.println("People (after refresh):  " + beanFactory.getBeansOfType(Person.class));

		System.out.println("john: " + beanFactory.getBean("john", Person.class));
		System.out.println("jane: " + beanFactory.getBean("jane", Person.class));

		context.close();
	}


	@Configuration
	static class Config {

		@Bean
		Person john() {
			return new Person("John");
		}
	}

	public static class Person {

		private String name;


		public Person() {
		}

		public Person(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		@Override
		public String toString() {
			return "Person [name=" + name + "]";
		}

	}

}
```

If you register the beans programmatically before refreshing the context as in the above test class, you will then see the following output (using a simple `Person` class instead of a `DataSource`).

```
People (before refresh): {}
People (after refresh):  {jane=Person [name=Jane], john=Person [name=John]}
john: Person [name=John]
jane: Person [name=Jane]
```

The above shows us that there are initially no `Person` beans in the application context (even though there is already a `BeanDefinition` for "John").  After the `refresh()` we see that there are now two `Person` beans in the context: 1 from the `@Bean` method and 1 that we registered programmatically.

I am therefore closing this issue since it works as designed.

**Closed by sbrannen** 2019-03-10 16:52 UTC
Labels: in: core, status: waiting-for-triage

**Comment by Joker1995** [comment] 2019-03-11 01:17
> > Something wrong in my code?
> 
> Yes, you are attempting to register beans after the context has been started (i.e., _refreshed_).
> 
> ```java
> public class BeanFactoryTests {
> 
> 	@Test
> 	public void test() {
> 		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
> 		context.register(Config.class);
> 
> 		DefaultListableBeanFactory beanFactory = (DefaultListableBeanFactory) context.getBeanFactory();
> 		System.out.println("People (before refresh): " + beanFactory.getBeansOfType(Person.class));
> 
> 		BeanDefinitionBuilder beanDefinitionBuilder = BeanDefinitionBuilder.genericBeanDefinition(Person.class);
> 		beanDefinitionBuilder.addPropertyValue("name", "Jane");
> 		beanFactory.registerBeanDefinition("jane", beanDefinitionBuilder.getRawBeanDefinition());
> 		context.refresh();
> 
> 		System.out.println("People (after refresh):  " + beanFactory.getBeansOfType(Person.class));
> 
> 		System.out.println("john: " + beanFactory.getBean("john", Person.class));
> 		System.out.println("jane: " + beanFactory.getBean("jane", Person.class));
> 
> 		context.close();
> 	}
> 
> 
> 	@Configuration
> 	static class Config {
> 
> 		@Bean
> 		Person john() {
> 			return new Person("John");
> 		}
> 	}
> 
> 	public static class Person {
> 
> 		private String name;
> 
> 
> 		public Person() {
> 		}
> 
> 		public Person(String name) {
> 			this.name = name;
> 		}
> 
> 		public String getName() {
> 			return name;
> 		}
> 
> 		public void setName(String name) {
> 			this.name = name;
> 		}
> 
> 		@Override
> 		public String toString() {
> 			return "Person [name=" + name + "]";
> 		}
> 
> 	}
> 
> }
> ```
> 
> If you register the beans programmatically before refreshing the context as in the above test class, you will then see the following output (using a simple `Person` class instead of a `DataSource`).
> 
> ```
> People (before refresh): {}
> People (after refresh):  {jane=Person [name=Jane], john=Person [name=John]}
> john: Person [name=John]
> jane: Person [name=Jane]
> ```
> The above shows us that there are initially no `Person` beans in the application context (even though there is already a `BeanDefinition` for "John"). After the `refresh()` we see that there are now two `Person` beans in the context: 1 from the `@Bean` method and 1 that we registered programmatically.
> 
> I am therefore closing this issue since it works as designed.

Thanks,But when I try to refresh applicationContext ,there has a problem call 
```
java.lang.IllegalStateException: GenericApplicationContext does not support multiple refresh attempts: just call 'refresh' once
	at org.springframework.context.support.GenericApplicationContext.refreshBeanFactory(GenericApplicationContext.java:264)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:619)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
```
I think the best way maybe just getBean by name,refresh context maybe carry out some oncurrency problem.

**Comment by sbrannen** [comment] 2019-03-11 14:01
You should not be refreshing the context after is has already been refreshed.

As I demonstrated in the example I provided, you cannot refresh/start the `ApplicationContext` until after you have registered all bean definitions. You therefore need to rethink your whole setup process and ensure that bean definitions are registered at the appropriate time.

**Comment by Joker1995** [comment] 2019-03-12 14:04
> You should not be refreshing the context after is has already been refreshed.
> 
> As I demonstrated in the example I provided, you cannot refresh/start the `ApplicationContext` until after you have registered all bean definitions. You therefore need to rethink your whole setup process and ensure that bean definitions are registered at the appropriate time.

Yeap,this function just for sometime anyone can register datasource bean dynamically,because I can't predict the jdbcUrl and user,password....Anyway,sir,Thanks for your patience.

**Comment by sbrannen** [comment] 2019-03-12 14:22
> Yeap,this function just for sometime anyone can register datasource bean dynamically,because I can't predict the jdbcUrl and user,password....Anyway,sir,Thanks for your patience.

Have you considered externalizing those values in a properties file that's registered via `@PropertySource` and using `@Value` to inject the values?

Or is that not an option for you?

**Comment by Joker1995** [comment] 2019-03-14 14:35
> > Yeap,this function just for sometime anyone can register datasource bean dynamically,because I can't predict the jdbcUrl and user,password....Anyway,sir,Thanks for your patience.
> 
> Have you considered externalizing those values in a properties file that's registered via `@PropertySource` and using `@Value` to inject the values?
> 
> Or is that not an option for you?

I may not be so clear by those word,so these has something to show you what  I'm doing:
![小Q截图-20190314222322](https://user-images.githubusercontent.com/12840349/54365213-6639eb80-46a9-11e9-886f-f24de8df87a4.png)

Because I can't unstand what data the user would fill out,so that I try to register bean dynamically,well,I can save those data on the database ,but  I think those data is not import so I don't try to save them.Database is a good idea,I think.So sorry to bother you.Sir!
