### ISSUE TITLE
reactor-bom issue

### ISSUE THREAD

**Issue by itransform** [spring-projects/spring-framework#27264] opened 2021-08-12 02:24 UTC
mavenBom "io.projectreactor:reactor-bom:2020.0.10-SNAPSHOT"

why does this build not use the official version

**Comment by snicoll** [comment] 2021-08-12 07:03
This was released Tuesday and we didn't updated it. There is already an issue in the issue tracker.

Duplicate of #27250

**Closed by snicoll** 2021-08-12 07:03 UTC
Labels: status: waiting-for-triage
